### PR TITLE
Skip slot cache optimization for AOF client to prevent key duplication and data corruption

### LINKED ISSUE #2995: [BUG] Valkey cluster is duplicating keys when loading AOF
**Describe the bug**

When a key appear on `.base.rdb` and `.incr.aof` (inside a `MULTI/EXEC` block and after another command that manipulates another key) it is being duplicated by the server. After that, the primary cannot replicate and all replicas fail with "duplicate key" error. In addition, if the primary saves its memory content (via `SAVE` or `BGREWRITEAOF`) and restarts, it crashes at startup, which is serious because after that duplication the server will not be able to restart and stay online (e.g., for an update).

**To reproduce**

Below is an example of the data folder contents that reproduces the error. I used the latest valkey (`9.0.1-trixie`, but it also happens on the version compiled from the latest commit on `unstable` branch) from dockerhub with the flags `--cluster-enabled yes --appendonly yes --enable-debug-command yes`.

[data.zip](https://github.com/user-attachments/files/24408811/data.zip)

If you start the server with this data folder and run `KEYS *` via `valkey-cli` it displays
```
1) "k0"
2) "k1"
3) "k0"
```

If you run `GET k0`, it displays
```
"a"
```

Another way to simulate this behavior is to start a clean cluster (with the previous flags enabled), add the initial slots via `CLUSTER ADDSLOTSRANGE 0 16383` (wait for the cluster state to be `"ok"`) and run the following commands on it:

```
SET k0 a
BGREWRITEAOF
WAITAOF 1 0 60
SET k1 b
MULTI
SET k0 c
APPEND k0 d
EXEC
```

It will create a key `k0` with `"a"` as its value, save the AOF on background, wait for it to complete, then insert a key `k1` with `"b"` as its value, and finally start a transaction that resets `k0` to `"c"` and then appends `"d"` to it. The AOF must not be saved again afterwards to ensure the first `SET` comes from the `.base.rdb` file and the following commands come from the `.incr.aof` file.

Then, restart the server without saving or run `DEBUG LOADAOF` and then run `KEYS *` on it. The output should be the same.

You can simulate the crash by either:
- Restarting the server without rewriting AOF followed by running `DEBUG RELOAD` or `DEBUG LOADAOF`;
- Running `DEBUG LOADAOF` followed by `DEBUG RELOAD`;
- Running `DEBUG LOADAOF` + `BGREWRITEAOF` + `WAITAOF 1 0 60` followed by running `DEBUG LOADAOF`.

Also, if you start the server with the flag `--enable-debug-assert yes`, it crashes instantly with a failed assertion on restart or when you run `DEBUG LOADAOF`.

Note that, until you restart the server or run `DEBUG LOADAOF`, it will display the expected result (`KEYS *` == `[k0, k1]` and `GET k0` == `"cd"`).

**Expected behavior**

It must not duplicate `k0`:
- After running `KEYS *`, it must return only `k0` and `k1`, without duplication;
- After running `GET k0`, it must return `"cd"`.

**Additional information**

I started debugging the valkey-server code to understand this issue and found out that, on the `MULTI/EXEC` block, `k0` is using the same keyslot from `k1` (probably from keyslot caching that is not overwritten during `MULTI/EXEC`) and, thus, being inserted again at the wrong location.

If you comment out [this conditional block](https://github.com/valkey-io/valkey/blob/122070cf8f98febbc31e2daf8f2cd2bdd9ce078b/src/db.c#L251) the server behaves correctly, but always recompute the keyslot.

### PR DESCRIPTION
**Pull request by AdityaTeltia**
When loading AOF in cluster mode, keys inside a MULTI/EXEC block could be
inserted into wrong hash slots, causing key duplication and data corruption.

The root cause was the slot caching optimization in getKeySlot(). This
optimization reuses a cached slot value to avoid recalculating the hash
for every key operation. However, when replaying AOF, a transaction may
contain commands affecting keys in different slots. The cached slot from
a previous command (e.g., SET k1) would incorrectly be used for subsequent
commands in the transaction (e.g., SET k0), causing k0 to be stored in k1's
slot.

The existing code already skipped this optimization for replicated clients
(commands from primary) using isReplicatedClient(). This change extends
that to also skip for AOF clients by using mustObeyClient() instead, which
covers both replicated clients and the AOF client.

Fixes #2995, introduced in #1949.

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]
LGTM, thanks for the fix.

File: src/db.c [hunk 1]
```diff
@@ -246,10 +246,10 @@ int getKeySlot(sds key) {
      * the key slot would fallback to keyHashSlot.
      *
      * Modules and scripts executed on the primary may get replicated as multi-execs that operate on multiple slots,
-     * so we must always recompute the slot for commands coming from the primary.
+     * so we must always recompute the slot for commands coming from the primary or AOF.
      */
     if (server.current_client && server.current_client->slot >= 0 && server.current_client->flag.executing_command &&
-        !isReplicatedClient(server.current_client)) {
+        !mustObeyClient(server.current_client)) {
```
Comment (enjoy-binbin) [inline src/db.c:252]: I think we are missing the slot migration client.
```
/* Determines if commands on this client are replicated from some source */
int isReplicatedClient(client *c) {
    return c->flag.primary || (c->slot_migration_job && isImportSlotMigrationJob(c->slot_migration_job));
}
```

File: tests/unit/multi.tcl [hunk 2]
```diff
@@ -992,3 +992,23 @@ start_cluster 1 0 {tags {"external:skip cluster"}} {
         assert_equal [R 0 EXEC] {1 FIZZ}
     }
 }
+
+start_cluster 1 0 {tags {"external:skip cluster needs:debug"} overrides {appendonly yes}} {
```
Comment (enjoy-binbin) [inline tests/unit/multi.tcl:996]: BTW, i see the test can pass in 8.0, am i missing something?

Comment (AdityaTeltia) [reply tests/unit/multi.tcl:996]: It fails in `unstable` branch without `mustObeyClient` fix. 
I think it got introduced in this commit - https://github.com/valkey-io/valkey/commit/d7993b78d82d9c9d2f9298159acd8f5a2fc997d4

File: src/db.c (hunk 1 above)
Comment (AdityaTeltia) [reply src/db.c:252]: mustObeyClient covers all three AOF || primary || slot_migration_import

```
/* Commands arriving from the primary client or AOF client, should never be rejected. */
int mustObeyClient(client *c) {
    return c->id == CLIENT_ID_AOF || isReplicatedClient(c);
}
```

Comment (enjoy-binbin) [reply src/db.c:252]: ohh, right, sorry, i somehow read the old code in my local PC.

File: tests/unit/multi.tcl (hunk 2 above)
Comment (enjoy-binbin) [reply tests/unit/multi.tcl:996]: ok, so it was introduced in 9.0, thanks for the track

Comment (murphyjacob4) [reply tests/unit/multi.tcl:996]: Yeah I think the problem is that the code was implicitly relying on the fact that AOF would never have the slot set on the client. With atomic slot migration we opportunistically set the slot on the client so it exposed the other bug, which was that AOF was not being exempted from this caching explicitly.

**Comment by murphyjacob4** [comment]
For the purpose of understanding the impact, I think the only way to get a cross-slot MULTI/EXEC in the AOF is:

1. Load an AOF from a cluster mode disabled instance (where cross-slot transactions are permitted)
2. Load an AOF with content generated from a script or module that executes a cross-slot transaction

But yeah definitely a bug. Good find!

**Comment by murphyjacob4** [comment]
> I think the only way to get a cross-slot MULTI/EXEC in the AOF is

Sorry, read through the issue again. It looks like the issue is also occurring with a same-slot MULTI/EXEC. It is basically using the slot of the previous command execution. So yeah - not just cross-slot MULTI/EXEC

**Review by murphyjacob4 — APPROVED** [review]
