### PR TITLE
Fix missing response when AUTH is errored inside a transaction

### LINKED ISSUE #2106: [BUG] missing response when AUTH is errored inside a transaction
When we introduced module based authentication, we provided a way for the module to own the authentication and fail it in case needed.
for this we do not write error reply in case the auth identify there are existing replies in the client reply list:

```
/* If `err` is provided, this is added as an error reply to the client.
 * Otherwise, the standard Auth error is added as a reply. */
void addAuthErrReply(client *c, robj *err) {
    if (clientHasPendingReplies(c)) return; <---------- here
    if (!err) {
        addReplyError(c, "-WRONGPASS invalid username-password pair or user is disabled.");
        return;
    }
    addReplyError(c, err->ptr);
}
```

However this introduces an issue as the auth might be used inside a transaction or pipeline which already has some pending replies in the client reply list. 

example using valkey-cli:

> multi
> auth no-user 123
> exec

Credits to @uriyage for locating this

### PR DESCRIPTION
**Pull request by enjoy-binbin**
When we add f8a5a4f70ccada85943af90f6f2db3250ee50b27, a module auth
can add reply in its callback, or not add reply and just return an
error robj in its callback, and we have to figure a way to determine
whether it has added the reply.

Before we are using `clientHasPendingReplies` and it had a issue,
the auth might be used inside a transaction or pipeline which already
has some pending replies in the client reply list. It causes us to
not add the error reply to auth.

After #1819, now we have a buffered_reply client flag, it indicates
the reply for the current command was buffered, either in client::reply
or in client::buf. We can use this flag to check.

Fixes #2106.

### CODE REVIEW

File: src/acl.c [hunk 1]
```diff
@@ -1439,7 +1439,7 @@ int ACLCheckUserCredentials(robj *username, robj *password) {
 /* If `err` is provided, this is added as an error reply to the client.
  * Otherwise, the standard Auth error is added as a reply. */
 void addAuthErrReply(client *c, robj *err) {
-    if (clientHasPendingReplies(c)) return;
+    if (c->flag.buffered_reply) return;
```
Comment (ranshid) [inline src/acl.c:1446]: Can we just improve the function documentation by explaining this logic. it was also missing before

**Review by ranshid — APPROVED** [review]
Generally LGTM. small comment to improve the documentation.

File: src/acl.c (hunk 1 above)
Comment (enjoy-binbin) [reply src/acl.c:1446]: do you like the way i do it now? Or can you suggest a text so that i can copy it

Comment (ranshid) [reply src/acl.c:1446]: This looks fine. Thank you!

**Comment by ranshid** [comment]
@enjoy-binbin will you cherry pick to 8.1?

**Comment by enjoy-binbin** [comment]
https://github.com/valkey-io/valkey/commit/2b1981741095da76df6b44ddacbf59b34b6f3c13
pushed the commit to 8.1 branch

I dont know how to handle the projects label, we need a new 8.1.3 project?
