### PR TITLE
Fix module key memory usage accounting

### LINKED ISSUE #2660: [BUG] MEMORY USAGE command does not account for key size for module type
**Describe the bug**

When running MEMORY USAGE command handler of a module type, key size is not accounted for, only value size is returned.

The reason is that `memoryCommand` used to compute key size [here](https://github.com/valkey-io/valkey/blame/7.2/src/object.c#L1567-L1569), but now these code are gone. Assuming module is expected to only return value size from `mem_usage` callback, we should probably compute key size in Valkey, for module type. 

**To reproduce**

Register a module type, set a key of that type, and execute MEMORY USAGE command against the key. The command won't account for the key size.

**Expected behavior**

MEMORY USAGE command should return key size + value size for module type.

**Additional information**

Any additional information that is relevant to the problem.

### PR DESCRIPTION
**Pull request by ranshid**
Make objectComputeSize account for the key size as well when the key is a module datatype

fixes: https://github.com/valkey-io/valkey/issues/2660

### CODE REVIEW

File: src/object.c [hunk 1]
```diff
@@ -1295,7 +1295,7 @@ size_t objectComputeSize(robj *key, robj *o, size_t sample_size, int dbid) {
             if (samples) asize += (double)elesize / samples * raxSize(s->cgroups);
         }
     } else if (o->type == OBJ_MODULE) {
-        asize = moduleGetMemUsage(key, o, sample_size, dbid);
+        asize = zmalloc_size((void *)o) + moduleGetMemUsage(key, o, sample_size, dbid);
```
Comment (zuiderkwast) [inline src/object.c]: It looks like `zmalloc_size((void *)o)` is part of every case in this long else-if chain. We could factor it out and initialize `size_t asize = zmalloc_size((void *)o);` once for all cases.

**Review by zuiderkwast — APPROVED** [review]
Good catch!

File: src/object.c (hunk 1 above)
Comment (ranshid) [reply src/object.c]: Agree. I think it was attempted to keep the existing staructure when it was modified in https://github.com/valkey-io/valkey/pull/2290, but your point is valid

Comment (zuiderkwast) [reply src/object.c]: If you want to keep the change small, to make it easier to backport, etc., just merge it as is. :+1:

Comment (ranshid) [reply src/object.c]: @zuiderkwast checkout the latest and see if it seems correct to you.

**Review by zuiderkwast — APPROVED** [review]
