### PR TITLE
To avoid bouncing -REDIRECT during FAILOVER

### LINKED ISSUE #821: [BUG] `CLIENT CAPA redirect` may result in bouncing redirects during failover
**Describe the bug**

A client using the new `CLIENT CAPA redirect` feature may see bouncing `REDIRECT` responses
during a failover initiated by the `FAILOVER` command. To be more precise, during the
`FAILOVER_IN_PROGRESS` failover state.

While the current primary is in `FAILOVER_IN_PROGRESS` state, `server.primary_host` is already
set to the designated primary. However, the designated primary still acts as a replica until the `PSYNC FAILOVER` command is processed.

The primary will already reply with a `REDIRECT` (to the designated primary) in this situation. But the latter is still a replica and will `REDIRECT` the client back to the old primary.

**To reproduce**

This is hard to reproduce since, under normal circumstances, the duration of the 
`FAILOVER_IN_PROGRESS` state is very short: During this phase, a connection from the primary 
to the designated primary is opened to send, among other commands, the `PSYNC FAILOVER` command.

Nevertheless, in case of e.g. a network glitch, this may take much longer (actually, there
seems to be no timeout for this phase(?))

I produced this behavior by blocking the client when receiving the `PSYNC FAILOVER` in `syncCommand`.

Update: The behavior can also be reproduced by letting the replica sleep, see https://github.com/gmbnomis/valkey/commit/ca708a424c7df482344401ec67f26263074996c7 for a demonstration.

**Expected behavior**

During the first phase of a failover (`FAILOVER_WAIT_FOR_SYNC`), a writing client will be paused
while reads can still proceed. During the second phase (`FAILOVER_IN_PROGRESS`) the same behavior
is expected.

Only after finishing the failover procedure, i.e. when the clients are unpaused again, `REDIRECT` replies
should be sent (since the new primary is ready to accept writes now.)

**Additional information**

Note that it isn't sufficient to just ensure that we aren't in a "failover" when sending redirect at https://github.com/valkey-io/valkey/blob/59aa00823c3691c50da452f2df2c4bc24e46696d/src/server.c#L3903, e.g.:

```c
    if (!server.cluster_enabled && c->capa & CLIENT_CAPA_REDIRECT && server.primary_host && server.failover_state == NO_FAILOVER &&
        !obey_client && (is_write_command || (is_read_command && !c->flag.readonly))) {
        addReplyErrorSds(c, sdscatprintf(sdsempty(), "-REDIRECT %s:%d", server.primary_host, server.primary_port));
        return C_OK;
    }
```

Instead of `REDIRECT`, the client will see `READONLY` errors during `FAILOVER_IN_PROGRESS` (caused by https://github.com/valkey-io/valkey/blob/59aa00823c3691c50da452f2df2c4bc24e46696d/src/server.c#L3987), which as explained in #319, prevents a smooth switch.

We could add a corresponding `server.failover_state == NO_FAILOVER` clause to the respective `if`. However, it looks like [`MASTERDOWN`](https://github.com/valkey-io/valkey/blob/59aa00823c3691c50da452f2df2c4bc24e46696d/src/server.c#L4007) could be triggered during `FAILOVER_IN_PROGRESS` as well if `replica-serve-stale-data` is `no` (I did not test this).

It may also be worth considering whether we should change the order of the if clauses (i.e. pause clients "earlier").

### PR DESCRIPTION
**Pull request by soloestoy**
Fix #821

During the `FAILOVER` process, when conditions are met (such as when the force time is reached or the primary and replica offsets are consistent), the primary actively becomes the replica and transitions to the `FAILOVER_IN_PROGRESS` state. After the primary becomes the replica, and after handshaking and other operations, it will eventually send the `PSYNC FAILOVER` command to the replica, after which the replica will become the primary. This means that the upgrade of the replica to the primary is an asynchronous operation, which implies that during the `FAILOVER_IN_PROGRESS` state, there may be a period of time where both nodes are replicas. In this scenario, if a `-REDIRECT` is returned, the request will be redirected to the replica and then redirected back, causing back and forth redirection. To avoid this situation, during the `FAILOVER_IN_PROGRESS state`, we temporarily suspend the clients that need to be redirected until the replica truly becomes the primary, and then resume the execution.

### CODE REVIEW

File: src/server.c [hunk 1]
```diff
@@ -3902,7 +3902,30 @@ int processCommand(client *c) {
...
+             * FAILOVER_IN_PROGRESS state, there may be a period of time where
+             * both nodes are replicas.
+             *
+             * In this scenario, if a -REDIRECT is returned, the request will be
+             * redirected to the replica and then redirected back, causing back
+             * and forth redirection. To avoid this situation, during the
+             * FAILOVER_IN_PROGRESS state, we temporarily suspend the clients
+             * that need to be redirected until the replica truly becomes the primary,
+             * and then resume the execution. */
+            blockPostponeClient(c);
```
Comment (gmbnomis) [inline src/server.c:3925]: I think this may block reading clients as well, which is a behavioral change since we are only in `CLIENT PAUSE WRITE` during this phase.

The simplest solution I came up with was to add `&& server.failover_state == NO_FAILOVER` to the `if` for the redirect case (in line 3903) and to the `if` for the read only replica case in https://github.com/valkey-io/valkey/pull/871/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9R4012. 

The rationale for this is that during a failover, we should prefer to block clients (which will happen here https://github.com/valkey-io/valkey/pull/871/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9R4082) instead of redirecting them or giving them answers that may not be valid anymore after the failover (keep in mind that failover may still fail at this point in time).

**Review by gmbnomis — COMMENTED** [review]
fyi, a potential test case for this bug is part of my PR #848 , see FIXME at https://github.com/valkey-io/valkey/pull/848/files#diff-fdef28e02ac8048541ebebbb829193ffd25622dc438bd8d921b167e51564bdd0R177. Just saying :wink:

File: src/server.c (hunk 1 above)
Comment (soloestoy) [reply src/server.c:3925]: >I think this may block reading clients as well, which is a behavioral change since we are only in CLIENT PAUSE WRITE during this phase.

When the client does not execute the `readonly` command, read operations will also be redirected, so read operations also need to be suspended. This is a special state of `FAILOVER_IN_PROGRESS`.

Comment (soloestoy) [reply src/server.c:3925]: >The rationale for this is that during a failover, we should prefer to block clients (which will happen here https://github.com/valkey-io/valkey/pull/871/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9R4082) instead of redirecting them or giving them answers that may not be valid anymore after the failover (keep in mind that failover may still fail at this point in time).

This is exactly what this PR does.

Comment (gmbnomis) [reply src/server.c:3925]: > When the client does not execute the `readonly` command, read operations will also be redirected, so read operations also need to be suspended. This is a special state of `FAILOVER_IN_PROGRESS`.

If I understand you correctly, you are saying that reading (which is possible in both failover states up to now) is a problem during `FAILOVER_IN_PROGRESS`. Sorry, but I don't understand the reason why this is the case. 

But if so, why are we only blocking clients that understand REDIRECT? Shouldn't we block all clients in this phase, then?

Comment (madolson) [inline src/server.c:3925]: When do these get unblocked? This occurs on the replica, which was never paused so we never call the unpause code.

**Review by madolson — APPROVED** [review]
It makes sense to me. It would be nice to add a test though.

File: src/server.c (hunk 1 above)
Comment (soloestoy) [reply src/server.c:3925]: Both read and write commands may receive a `-REDIRECT`. The issue we are currently addressing is when the primary is demoted to a replica and is in the `FAILOVER_IN_PROGRESS` state, the replica may not have become the primary yet. The solution is to pause both read and write commands during `FAILOVER_IN_PROGRESS`, there is no need to pause non-read-write commands any time.

>why are we only blocking clients that understand REDIRECT?

We don't care about clients without redirect capa, they would never receive `-REDIRECT`, instead they can receive `-READONLY`.

Comment (gmbnomis) [reply src/server.c:3925]: I don't seem to get my message across, but maybe I understand now why you consider `FAILOVER_IN_PROGRESS` to be special:

During the entire failover procedure, no change can happen on the primary since all writing commands are blocked (by postponing them). Therefore, I thought that continuing to answer reads is fine in `FAILOVER_WAIT_FOR_SYNC` as well as in  `FAILOVER_IN_PROGRESS`.

But there is a time delay between the new primary becoming primary and the old primary realizing that the switch happened. If a new client happens to connect to the new primary and writes during this time, we may return stale data to a reading "READWRITE" client on the old primary if we allow reading instead of blocking it.

Is this why we need to block reads as well?

Do we need to document this change? (the documentation of the FAILOVER command does say that only writing clients are blocked)

Comment (soloestoy) [reply src/server.c:3925]: >Do we need to document this change? (the documentation of the FAILOVER command does say that only writing clients are blocked)

Yes, see https://github.com/valkey-io/valkey-doc/pull/162

File: tests/integration/replica-redirect.tcl [hunk 2]
```diff
@@ -32,5 +37,42 @@ start_server {tags {needs:repl external:skip}} {
             r readonly
             r get foo
         } {}
+
+        test {client paused during failover-in-progress} {
+            pause_process $replica_pid
+            # replica will never acknowledge this write
+            r -1 set foo bar
+            r -1 failover to $replica_host $replica_port TIMEOUT 100 FORCE
```
Comment (madolson) [inline tests/integration/replica-redirect.tcl:45]: @soloestoy This tests seems to be consistently failing under valgrind. We might need some better checks to make sure the node is online before continuing here. https://github.com/valkey-io/valkey/actions/runs/10396494542/job/28794814216

Comment (gmbnomis) [reply tests/integration/replica-redirect.tcl:45]: @madolson @soloestoy Proposed fix is at #917
