### PR TITLE
Fix large allocations crashing Valkey during active defrag

### LINKED ISSUE #2348: [CRASH] assertion failed: allocator_defrag.c:396 'binind < je_cb.nbins && region_size == je_cb.bin_info[binind].reg_size' is not true
### Crash report

```shell
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.509+00:00" level=notice message="oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.509+00:00" level=notice message="Valkey version=255.255.255, bits=64, commit=2cd62fa8, modified=0, pid=1300042, just started"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.509+00:00" level=notice message="Configuration loaded"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.509+00:00" level=notice message="Increased maximum number of open files to 10032 (it was originally set to 1024)."
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.509+00:00" level=notice message="monotonic clock: POSIX clock_gettime"
                .+^+.                                                
            .+#########+.                                            
        .+########+########+.           Valkey 255.255.255 (2cd62fa8/0) 64 bit
    .+########+'     '+########+.                                    
 .########+'     .+.     '+########.    Running in standalone mode
 |####+'     .+#######+.     '+####|    Port: 17621
 |###|   .+###############+.   |###|    PID: 1300042                     
 |###|   |#####*'' ''*#####|   |###|                                 
 |###|   |####'  .-.  '####|   |###|                                 
 |###|   |###(  (@@@)  )###|   |###|          https://valkey.io      
 |###|   |####.  '-'  .####|   |###|                                 
 |###|   |#####*.   .*#####|   |###|                                 
 |###|   '+#####|   |#####+'   |###|                                 
 |####+.     +##|   |#+'     .+####|                                 
 '#######+   |##|        .+########'                                 
    '+###|   |##|    .+########+'                                    
        '|   |####+########+'                                        
             +#########+'                                            
                '+v+'                                                

pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="Server initialized"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="Reading RDB base file on AOF loading..."
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="Loading RDB produced by Valkey version 8.1.3"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="RDB age 11960 seconds"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="RDB memory usage when created 15188.15 Mb"
pid=1300042 role=primary timestamp="2025-07-13T20:02:02.510+00:00" level=notice message="RDB is base AOF"
pid=1300042 role=primary timestamp="2025-07-13T20:04:33.441+00:00" level=notice message="Done loading RDB, keys loaded: 150, keys expired: 0."
pid=1300042 role=primary timestamp="2025-07-13T20:04:33.441+00:00" level=notice message="DB loaded from base file appendonly.aof.198.base.rdb: 150.931 seconds"
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.388+00:00" level=info message="Starting active defrag, frag=10%, frag_bytes=1142398384, cpu=1%"


=== VALKEY BUG REPORT START: Cut & paste starting from here ===
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.388+00:00" level=warning message="=== ASSERTION FAILED ==="
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.388+00:00" level=warning message="==> allocator_defrag.c:396 'binind < je_cb.nbins && region_size == je_cb.bin_info[binind].reg_size' is not true"

------ STACK TRACE ------

1300044 bio_aof
/usr/lib/libc.so.6(+0x9de22) [0x7973184afe22]
/usr/lib/libc.so.6(+0x91fda) [0x7973184a3fda]
/usr/lib/libc.so.6(+0x9264c) [0x7973184a464c]
/usr/lib/libc.so.6(pthread_cond_wait+0x14e) [0x7973184a6d1e]
src/valkey-server googl 0.0.0.0:17621(bioProcessBackgroundJobs+0x1af) [0x642734598a3f]
/usr/lib/libc.so.6(+0x957eb) [0x7973184a77eb]
/usr/lib/libc.so.6(+0x11918c) [0x79731852b18c]

1300046 io_thd_1
/usr/lib/libc.so.6(+0x92880) [0x7973184a4880]
/usr/lib/libc.so.6(pthread_mutex_lock+0x101) [0x7973184aae61]
src/valkey-server googl 0.0.0.0:17621(+0xcd6c4) [0x6427344d16c4]
/usr/lib/libc.so.6(+0x957eb) [0x7973184a77eb]
/usr/lib/libc.so.6(+0x11918c) [0x79731852b18c]

1300042 valkey-server *
src/valkey-server googl 0.0.0.0:17621(allocatorShouldDefrag+0x1f8) [0x6427345f5548]
src/valkey-server googl 0.0.0.0:17621(+0x9bc6b) [0x64273449fc6b]
src/valkey-server googl 0.0.0.0:17621(+0x1f5a01) [0x6427345f9a01]
src/valkey-server googl 0.0.0.0:17621(+0xa09bf) [0x6427344a49bf]
src/valkey-server googl 0.0.0.0:17621(+0x1f6cc0) [0x6427345facc0]
src/valkey-server googl 0.0.0.0:17621(+0x1f794b) [0x6427345fb94b]
src/valkey-server googl 0.0.0.0:17621(whileBlockedCron+0x99) [0x6427344aa6e9]
src/valkey-server googl 0.0.0.0:17621(processEventsWhileBlocked+0xdd) [0x6427344e9b7d]
src/valkey-server googl 0.0.0.0:17621(loadSingleAppendOnlyFile+0x4e1) [0x642734558b41]
src/valkey-server googl 0.0.0.0:17621(loadAppendOnlyFiles+0x4ed) [0x6427345598bd]
src/valkey-server googl 0.0.0.0:17621(loadDataFromDisk+0x1d4) [0x6427344bb2e4]
src/valkey-server googl 0.0.0.0:17621(main+0x339) [0x64273448fe69]
/usr/lib/libc.so.6(+0x276b5) [0x7973184396b5]
/usr/lib/libc.so.6(__libc_start_main+0x89) [0x797318439769]
src/valkey-server googl 0.0.0.0:17621(_start+0x25) [0x642734491ac5]

1300045 bio_lazy_free
/usr/lib/libc.so.6(+0x9de22) [0x7973184afe22]
/usr/lib/libc.so.6(+0x91fda) [0x7973184a3fda]
/usr/lib/libc.so.6(+0x9264c) [0x7973184a464c]
/usr/lib/libc.so.6(pthread_cond_wait+0x14e) [0x7973184a6d1e]
src/valkey-server googl 0.0.0.0:17621(bioProcessBackgroundJobs+0x1af) [0x642734598a3f]
/usr/lib/libc.so.6(+0x957eb) [0x7973184a77eb]
/usr/lib/libc.so.6(+0x11918c) [0x79731852b18c]

1300043 bio_close_file
/usr/lib/libc.so.6(+0x9de22) [0x7973184afe22]
/usr/lib/libc.so.6(+0x91fda) [0x7973184a3fda]
/usr/lib/libc.so.6(+0x9264c) [0x7973184a464c]
/usr/lib/libc.so.6(pthread_cond_wait+0x14e) [0x7973184a6d1e]
src/valkey-server googl 0.0.0.0:17621(bioProcessBackgroundJobs+0x1af) [0x642734598a3f]
/usr/lib/libc.so.6(+0x957eb) [0x7973184a77eb]
/usr/lib/libc.so.6(+0x11918c) [0x79731852b18c]

5/5 expected stacktraces.

------ STACK TRACE DONE ------

------ INFO OUTPUT ------
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:255.255.255
valkey_release_stage:dev
redis_git_sha1:2cd62fa8
redis_git_dirty:0
redis_build_id:fa035a1e6ee06f82
server_mode:standalone
os:Linux 6.14.6-arch1-1 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:15.1.1
process_id:1300042
process_supervised:no
run_id:5592a1c1a78e9dc4988db81803f486bb73fd4423
tcp_port:17621
server_time_usec:1752437126388046
uptime_in_seconds:204
uptime_in_days:0
hz:10
configured_hz:10
clients_hz:0
lru_clock:7606458
executable:/home/fusl/Projects/valkey-io/valkey/src/valkey-server
config_file:
io_threads_active:0
availability_zone:
listener0:name=tcp,bind=0.0.0.0,port=17621

# Clients
connected_clients:0
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0
paused_reason:none
paused_actions:none
paused_timeout_milliseconds:0

# Memory
used_memory:11419014720
used_memory_human:10.63G
used_memory_rss:12828397568
used_memory_rss_human:11.95G
used_memory_peak:12529414072
used_memory_peak_human:11.67G
used_memory_peak_perc:91.14%
used_memory_overhead:919376
used_memory_startup:912032
used_memory_dataset:11418095344
used_memory_dataset_perc:100.00%
allocator_allocated:11421611088
allocator_active:12561797120
allocator_resident:12834025472
allocator_muzzy:0
total_system_memory:67323842560
total_system_memory_human:62.70G
used_memory_lua:32768
used_memory_vm_eval:32768
used_memory_lua_human:32.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:33792
used_memory_vm_total:66560
used_memory_vm_total_human:65.00K
used_memory_functions:224
used_memory_scripts:224
used_memory_scripts_human:224B
maxmemory:137438953472
maxmemory_human:128.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.10
allocator_frag_bytes:1140186032
allocator_rss_ratio:1.02
allocator_rss_bytes:272228352
rss_overhead_ratio:1.00
rss_overhead_bytes:-5627904
mem_fragmentation_ratio:1.12
mem_fragmentation_bytes:1407234112
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:0
mem_cluster_links:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.3.0
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:1
lazyfree_pending_objects:0
lazyfreed_objects:22

# Persistence
loading:1
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:61674939
rdb_bgsave_in_progress:0
rdb_last_save_time:1752436922
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:150
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
loading_start_time:1752436922
loading_total_bytes:6663372508
loading_rdb_used_mem:15925932744
loading_loaded_bytes:5234993556
loading_loaded_perc:78.56
loading_eta_seconds:55

# Stats
total_connections_received:0
total_commands_processed:2250068
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
total_net_repl_input_bytes:0
total_net_repl_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:2
active_defrag_misses:1076
active_defrag_key_hits:2
active_defrag_key_misses:271
total_active_defrag_time:4
current_active_defrag_time:4
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:0
total_writes_processed:0
io_threaded_reads_processed:0
io_threaded_writes_processed:0
io_threaded_freed_objects:0
io_threaded_accept_processed:0
io_threaded_poll_processed:0
io_threaded_total_prefetch_batches:0
io_threaded_total_prefetch_entries:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:0
reply_buffer_expands:0
eventloop_cycles:0
eventloop_duration_sum:0
eventloop_duration_cmd_sum:0
instantaneous_eventloop_cycles_per_sec:0
instantaneous_eventloop_duration_usec:0
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0
acl_access_denied_tls_cert:0

# Replication
role:master
connected_slaves:0
replicas_waiting_psync:0
master_failover_state:no-failover
master_replid:46da14134766c921d77ace12b87012fb8bed96d4
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:67108864
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:14.599551
used_cpu_user:173.580877
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:14.586085
used_cpu_user_main_thread:173.577486

# Modules

# Commandstats

# Errorstats

# Latencystats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=150,expires=123,avg_ttl=0

------ CLIENT LIST OUTPUT ------

------ CURRENT CLIENT INFO ------
id=18446744073709551615 addr= laddr= fd=-1 name= age=53 idle=53 flags=x capa= db=0 sub=0 psub=0 ssub=0 multi=0 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=17024 events= cmd=multi user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=0 tot-net-out=0 tot-cmds=2250068
argc: 0

------ EXECUTING CLIENT INFO ------
id=18446744073709551615 addr= laddr= fd=-1 name= age=53 idle=53 flags=x capa= db=0 sub=0 psub=0 ssub=0 multi=0 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=17024 events= cmd=multi user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=0 tot-net-out=0 tot-cmds=2250068
argc: 0

------ MODULES INFO OUTPUT ------

------ CONFIG DEBUG OUTPUT ------
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
debug-context ""
activedefrag yes
lazyfree-lazy-user-flush yes
dual-channel-replication-enabled yes
lazyfree-lazy-eviction yes
proto-max-bulk-len 512mb
repl-diskless-load swapdb
slave-read-only yes
repl-diskless-sync yes
list-compress-depth 0
lazyfree-lazy-user-del yes
client-query-buffer-limit 512mb
sanitize-dump-payload no
io-threads 2
replica-read-only yes
import-mode no

------ FAST MEMORY TEST ------
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.392+00:00" level=warning message="Bio worker thread #0 terminated"
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.392+00:00" level=warning message="Bio worker thread #1 terminated"
pid=1300042 role=primary timestamp="2025-07-13T20:05:26.392+00:00" level=warning message="Bio worker thread #2 terminated"
^C1300042:signal-handler (1752437438) Received shutdown signal during loading, scheduling shutdown.
^C1300042:signal-handler (1752437441) You insist... exiting now.
```

### Additional information

One of our production Valkey servers running inside an Alpine container using `valkey/valkey:alpine` randomly crashed with the above crash report.

`Valkey server v=8.1.3 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=51271b665c2cd040` using Docker image `valkey/valkey:alpine` on `Linux sg-katana-b70r643 6.8.12-9-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-9 (2025-03-16T19:18Z) x86_64 GNU/Linux`

The crash also happens after restarting the server while replaying the AOF file so I tried copying the appendonlydir to my local machine, built Valkey from `unstable` and was able to reproduce the exact same crash during replaying the AOF file there.

Disabling `activedefrag` allows Valkey to start up without crashing. I created a permanent copy of the AOF base and journal file to be able to reproduce the bug at will and can share the files through a private channel if needed.

### PR DESCRIPTION
**Pull request by Fusl**
When querying large objects, the memory allocator may return allocation sizes (for example 4GiB, `4294967296`) that fit into the `out` array which is a `size_t` so the resulting `out` array becomes `{0, 1, 4294967296}`. When calculating the `region_size` we try to fit the allocation size into an `unsigned` which causes `4294967296` to overflow to `0`. With that 0, we unconditionally call `jeSize2BinIndexLgQ3` which _basically_ returns `sz-1`, so the return value becomes `-1`, overflowing the `unsigned binind` integer to `4294967295` which is far outside the length of `je_cb.bin_info` triggering the asserting sanity check.

Using `size_t` instead of `unsigned` for `region_size` ensures we can actually fit the allocated size into a variable and then return early on the `region_size > je_cb.bin_info[je_cb.nbins - 1].reg_size` check that follows right after.

Fixes https://github.com/valkey-io/valkey/issues/2348

Reproduction steps:

* Start up Valkey:
  ```
  valkey-server \
  --activedefrag no \
  --enable-debug-command local \
  --save '' \
  --active-defrag-cycle-min 99 \
  --active-defrag-threshold-lower 0 \
  --active-defrag-ignore-bytes 1
  ```
* Allocate a 10GiB string: `valkey-cli debug populate 1 '' 10737418240`
* Enable active defrag: `valkey-cli config set activedefrag yes`
* Valkey process crashes with `allocator_defrag.c:396 'binind < je_cb.nbins && region_size == je_cb.bin_info[binind].reg_size' is not true`

Unsure how to properly implement a test for this case considering it seemingly requires at least 10GiB to test. Open for suggestions.

### CODE REVIEW

File: src/allocator_defrag.c [hunk 1]
```diff
@@ -385,7 +385,7 @@ int allocatorShouldDefrag(void *ptr) {
     assert(SLAB_NUM_REGS(out, 0) > 0);
     assert(SLAB_LEN(out, 0) > 0);
     assert(SLAB_NFREE(out, 0) != (size_t)-1);
-    unsigned region_size = SLAB_LEN(out, 0) / SLAB_NUM_REGS(out, 0);
+    size_t region_size = SLAB_LEN(out, 0) / SLAB_NUM_REGS(out, 0);
```
Comment (zuiderkwast) [inline src/allocator_defrag.c:388]: This seems reasonable. Out is an array of size_t.

**Review by zuiderkwast — APPROVED** [review]
LGTM!

I don't think we need to add a test that requires 10GiB of memory. Possibly we could factor out some of these computations so we can verify them in unit tests, but it doesn't look trivial to me. We can merge it without a test. A few more eyes on it would be good though.

**Comment by zuiderkwast** [comment]
@zvi-code It would be great if you can take a look since you wrote this code and know it better than anyone.

**Comment by zvi-code** [comment]
Seems like a good catch, will take a look later today/tomorrow

**Review by zvi-code — APPROVED** [review]
LGTM

**Review by enjoy-binbin — APPROVED** [review]

**Comment by PingXie** [comment]
Looks like buster reached EoL already. given that this is a small change. I merged it without the test results. Also, I think this is a good candidate for backporting (8.1)

```
Run apt-get update && apt-get install -y build-essential
Ign:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
Ign:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 http://deb.debian.org/debian buster Release
  404  Not Found [IP: 146.75.94.132 80]
Err:5 http://deb.debian.org/debian-security buster/updates Release
  404  Not Found [IP: 146.75.94.132 80]
Err:6 http://deb.debian.org/debian buster-updates Release
  404  Not Found [IP: 146.75.94.132 80]
Reading package lists...
E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian-security buster/updates Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
/__w/_temp/cd6e3fe0-daaa-448e-b09f-76d9689007a0.sh: 2: /__w/_temp/cd6e3fe0-daaa-448e-b09f-76d9689007a0.sh: make: not found
```
