### PR TITLE
fix(HSETEX): replace strcmp with strcasecmp

### LINKED ISSUE #2996: [BUG] Incorrect handling of case sensitivity for HSETEX propagation
If you execute:
```
127.0.0.1:6379> HSETEX key nx fields 1 foo bar
(integer) 1
127.0.0.1:6379> HSETEX key2 NX fields 1 foo bar
(integer) 1
```

The replica will see:
```
1767388557.168465 [0 127.0.0.1:6379] "SELECT" "0"
1767388557.168533 [0 127.0.0.1:6379] "HSETEX" "key" "nx" "fields" "1" "foo" "bar"
1767388572.586961 [0 127.0.0.1:6379] "HSETEX" "key2" "fields" "1" "foo" "bar"
```

Tokens should be case insensitive, so we shouldn't be replicating the NX field in the first case. (Although not sure these are really needed).

The root cause seems to be calling `strcmp` here:
https://github.com/valkey-io/valkey/blob/15e79ef00a5e98a062776e7656ed34f834dd2d8a/src/t_hash.c#L1361

We should be calling `strcasecmp` instead.

### PR DESCRIPTION
**Pull request by frostzt**
HSETEX right now uses `strcmp` which does not account for case-insensitivity replaced it with `strcasecmp`.
Fixes #2996

### CODE REVIEW

File: src/t_hash.c [hunk 1]
```diff
@@ -38,6 +38,7 @@
 #include "vset.h"
 #include "server.h"
 #include "zmalloc.h"
+#include <_strings.h>
```
Comment (ranshid) [inline src/t_hash.c]: I don't think we ever include that explicitly anywhere else...

**Review by ranshid — COMMENTED** [review]
I would love if we can also include a test for this case.
Suggesting something like:
```
 test {HSETEX is not replicating validation arguments} {
        r flushall            
        set repl [attach_to_replication_stream]
        set exp [get_longer_then_long_expire_value PXAT]
        r HSETEX myhash NX PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash XX PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash FNX PXAT $exp FIELDS 1 f2 v2
        r HSETEX myhash FXX PXAT $exp FIELDS 1 f2 v2
        r HSETEX myhash nx PXAT $exp FIELDS 1 f3 v3
        r HSETEX myhash xx PXAT $exp FIELDS 1 f3 v3
        r HSETEX myhash fnx PXAT $exp FIELDS 1 f4 v4
        r HSETEX myhash fxx PXAT $exp FIELDS 1 f5 v5

        assert_replication_stream $repl [subst {
            {select *}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
            {hsetex myhash PXAT $exp FIELDS 1 f5 v5}
            {hsetex myhash PXAT $exp FIELDS 1 f5 v5}
        }]
        close_replication_stream $repl
    }
```

**Comment by ranshid** [comment]
@hanxizh9910 Note about this PR. I know you were also going to work on it

File: src/t_hash.c (hunk 1 above)
Comment (frostzt) [reply src/t_hash.c]: ah got it lemme get rid of it

**Comment by frostzt** [comment]
Hey @ranshid might need a little help with how tests work in valkey created a basic test as you suggested.

**Comment by ranshid** [comment]
> Hey @ranshid might need a little help with how tests work in valkey created a basic test as you suggested.

Thank you! 
So I think the test itself is fine, just maybe I would move it into a different test section. 
a test section usually starts with a `start_server` `start_cluster` which means it will spawn a valkey instance and operate the test commands on it.
In this case I think you used the correct test file (hashexpire.tcl) but I would move it into the section which focus on HSETEX command.
So I would place it after line 787 in unit/hashexpire.tcl, right after `test {HSETEX EX XX FXX - set only if key exists and all fields exist} ` and in your test replace `$primary` with `r`

**Comment by frostzt** [comment]
Thanks a lot @ranshid made the suggested changes! Got a few things hopefully I can pick more issues and get myself more familiar with the architecture.

File: tests/unit/hashexpire.tcl [hunk 2]
```diff
@@ -785,6 +785,33 @@ start_server {tags {"hashexpire"}} {
...
+
+        assert_replication_stream $repl [subst {
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
+            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
+            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
+            {hsetex myhash PXAT $exp FIELDS 1 f5 v5}
```
Comment (ranshid) [inline tests/unit/hashexpire.tcl]: Oooops, the last check is currently not replicated because it will only operate and replicate in case the field already exists

```suggestion
        r HSETEX myhash fxx PXAT $exp FIELDS 1 f4 v4

        assert_replication_stream $repl [subst {
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
```

Comment (ranshid) [reply tests/unit/hashexpire.tcl]: @frostzt do you want to take the suggestion? currently the tests are failing

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: Yep making the change!

Comment (ranshid) [reply tests/unit/hashexpire.tcl]: @frostzt Just as a general knowledge: there is a button "Sign off and commit suggestion" which you can use to merge the suggested changes to the source PR branch. In that case I will also be a co-author (if that is fine by you) and might make it easier for you. Just saying... :)

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: Oh I never trusted that lol lemme try it this time 😅

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: Alright done! Thanks a lot again haha

Comment (ranshid) [reply tests/unit/hashexpire.tcl]: Also on a side note: If you spend long time running the test only in order to test the specific fix in a specific test, you can try and run only a specific test file using `--single` and even skip all tests beside the one you target using `--only`
eg:
```
./runtest --single unit/hashexpire --only "HSETEX is not replicating validation arguments"
```

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: @ranshid should we have `{select 9}` in the `assert_replication_stream` I think that's missing

File: tests/unit/hashexpire.tcl [hunk 3]
```diff
@@ -785,6 +785,33 @@ start_server {tags {"hashexpire"}} {
...
+        r HSETEX myhash fnx PXAT $exp FIELDS 1 f4 v4
+        r HSETEX myhash fxx PXAT $exp FIELDS 1 f4 v4
+
+        assert_replication_stream $repl [subst {
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
+            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
```
Comment (frostzt) [inline tests/unit/hashexpire.tcl]: @ranshid this is the only thing that's getting overwritten right now! Are we expecting this? Here is what I got on my local machine adding `{select 9}`

Output:
```
{select 9}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f1 v1}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f1 v1}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f2 v2}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f2 v2}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f3 v3}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f4 v4}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f4 v4}
{}
```

Expected
```
{select 9}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f1 v1}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f1 v1}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f2 v2}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f2 v2}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f3 v3}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f3 v3}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f4 v4}
{hsetex myhash PXAT 1768660844326 FIELDS 1 f4 v4}
```

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: Um ok expecting the following works:
```
assert_replication_stream $repl [subst {
            {select 9}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
        }]
```

So `f3` is being overwritten?

Comment (ranshid) [reply tests/unit/hashexpire.tcl]: Oh sorry, also need a new object :)

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: Alright just pushed the changes this should be good

File: tests/unit/hashexpire.tcl [hunk 4]
```diff
@@ -785,6 +785,33 @@ start_server {tags {"hashexpire"}} {
...
+        assert_replication_stream $repl [subst {
+            {select 9}
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
+            {hsetex myhash PXAT $exp FIELDS 1 f3 v3}
+            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
+            {hsetex myhash PXAT $exp FIELDS 1 f4 v4}
+        }]
```
Comment (ranshid) [inline tests/unit/hashexpire.tcl:812]: `select *` should be fine as we are doing a regexp compare
```suggestion
        r HSETEX myhash NX PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash XX PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash FNX PXAT $exp FIELDS 1 f2 v2
        r HSETEX myhash FXX PXAT $exp FIELDS 1 f2 v2
        r HSETEX myhash2 nx PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash2 xx PXAT $exp FIELDS 1 f1 v1
        r HSETEX myhash2 fnx PXAT $exp FIELDS 1 f2 v2
        r HSETEX myhash2 fxx PXAT $exp FIELDS 1 f2 v2

        assert_replication_stream $repl [subst {
            {select *}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash2 PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash2 PXAT $exp FIELDS 1 f1 v1}
            {hsetex myhash2 PXAT $exp FIELDS 1 f2 v2}
            {hsetex myhash2 PXAT $exp FIELDS 1 f2 v2}
        }]
```

Comment (frostzt) [reply tests/unit/hashexpire.tcl:812]: haha this works too!

**Review by ranshid — APPROVED** [review]
LGTM! 
Thank you for your patience.
I will merge as soon as the tests pass

File: tests/unit/hashexpire.tcl [hunk 5]
```diff
@@ -785,6 +785,34 @@ start_server {tags {"hashexpire"}} {
...
+        r HSETEX myhash XX PXAT $exp FIELDS 1 f1 v1
+        r HSETEX myhash FNX PXAT $exp FIELDS 1 f2 v2
+        r HSETEX myhash FXX PXAT $exp FIELDS 1 f2 v2
+        r HSETEX myhash2 nx PXAT $exp FIELDS 1 f1 v1
+        r HSETEX myhash2 xx PXAT $exp FIELDS 1 f1 v1
+        r HSETEX myhash2 fnx PXAT $exp FIELDS 1 f2 v2
+        r HSETEX myhash2 fxx PXAT $exp FIELDS 1 f2 v2
+
+        assert_replication_stream $repl [subst {
+            {select 9}
```
Comment (ranshid) [inline tests/unit/hashexpire.tcl]:
```suggestion
            {select *}
```

Comment (ranshid) [reply tests/unit/hashexpire.tcl]: we still need that, since in some tests we might use a different database

Comment (frostzt) [reply tests/unit/hashexpire.tcl]: done thanks a lot!

**Comment by frostzt** [comment]
Thanks a lot @ranshid for guiding me through this! Means a lot honestly. I'll start actively looking at issues at Valkey and hopefully will be able to pick up more things to work on.

**Comment by dvkashapov** [comment]
@ranshid Looks like this assertion failure is related but this PR did not really cause it, rather exposed something that was here before, WDYT? https://github.com/valkey-io/valkey/actions/runs/20684919495/job/59384044366
I've taken a quick look and seems that in `dbSetValue()` we have to handle case where old robj is a hash with volatile fields. My idea is that currently we're leaving a stale pointer in `keys_with_volatile_items` pointing to an object that's no longer a hash.

**Comment by frostzt** [comment]
> @ranshid Looks like this assertion failure is related but this PR did not really cause it, rather exposed something that was here before, WDYT? https://github.com/valkey-io/valkey/actions/runs/20684919495/job/59384044366 I've taken a quick look and seems that in `dbSetValue()` we have to handle case where old robj is a hash with volatile fields. My idea is that currently we're leaving a stale pointer in `keys_with_volatile_items` pointing to an object that's no longer a hash.

Hey @dvkashapov @ranshid I tried out what you said and seems like we run into an assertion error here's what I did I ran the following:
```
127.0.0.1:6379> HSETEX myhash EX 100 FIELDS 1 field1 value1
(integer) 1
127.0.0.1:6379> keys *(
(empty array)
127.0.0.1:6379> keys *
1) "myhash"
127.0.0.1:6379> info keyspace
# Keyspace
db0:keys=1,expires=0,avg_ttl=0,keys_with_volatile_items=1
127.0.0.1:6379> info keyspace
# Keyspace
db0:keys=1,expires=0,avg_ttl=0,keys_with_volatile_items=1
127.0.0.1:6379> SET myhash "I'm a string now"
OK
127.0.0.1:6379>
```

The moment I ran the last the `valkey-server` crashed with the following:
```

=== VALKEY BUG REPORT START: Cut & paste starting from here ===
51921:M 04 Jan 2026 15:34:36.393 # === ASSERTION FAILED ===
51921:M 04 Jan 2026 15:34:36.393 # ==> t_hash.c:72 'o->type == OBJ_HASH' is not true

------ STACK TRACE ------

Backtrace:
0   valkey-server                       0x00000001044427bc fieldExpireScanCallback + 3368
1   valkey-server                       0x00000001043260f0 hashtableScanDefrag + 1248
2   valkey-server                       0x0000000104328290 kvstoreScan + 284
3   valkey-server                       0x0000000104442d58 activeExpireCycleJob + 768
4   valkey-server                       0x00000001044429cc activeExpireCycle + 264
5   valkey-server                       0x000000010432f5a8 serverCron + 2096
6   valkey-server                       0x0000000104320aa8 aeProcessEvents + 672
7   valkey-server                       0x000000010434ad98 main + 27228
8   dyld                                0x0000000197d69d54 start + 7184

------ STACK TRACE DONE ------
```

I assume the job that runs to clean this up fails in this function because `myhash` is now a `string`
```
bool hashTypeHasVolatileFields(robj *o) {
    if (o == NULL) return false;
    serverAssert(o->type == OBJ_HASH);
    if (o->encoding == OBJ_ENCODING_HASHTABLE) {
        vset *set = hashTypeGetVolatileSet(o);
        if (set && !vsetIsEmpty(set))
            return true;
    }
    return false;
}
```
I have a commit ready for this would be happy to raise a PR and you can check it once hopefully?
My idea here being, 
1. Check if old object was a hash with volatile fields
2. Check if new object is a hash with volatile fields  
3. Update `keys_with_volatile_items` accordingly:
   - **Untrack** if old was tracked and new isn't
   - **Update pointer** if both are tracked
   - **Track** if new is tracked and old wasn't

**Comment by dvkashapov** [comment]
> My idea here being,
Check if old object was a hash with volatile fields
Check if new object is a hash with volatile fields
Update keys_with_volatile_items accordingly:
Untrack if old was tracked and new isn't
Update pointer if both are tracked
Track if new is tracked and old wasn't

Makes sense to me, let’s wait for @ranshid to take a look

**Comment by ranshid** [comment]
@dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.

**Comment by frostzt** [comment]
> @dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.

@ranshid if the above looks good I can raise a PR?

**Comment by ranshid** [comment]
> > @dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.
> 
> @ranshid if the above looks good I can raise a PR?

I prefer to handle this in dbSetValue as suggested by @dvkashapov

**Comment by frostzt** [comment]
> > > @dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.
> 
> > 
> 
> > @ranshid if the above looks good I can raise a PR?
> 
> 
> 
> I prefer to handle this in dbSetValue as suggested by @dvkashapov 

Awesome I'll check and raise a PR with the changes as suggested by @dvkashapov

**Comment by ranshid** [comment]
> > > > @dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.
> > 
> > 
> > > 
> > 
> > 
> > > @ranshid if the above looks good I can raise a PR?
> > 
> > 
> > I prefer to handle this in dbSetValue as suggested by @dvkashapov
> 
> Awesome I'll check and raise a PR with the changes as suggested by @dvkashapov

should be something like:
```
diff --git a/src/db.c b/src/db.c
index af336a60e..ab0f019d0 100644
--- a/src/db.c
+++ b/src/db.c
@@ -335,6 +335,10 @@ static void dbSetValue(serverDb *db, robj *key, robj **valref, int overwrite, vo
         moduleNotifyKeyUnlink(key, old, db->id, DB_FLAG_KEY_OVERWRITE);
         /* We want to try to unblock any module clients or clients using a blocking XREADGROUP */
         signalDeletedKeyAsReady(db, key, old->type);
+        /* If overwriting a hash object, un-track it from the volatile items tracking if it contains volatile items.*/
+        if (old->type == OBJ_HASH && hashTypeHasVolatileFields(old)) {
+            dbUntrackKeyWithVolatileItems(db, old);
+        }
         decrRefCount(old);
         /* Because of VM_StringDMA, old may be changed, so we need get old again */
         old = *oldref;
```

**Comment by frostzt** [comment]
> > > > > @dvkashapov spot on! this is indeed a bug (from 9.0) - I agree we need a fix for the setKey flow.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > @ranshid if the above looks good I can raise a PR?
> > > 
> > > 
> > > I prefer to handle this in dbSetValue as suggested by @dvkashapov
> > 
> > 
> > Awesome I'll check and raise a PR with the changes as suggested by @dvkashapov
> 
> should be something like:
> 
> ```
> diff --git a/src/db.c b/src/db.c
> index af336a60e..ab0f019d0 100644
> --- a/src/db.c
> +++ b/src/db.c
> @@ -335,6 +335,10 @@ static void dbSetValue(serverDb *db, robj *key, robj **valref, int overwrite, vo
>          moduleNotifyKeyUnlink(key, old, db->id, DB_FLAG_KEY_OVERWRITE);
>          /* We want to try to unblock any module clients or clients using a blocking XREADGROUP */
>          signalDeletedKeyAsReady(db, key, old->type);
> +        /* If overwriting a hash object, un-track it from the volatile items tracking if it contains volatile items.*/
> +        if (old->type == OBJ_HASH && hashTypeHasVolatileFields(old)) {
> +            dbUntrackKeyWithVolatileItems(db, old);
> +        }
>          decrRefCount(old);
>          /* Because of VM_StringDMA, old may be changed, so we need get old again */
>          old = *oldref;
> ```

Hey @ranshid and @dvkashapov raised a PR for this (#3003) sorry for the delay 😅
