### PR TITLE
Skip large-memory unit test with ASan that go OOM

### LINKED ISSUE #3221: [TEST-FAILURE] Large Memory Daily Test Failures
**Summary**

We are seeing consistent daily test failures in the large memory tests after the test `EVAL - JSON string encoding a string larger than 2GB`. These tests seem to be failing due to memory exhaustion where the server is left in a memory-stressed state. This causes the subsequent tests to fail.

**Failing test(s)**

- Test name: test-sanitizer-undefined-large-memory (clang) / (gcc) and test-sanitizer-adress-large-memory (clang) / (gcc)
- CI link(s): 
       - https://github.com/valkey-io/valkey/actions/runs/21928373787/job/63326360089
       - https://github.com/valkey-io/valkey/actions/runs/21928373787/job/63326360092

### PR DESCRIPTION
**Pull request by Nikhil-Manglore**
The `test_quicklistCompressAndDecompressQuicklistListpackNode` unit test was failing with ASan in CI with OOM errors. The test was allocating and compressing up to 1GB of data (32 iterations × 32MB), which exceeded available memory in CI environments. The test is skipped for ASan builds.

This PR addressed the unit test failures in `test-sanitizer-address-large-memory` for both GCC and CLANG

Test Run: https://github.com/Nikhil-Manglore/valkey/actions/runs/22159517734/job/64072360332

Resolves #3221

### CODE REVIEW

**Review by sarthakaggarwal97 — APPROVED** [review]
Thanks @Nikhil-Manglore for helping with this one. LGTM!

**Review by dvkashapov — APPROVED** [review]

**Review by roshkhatri — COMMENTED** [review]
The runners have 16GB RAM : https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
I want to make sure we are not changing anything that would create a test gap.
What is the available memory in CI environments?

File: src/unit/test_quicklist.c [hunk 1]
```diff
@@ -2226,8 +2226,8 @@ int test_quicklistCompressAndDecompressQuicklistListpackNode(int argc, char **ar
     unsigned char *s = zmalloc(sz);
     randstring(s, sz);
 
-    /* Keep filling the node, until it reaches 1GB */
-    for (int i = 0; i < 32; i++) {
+    /* Keep filling the node, until it reaches 256MB */
+    for (int i = 0; i < 8; i++) {
```
Comment (zuiderkwast) [inline src/unit/test_quicklist.c]: I agree with @roshkhatri. There's a risk we're creating a test gap if we test only smaller sizes.

Let's use `#ifdef __SANITIZE_ADDRESS__` to skip it only for santitizers?

Comment (zuiderkwast) [inline src/unit/test_quicklist.c]: We could, instead of reducing the final size below 1GB, add more bytes per round so we reach 1GB in 8 rounds? We can change `1 << 32` to `1 << 34`.

With fewer reallocs maybe ASAN would use less total memory.

Comment (sarthakaggarwal97) [reply src/unit/test_quicklist.c]: Yes, we can do this only for ASan.

Comment (Nikhil-Manglore) [reply src/unit/test_quicklist.c]: I tried `1 << 27` (128 mb for 8 rounds) but still ran into timeouts. I think skipping the test for ASAN is the best option.

File: src/unit/test_quicklist.c [hunk 2]
```diff
@@ -2213,6 +2213,11 @@ int test_quicklistCompressAndDecompressQuicklistListpackNode(int argc, char **ar
 
     if (!(flags & UNIT_TEST_LARGE_MEMORY)) return 0;
 
+#ifdef VALKEY_ADDRESS_SANITIZER
+    /* Skip this test under sanitizers */
```
Comment (zuiderkwast) [inline src/unit/test_quicklist.c]:
```suggestion
    /* Skip this test under sanitizers to avoid OOM in github actions */
```

File: src/unit/test_quicklist.c (hunk 1 above)
Comment (zuiderkwast) [reply src/unit/test_quicklist.c]: Of course 1 << 27. What was i thinking...

Ok, it didn't work, so yeah lets skip it for Asan to make it green.

**Review by zuiderkwast — APPROVED** [review]
