### PR TITLE
Optimize cluster failure report

### LINKED ISSUE #2139: [NEW] Performance bottleneck in clusterNodeCleanupFailureReports under heavy failure load
The current implementation of `clusterNodeCleanupFailureReports` walks the entire fail reports in the list on every invocation and performs a listDelNode() for each expired or non‑voting entry. When a cluster node has accumulated hundreds or thousands of failure reports, this function becomes a CPU hotspot.

https://github.com/valkey-io/valkey/blob/3ceae81fc4cf065dae00888ab92b7aa069fde111/src/cluster_legacy.c#L1702-L1721

Image
Image
(The above result was observed during a 2,000‑node cluster failover scenario)

**Current behavior:**
- Where N is the number of failure reports, O(N) scan on every call, regardless of how many reports are actually expired.

**Improvement ideas:**
- ~~Use a priority queue with expiration time, so expired nodes can be removed in O(RlogN) rather than scanned in full. (R is # of actually expired reports)~~
- Use lazy deletion instead of removing them on every call
- Use early exit when meeting quorum

### PR DESCRIPTION
**Pull request by sungming2**
Closes https://github.com/valkey-io/valkey/issues/2139

### Summary
The original implementation used a simple list to track failure reports, which made core operations (update, delete, and cleanup) run in O(N) time. This became a serious bottleneck when many nodes failed simultaneously, as each new report or cleanup operation required scanning the entire list regardless of whether the reports were expired or still valid. This led to severe performance degradation under high failure scenarios due to repeated full list scans and inefficient lookups.

### Key changes
This PR replaces the legacy fail_reports list with a new report implementation that uses radix tree to manage failure reports more efficiently and robustly.
This is the simplest and most targeted fix: we keep just the radix tree to maintain sorted reports. This avoids adding a new composite structure or changing the core failure report API. It directly addresses the main bottleneck: clusterNodeCleanupFailureReports() by enabling fast expiration with minimal code change. it’s sufficient and easy to maintain.
To reduce memory overhead and excessive node splits caused by millisecond level keys, we need to round expiry timestamps up to the nearest second. This time bucketing keeps rax structure compact enough.

### Performance Test
The test is performed on m7g.2xlarge with 2000 nodes cluster (1000 primaries/1000 replicas)

* Original implementation shows  100% CPU utilization during 300 nodes failover. In this case, `cleanupFailreReports` accounts for around 60% of the total CPU usage.
image
image
image

* Current implemenation shows ~30% CPU utilization during 450 nodes failover. (Tested multiple times)
image

### CODE REVIEW

**Review by hpatro — COMMENTED** [review]
High level cursory thought:

If we plan to introduce Linked List + hashtable combination to reduce the time complexity, I would prefer to be independent API(s) to consume. Currently, it looks quite easy to introduce bugs and difficult to unit test.

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -1664,109 +1670,100 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
-        fr = ln->value;
-        if (fr->node == sender) {
-            fr->time = now;
-            return 0;
-        }
+    mstime_t expiry = now + server.cluster_node_timeout * CLUSTER_FAIL_REPORT_VALIDITY_MULT;
+
+    clusterNodeFailReport *f = failing->fail_report;
+    sds sender_name = sdsnewlen(sender->name, CLUSTER_NAMELEN);
+    clusterNodefailReportEntry *e = dictFetchValue(f->reports, sender_name);
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: let's have a more descriptive variable name.

File: src/cluster_legacy.c [hunk 2]
```diff
@@ -1664,109 +1670,100 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    int new_report = 0;
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: do we need a new variable? if yes, can we prefix it with `is_` since it's used like a bool

File: src/cluster_legacy.c [hunk 3]
```diff
@@ -1664,109 +1670,100 @@ clusterNode *createClusterNode(char *nodename, int flags) {
     node->tcp_port = 0;
     node->cport = 0;
     node->tls_port = 0;
-    node->fail_reports = listCreate();
+    node->fail_report = zmalloc(sizeof(*node->fail_report));
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: if we have a init function, should we merge these two statements.

File: src/cluster_legacy.h [hunk 4]
```diff
@@ -71,10 +71,18 @@ typedef struct clusterLink {
...
+} clusterNodefailReportEntry;
+
 /* This structure represent elements of node->fail_reports. */
-typedef struct clusterNodeFailReport {
-    clusterNode *node; /* Node reporting the failure condition. */
-    mstime_t time;     /* Time of the last report from this node. */
+typedef struct {
+    dict *reports;     /* Hash table of node name -> clusterNodefailReportEntry structure */
+    list *expiry_list; /* Entries in ascending expiry order */
+    int report_count;  /* Number of active reports */
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.h]: do we need this `report_count` variable?

**Review by sarthakaggarwal97 — COMMENTED** [review]
Took an initial look at the approach. It's nice to see the improvement in time complexity but I am unsure how to test it.

File: src/cluster_legacy.c (hunk 3 above)
Comment (sungming2) [reply src/cluster_legacy.c]: Yes, I will address similar things while working on API(s), thanks

File: src/cluster_legacy.h (hunk 4 above)
Comment (sungming2) [reply src/cluster_legacy.h]: This is a good point, we can use list len instead. thanks

File: src/cluster_legacy.h [hunk 5]
```diff
@@ -364,7 +372,7 @@ struct _clusterNode {
     int cport;                              /* Latest known cluster port of this node. */
     clusterLink *link;                      /* TCP/IP link established toward this node */
     clusterLink *inbound_link;              /* TCP/IP link accepted from this node */
-    list *fail_reports;                     /* List of nodes signaling this as failing */
+    clusterNodeFailReport *fail_report;     /* List of nodes signaling this as failing */
```
Comment (sungming2) [inline src/cluster_legacy.h]: Comment should be changed

**Comment by hpatro** [comment]
@sungming2 I was alluding to introducing a separate data structure file, let's say lru_cache.h/lru_cache.c and use it from methods in cluster file. Through that we could add unit test to the add/remove functionality of lru_cache.c/lru_cache.h.

The API(s) could be:

lruNew, lruPut, lruGet, lruDelete, lruFree

**Comment by hpatro** [comment]
> @sungming2 I was alluding to introducing a separate data structure file, let's say lru_cache.h/lru_cache.c and use it from methods in cluster file. Through that we could add unit test to the add/remove functionality of lru_cache.c/lru_cache.h.
> 
> The API(s) could be:
> 
> lruNew, lruPut, lruGet, lruDelete, lruFree

@madolson / @sarthakaggarwal97 do you agree with this approach ? I agree with @sungming2's approach about the usage of this data structure. I couldn't think of any other alternative to address the high CPU utilization.

**Comment by sarthakaggarwal97** [comment]
> @madolson / @sarthakaggarwal97 do you agree with this approach ? I agree with @sungming2's approach about the usage of this data structure. I couldn't think of any other alternative to address the high CPU utilization.

yeah the data structures look fine to me. I had this idea where we can use expiry timestamp as the key in dictionary, the values could be the list of nodes and evict based on current time. But I haven't put a lot of thought if this can address the problem.

File: src/cluster_legacy.c [hunk 6]
```diff
@@ -1664,118 +1665,65 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    return removed;
 }
 
 /* Return the number of external nodes that believe 'node' is failing,
  * not including this node, that may have a PFAIL or FAIL state for this
  * node as well. */
 int clusterNodeFailureReportsCount(clusterNode *node) {
-    clusterNodeCleanupFailureReports(node);
-    return listLength(node->fail_reports);
+    return expirySetCount(node->fail_report);
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: do we not free the expired failed reports anymore before retrieving the count?

File: src/cluster_legacy.c [hunk 7]
```diff
@@ -2255,6 +2205,8 @@ void clearNodeFailureIfNeeded(clusterNode *node) {
         node->flags &= ~CLUSTER_NODE_FAIL;
         clusterDoBeforeSleep(CLUSTER_TODO_UPDATE_STATE | CLUSTER_TODO_SAVE_CONFIG);
     }
+
+    clusterNodeCleanupFailureReports(node);
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: why did we add this call here?

File: src/expiry_set.c [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+ * then frees the entry object. */
+void expirySetRemoveEntry(ExpirySet *es, ExpirySetEntry *es_entry) {
+    if (es == NULL || es_entry == NULL) return;
+    listDelNode(es->expiry_list, es_entry->ln);
+    dictDelete(es->dict, es_entry->key);
+    zfree(es_entry);
+}
+
+/* Allocate and initialize a new ExpirySet. */
+ExpirySet *expirySetCreate(dictType *dt) {
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: I think Init or Initialize might sound better here.

File: src/expiry_set.c [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+    } else {
+        /* new entry */
+        es_entry = zmalloc(sizeof(*es_entry));
+        es_entry->key = key;
+        es_entry->expiry = expiry;
+        dictAdd(es->dict, key, es_entry);
+        is_new = 1;
+    }
+    /* append at tail (most recently used/updated) */
+    listAddNodeTail(es->expiry_list, es_entry);
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: can this be unordered ever?

File: src/expiry_set.c [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+    dictDelete(es->dict, es_entry->key);
+    zfree(es_entry);
+}
+
+/* Allocate and initialize a new ExpirySet. */
+ExpirySet *expirySetCreate(dictType *dt) {
+    assert(dt != NULL);
+    ExpirySet *es = zmalloc(sizeof(*es));
+    if (!es) return NULL;
+    es->dict = dictCreate(dt);
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: can we put some guardrails to ensure both dict and list are created? if any of them fails, we error out and free the resources? Let's see if we can add the test for it as well.

File: src/expiry_set.c [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+/* Add a new key with its expiry timestamp, or refresh an existing one. */
+int expirySetAdd(ExpirySet *es, void *key, mstime_t expiry) {
+    assert(es && key);
+    ExpirySetEntry *es_entry = dictFetchValue(es->dict, key);
+    int is_new = 0;
+    if (es_entry) {
+        /* refresh expiry */
+        listDelNode(es->expiry_list, es_entry->ln);
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: can the refresh actually make the list unordered?

Something like this sequence?

Initial sequence
```
Head →  A(exp=1000)  B(exp=2000)
```

A is refreshed
```
Head →  B(exp=2000)  A(exp=3000)
```

C is added but has lesser time of expiry

```
Head →  B(2000)  A(3000)  C(1500)   ← out of order
```

We should have some validation in order to ensure that the list if never out of order. If the order breaks, so does the API.

Comment (sarthakaggarwal97) [reply src/expiry_set.c]: We should have a test to ensure this validation as well.

File: src/unit/test_expiry_set.c [hunk 12]
```diff
@@ -0,0 +1,121 @@
+#include <stdint.h>
```
Comment (sarthakaggarwal97) [inline src/unit/test_expiry_set.c]: we might need more tests which plays with staggered expiries, possible unordered nature, same expiry elements etc

**Review by sarthakaggarwal97 — COMMENTED** [review]
Took a look at the APIs. I might have to think more if we can break something we these API but dropped few comments for you till then. Thanks for following up on this,

File: src/cluster_legacy.c (hunk 6 above)
Comment (sungming2) [reply src/cluster_legacy.c]: We free the expired reports
```
int expirySetCount(ExpirySet *es) {
    assert(es);
    expirySetExpire(es);
    return es->expiry_list->len;
}
```

File: src/cluster_legacy.c (hunk 7 above)
Comment (sungming2) [reply src/cluster_legacy.c]: Whenever a node previously marked FAIL becomes reachable again, any stale failure reports can be purged with this. It is not harmful, even if there are no expired reports.

File: src/expiry_set.c (hunk 8 above)
Comment (sungming2) [reply src/expiry_set.c]: Yeah that makes sense but I was referring to what we have

https://github.com/valkey-io/valkey/blob/e279b00f854b7b4cfe06f8a3eb7c89fd7ce25bdc/src/adlist.c#L44

https://github.com/valkey-io/valkey/blob/e279b00f854b7b4cfe06f8a3eb7c89fd7ce25bdc/src/dict.c#L184

File: src/expiry_set.c (hunk 10 above)
Comment (sungming2) [reply src/expiry_set.c]: I think this is a good idea, thanks

File: src/expiry_set.c (hunk 8 above)
Comment (sarthakaggarwal97) [reply src/expiry_set.c]: ok. if there is precedence then let's follow the existing format.

File: src/cluster_legacy.c (hunk 7 above)
Comment (sarthakaggarwal97) [reply src/cluster_legacy.c]: Wouldn't it take compute? My concern is that we didn't have this before, so why do we need to add it now?

File: src/cluster_legacy.c (hunk 6 above)
Comment (sarthakaggarwal97) [reply src/cluster_legacy.c]: okay wrapper around `expirySetExpire` is fine.

File: src/expiry_set.c (hunk 11 above)
Comment (sungming2) [reply src/expiry_set.c]: You are right, because it basically requires monotonic expiry such as
```
expiry = now + CONSTANT_WINDOW;
```
so each new or refreshed expiry is strictly greater than any existing expiry. 

I might need to think more about this case, but now what I can do is:

```
expirySetAdd(ExpirySet *es, void *key, mstime_t expiry)
  if (expiry >= list->tail->expiry)
     add the node to the tail
  else
     scan from tail backward to insert the node
     
```

With this, 
1. O(1) insertion for monotonic case
2. O(N) insertion for arbitrary case
while other operations are still in O(1)

What do you think about this approach?

File: src/expiry_set.c (hunk 9 above)
Comment (sungming2) [reply src/expiry_set.c]: same comment

File: src/unit/test_expiry_set.c (hunk 12 above)
Comment (sungming2) [reply src/unit/test_expiry_set.c]: I agree with that

File: src/expiry_set.c [hunk 13]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+/* Expire all entries whose timestamp ≤ now. */
+int expirySetExpire(ExpirySet *es) {
+    assert(es);
+    int removed = 0;
+    listNode *ln;
+    mstime_t now = mstime();
+    /* expire from head while expiry ≤ now */
+    while ((ln = listFirst(es->expiry_list))) {
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: Can this be O(N)? I see that we might be exiting early due to sorted nature of the data structure, but can we end up looping through all entries?

File: src/expiry_set.c (hunk 11 above)
Comment (sarthakaggarwal97) [reply src/expiry_set.c]: I think I am ok with this approach. I am kind of on the fence for keeping this data structure strictly increasing as well. We can discuss the pros and cons. @hpatro if you have any thoughts on this.

File: src/expiry_set.c (hunk 13 above)
Comment (sungming2) [reply src/expiry_set.c]: > Can this be O(N)?

Yes, I already mentioned in the description that it takes `O(1) per expired entry`

Comment (hpatro) [reply src/expiry_set.c]: This should be termed as O(N).

File: src/expiry_set.c [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+        expirySetRemoveEntry(es, es_entry);
+    }
+    dictRelease(es->dict);
+    listRelease(es->expiry_list);
+    zfree(es);
+}
+
+/* Add a new key with its expiry timestamp, or refresh an existing one. */
+int expirySetAdd(ExpirySet *es, void *key, mstime_t expiry) {
+    assert(es && key);
```
Comment (hpatro) [inline src/expiry_set.c]: Some of these check could just be implicit i.e. usage of these API dictates the user to send valid values. Look at hashtable.c for example. We can avoid assert check throughout the file

File: src/expiry_set.c (hunk 11 above)
Comment (hpatro) [reply src/expiry_set.c]: I think we should have ordered insertion, we could further optimize the time complexity of insertion if we want to in the future.

File: src/expiry_set.c [hunk 15]
```diff
@@ -0,0 +1,111 @@
...
+    ExpirySet *es = zmalloc(sizeof(*es));
+    if (!es) return NULL;
+    es->dict = dictCreate(dt);
+    es->expiry_list = listCreate();
+    return es;
+}
+
+/* Destroy an ExpirySet and free all resources. */
+void expirySetFree(ExpirySet *es) {
+    if (!es) return;
```
Comment (hpatro) [inline src/expiry_set.c]: Remove.

File: src/expiry_set.h [hunk 16]
```diff
@@ -0,0 +1,46 @@
...
+ *  - Any scenario where you need to keep a set of pointers, support
+ *    fast add/remove, and periodically purge expired entries.
+ */
+
+/* Internal entry struct */
+typedef struct ExpirySetEntry {
+    void *key;       /* Key */
+    mstime_t expiry; /* Expiry time */
+    listNode *ln;    /* Back pointer into expiry_list */
+} ExpirySetEntry;
```
Comment (hpatro) [inline src/expiry_set.h]: Can't the listNode have key and expiry in it? We could avoid the back pointer altogether with that.

**Comment by sungming2** [comment]
CPU utilization with updated changes during the 450 primaries failover

화면 캡처 2025-07-10 220950
화면 캡처 2025-07-10 220850
화면 캡처 2025-07-10 220859

File: src/cluster_legacy.c [hunk 17]
```diff
@@ -1850,12 +1799,14 @@ void freeClusterNode(clusterNode *n) {
     if (n->link) freeClusterLink(n->link);
     if (n->inbound_link) freeClusterLink(n->inbound_link);
 
+    /* Free all entries in the expiry_list */
+    expirySetFree(n->fail_report);
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: I think I probably asked this before, but why are we executing this when we didn't have to do this before? I am basing this on the like for like comparison from previous to current logic.

Comment (sungming2) [reply src/cluster_legacy.c]: I think you are talking about this, which I removed in the latest commit. Freeing the failure report in `freeClusterNode` is what we have been doing.

```
@@ -2255,6 +2205,8 @@ void clearNodeFailureIfNeeded(clusterNode *node) {
        node->flags &= ~CLUSTER_NODE_FAIL;
        clusterDoBeforeSleep(CLUSTER_TODO_UPDATE_STATE | CLUSTER_TODO_SAVE_CONFIG);
    }

    clusterNodeCleanupFailureReports(node); <<
```

File: src/expiry_set.c [hunk 18]
```diff
@@ -0,0 +1,187 @@
...
+        expirySetRemove(es, key);
+        return 0;
+    }
+    return 1;
+}
+
+/* Retrieve the expiry timestamp for the key.
+ * If the expiry ≤ current time, it is removed and treated as missing.
+ * Returns 1 if key exists, 0 otherwise */
+int expirySetGetExpiry(ExpirySet *es, void *key, mstime_t *out_expiry) {
```
Comment (sarthakaggarwal97) [inline src/expiry_set.c]: Is this API being used anywhere?

File: src/expiry_set.c [hunk 19]
```diff
@@ -0,0 +1,187 @@
...
+ * It maintains:
+ *  - A hash table mapping each key directly to its list node for constant-time lookup and removal.
+ *  - A doubly‐linked list of ExpirySetItem structs, always keep in ascending order
+ *        of expiry so that all expired entries can be purged by scanning
+ *        from the head.
+ *
+ * Common use cases:
+ *  - Cluster failure reporting: track per-node failure votes with automatic
+ *    eviction once they age out.
+ *  - TTL-based caches: insert items with individual timeouts and expire
```
Comment (zuiderkwast) [inline src/expiry_set.c]: The purpose of this "expiry set" looks a bit similar to the "volatile set" introduced for hash field expiration by @ranshid in another PR.

The purposes of these are not exactly the same but the names are setting up a trap for potential confusion.

Would it be possible to reuse something here?

Comment (sungming2) [reply src/expiry_set.c]: Yes, they do look similar, but I think the core goal is different.
The expiry_set is time complexity optimized, supporting O(1) by key. In contrast, volatile_set encodes expiry and pointer into a radix key for space efficiency that each operation always requires O(L) (where L is the key length) to traverse the tree.
I initially thought about using radix tree with expiry too, but I chose this structure to maximize the performance in terms of time complexity, which was the main bottleneck of this issue and maintaining expiry+pointer as a key is more error-prone in updating an existing record (likely causing orphaned key in the structure)


I'm very open to better naming ideas. Now the options I can think of are ttl_set or ttl_map.

**Comment by hpatro** [comment]
@sungming2 is currently evaluating if vset would do the job. We will get back soon on this.

**Comment by sungming2** [comment]
There have been multiple solutions discussed for improving failure report handling. Each has different trade offs in terms of complexity, maintainability, and performance:

1. List (original failure report)
A simple linked list of reports, but operations like refresh, removal, and expiration all require full scans (O(N)), making it inefficient at scale.

2. Dict + List
Adds a dictionary for O(1) lookup, update, and removal of failure reports. The list still holds reports in insertion order, so sorting is done during insertions. While it improves access performance, maintaining both structures adds code complexity.

3. Dict + RAX
Similar to (dict+list), but uses a radix tree to maintain sorted order automatically. This reduces code for ordering and makes expiration scans more efficient. Still requires managing two structures.

4. Dict + VSET ([vset link](https://github.com/ranshid/valkey/pull/5/files#diff-832c5602f4c0f09926bba2f8008287209d9b6c4e22b1248805608a6a5a5058b1))
Similar to (dict+rax), vset uses hybrid structure that internally switches between vector, rax, and hash representations based on number of entries with timebucket mechanism. While promising in theory, the API is restrictive, and it’s currently optimized for hash field expirations. May not generalize well for our case without additional API work and it still needs two structures.

5. RAX only
This is the simplest and most targeted fix: we keep just the radix tree to maintain sorted reports. This avoids adding a new composite structure or changing the core failure report API. It directly addresses the main bottleneck: clusterNodeCleanupFailureReports() by enabling fast expiration with minimal code change. it’s sufficient and easy to maintain.
To reduce memory overhead and excessive node splits caused by millisecond level keys, we need to round expiry timestamps up to the nearest second. This time bucketing keeps rax structure compact enough.

In short, I think rax only is a minimal, targeted fix that improves cleanup efficiency while keeping the implementation clean and focused.

| **Operation**                    | **list (original)**                                                                                          | **rax**                                                                                      | **dict + list**                                                                                                         | **dict + radix**                                                                                                              |
|----------------------------------|--------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| **Add new report**              | O(1) (add tail)                                                                                              | O(L)=O(1) (raxInsert)                                                                         | O(1) (dict lookup)  <br> O(N) (scan list backward worst‑case) <br> O(1) (list insert/delete) <br> O(1) (dictReplace) <br> **Overall:** O(N) worst‑case, O(1) monotonic-case | O(1) (dict lookup) <br> O(L) (raxInsert) <br> O(1) (dictAdd) <br> **Overall:** O(L)=O(1)                                  |
| **Refresh existing report**     | O(N) (full-scan update)                                                                                       | O(N) (full-scan update)                                                                       | O(1) (dict lookup) <br> O(1) (list insert/delete) <br> O(1) (dictReplace) <br> **Overall:** O(1)                         | O(1) (dict lookup) <br> O(L) (raxRemove) <br> O(L) (raxInsert) <br> O(1) (dictReplace) <br> **Overall:** O(L)=O(1)           |
| **Remove a report early**       | O(N) (full-scan remove)                                                                                       | O(N) (full-scan remove)                                                                       | O(1) (dict lookup) <br> O(1) (listDelNode) <br> O(1) (dictDelete) <br> **Overall:** O(1)                                 | O(1) (dict lookup) <br> O(L) (raxRemove) <br> O(1) (dictDelete) <br> **Overall:** O(L)=O(1)                                   |
| **Count reports**               | O(N) (expire reports) <br> O(1) (listSize)  <br> **Overall:** O(N)                                                                   | O(E) (expire reports) <br> O(1) (rax size) <br> **Overall:** O(E)                             | O(E) (expire reports) <br> O(1) (list length) <br> **Overall:** O(E)                                                  | O(L\*E) = O(E) (expire reports) <br> O(1) (dictSize) <br> **Overall:** O(E)                                                  |
| **Expire old reports**          | O(N) (full-scan expiration)                                                                                   | O(E) (scan/remove E items) <br> **Overall:** O(E)                                             | O(E) (scan/remove E items) <br> **Overall:** O(E)                                                                       | O(L) per expired entry (next+remove E items) <br> **Overall:** O(L\*E)=O(E)                                                  |
| **CPU Utilization (450 failover)**             | 100%                                                                                                          | 35%                                                                                           | 30%                                                                                                                    | 32%                                                                                                                           |
* L = length of the key for radix = 16bytes (8 expiry + 8 node)

**Comment by hpatro** [comment]
Thanks @sungming2 for the thorough analysis https://github.com/valkey-io/valkey/pull/2277#issuecomment-3104709570. Great work here, thanks for the patience.

> RAX only
This is the simplest and most targeted fix: we keep just the radix tree to maintain sorted reports. This avoids adding a new composite structure or changing the core failure report API. It directly addresses the main bottleneck: clusterNodeCleanupFailureReports() by enabling fast expiration with minimal code change. it’s sufficient and easy to maintain.
To reduce memory overhead and excessive node splits caused by millisecond level keys, we need to round expiry timestamps up to the nearest second. This time bucketing keeps rax structure compact enough.


I'm aligned to take the RAX only approach forward. The trick which helped us avoid the CPU utilization spike is by getting the failure report ordered via RAX and then by rounding off to the nearest second helped with grouping and help cleanup faster. The change will be also very limited in scope.

@sarthakaggarwal97 / @madolson Please share your thoughts.

**Comment by sarthakaggarwal97** [comment]
The approach with using just RAX sounds good to me too. It is simple, doesn't require adding an additional custom data structure and keeps the diff small. Also, rather than nearest second (lower or upper), I would probably like the next nearest second (just upper), so that if there is a margin of error for expiry, better give more time to avoid an extra cycle to achieve a quorum.

File: src/cluster_legacy.c [hunk 20]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    node->fail_reports = raxNew();
     node->orphaned_time = 0;
     node->repl_offset = 0;
-    listSetFreeMethod(node->fail_reports, zfree);
     node->is_node_healthy = 0;
     return node;
 }
 
+/* 8 bytes mstime + 8 bytes cluster node */
+#define FAILURE_REPORT_ST_KEYLEN 16
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: what is ST here? String?

File: src/cluster_legacy.c [hunk 21]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+
+/* The expiry time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t expiry, clusterNode *node) {
+    mstime_t bt = ((expiry + 999) / 1000) * 1000;
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: can we add a comment to explain this expression.

File: src/cluster_legacy.c [hunk 22]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    uint64_t be = htonu64((uint64_t)bt);
+    memcpy(buf, &be, 8);
+    memcpy(buf + 8, &node, sizeof(node));
+    if (sizeof(node) == 4) memset(buf + 12, 0, 4);
+}
```
Comment (hpatro) [inline src/cluster_legacy.c]: Let's not store the pointer address. It's error prone, what if the node is already freed (via CLUSTER FORGET) while trying to access it back, this will cause a use-after-free crash. Let's use sds api to form the key  `ts + _ + nodename`.

File: src/cluster_legacy.c [hunk 23]
```diff
@@ -1690,29 +1713,33 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
-     * the timestamp. */
-    listRewind(l, &li);
+    unsigned char buf[FAILURE_REPORT_ST_KEYLEN];
     mstime_t now = mstime();
-    while ((ln = listNext(&li)) != NULL) {
-        fr = ln->value;
-        if (fr->node == sender) {
-            fr->time = now;
-            return 0;
+    int is_new = 1;
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c:1728]: I think we have started to allow bool (I read it here https://github.com/valkey-io/valkey/issues/2352), wondering if we can start using it now.

File: src/cluster_legacy.c [hunk 24]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+}
+
+/* Reverses the operation of encodeFailureReportKey, reading back a timestamp
+ * and the pointer to the associated clusterNode. */
+static void decodeFailureReportKey(unsigned char *buf, mstime_t *expiry_ptr, clusterNode **node_ptr) {
+    uint64_t be;
+    memcpy(&be, buf, 8);
+    *expiry_ptr = (mstime_t)ntohu64(be);
+    memcpy(node_ptr, buf + 8, sizeof(*node_ptr));
+}
```
Comment (hpatro) [inline src/cluster_legacy.c]: Let's not use magic number like `8` here rather depend on sizeof to determine the bytes to copy or seek.

File: src/cluster_legacy.c (hunk 21 above)
Comment (sarthakaggarwal97) [reply src/cluster_legacy.c]: Also, let's make it a constant.

**Review by sarthakaggarwal97 — COMMENTED** [review]
The new implementation looks so simple! Thanks for churning through different approaches @sungming2. Some minor comments from me.

File: src/cluster_legacy.c [hunk 25]
```diff
@@ -1756,33 +1787,31 @@ void clusterNodeCleanupFailureReports(clusterNode *node) {
...
-        if (fr->node == sender) break;
+    raxIterator ri;
+    raxStart(&ri, node->fail_reports);
+    raxSeek(&ri, "^", NULL, 0);
+
+    while (raxNext(&ri)) {
+        mstime_t stored_ts;
+        clusterNode *stored_sender;
+        decodeFailureReportKey(ri.key, &stored_ts, &stored_sender);
+        if (stored_sender == sender) {
```
Comment (hpatro) [inline src/cluster_legacy.c]: Just realized, we never access the address after storing and just compare the address here. So, we're fine with the logic.

File: src/cluster_legacy.c [hunk 26]
```diff
@@ -1721,27 +1748,31 @@ int clusterNodeAddFailureReport(clusterNode *failing, clusterNode *sender) {
...
-        }
+    raxIterator ri;
+    raxStart(&ri, node->fail_reports);
+    raxSeek(&ri, "^", NULL, 0);
+
+    while (raxNext(&ri)) {
+        mstime_t stored_ts;
+        clusterNode *stored_sender;
+        decodeFailureReportKey(ri.key, &stored_ts, &stored_sender);
+        if (stored_ts > cutoff) break;
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: we can rename `stored_ts` to `reported_at_ms` for clarity.

File: src/cluster_legacy.c [hunk 27]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+
+/* The expiry time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t expiry, clusterNode *node) {
+    mstime_t bt = ((expiry + 999) / 1000) * 1000;
+    uint64_t be = htonu64((uint64_t)bt);
+    memcpy(buf, &be, 8);
+    memcpy(buf + 8, &node, sizeof(node));
+    if (sizeof(node) == 4) memset(buf + 12, 0, 4);
```
Comment (hpatro) [inline src/cluster_legacy.c]: Why is this condition required? Seems error prone.

File: src/cluster_legacy.c (hunk 21 above)
Comment (hpatro) [reply src/cluster_legacy.c]: what does `bt` and `be` stands for ? You can pick a more human friendly variable name.

File: src/cluster_legacy.c [hunk 28]
```diff
@@ -1671,17 +1671,40 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
     return node;
 }
 
+/* 8 bytes mstime + 8 bytes cluster node */
+#define FAILURE_REPORT_ST_KEYLEN 16
+
+/* The expiry time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t expiry, clusterNode *node) {
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c]: this `expiry` is actually the reported time. Can we name these variables accordingly to avoid confusion.

File: src/cluster_legacy.c (hunk 27 above)
Comment (sungming2) [reply src/cluster_legacy.c]: This is for platforms where pointers are 32 bits, the remaining 4 bytes are zeroed for alignment.

File: src/cluster_legacy.c (hunk 23 above)
Comment (sungming2) [reply src/cluster_legacy.c:1728]: I think we can start using it once we finalize

File: src/cluster_legacy.c [hunk 29]
```diff
@@ -1671,17 +1671,49 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+/* 8 bytes mstime + 8 bytes cluster node */
+#define FAILURE_REPORT_KEYLEN 16
+
+/* The report time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t report_time, clusterNode *node) {
+    const uint64_t sec_in_ms = 1000ULL;
+    const uint64_t ceil_offset_ms = sec_in_ms - 1;
+    const size_t node_ptr_pad_bytes = (sizeof(clusterNode *) == 4) ? 4 : 0; // pad on 32-bit
```
Comment (hpatro) [inline src/cluster_legacy.c:1690]: Was a bit apprehensive initially with the trick. And was chatting with @sungming2 and he highlighted this approach is being used in the code base in timeout.c. So, feels less risky to me now.

https://github.com/valkey-io/valkey/blob/a739531106ec54681b2b31a272b91d4875b436c2/src/timeout.c#L91-L105

File: src/cluster_legacy.c [hunk 30]
```diff
@@ -1690,29 +1722,33 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    while (raxNext(&ri)) {
+        mstime_t reported_time;
+        clusterNode *reported_node;
+        decodeFailureReportKey(ri.key, &reported_time, &reported_node);
+        if (reported_node == sender) {
+            raxRemove(failing->fail_reports,
+                      ri.key, ri.key_len, NULL);
+            is_new = 0;
+            break;
         }
```
Comment (hpatro) [inline src/cluster_legacy.c]: Potential optimization: We could check the timestamp and if it is the same time, we could perform of an early exit. Instead of performing a delete and insert again.

**Comment by sarthakaggarwal97** [comment]
@sungming2 please change the PR description to reflect the current implementation of the PR when you get a chance.

**Review by hpatro — COMMENTED** [review]
Mostly LGTM. 

Could we update the failure-marking.tcl test to verify there is no failure report left at the end?

We could add the following to the test `Only primary with slots has the right to mark a node as failed`

```tcl
# Check there are no failure reports left.
wait_for_condition 1000 50 {
    [R 0 CLUSTER COUNT-FAILURE-REPORTS $replica_id] == 0 &&
    [R 2 CLUSTER COUNT-FAILURE-REPORTS $replica_id] == 0 &&
    [R 3 CLUSTER COUNT-FAILURE-REPORTS $replica_id] == 0 &&
    [R 4 CLUSTER COUNT-FAILURE-REPORTS $replica_id] == 0
} else {
    fail "Cluster COUNT-FAILURE-REPORTS is not right."
}
```

**Review by sarthakaggarwal97 — APPROVED** [review]

File: src/cluster_legacy.c (hunk 30 above)
Comment (sungming2) [reply src/cluster_legacy.c]: This is a good idea, thanks

**Review by hpatro — APPROVED** [review]
LGTM.

For others reviewing it, the failure report now is rounded up to the nearest second (ceil). So for the cleanup we will delay it by maximum of a second which seems reasonable to me. However, there is no delay in failover.

**Comment by hpatro** [comment]
@madolson / @enjoy-binbin Would be nice if one of you could take a pass.

File: src/cluster_legacy.c [hunk 31]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
 
+/* 8 bytes mstime + 8 bytes cluster node */
+#define FAILURE_REPORT_KEYLEN 16
+#define SEC_IN_MS 1000ULL
+#define CEIL_OFFSET_MS (SEC_IN_MS - 1)
+
+/* The report time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t report_time, clusterNode *node) {
```
Comment (madolson) [inline src/cluster_legacy.c]: Typically inputs are first, and then outputs passed by reference are second
```suggestion
static void encodeFailureReportKey(mstime_t report_time, clusterNode *node, unsigned char *buf) {
```

File: src/cluster_legacy.c [hunk 32]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    memcpy(buf, &big_endian_time, sizeof(uint64_t));
+
+    /* Append the node pointer, plus padding if necessary */
+    memcpy(buf + sizeof(uint64_t), &node, sizeof(node));
+    if (node_ptr_pad_bytes) memset(buf + sizeof(uint64_t) + sizeof(node), 0, node_ptr_pad_bytes);
+}
+
+/* Reverses the operation of encodeFailureReportKey, reading back a timestamp
+ * and the pointer to the associated clusterNode. */
+static void decodeFailureReportKey(unsigned char *buf, mstime_t *report_time, clusterNode **node_ptr) {
```
Comment (madolson) [inline src/cluster_legacy.c:1706]:
```suggestion
static void decodeFailureReportKey(unsigned char *buf, mstime_t *report_time, clusterNode **node_ptr) {
```

File: src/cluster_legacy.c (hunk 29 above)
Comment (madolson) [reply src/cluster_legacy.c:1690]: Should we write a smaller helper function for it? It definitely feels sketch, but the math seems sane.
```
void paddedPtrCopy(char *buf, (void *) ptr) {
    const size_t node_ptr_pad_bytes = (sizeof(clusterNode *) == 4) ? 4 : 0; // pad on 32-bit
    memcpy(buf + sizeof(uint64_t), &node, sizeof(node));
    if (node_ptr_pad_bytes) memset(buf + sizeof(node), 0, node_ptr_pad_bytes);
}
```

Then this just becomes:
```
memcpy(buf, &big_endian_time, sizeof(uint64_t));
paddedPtrCopy(buf + sizeof(uint64_t), node);
```

File: src/cluster_legacy.c [hunk 33]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+    uint64_t big_endian_time;
+    memcpy(&big_endian_time, buf, sizeof(uint64_t));
+    *report_time = (mstime_t)ntohu64(big_endian_time);
+    memcpy(node_ptr, buf + sizeof(uint64_t), sizeof(*node_ptr));
```
Comment (madolson) [inline src/cluster_legacy.c:1710]: Feels weird there isn't comparable 32bit logic here.

File: src/cluster_legacy.c [hunk 34]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
-    node->fail_reports = listCreate();
+    node->fail_reports = raxNew();
     node->orphaned_time = 0;
     node->repl_offset = 0;
-    listSetFreeMethod(node->fail_reports, zfree);
     node->is_node_healthy = 0;
     return node;
 }
 
+/* 8 bytes mstime + 8 bytes cluster node */
```
Comment (madolson) [inline src/cluster_legacy.c]:
```suggestion
/* 8 bytes mstime + 8 bytes cluster node pointer (padded with zeros on 32-bit systems. */
```

File: src/cluster_legacy.c [hunk 35]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+#define CEIL_OFFSET_MS (SEC_IN_MS - 1)
+
+/* The report time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(unsigned char *buf, mstime_t report_time, clusterNode *node) {
+    const size_t node_ptr_pad_bytes = (sizeof(clusterNode *) == 4) ? 4 : 0; // pad on 32-bit
+
+    /* Round up to the next second for fewer key splits and quorum grace */
+    mstime_t bucketed_time = ((report_time + CEIL_OFFSET_MS) / SEC_IN_MS) * SEC_IN_MS;
```
Comment (madolson) [inline src/cluster_legacy.c]:
```suggestion
    mstime_t bucketed_time = report_time / SEC_IN_MS * SEC_IN_MS + 1;
```
I don't understand why we chose to round up, as opposed to down then plus one to force it into the next bucket for the grace. This is mostly a nitpick, it's just a bit more compact.

File: src/cluster_legacy.c [hunk 36]
```diff
@@ -1721,27 +1764,33 @@ int clusterNodeAddFailureReport(clusterNode *failing, clusterNode *sender) {
...
+
+    while (raxNext(&ri)) {
+        mstime_t reported_time;
+        clusterNode *reported_node;
+        decodeFailureReportKey(ri.key, &reported_time, &reported_node);
+        if (reported_time > cutoff) break;
+        if (raxRemove(node->fail_reports, ri.key, ri.key_len, NULL)) {
+            /* Move directly to the next element after the tree mutation due to removal */
+            raxSeek(&ri, ">=", ri.key, ri.key_len);
         }
```
Comment (madolson) [inline src/cluster_legacy.c]:
```suggestion
        int retval = raxRemove(node->fail_reports, ri.key, ri.key_len, NULL));
        serverAssert(retval != 1);
        /* Move directly to the next element after the tree mutation due to removal */
        raxSeek(&ri, ">=", ri.key, ri.key_len);
```
This should never fail right?

**Review by madolson — COMMENTED** [review]
Mostly nitpicks and a comment about 32bit decodes. I'll also throw on the run extra tests so we get a 32bit test run.

File: src/cluster_legacy.c (hunk 33 above)
Comment (sungming2) [reply src/cluster_legacy.c:1710]: We only read sizeof(pointer) bytes for the pointer, so it doesn't need to skip or detect padding in the decode logic.

File: src/cluster_legacy.c (hunk 29 above)
Comment (hpatro) [reply src/cluster_legacy.c:1690]: we can tackle it in an independent PR for both timeout.c and cluster_legacy.c. Seems good to close this out.

Comment (madolson) [reply src/cluster_legacy.c:1690]: Why should we tackle it in a separate PR? I would have rather done it here.

Comment (hpatro) [reply src/cluster_legacy.c:1690]: I didn't feel strongly about it. There wasn't any difference in behavior to the implementation already present in timeout.c.

Comment (hpatro) [reply src/cluster_legacy.c:1690]: Linking the issue I had filled: https://github.com/valkey-io/valkey/issues/2383

File: src/cluster_legacy.c [hunk 37]
```diff
@@ -1671,48 +1671,91 @@ clusterNode *createClusterNode(char *nodename, int flags) {
...
+#define CEIL_OFFSET_MS (SEC_IN_MS - 1)
+
+/* The report time is rounded up (ceiled) to the nearest second in order to bucket
+ * timestamps and keep the radix‐tree keys compact.  The resulting timestamp is stored
+ * in big‑endian format, followed by the pointer to the clusterNode. */
+static void encodeFailureReportKey(clusterNode *node, mstime_t report_time, unsigned char *buf_out) {
+    const size_t node_ptr_pad_bytes = (sizeof(clusterNode *) == 4) ? 4 : 0; // pad on 32-bit
+
+    /* Round up to the next second for fewer key splits and quorum grace */
+    mstime_t bucketed_time = (report_time / SEC_IN_MS) * SEC_IN_MS + SEC_IN_MS;
```
Comment (sarthakaggarwal97) [inline src/cluster_legacy.c:1693]: I am thinking if we can ignore the hour part and tens of minutes in the timestamp (HH:MM:SS) to create fewer nodes in the radix tree. In some corner cases, say if the report for a failed node is received at 12:59:59, then next report will have a lot of digits changed. if it sounds valid, I can create an issue for this as well.

wdyt @hpatro @sungming2?
