### PR TITLE
Increase embedded string threshold from 64 to 128 bytes

### LINKED ISSUE #3025: [PERFORMANCE] Potential regression due to Removal of internal server object pointer overhead
A potential performance regression due to https://github.com/valkey-io/valkey/pull/2516

We are seeing a drop of about:
1. 6% in a SET workload of 96 Bytes, 9 IO-Threads, 10 Pipelining, aarch64 from 1.86M to 1.75M rps

Image

2. 6% in GET workload of 16 Bytes, 9 IO-Threads, 10 Pipelining, aarch64 from 2.63M to 2.47M rps

Image

Dashboard Snapshot: https://perf-dashboard.valkey.io/public-dashboards/3e45bf8ded3043edaa941331cd1a94e2?from=2026-01-05T19:00:00.000Z&to=2026-01-06T06:59:58.000Z&timezone=UTC

FYI @rainsupreme

### PR DESCRIPTION
**Pull request by Nikhil-Manglore**
This PR increases the embedded string threshold to 128 bytes (2 cache lines) in order to improve memory overhead. I also fixed the tests that pertained to embedded values

Closes #3025

### CODE REVIEW

**Comment by rainsupreme** [comment]
+31% performance is wild, to the point of being suspicious. What's going on there? I want to see if it's repeatable

**Comment by rainsupreme** [comment]
I'm very curious why this is producing a 31% performance gain, but I'm not complaining either 😆

**Comment by sarthakaggarwal97** [comment]
That's quite a gain. Curious if this is because that 96 bytes value is now treated as `EMBSTR` instead of `RAW`? I guess it reduces the number of look ups since the value is already embedded with the key? But probably still doesn't explain this much. It would great to profile this. 

Explanation from Codex about the total size of the `EMBSTR`
```
base robj-ptr slot   8
embedded key        18
96B value SDS      100
total              126
```

**Comment by Nikhil-Manglore** [comment]
The tests `embedded_string_with_key` and `embedded_string_with_key_and_expire` pass now. The failing test is an unrelated flaky test, we can rerun it.

**Review by zuiderkwast — APPROVED** [review]
The jemalloc size classes in this range are in intervals of 16 bytes (64, 80, 96, 112, 128) so in the worst case, we get 15 bytes internal fragmentation in the allocation, but we save 8 bytes for the pointer.

Previously, for unembedded strings in the range 64-128, the internal fragmentation is up 15 bytes (for 96B strings, 100B sds representation, 112B bucket, wasted 12B) plus the fixed 8 bytes for the obj->ptr.

Also optimal performance in most cases, it seems. 💯

**Review by sarthakaggarwal97 — APPROVED** [review]
LGTM! We should also change our performance benchmarks to include more string sizes after this PR gets merged.

**Review by rainsupreme — APPROVED** [review]
Huzzah 🥳 
(lgtm!)

**Comment by Nikhil-Manglore** [comment]
> That's quite a gain. Curious if this is because that 96 bytes value is now treated as `EMBSTR` instead of `RAW`? I guess it reduces the number of look ups since the value is already embedded with the key? But probably still doesn't explain this much. It would great to profile this.
> 
> Explanation from Codex about the total size of the `EMBSTR`
> 
> ```
> base robj-ptr slot   8
> embedded key        18
> 96B value SDS      100
> total              126
> ```

Yeah 96 byte values are now treated as `EMBSTR`. Now that the value is embedded the number of cache misses is drastically reduced and there's no pointer dereference for 96 byte values. At high throughput configurations the throughput increases due to how the per-call savings is multiplied across all io-threads.

File: src/object.c [hunk 1]
```diff
@@ -274,7 +274,6 @@ void *objectGetVal(const robj *o) {
             data += 1 + hdr_size;                /* +1 for header size byte */
             data += sdslen((const_sds)data) + 1; /* +1 for null terminator */
         }
-        assert(o->encoding == OBJ_ENCODING_EMBSTR);
         return data + sdsHdrSize(SDS_TYPE_8);
```
Comment (zuiderkwast) [inline src/object.c:277]: I don't know why the assert was removed. Avoid unnecessary coupling between `o->hasembval` and `o->encoding`? Or performance, save a few instructions?

Hypothetically, in the future we may want to embed values that are not strings, for example the header of a hash, set, sorted set. In that case, we shouldn't return `data + sdsHdrSize(SDS_TYPE_8)`, but that's a future problem.

Comment (Nikhil-Manglore) [reply src/object.c:277]: When I was initially looking into the performance degradation I had removed it for performance reasons so I also removed it in this PR.
