### PR TITLE
Calculate the actual mask to be removed in the eventloop before aeApiDelEvent

### LINKED ISSUE #715: [BUG] inconsistent behavior of kqueue aeApiDelEvent comparing to the code before #638
**Describe the bug**

If `writable` is registered into the kqueue and `readable` is not, `aeDeleteFileEvent` will fail if the mask is `AE_READABLE | AE_WRITABLE` or simply `-1`  
Tested on `macOS Ventura 13.6.7, x86_64`.

**To reproduce**

1. only watch `AE_WRITABLE` events using `aeCreateFileEvent`
2. call `aeDeleteFileEvent` with `mask = -1`
3. the `writable` event still fires

**Expected behavior**

The `writable` event should not fire after calling `aeDeleteFileEvent` with `mask = -1`

**Additional information**

This is related to #638 

The current `ae_kqueue#aeApiDelEvent` uses a single `kevent` to remove both `readable` and `writable` events with a single syscall,
but unlike `EV_ADD`, the `EV_DELETE` fails if the `EVFILT_xxx` is not previously registered into `kqueue`.

If `EVFILT_READ` is not registered, the `kevent` will fail and `EVFILT_WRITE` will not be deleted.

This behavior can be verified by the following simple code snippet:

```c
#include <stdio.h>
#include <sys/event.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <string.h>

int main(int argc, char** argv) {
    int kqfd = kqueue();
    printf("kqfd = %d\n", kqfd);

    int listenfd = socket(AF_INET, SOCK_STREAM, 0);
    printf("tcp listen fd = %d\n", listenfd);

    struct sockaddr_in bind_addr = {0};
    bind_addr.sin_family = AF_INET;
    bind_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    bind_addr.sin_port = htons(8000);

    bind(listenfd, (struct sockaddr*)&bind_addr, sizeof(bind_addr));
    listen(listenfd, 1);

    int sock = accept(listenfd, NULL, NULL);
    printf("accepted fd = %d\n", sock);

    struct kevent evs[2];
    EV_SET(&evs[0], sock, EVFILT_WRITE, EV_ADD, 0, 0, NULL);
    int err = kevent(kqfd, evs, 1, NULL, 0, NULL);
    printf("add EVFILT_WRITE result = %d\n", err);

    EV_SET(&evs[0], sock, EVFILT_READ, EV_DELETE, 0, 0, NULL);
    EV_SET(&evs[1], sock, EVFILT_WRITE, EV_DELETE, 0, 0, NULL);
    err = kevent(kqfd, evs, 2, NULL, 0, NULL);
    printf("del EVFILT_READ and EVFILT_WRITE result = %d, errno=%d(%s)\n", err, errno, strerror(errno));

    int ret = kevent(kqfd, NULL, 0, evs, 2, NULL);
    printf("kq_poll returns %d\n", ret);
    for (int i = 0; i < ret; ++i) {
        struct kevent* e = &evs[i];
        int fd = e->ident;
        int filter = e->filter;

        printf(">>> fd=%d", fd);
        printf(", filter=");
        if (filter == EVFILT_WRITE) {
            printf("EVFILT_WRITE");
        } else if (filter == EVFILT_READ) {
            printf("EVFILT_READ");
        } else {
            printf("%d", filter);
        }
        printf("\n");
    }
    fflush(stdout);
    return 0;
}
```

The output would be:

```
kqfd = 3
tcp listen fd = 4
accepted fd = 5
add EVFILT_WRITE result = 0
del EVFILT_READ and EVFILT_WRITE result = -1, errno=2(No such file or directory)
kq_poll returns 1
>>> fd=5, filter=EVFILT_WRITE
```

This can be easily fixed, just modify the mask `mask = mask & fe->mask` before calling `aeApiDelEvent`.  
I'm willing to submit a PR if this is desired.

### PR DESCRIPTION
**Pull request by wkgcass**
fixes #715 

for kqueue:  
EV_DELETE fails if the specified fd is not associated with the kqfd. If EVFILT_WRITE is associated but EVFILT_READ is not, then calling aeApiDelEvent with mask = -1 or `(AE_READABLE|AE_WRITABLE)` will cause the kevent() to fail with errno = 2(No such file or directory) and EVFILT_WRITE not dissociated.  
So we need to calculate the actual mask to be removed, instead of passing in whatever user provides.

for evport:  
The comment clearly states that aeApiDelEvent "rely on the fact that our caller has already updated the mask in the eventLoop".

for epoll:  
There's no need to calculate the "actual mask" twice, once in `aeDeleteFileEvent` and another in `aeApiDelEvent`, let's just use the mask recorded in the eventLoop.

### CODE REVIEW

**Comment by wkgcass** [comment]
Oh, my bad. I didn't enable the workflow in my fork repo

Now it should be fine, I've ran [the workflow](https://github.com/wkgcass/valkey/actions) twice.

**Comment by madolson** [comment]
@enjoy-binbin Can you take a look?

**Comment by enjoy-binbin** [comment]
The code looks reasonable, @panjf2000 since you have done a lot of research in this area, would it be convenient for you to review it? thanks.

File: src/ae_epoll.c [hunk 1]
```diff
@@ -87,10 +87,12 @@ static int aeApiAddEvent(aeEventLoop *eventLoop, int fd, int mask) {
     return 0;
 }
 
-static void aeApiDelEvent(aeEventLoop *eventLoop, int fd, int delmask) {
+static void aeApiDelEvent(aeEventLoop *eventLoop, int fd, int mask) {
```
Comment (panjf2000) [inline src/ae_epoll.c:90]: We've sanitized the `mask` and we can now use `fe->mask` directly, which makes the `mask` argument seem redundant. We may want to update this function signature and get rid of this argument?

File: src/ae.c [hunk 2]
```diff
@@ -193,6 +195,9 @@ void aeDeleteFileEvent(aeEventLoop *eventLoop, int fd, int mask) {
             if (eventLoop->events[j].mask != AE_NONE) break;
         eventLoop->maxfd = j;
     }
+    /* Must be invoked after the eventLoop mask is modified,
+     * which is required by evport and epoll */
+    aeApiDelEvent(eventLoop, fd, mask);
```
Comment (panjf2000) [inline src/ae.c]: One possible optimization here: I think we should be able to avoid this function call by checking if `fe->mask` remains the same after we factor out whatever in `mask` from it.

**Comment by panjf2000** [comment]
This looks good to me in general. I've had encountered this issue before. Actually, the current codebase of redis/valkey is still reproducing this issue: it calls `aeDeleteFileEvent()` trying to delete some events that weren't even registered from somewhere. The only reason why the system still going on without fatal errors being spotted is because we've been ignoring those errors in `aeApiDelEvent()`. I've made some similar code changes for kqueue-based `aeApiDelEvent()`, check out [this](https://github.com/valkey-io/valkey/pull/449/files#diff-1d4380c5e6b3cc847f2dce4446b6379f40730c4a5496a23e7c0e51455b6b190c) for details.

>     /* At this point, we somehow receive deletion requests for events that
     * are not registered in kqueue yet, which could causes kevent(2) to
     * fail and return ENOENT. Therefore, we need to use aeEventLoop->events
     * to mask out the events that are not registered in kqueue and get the
     * valid events which are requested to be deleted. */
    int delmask = eventLoop->events[fd].mask & mask;

If we get this PR landed, I think I can remove that portion of the code in #449. Nevertheless, there are still remaining issues for `aeApiDelEvent()`: we never handle the potential errors from the system calls, which is definitely a mistake and might lead to potential risks. We've debated about it in #449 and #528, and I think we should prioritize them in the near future.

File: src/ae_epoll.c (hunk 1 above)
Comment (wkgcass) [reply src/ae_epoll.c:90]: Based on the current implementation, the `kqueue` impl still needs the `mask` parameter to know which filters should be deleted.  
I'm afraid that, since the `aeApiXxx` functions are used as something like "abstract methods", the `epoll` impl has to follow the method signature, even if it's not used.

Comment (wkgcass) [reply src/ae_epoll.c:90]: @panjf2000 hi, are there more suggestions about the code, or shall we resolve the conversation?

Comment (panjf2000) [reply src/ae_epoll.c:90]: You're right about this. I guess we have no choice but to keep this parameter at the moment.

**Review by panjf2000 — CHANGES_REQUESTED** [review]

File: src/ae.c (hunk 2 above)
Comment (wkgcass) [reply src/ae.c]: Great suggestion!  
We can use the `mask` variable directly to check, since it's the `actual` mask to be deleted.  
Also we can handle the situation that user may only remove `AE_BARRIER` without touching the actual events.  
(Currently there's no `AE_BARRIER` usage and it was always used together with `AE_WRITABLE` in the history, but we can improve robustness by doing so)

A new commit is pushed, please review when you have time ~

**Review by panjf2000 — APPROVED** [review]
LGTM

**Comment by wkgcass** [comment]
@enjoy-binbin hi, the issues seem to have been settled, do you have time to review the latest commit please?

**Review by enjoy-binbin — APPROVED** [review]
ok, the code LGTM, thanks.
