### PR TITLE
Fix client trackinginfo crash when tracking off by default

### LINKED ISSUE #1683: [CRASH] client trackinginfo coredump when tracking is off
## step to reproduce

1. compile valkey unstable branch and start at 6379 port.
2. use cli connect to 6379 and execute `client trackinginfo`
3. then will get coredump
```
/lib64/libpthread.so.0(+0xf630)[0x7fab74931630]
./src/valkey-server *:6379(clientTrackingInfoCommand+0x12b)[0x57f8db]
./src/valkey-server *:6379(call+0x5ba)[0x5a791a]
./src/valkey-server *:6379(processCommand+0x968)[0x5a8938]
./src/valkey-server *:6379(processInputBuffer+0x18d)[0x58381d]
./src/valkey-server *:6379(readQueryFromClient+0x59)[0x585ea9]
./src/valkey-server *:6379[0x46fa4d]
./src/valkey-server *:6379(aeMain+0x89)[0x5bf3e9]
./src/valkey-server *:6379(main+0x4e1)[0x455821]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fab74576555]
./src/valkey-server *:6379[0x4564f2]
```
4. gdb will get core at `networking.c:4103`, because `c->pubsub_data` is null.

```
Thread 1 "valkey-server" received signal SIGSEGV, Segmentation fault.
0x000000000057f8db in clientTrackingInfoCommand (c=0x7ffff6c57800) at networking.c:4103
4103	    if (c->pubsub_data->client_tracking_prefixes) {
(gdb) p c
$1 = (client *) 0x7ffff6c57800
(gdb) p c->pubsub_data
$2 = (ClientPubSubData *) 0x0
```

## how to fix

1. judge `c->pubsub_data` is null (I prefre)

```
diff --git a/src/networking.c b/src/networking.c
index 7701ad88c..1a26aa4a2 100644
--- a/src/networking.c
+++ b/src/networking.c
@@ -4100,7 +4100,7 @@ void clientTrackingInfoCommand(client *c) {
 
     /* Prefixes */
     addReplyBulkCString(c, "prefixes");
-    if (c->pubsub_data->client_tracking_prefixes) {
+    if (c->pubsub_data && c->pubsub_data->client_tracking_prefixes) {
         addReplyArrayLen(c, raxSize(c->pubsub_data->client_tracking_prefixes));
```

2. when enable tracking, will call `initClientPubSubData()`, maybe we can also call this when tracking is off.

### PR DESCRIPTION
**Pull request by yangbodong22011**
After #1405, `client trackinginfo` will crash when tracking is off
```
/lib64/libpthread.so.0(+0xf630)[0x7fab74931630]
./src/valkey-server *:6379(clientTrackingInfoCommand+0x12b)[0x57f8db]
./src/valkey-server *:6379(call+0x5ba)[0x5a791a]
./src/valkey-server *:6379(processCommand+0x968)[0x5a8938]
./src/valkey-server *:6379(processInputBuffer+0x18d)[0x58381d]
./src/valkey-server *:6379(readQueryFromClient+0x59)[0x585ea9]
./src/valkey-server *:6379[0x46fa4d]
./src/valkey-server *:6379(aeMain+0x89)[0x5bf3e9]
./src/valkey-server *:6379(main+0x4e1)[0x455821]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fab74576555]
./src/valkey-server *:6379[0x4564f2]
```

The reason is that we did not init pubsub_data by default, we only
init it when tracking on.

Fixes #1683.

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]
@uriyage please take a look

File: src/networking.c [hunk 1]
```diff
@@ -4100,7 +4100,7 @@ void clientTrackingInfoCommand(client *c) {
 
     /* Prefixes */
     addReplyBulkCString(c, "prefixes");
-    if (c->pubsub_data->client_tracking_prefixes) {
+    if (c->pubsub_data && c->pubsub_data->client_tracking_prefixes) {
```
Comment (zuiderkwast) [inline src/networking.c]: This fix looks correct.

There are more occurrences of `c->pubsub_data->client_tracking_redirection` where we don't check `c->pubsub_data` first, for example 7 lines above this line, but in those cases we check `c->flag.tracking` first. Can we rely on this being initialized when the tracking flag is set?

If yes, then should we just check `c->flag.tracking` here too?

```suggestion
    if (c->flag.tracking) {
        serverAssert(c->pubsub_data && c->pubsub_data->client_tracking_prefixes);
```

Comment (yangbodong22011) [reply src/networking.c]: > If yes, then should we just check c->flag.tracking here too?

Yes, I think we can use `c->flag.tracking`. when `enableTracking`, will set c->flag.tracking = 1 and initClientPubSubData.

**Review by zuiderkwast — APPROVED** [review]

**Comment by zuiderkwast** [comment]
Checking the flag seems to be not enough. We got this in the CI job:

Test case `CLIENT TRACKINGINFO provides reasonable results when tracking on`.

```
7635:M 07 Feb 2025 14:56:21.674 # === ASSERTION FAILED ===
7635:M 07 Feb 2025 14:56:21.674 # ==> networking.c:4104 'c->pubsub_data && c->pubsub_data->client_tracking_prefixes' is not true
```

File: src/networking.c [hunk 2]
```diff
@@ -4100,7 +4100,8 @@ void clientTrackingInfoCommand(client *c) {
 
     /* Prefixes */
     addReplyBulkCString(c, "prefixes");
-    if (c->pubsub_data->client_tracking_prefixes) {
+    if (c->flag.tracking) {
+        serverAssert(c->pubsub_data && c->pubsub_data->client_tracking_prefixes);
```
Comment (zuiderkwast) [inline src/networking.c]: I guess your original fix was better. :cry:

`c->pubsub_data->client_tracking_prefixes` doesn't always exist when tracking is on.

Maybe this works?

```suggestion
    if (c->flag.tracking && c->pubsub_data->client_tracking_prefixes) {
```

**Review by zuiderkwast — APPROVED** [review]

**Comment by zuiderkwast** [comment]
@yangbodong22011 Can you fix the DCO issue?

See the Details link next to the failing DCO CI job. There's some instructions about how to fix it. (`git rebase HEAD~3 --signoff` and force-push.)

**Comment by yangbodong22011** [comment]
> @yangbodong22011 Can you fix the DCO issue?
> 
> See the Details link next to the failing DCO CI job. There's some instructions about how to fix it. (`git rebase HEAD~3 --signoff` and force-push.)

Sorry for late, done.
