### PR TITLE
Fix CLUSTER SLOTS crash when called from module timer callback

### LINKED ISSUE #2912: [BUG] CLUSTER SLOTS crashes when used with fake-client.
**Describe the bug**

If a module creates a fake client and executes a VM_CALL to "CLUSTER SLOTS", then it crashes the server. Some debugging appeared to indicate that this was because CLUSTER SLOTS creates it's own fake client in order to cache its results for better performance. This doesn't work when the original client was also fake.

**To reproduce**

Have a module create a fake context and then perform an VM_Call to "CLUSTER SLOTS" command.

**Expected behavior**

No crash and good results from CLUSTER SLOTS

### PR DESCRIPTION
**Pull request by bandalgomsu**
The CLUSTER SLOTS reply depends on whether the client is connected over IPv6, but for a fake client there is no connection and when this command is called from a module timer callback or other scenario where no real client is involved, there is no connection to check IPv6 support on. This fix handles the missing case by returning the reply for IPv4 connected clients.

Fixes #2912.

### CODE REVIEW

File: tests/modules/cluster.c [hunk 1]
```diff
@@ -1,8 +1,46 @@
...
+ValkeyModuleCtx *detached_ctx = NULL;
+
+pthread_t tid;
+
+void* worker(void *arg) {
+    UNUSED(arg);
+
+    for (int i = 0; i < 100; i++) {
+        ValkeyModuleCallReply *rep = ValkeyModule_Call(detached_ctx, "CLUSTER", "c", "SLOTS");
+        ValkeyModule_Log(detached_ctx, "notice", "Worker reply %d", i);
```
Comment (allenss-amazon) [inline tests/modules/cluster.c]: Maybe we could take a peek at the data which is returned, just enough to know it's correct?

**Comment by allenss-amazon** [comment]
@zuiderkwast This PR was separated tested and was found to solve the problem. So thanks!!

It would be tremendously helpful if this could get into the 9.0.1 release.

**Review by zuiderkwast — CHANGES_REQUESTED** [review]
This test calls CLUSTER SLOTS from two threads in parallel without any locks. In general, command execution in Valkey is not thread safe and it's not allowed to execute two commands in parallel.

I tried locally to modify the new test case by adding the proper locking, with `ValkeyModule_ThreadSafeContextLock` and `ValkeyModule_ThreadSafeContextUnlock`.

When `test_cluster_slots_fake_client` is called, a lock is already held, so to allow `worker` to use acquire the lock, the main thread first needs to release the lock.

With these changes, the changes to CLUSTER SLOTS are not necessary:

```diff
 void* worker(void *arg) {
     UNUSED(arg);
 
     for (int i = 0; i < 100; i++) {
+        ValkeyModule_ThreadSafeContextLock(detached_ctx);
         ValkeyModuleCallReply *rep = ValkeyModule_Call(detached_ctx, "CLUSTER", "c", "SLOTS");
         ValkeyModule_Log(detached_ctx, "notice", "Worker reply %d", i);
         ValkeyModule_FreeCallReply(rep);
+        ValkeyModule_ThreadSafeContextUnlock(detached_ctx);
     }
 
     return NULL;
 }
 
 int test_cluster_slots_fake_client(ValkeyModuleCtx *ctx, ValkeyModuleString **argv, int argc) {
     UNUSED(argv);
 
     if (argc != 1) return ValkeyModule_WrongArity(ctx);
+    ValkeyModule_ThreadSafeContextUnlock(ctx);
 
     pthread_create(&tid, NULL, worker, NULL);
 
     for (int i = 0 ; i < 100; i++) {
+        ValkeyModule_ThreadSafeContextLock(ctx);
         ValkeyModuleCallReply *rep = ValkeyModule_Call(ctx, "CLUSTER", "c", "SLOTS");
         ValkeyModule_Log(ctx, "notice", "Main reply %d", i);
         ValkeyModule_FreeCallReply(rep);
+        ValkeyModule_ThreadSafeContextUnlock(ctx);
     }
 
     pthread_join(tid, NULL);
 
+    ValkeyModule_ThreadSafeContextLock(ctx);
     ValkeyModule_ReplyWithSimpleString(ctx, "OK");
 
     return VALKEYMODULE_OK;
 }
```

This is what I think modules need to do when they call commands from multiple threads, so therefore I'm not ready to accept the change, unless I'm missing anything. (I was discussing this with @rjd15372.)

File: src/cluster.c [hunk 2]
```diff
@@ -1547,6 +1574,11 @@ void clusterCommandSlots(client *c) {
      *               3) node ID
      *           ... continued until done
      */
+    if (c->flag.fake) {
+        clusterCommandSlotsIfFakeClient(c);
+        return;
+    }
```
Comment (enjoy-binbin) [inline src/cluster.c]: can you share the crash log? I don't really like that we have a fast if here, i think this check should be done in something like generateClusterSlotResponse. (i don't know the details.)

Comment (bandalgomsu) [reply src/cluster.c]: As @zuiderkwast said, I made the mistake of not considering the thread-safe context, so the crash log I found in the test code may not be correct. 😞

Comment (allenss-amazon) [reply src/cluster.c]: The original failure was found by executing VM_Call from a server cron task. The locking issue wouldn't apply to that case. We have separately shown that this PR does actually fix that case. 

It's not hard for us to solve this with a separate thread that's dedicated to duplicating the server cron task, it's just a couple of MB of overhead.

I would note that the test case doesn't actually guarantee that the command runs without an error. One of the failure modes we saw was that the command executes (no crash) but returns an error, not the contents of the command.

**Comment by KarthikSubbarao** [comment]
Here is a reproduced crash when we try to call the `CLUSTER SLOTS` command from the timer cron job (without any separate separate thread contexts):
```
919190 valkey-server *
/lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7a159de45330]
./src/valkey-server *:8000 [cluster](getClientPeerId+0xa3)[0x649119aa8233]
./src/valkey-server *:8000 [cluster](+0x18d526)[0x649119b62526]
./src/valkey-server *:8000 [cluster](addNodeToNodeReply+0x228)[0x649119b45a48]
./src/valkey-server *:8000 [cluster](addNodeReplyForClusterSlot+0xd5)[0x649119b45ca5]
./src/valkey-server *:8000 [cluster](generateClusterSlotResponse+0x179)[0x649119b45f89]
./src/valkey-server *:8000 [cluster](clusterCommandSlots+0x404)[0x649119b46804]
./src/valkey-server *:8000 [cluster](call+0x156)[0x649119a881f6]
./src/valkey-server *:8000 [cluster](VM_Call+0x759)[0x649119bb4929]
/home/ubuntu/bandalgomsu/valkey/tests/modules/cluster.so(CronTimerHandlerCluster+0x42)[0x7a159e03e222]
./src/valkey-server *:8000 [cluster](moduleTimerHandler+0x1bb)[0x649119bba80b]
./src/valkey-server *:8000 [cluster](+0x93724)[0x649119a68724]
./src/valkey-server *:8000 [cluster](aeMain+0x148)[0x649119a732c8]
./src/valkey-server *:8000 [cluster](main+0x5dd)[0x649119a66e3d]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7a159de2a1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7a159de2a28b]
./src/valkey-server *:8000 [cluster](_start+0x25)[0x649119a68605]
```

The crash occurs due to how isClientConnIpV6 is called using the cached client created here from this:
```
client *recording_client = createCachedResponseClient(resp);
```

In the CLUSTER SLOTS Command, there are two calls to isClientConnIpV6. The first call to isClientConnIpV6(c) in clusterCommandSlots uses the original fake module client c (and this works fine). But the second call happens inside addNodeToNodeReply with the recording_client created by createCachedResponseClient. This is where the crash happens.


This issue is in `isClientConnIpV6`. Normal clients don't face the issue because `server.current_client` is set. In case of fake clients and calling from a module timer cron job, `getClientPeerId` will crash.
```
    if (c->flag.fake && server.current_client) {
        /* Fake client? Use current client instead.
         * Noted that in here we are assuming server.current_client is set
         * and real (aof has already violated this in loadSingleAppendOnlyFil). */
        c = server.current_client;
    }
    return getClientPeerId(c)[0] == '[';
```

The fix could be simpler than what is proposed in the PR and limited to just the `isClientConnIpV6` function.

An idea - this addresses the crash.
```
+    /* If we still have a fake client (e.g., called from module timer with no real client),
+     * default to IPv4 to avoid crashing when trying to get peer info from a dummy connection. */
+    if (c->flag.fake || !c->conn) {
+        return 0;
+    }
      return getClientPeerId(c)[0] == '[';
```

An alternative is to detect the state and not use the cachedResponseClient in certain cases.

Here is the diff to add the timer cron job to the same test module to reproduce the issue:
```
diff --git a/tests/modules/cluster.c b/tests/modules/cluster.c
index 2ba626b0e..a209896c0 100644
--- a/tests/modules/cluster.c
+++ b/tests/modules/cluster.c
@@ -2,6 +2,22 @@
 #include <string.h>
 
 #define UNUSED(x) (void)(x)
+static ValkeyModuleTimerID timer_id;
+
+void CronTimerHandler(ValkeyModuleCtx *ctx, void *data) {
+    UNUSED(data);
+    ValkeyModuleCallReply *rep = ValkeyModule_Call(ctx, "CLUSTER", "c", "SLOTS");
+    if (rep) {
+        ValkeyModule_Log(ctx, "notice", "VM_CALL reply type: %d", ValkeyModule_CallReplyType(rep));
+        size_t len;
+        const char *reply = ValkeyModule_CallReplyStringPtr(rep, &len);
+        ValkeyModule_Log(ctx, "notice", "VM_CALL response: %.*s", (int)len, reply);
+        ValkeyModule_FreeCallReply(rep);
+    } else {
+        ValkeyModule_Log(ctx, "notice", "VM_CALL returned NULL");
+    }
+    timer_id = ValkeyModule_CreateTimer(ctx, 1000, CronTimerHandler, NULL);
+}
 
 int test_cluster_slots(ValkeyModuleCtx *ctx, ValkeyModuleString **argv, int argc) {
     UNUSED(argv);
@@ -80,5 +96,6 @@ int ValkeyModule_OnLoad(ValkeyModuleCtx *ctx, ValkeyModuleString **argv, int arg
     /* Register our handlers for different message types. */
     ValkeyModule_RegisterClusterMessageReceiver(ctx, MSGTYPE_DING, DingReceiver);
     ValkeyModule_RegisterClusterMessageReceiver(ctx, MSGTYPE_DONG, DongReceiver);
+    timer_id = ValkeyModule_CreateTimer(ctx, 1000, CronTimerHandler, NULL);
     return VALKEYMODULE_OK;
 }
```

@bandalgomsu - Can we use this in the test?

File: src/cluster.c (hunk 2 above)
Comment (KarthikSubbarao) [reply src/cluster.c]: @enjoy-binbin - I shared the crash information here: https://github.com/valkey-io/valkey/pull/2915#issuecomment-3628025049

The crash occurs due to how `isClientConnIpV6` is called using the cached client created here from this:
```
client *recording_client = createCachedResponseClient(resp);
```

**Comment by zuiderkwast** [comment]
Thank you @KarthikSubbarao for finding the root cause of the problem!

```C
        /* Fake client? Use current client instead.
         * Noted that in here we are assuming server.current_client is set
         * and real (aof has already violated this in loadSingleAppendOnlyFil). */
```

The assumption mentioned in this comment doesn't hold. CLUSTER SHARDS and CLUSTER NODES are also using `isClientConnIpV6`, so they are affected too and would crash in the same way. The comment comes from another bugfix a year ago: #1063.

I agree we need a fallback case for case where we have a fake client and no current client. This is the fix I would like to merge. Let's also remove the part of the comment that says we're assuming server.current_client is set:

```diff
     /* The cached client peer id is on the form "[IPv6]:port" for IPv6
      * addresses, so we just check for '[' here. */
     if (c->flag.fake && server.current_client) {
-        /* Fake client? Use current client instead.
-         * Noted that in here we are assuming server.current_client is set
-         * and real (aof has already violated this in loadSingleAppendOnlyFil). */
+        /* Fake client? Use current client instead, if we have one. */
         c = server.current_client;
     }
+    if (c->flag.fake && !c->conn) {
+        /* If we still don't have a client with a real connection (e.g., called
+         * from module timer with no real current client), default to IPv4 to
+         * avoid crashing. */
+        return 0;
+    }
     return getClientPeerId(c)[0] == '[';
 }
```

What I still don't understand is why the first fix (just bypassing the reply cache for cluster slots) appeared to avoid the crash. That code is using is `isClientConnIpV6` too, so I would assume it can crash too (via clusterCommandSlotsIfFakeClient -> addNodeReplyForClusterSlot -> addNodeToNodeReply -> clusterNodeIp). Do you know why it doesn't crash here?

**Comment by KarthikSubbarao** [comment]
@zuiderkwast - Yes, that is a good question and I was wondering why as well (with respect to the first call to `isClientConnIpV6` from `clusterCommandSlots -> isClientConnIpV6`). Because the crash was happening only on the second call  to `isClientConnIpV6` from the `generateClusterSlotResponse` flow (when it used the cached cluster recording client).

The reason is: When we call `isClientConnIpV6` with the module fake client (in case of the VM_Call from a module timer job), it does does not have `server.current_client` set. So, it calls `getClientPeerId(c)[0] == '['` and does not crash because conn is NULL. This results in the peerid being an empty sds. While, it does not crash, the peerid remains an empty sds in all VM_Call usages.

When we call `isClientConnIpV6` with the cached client, since `conn` is initialized (with zcalloc), it enters the code path for obtaining the peer id and crashes in `connAddr` (Commented the line of code below).


```
// Creation of the fake module client
client *moduleAllocTempClient(void) { 
    // ...
    c = createClient(NULL);
    c->flag.fake = 1;
    // ...
}
```


```
// Creation of the cached cluster recording client
client *createCachedResponseClient(int resp) {
    struct client *recording_client = createClient(NULL);
    recording_client->conn = zcalloc(sizeof(connection));  // Zeroed out initialization
    recording_client->flag.fake = 1;
    // ...
}
```

```
char *getClientPeerId(client *c) {
    char peerid[CONN_ADDR_STR_LEN] = {0};
    if (c->peerid == NULL) {
        genClientAddrString(c, peerid, sizeof(peerid), 1);
        c->peerid = sdsnew(peerid);
    }
    return c->peerid;
}

void genClientAddrString(client *client, char *addr, size_t addr_len, int remote) {
    connFormatAddr(client->conn, addr, addr_len, remote);
}

static inline int connFormatAddr(connection *conn, char *buf, size_t buf_len, int remote) {
    char ip[CONN_ADDR_STR_LEN];
    int port;
    if (connAddr(conn, ip, sizeof(ip), &port, remote) < 0) {
        return -1;
    }
    return formatAddr(buf, buf_len, ip, port);
}

static inline int connAddr(connection *conn, char *ip, size_t ip_len, int *port, int remote) {
    if (conn && conn->type->addr) {
        return conn->type->addr(conn, ip, ip_len, port, remote); // We enter this when using the cached cluster recording client. Therefore it crashes
    }
    return -1; // We enter this when using a fake module client
}
```

**Comment by bandalgomsu** [comment]
Thanks @KarthikSubbarao !! 

I also think it would be good if it could be fixed more simply. 
What do you think about adding one more condition check to that connAddr() ??

Like 
```
if (conn && conn->type && conn->type->addr)
```

**Comment by zuiderkwast** [comment]
Thanks for the explanation! So `c->conn == NULL` is no crash, but `recording_client->conn = zcalloc(sizeof(connection))` causes the crash. This confirms that 8.1 is unaffected (and so are CLUSTER SHARDS and NODES).

@bandalgomsu will you update this PR to use the fix in `isClientConnIpV6` that @KarthikSubbarao suggested above, and test using a module timer? If not, maybe you @KarthikSubbarao want to do it since you have the code? I still want to include it in 9.0.1, which is not that urgent, but I want to release it soon.

File: src/networking.c [hunk 3]
```diff
@@ -4184,11 +4184,17 @@ int isClientConnIpV6(client *c) {
...
-         * Noted that in here we are assuming server.current_client is set
-         * and real (aof has already violated this in loadSingleAppendOnlyFil). */
+        /* Fake client? Use current client instead, if we have one. */
         c = server.current_client;
     }
+
+    if (c->flag.fake || !c->conn) {
+        /* If we still don't have a client with a real connection (e.g., called
+        * from module timer with no real current client), default to IPv4 to
+        * avoid crashing. */
```
Comment (enjoy-binbin) [inline src/networking.c]:
```suggestion
         * from module timer with no real current client), default to IPv4 to
         * avoid crashing. */
```

**Review by enjoy-binbin — APPROVED** [review]
i see, thanks.

File: tests/modules/cluster.c [hunk 4]
```diff
@@ -3,6 +3,29 @@
 
 #define UNUSED(x) (void)(x)
 
+void cluster_timer_handler(ValkeyModuleCtx *ctx, void *data) {
+    VALKEYMODULE_NOT_USED(data);
+
+    ValkeyModuleCallReply *rep = ValkeyModule_Call(ctx, "CLUSTER", "c", "SLOTS");
+
+    if (rep) {
+        ValkeyModule_Log(ctx, "notice", "Timer: CLUSTER SLOTS success");
```
Comment (zuiderkwast) [inline tests/modules/cluster.c]: We could peek at what we got (as Allen suggested earlier) to check that we got an array. We could also get an error reply (VALKEYMODULE_REPLY_ERROR) for example if cluster mode is not enabled or in some other cases.

```suggestion
        if (ValkeyModule_CallReplyType(rep) == VALKEYMODULE_REPLY_ARRAY) {
            ValkeyModule_Log(ctx, "notice", "Timer: CLUSTER SLOTS success");
        } else {
            ValkeyModule_Log(ctx, "notice",
                             "Timer: CLUSTER SLOTS unexpected reply type %d",
                             ValkeyModule_CallReplyType(rep));
        }
```

**Review by zuiderkwast — APPROVED** [review]
Yeah, this is good. Thanks!

**Comment by enjoy-binbin** [comment]
Don't we need to also backport this to 8.0 / 8.1? They were also affected.

> Like valkey-search 1.1, this valkey-search 1.2 release also requires Valkey core 9.0.1 or higher.

@allenss-amazon btw, is this issue the reason we need 9.0.1? If 8.0 pick this, dose 8.0 support Valkey-Search 1.2?
