### PR TITLE
valkey-cli: ensure output ends with a newline if missing when printing reply

### LINKED ISSUE #1778: [BUG] Incorrect output formatting in valkey-cli when queuing "client info" in a transaction
**Describe the bug**

When running client info inside a `MULTI` transaction, the response `QUEUED` is incorrectly concatenated with the prompt, making it hard to read. This appears to be an output formatting issue in `valkey-cli`.

```
127.0.0.1:6379> multi
OK
127.0.0.1:6379(TX)> client info
QUEUED127.0.0.1:6379(TX)>
```

**To reproduce**

```
127.0.0.1:6379> multi
127.0.0.1:6379(TX)> client info
```

**Expected behavior**

The expected output should properly format the QUEUED response, ensuring correct spacing and line breaks:
QUEUED  
127.0.0.1:6379(TX)>

**Additional information**
Other commands (set, get) inside a transaction do not exhibit this behavior.  The response type is `REDIS_REPLY_VERB` for `client info`.

### PR DESCRIPTION
**Pull request by xbasel**
Example:
```
   127.0.0.1:6379> multi
   OK
   127.0.0.1:6379(TX)> client info
   QUEUED127.0.0.1:6379(TX)>
```

Fixes:  https://github.com/valkey-io/valkey/issues/1778

### CODE REVIEW

**Comment by madolson** [comment]
I would guess it's more likely related to this code path, https://github.com/valkey-io/valkey/blob/221ff441d92ad74f3758d6492182b0ae7d4255df/src/valkey-cli.c#L2341, which explicitly changes the output mode to raw if it's an info command. Probably need to check for multi there.

File: src/valkey-cli.c [hunk 1]
```diff
@@ -2338,21 +2338,22 @@ static int cliSendCommand(int argc, char **argv, long repeat) {
...
+          (!strcasecmp(argv[1], "nodes") || !strcasecmp(argv[1], "info"))) ||
+         (argc >= 2 && !strcasecmp(command, "client") &&
+          (!strcasecmp(argv[1], "list") || !strcasecmp(argv[1], "info"))) ||
+         (argc == 3 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "graph")) ||
+         (argc == 2 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "doctor")) ||
+         /* Format PROXY INFO command for Cluster Proxy:
+          * https://github.com/artix75/redis-cluster-proxy */
+         (argc >= 2 && !strcasecmp(command, "proxy") && !strcasecmp(argv[1], "info")))) {
         output_raw = 1;
     }
```
Comment (enjoy-binbin) [inline src/valkey-cli.c:2358]: can we correct the `output_raw` in here? something like this:
```
if (config.in_multi) output_raw = 0; /* multi must in xxx mode. */
```

Comment (xbasel) [reply src/valkey-cli.c:2358]: Are you suggesting this for readability, or to address a problem?

Comment (madolson) [reply src/valkey-cli.c:2358]: I assume readability, as it has the same result. I will say I would prefer we add a comment somewhere to include why multi does this. My hot take was going to be let's just do:

```
if (!config.in_multi) output_raw = 1; /* In a multi block, commands will return status instead of verbatim. */
```

I don't feel all that strongly though.

Comment (xbasel) [reply src/valkey-cli.c:2358]: You meant:
```
if (config.in_multi) output_raw = 0; /* In a multi block, commands will return status instead of verbatim. */
```
?

I want to skip the big if. 
See https://github.com/valkey-io/valkey/pull/1782/commits/61559bfcb69b56edcddfb8ecd61e5025902f4d19


This function could be more readable; I can refactor it in a separate PR.

Comment (madolson) [reply src/valkey-cli.c:2358]: I meant my suggestion inside the block of text, so it minimizes the number of lines changed. I'm OK with this though.

File: src/valkey-cli.c [hunk 2]
```diff
@@ -2338,21 +2338,24 @@ static int cliSendCommand(int argc, char **argv, long repeat) {
...
-         (!strcasecmp(argv[1], "nodes") || !strcasecmp(argv[1], "info"))) ||
-        (argc >= 2 && !strcasecmp(command, "client") &&
-         (!strcasecmp(argv[1], "list") || !strcasecmp(argv[1], "info"))) ||
-        (argc == 3 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "graph")) ||
-        (argc == 2 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "doctor")) ||
-        /* Format PROXY INFO command for Cluster Proxy:
-         * https://github.com/artix75/redis-cluster-proxy */
-        (argc >= 2 && !strcasecmp(command, "proxy") && !strcasecmp(argv[1], "info"))) {
+    if (config.in_multi) {
+        /* In a multi block, commands will return status instead of verbatim. */
```
Comment (madolson) [inline src/valkey-cli.c]:
```suggestion
        /* In a multi block, commands will return status strings instead of verbatim strings. */
```

**Review by madolson — APPROVED** [review]

**Review by enjoy-binbin — APPROVED** [review]
i am ok with this, but i still prefer the smaller diff way. The logic is pretty simple, we can argue that we correct it after the big if block since it is in multi.

Not a blocker to me.

File: src/valkey-cli.c [hunk 3]
```diff
@@ -2338,21 +2338,24 @@ static int cliSendCommand(int argc, char **argv, long repeat) {
...
+                (!strcasecmp(argv[1], "nodes") || !strcasecmp(argv[1], "info"))) ||
+               (argc >= 2 && !strcasecmp(command, "client") &&
+                (!strcasecmp(argv[1], "list") || !strcasecmp(argv[1], "info"))) ||
+               (argc == 3 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "graph")) ||
+               (argc == 2 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "doctor")) ||
+               /* Format PROXY INFO command for Cluster Proxy:
+                * https://github.com/artix75/redis-cluster-proxy */
+               (argc >= 2 && !strcasecmp(command, "proxy") && !strcasecmp(argv[1], "info"))) {
         output_raw = 1;
     }
```
Comment (madolson) [inline src/valkey-cli.c]:
```suggestion
    if (!strcasecmp(command, "info") || !strcasecmp(command, "lolwut") ||
        (argc >= 2 && !strcasecmp(command, "debug") && !strcasecmp(argv[1], "htstats")) ||
        (argc >= 2 && !strcasecmp(command, "debug") && !strcasecmp(argv[1], "htstats-key")) ||
        (argc >= 2 && !strcasecmp(command, "debug") && !strcasecmp(argv[1], "client-eviction")) ||
        (argc >= 2 && !strcasecmp(command, "memory") &&
         (!strcasecmp(argv[1], "malloc-stats") || !strcasecmp(argv[1], "doctor"))) ||
        (argc == 2 && !strcasecmp(command, "cluster") &&
         (!strcasecmp(argv[1], "nodes") || !strcasecmp(argv[1], "info"))) ||
        (argc >= 2 && !strcasecmp(command, "client") &&
         (!strcasecmp(argv[1], "list") || !strcasecmp(argv[1], "info"))) ||
        (argc == 3 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "graph")) ||
        (argc == 2 && !strcasecmp(command, "latency") && !strcasecmp(argv[1], "doctor")) ||
        /* Format PROXY INFO command for Cluster Proxy:
         * https://github.com/artix75/redis-cluster-proxy */
        (argc >= 2 && !strcasecmp(command, "proxy") && !strcasecmp(argv[1], "info"))) {
        output_raw = 1;
    }

    /* In a multi block, commands will return status strings instead of verbatim strings. */
    if (config.in_multi) output_raw = 0;
```
