### PR TITLE
Change the same shard failover assert to if condition to avoid crash

### LINKED ISSUE #2423: [test-failure] AddressSanitizer test failure in cluster
https://github.com/valkey-io/valkey/actions/runs/16720515261/job/47323708440
https://github.com/valkey-io/valkey/actions/runs/16699138137/job/47267407010

Observed a flaky crash during CI runs with the following AddressSanitizer error:

```
[err]: Sanitizer error: =================================================================
==19898==ERROR: AddressSanitizer: unknown-crash on address 0x0000800f7000 at pc 0x7f84694fb42e bp 0x7ffe01308a70 sp 0x7ffe01308218
READ of size 1048576 at 0x0000800f7000 thread T0
    #0 0x7f84694fb42d in memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
    #1 0x5571da24cdf0 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:29
    #2 0x5571da24cdf0 in memtest_preserving_test.constprop.0 /home/runner/work/valkey/valkey/src/memtest.c:304
    #3 0x5571d9fee0cf in memtest_test_linux_anonymous_maps /home/runner/work/valkey/valkey/src/debug.c:1995
    #4 0x5571d9ff351a in doFastMemoryTest /home/runner/work/valkey/valkey/src/debug.c:2038
    #5 0x5571d9ff351a in printCrashReport /home/runner/work/valkey/valkey/src/debug.c:2242
    #6 0x5571d9fd566b in _serverAssert /home/runner/work/valkey/valkey/src/debug.c:1060
    #7 0x5571da030f1f in clusterProcessPacket /home/runner/work/valkey/valkey/src/cluster_legacy.c:3713
    #8 0x5571da03160b in clusterReadHandler /home/runner/work/valkey/valkey/src/cluster_legacy.c:4147
    #9 0x5571da1dfa9c in callHandler /home/runner/work/valkey/valkey/src/connhelpers.h:79
    #10 0x5571da1dfa9c in connSocketEventHandler /home/runner/work/valkey/valkey/src/socket.c:301
    #11 0x5571d9db62dc in aeProcessEvents /home/runner/work/valkey/valkey/src/ae.c:486
    #12 0x5571d9db62dc in aeProcessEvents /home/runner/work/valkey/valkey/src/ae.c:411
    #13 0x5571d9db62dc in aeMain /home/runner/work/valkey/valkey/src/ae.c:543
    #14 0x5571d9d9586b in main /home/runner/work/valkey/valkey/src/server.c:7332
    #15 0x7f846902a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
    #16 0x7f846902a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
    #17 0x5571d9d97ef4 in _start (/home/runner/work/valkey/valkey/src/valkey-server+0x14eef4) (BuildId: 41c6564d21892c806c4de8afed97a9be1625ac85)
```

### PR DESCRIPTION
**Pull request by enjoy-binbin**
The assert was added in #2301 and we found that there are some situations
would trigger assert and crash the server.

The reason we added the assert is because, in the code:
1. sender_claimed_primary and sender are in the same shard
2. and sender is the old primary, sender_claimed_primary is the old replica
3. and now sender become a replica, sender_claimed_primary become a primary

That means a failover happend in the shard, and sender should be the primary
of sender_claimed_primary. But obviously this assumption may be wrong, we rely
on shard_id to determine whether it is in a same shard, and assume that a shard
can only have one primary.

But this is wrong, from #2279 we can know there will be a case that we can
create two primaries in the same shard due to the untimely update of shard_id.
So we can create a test that trigger the assert in this way:
1. pre condition: two primaries in the same shard, one has slots and one is empty.
2. replica doing a cluster failover
3. the empty primary doing a cluster replicate with the replica (new primary)

We change the assert to an if condition to fix it.

Closes #2423.

Note that the test written here also exposes the issue in #2441, so these two
may need to be addressed together.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
also see https://github.com/valkey-io/valkey/pull/2301#pullrequestreview-3085153730 for some details, i will add the test later tomorrow.

**Comment by sarthakaggarwal97** [comment]
The removal of this assert will fix: https://github.com/valkey-io/valkey/issues/2423.

**Review by madolson — APPROVED** [review]

**Review by sarthakaggarwal97 — APPROVED** [review]

**Comment by sarthakaggarwal97** [comment]
@enjoy-binbin @PingXie not sure what happened recently, but the assertion is failing in some of the PR runs now. Eg: https://github.com/valkey-io/valkey/actions/runs/16834099551/job/47689042910?pr=2452

It would be good to have this PR merged.

**Comment by enjoy-binbin** [comment]
Just waitting for Ping to review it. There is also another issue need to be fix: #2441. The test i write in this PR will trigger #2441 issue, so these two might need to be fix together.

Or the other way is i can merge this PR first and then leave #2441 for a while since it is a debugAssert. But let's wait @PingXie for another one or two days. I will ping he in the private thread.

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -3767,8 +3767,8 @@ int clusterProcessPacket(clusterLink *link) {
                             /* This packet is stale so we avoid processing it anymore. Otherwise
                              * this may cause a primary-replica chain issue. */
                             return 1;
-                        } else if (nodeIsReplica(sender_claimed_primary)) {
-                            serverAssert(sender_claimed_primary->replicaof == sender);
+                        } else if (nodeIsReplica(sender_claimed_primary) &&
+                                   sender_claimed_primary->replicaof == sender) {
```
Comment (zuiderkwast) [inline src/cluster_legacy.c:3802]: This change looks safe and it avoids the crash that we have seen in CI. I think we need to merge it.

**Review by zuiderkwast — APPROVED** [review]

File: tests/unit/cluster/manual-failover.tcl [hunk 2]
```diff
@@ -502,3 +502,196 @@ start_cluster 3 1 {tags {external:skip cluster}} {
         wait_for_cluster_propagation
     }
 }
+
+start_cluster 3 2 {tags {external:skip cluster}} {
+    # This test consists of two blocks.
```
Comment (PingXie) [inline tests/unit/cluster/manual-failover.tcl]: nit 
```suggestion
    # This test consists of two phases.
```

File: tests/unit/cluster/manual-failover.tcl [hunk 3]
```diff
@@ -502,3 +502,196 @@ start_cluster 3 1 {tags {external:skip cluster}} {
...
+    # 9. R0 (empty primary) and R4 (new primary) end up being primaries in the same shard while R4 continues to own slots.
+    #
+    # The second block.
+    # In the R0/R3/R4 shard, R4 is the primary, R3 is the replica, and R0 is en empty primary.
+    # 1. We will perform a failover on R3, and perform a replicate on R0 to make R0 a replica of R3.
+    # 2. When R3 becomes the new primary node, it will broadcast a message to all nodes in the cluster.
+    # 3. When R4 receives the message, it becomes the new replica and also will broadcast the message to all nodes in the cluster.
+    # 4. When R0 becomes a replica after the replicate, it will broadcast a message to all nodes in the cluster.
+    # 5. Let's assume that R1 and R2 receive the message from R0 and R4 first and then the message from R3 (new primary) later.
+    # 6. R1 will receive messages from R0 after the replicate, R0 is a replica, and its primary is R3.
```
Comment (PingXie) [inline tests/unit/cluster/manual-failover.tcl]:
```suggestion
    # 6. R1 will receive messages from R0 after the replication, R0 is a replica, and its primary is R3.
```

File: tests/unit/cluster/manual-failover.tcl [hunk 4]
```diff
@@ -502,3 +502,196 @@ start_cluster 3 1 {tags {external:skip cluster}} {
...
+    #       R0 (old primary) become an empty primary.
+    #    c. R0 (empty primary) then updates the actual shard_id of R4 (new primary) while processing the ping extensions.
+    # 9. R0 (empty primary) and R4 (new primary) end up being primaries in the same shard while R4 continues to own slots.
+    #
+    # The second block.
+    # In the R0/R3/R4 shard, R4 is the primary, R3 is the replica, and R0 is en empty primary.
+    # 1. We will perform a failover on R3, and perform a replicate on R0 to make R0 a replica of R3.
+    # 2. When R3 becomes the new primary node, it will broadcast a message to all nodes in the cluster.
+    # 3. When R4 receives the message, it becomes the new replica and also will broadcast the message to all nodes in the cluster.
+    # 4. When R0 becomes a replica after the replicate, it will broadcast a message to all nodes in the cluster.
```
Comment (PingXie) [inline tests/unit/cluster/manual-failover.tcl]:
```suggestion
    # 4. When R0 becomes a replica after the replication, it will broadcast a message to all nodes in the cluster.
```

**Review by PingXie — APPROVED** [review]
this change make senses. basically the removed assert will fire for any "multiple primaries" case and #2301 could just be one of them.

File: src/cluster_legacy.c (hunk 1 above)
Comment (enjoy-binbin) [reply src/cluster_legacy.c:3802]: Not that we got ACK from Ping, i am merging it.
