### PR TITLE
Fix replica can't finish failover when config epoch is outdated

### LINKED ISSUE #2169: [BUG] Failover auth denied to a replica pod because slot epoch (5) > reqConfigEpoch (2) - a bug?
Ocasionally when a primary pod is killed, failover cannot happen due to error (epoch values might differ - but there is a mismatch):

Failover auth denied to a pod because slot epoch (5) > reqConfigEpoch (2).

Initially cluster configEpoch is 0, each time when pod is created epoch is raised by one. Epoch values raise as pods are being created. Also when we observe other actions being done in the cluster that cause the epoch to change – servers start to restart one by one - and as a result with each restart epoch value raises - up to this point expected behavior. 

Then we see that one replica tries to do failover after it’s primary was killed and we see that Failover happens and configEpoch value also raises.

And so on  - with each cluster change (in this example pod kill, failover, new pod creation) - epoch value raises by 1 - so  again expected behavior.

But in some scenarios the replica cannot do the Failover due to Failover auth denied, because required config epoch is 2 – so very early stage of cluster existence.

Given epoch is 5 so also very early stage of the cluster (when not even all pods were created).
It seems that in this case – while Failover attempt started, cluster did only know about earlier epoch values.
Observed on Valkey 8.0. and also 8.1. 

Failing scenario:
Replica cannot do the Failover due to Failover auth denied. Like in this example – primary d4c2 is killed – it’s replica is 0a03

```
I0521 10:06:33.326579       1 *142] 18:M Client closed connection id=178 addr=10.1.58.249:38342 laddr=10.1.232.42:6380 fd=17 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=0 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=570 tot-net-out=1245 tot-cmds=5
I0521 10:06:33.334852       1 *142] 18:M Accepted 10.1.58.249:38350
I0521 10:06:33.409015       1 *142] 18:M Connection with Node d4c2cd060ce031a35f35efeea956e710c981e683 at 10.1.154.149:16380 failed: (null)
I0521 10:06:33.409050       1 * 18:M Freeing cluster link for node: d4c2cd060ce031a35f35efeea956e710c981e683:outbound ()
I0521 10:06:33.437434       1 *142] 18:M Client closed connection id=179 addr=10.1.58.249:38350 laddr=10.1.232.42:6380 fd=17 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=0 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=570 tot-net-out=1248 tot-cmds=5
I0521 10:06:33.438879       1 *142] 18:M Accepted 10.1.58.249:38366
I0521 10:06:33.509920       1 *142] 18:M Connection with Node d4c2cd060ce031a35f35efeea956e710c981e683 at 10.1.154.149:16380 failed: (null)
I0521 10:06:33.509955       1 * 18:M Freeing cluster link for node: d4c2cd060ce031a35f35efeea956e710c981e683:outbound ()
I0521 10:06:33.586323       1 * 18:M --- Processing packet of type auth-req, 2256 bytes
W0521 10:06:33.586354       1 *176] 18:M Failover auth denied to 0a035c77da5c7660d23cdd4caa00069b3c6b31c9 (): slot 0 epoch (5) > reqConfigEpoch (2)
I0521 10:06:34.013625       1 * 18:M Sending ping packet to node 3a170f451202a5c6e29ef9c7cfcd63424cc9b1f3 () on outbound link
I0521 10:06:34.014535       1 * 18:M --- Processing packet of type pong, 2616 bytes
I0521 10:06:34.014554       1 * 18:M pong packet received: 3a170f451202a5c6e29ef9c7cfcd63424cc9b1f3
I0521 10:06:34.014559       1 * 18:M node 3a170f451202a5c6e29ef9c7cfcd63424cc9b1f3 () announces that it is a replica in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:34.014565       1 * 18:M GOSSIP 0a035c77da5c7660d23cdd4caa00069b3c6b31c9 10.1.179.177:6380@16380 slave
I0521 10:06:34.014569       1 * 18:M GOSSIP 7fc336632ffb5c09733f47969e6bd281d9afafe8 10.1.207.150:6380@16380 slave
I0521 10:06:34.014573       1 * 18:M GOSSIP d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master
```

Logs from replica 0a03 that tries to do Failover -it logs node config epoch – 2:

```
I0521 10:06:33.464089       1 *142] 17:S Accepted 10.1.58.249:48116
I0521 10:06:33.497961       1 *142] 17:S Accepted 127.0.0.1:33622
I0521 10:06:33.505982       1 *142] 17:S Connection with Node d4c2cd060ce031a35f35efeea956e710c981e683 at 10.1.154.149:16380 failed: (null)
I0521 10:06:33.506020       1 *178] 17:S Freeing cluster link for node: d4c2cd060ce031a35f35efeea956e710c981e683:outbound ()
I0521 10:06:33.510807       1 *142] 17:S Client closed connection id=80 addr=127.0.0.1:33622 laddr=127.0.0.1:6380 fd=20 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=slowlog|get user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=471 tot-net-out=16680 tot-cmds=9
I0521 10:06:33.585547       1 *174] 17:S Forced failover user request accepted (user request from 'id=79 addr=10.1.58.249:48116 laddr=10.1.179.177:6380 fd=19 name=*redacted* user=*redacted* lib-name= lib-ver=').
I0521 10:06:33.585597       1 *174] 17:S Start of election delayed for 0 milliseconds (rank #0, primary rank #0, offset 476).
I0521 10:06:33.585606       1 *174] 17:S Starting a failover election for epoch 16, node config epoch is 2
I0521 10:06:33.588201       1 *178] 17:S --- Processing packet of type auth-ack, 2256 bytes
I0521 10:06:33.588244       1 *174] 17:S Currently unable to failover: Waiting for votes, but majority still not reached.
I0521 10:06:33.588253       1 *174] 17:S Needed quorum: 2. Number of votes received so far: 1
I0521 10:06:34.008540       1 *178] 17:S Pinging node 7fc336632ffb5c09733f47969e6bd281d9afafe8
I0521 10:06:34.008585       1 *178] 17:S Sending ping packet to node 7fc336632ffb5c09733f47969e6bd281d9afafe8 () on outbound link
I0521 10:06:34.008597       1 *174] 17:S Currently unable to failover: Waiting for votes, but majority still not reached.
I0521 10:06:34.008606       1 *174] 17:S Needed quorum: 2. Number of votes received so far: 1
I0521 10:06:34.009246       1 *178] 17:S --- Processing packet of type pong, 2568 bytes

```
**To reproduce**
So far we observed this issue only when primary which was created as a first primary in the cluster is deleted. When other primaries are deleted, Failover happens.

**Expected behavior**

No mismatch in configEpoch values, so that Failover auth is granted.

Logs from passing scenario: 

```
I0521 10:06:16.573955       1 * 18:S Manual failover user request accepted (user request from 'id=81 addr=10.1.58.249:46486 laddr=10.1.232.42:6380 fd=25 name=*redacted* user=*redacted* lib-name= lib-ver=').
I0521 10:06:16.574620       1 * 18:S --- Processing packet of type ping, 2568 bytes
I0521 10:06:16.574635       1 redislogger.go:174] 18:S Received replication offset for paused primary manual failover: 238
I0521 10:06:16.574641       1 * 18:S Sending pong packet to node f239c865cd45746d02ef1196bfd50f611cd47edd () on outbound link
I0521 10:06:16.574718       1 * 18:S ping packet received: f239c865cd45746d02ef1196bfd50f611cd47edd
I0521 10:06:16.574726       1 * 18:S node f239c865cd45746d02ef1196bfd50f611cd47edd () announces that it is a primary in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:16.574730       1 * 18:S GOSSIP 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave
I0521 10:06:16.574733       1 * 18:S GOSSIP d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master
I0521 10:06:16.574737       1 * 18:S All primary replication stream processed, manual failover can start.
I0521 10:06:16.574750       1 * 18:S Start of election delayed for 0 milliseconds (rank #0, primary rank #0, offset 238).
I0521 10:06:16.574753       1 *18:S Starting a failover election for epoch 11, node config epoch is 9
I0521 10:06:16.577136       1 * 18:S --- Processing packet of type auth-ack, 2256 bytes
I0521 10:06:16.577162       1 * 18:S --- Processing packet of type auth-ack, 2256 bytes
I0521 10:06:16.577169       1 * 18:S Failover election won: I'm the new primary.
I0521 10:06:16.577175       1 * 18:S configEpoch set to 11 after successful failover
I0521 10:06:16.579316       1 * f239c865cd45746d02ef1196bfd50f611cd47edd 10.1.58.252:6380@16380 master - 0 1747821976029 9 connected
I0521 10:06:16.579338       1 * 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master - 0 1747821976029 7 connected 5461-10922
I0521 10:06:16.579343       1 * f6341f2c3e0147f218e2c1a74370f32d47acf0f2 10.1.232.42:6380@16380 myself,master - 0 0 11 connected 10923-16383
I0521 10:06:16.579346       1 * 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave 05b93f680873c3722254841418a9af6311ee37e2 0 1747821976000 7 connected
I0521 10:06:16.579349       1 * ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave d4c2cd060ce031a35f35efeea956e710c981e683 0 1747821976139 5 connected
I0521 10:06:16.579352       1 * d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master - 0 1747821976130 5 connected 0-5460
I0521 10:06:16.579354       1 *
I0521 10:06:16.579407       1 * 18:S Setting myself to primary in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3 after failover; my old primary is f239c865cd45746d02ef1196bfd50f611cd47edd ()
I0521 10:06:16.579418       1 * 18:M Connection with primary lost.
I0521 10:06:16.579423       1 * 18:M Caching the disconnected primary state.
I0521 10:06:16.579432       1 * 18:M Discarding previously cached primary state.
I0521 10:06:16.579436       1 * 18:M Setting secondary replication ID to 7d94b2e191a4f888bbe5a008d2b228584d88ca72, valid up to offset: 239. New replication ID is 8956493558df53c3f2daa10a6fbc82a5bc7e4cd5
I0521 10:06:16.579440       1 * 18:M Sending pong packet to node f239c865cd45746d02ef1196bfd50f611cd47edd () on outbound link
I0521 10:06:16.579445       1 * 18:M Sending pong packet to node 05b93f680873c3722254841418a9af6311ee37e2 () on outbound link
I0521 10:06:16.579449       1 * 18:M Sending pong packet to node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () on outbound link
I0521 10:06:16.579455       1 * 18:M Sending pong packet to node ec87079104e9f7205d69a3390e03d4124863ff84 () on outbound link
I0521 10:06:16.579459       1 * 18:M Sending pong packet to node d4c2cd060ce031a35f35efeea956e710c981e683 () on outbound link
I0521 10:06:16.579464       1 * 18:M --- Processing packet of type auth-ack, 2256 bytes
I0521 10:06:16.580657       1 redislogger.go:142] 18:M Accepted 10.1.58.252:51054
I0521 10:06:16.583402       1 * 18:M --- Processing packet of type pong, 2672 bytes
I0521 10:06:16.583419       1 * 18:M pong packet received: f239c865cd45746d02ef1196bfd50f611cd47edd
I0521 10:06:16.583426       1 * 18:M node f239c865cd45746d02ef1196bfd50f611cd47edd () announces that it is a replica in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:16.583432       1 * 18:M A failover occurred in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3; node f239c865cd45746d02ef1196bfd50f611cd47edd () failed over to node f6341f2c3e0147f218e2c1a74370f32d47acf0f2 () with a config epoch of 11
I0521 10:06:16.583440       1 * 18:M Node f239c865cd45746d02ef1196bfd50f611cd47edd () is now a replica of node f6341f2c3e0147f218e2c1a74370f32d47acf0f2 () in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:16.583445       1 * 18:M GOSSIP 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave
I0521 10:06:16.583453       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:16.583459       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:16.590764       1 * 18:M Replica 10.1.58.252:6380 asks for synchronization
I0521 10:06:16.590785       1 * 18:M [PSYNC] Replica request offset: 239
I0521 10:06:16.590857       1 * 18:M [PSYNC] Backlog history len is zero
I0521 10:06:16.590864       1 redislogger.go:174] 18:M Partial resynchronization request from 10.1.58.252:6380 accepted. Sending 0 bytes of backlog starting from offset 239.
I0521 10:06:16.703300       1 * 18:M I/O error reading from node link (05b93f680873c3722254841418a9af6311ee37e2:outbound): error:0A000126:SSL routines::unexpected eof while reading
I0521 10:06:16.703343       1 * 18:M Freeing cluster link for node: 05b93f680873c3722254841418a9af6311ee37e2:outbound ()
I0521 10:06:16.706716       1 * 18:M I/O error reading from node link (05b93f680873c3722254841418a9af6311ee37e2:inbound): error:0A000126:SSL routines::unexpected eof while reading
I0521 10:06:16.706735       1 * 18:M Freeing cluster link for node: 05b93f680873c3722254841418a9af6311ee37e2:inbound ()
I0521 10:06:16.735085       1 * 18:M Connection with Node 05b93f680873c3722254841418a9af6311ee37e2 at 10.1.179.186:16380 failed: (null)
I0521 10:06:16.735112       1 * 18:M Freeing cluster link for node: 05b93f680873c3722254841418a9af6311ee37e2:outbound ()
I0521 10:06:16.792906       1 * 18:M Client closed connection id=81 addr=10.1.58.249:46486 laddr=10.1.232.42:6380 fd=25 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=760 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=721 tot-net-out=3824 tot-cmds=10
I0521 10:06:16.804558       1 * 18:M Accepted 10.1.58.249:44784
I0521 10:06:16.847634       1 * 18:M Connection with Node 05b93f680873c3722254841418a9af6311ee37e2 at 10.1.179.186:16380 failed: (null)
I0521 10:06:16.847665       1 * 18:M Freeing cluster link for node: 05b93f680873c3722254841418a9af6311ee37e2:outbound ()
I0521 10:06:16.903101       1 * 18:M Client closed connection id=85 addr=10.1.58.249:44784 laddr=10.1.232.42:6380 fd=17 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=0 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=570 tot-net-out=1236 tot-cmds=5
I0521 10:06:16.903325       1 * 18:M Accepted 10.1.58.249:44798
I0521 10:06:16.937629       1 * 18:M Connection with Node 05b93f680873c3722254841418a9af6311ee37e2 at 10.1.179.186:16380 failed: (null)
I0521 10:06:16.937665       1 * 18:M Freeing cluster link for node: 05b93f680873c3722254841418a9af6311ee37e2:outbound ()
I0521 10:06:16.959105       1 * 18:M --- Processing packet of type ping, 2672 bytes
I0521 10:06:16.959182       1 * 18:M Sending pong packet to node f239c865cd45746d02ef1196bfd50f611cd47edd () on inbound link
I0521 10:06:16.959189       1 * 18:M ping packet received: f239c865cd45746d02ef1196bfd50f611cd47edd
I0521 10:06:16.959195       1 * 18:M node f239c865cd45746d02ef1196bfd50f611cd47edd () announces that it is a replica in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:16.959201       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:16.959206       1 * 18:M GOSSIP 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave
I0521 10:06:16.959212       1 * 18:M GOSSIP d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master
I0521 10:06:16.999789       1 * 18:M Client closed connection id=86 addr=10.1.58.249:44798 laddr=10.1.232.42:6380 fd=17 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=0 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=570 tot-net-out=1239 tot-cmds=5
I0521 10:06:17.011366       1 * 18:M Accepted 10.1.58.249:44806
I0521 10:06:17.037994       1 * 18:M Pinging node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6
I0521 10:06:17.038033       1 * 18:M Sending ping packet to node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () on outbound link
I0521 10:06:17.038041       1 * 18:M Sending ping packet to node f239c865cd45746d02ef1196bfd50f611cd47edd () on outbound link
I0521 10:06:17.038047       1 * 18:M Sending ping packet to node 05b93f680873c3722254841418a9af6311ee37e2 () on outbound link
I0521 10:06:17.038510       1 * 18:M --- Processing packet of type pong, 2616 bytes
I0521 10:06:17.038524       1 * 18:M pong packet received: 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6
I0521 10:06:17.038538       1 * 18:M node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () announces that it is a replica in shard 2b7282a44c31f2b1ca3ef83ec18885f29a59e0e6
I0521 10:06:17.038541       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:17.038641       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:17.038650       1 * 18:M GOSSIP f239c865cd45746d02ef1196bfd50f611cd47edd 10.1.58.252:6380@16380 slave
I0521 10:06:17.038654       1 * 18:M --- Processing packet of type pong, 2464 bytes
I0521 10:06:17.038658       1 * 18:M pong packet received: f239c865cd45746d02ef1196bfd50f611cd47edd
I0521 10:06:17.038662       1 * 18:M node f239c865cd45746d02ef1196bfd50f611cd47edd () announces that it is a replica in shard c826678a1dc9e22c59567eb378cc1356a0bf24e3
I0521 10:06:17.038666       1 * 18:M GOSSIP 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave
I0521 10:06:17.092958       1 * 18:M --- Processing packet of type ping, 2616 bytes
I0521 10:06:17.092987       1 * 18:M Sending pong packet to node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () on inbound link
I0521 10:06:17.092992       1 * 18:M ping packet received: 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6
I0521 10:06:17.092995       1 * 18:M node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () announces that it is a replica in shard 2b7282a44c31f2b1ca3ef83ec18885f29a59e0e6
I0521 10:06:17.093000       1 * 18:M GOSSIP d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master
I0521 10:06:17.093003       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:17.093006       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:17.138916       1 * 18:M Total: 3 clients connected (1 replicas), 2728960 (2.60M) bytes in use
I0521 10:06:17.138950       1 * 18:M Sending ping packet to node d4c2cd060ce031a35f35efeea956e710c981e683 () on outbound link
I0521 10:06:17.139711       1 * 18:M --- Processing packet of type pong, 2672 bytes
I0521 10:06:17.139727       1 * 18:M pong packet received: d4c2cd060ce031a35f35efeea956e710c981e683
I0521 10:06:17.139732       1 * 18:M node d4c2cd060ce031a35f35efeea956e710c981e683 () announces that it is a primary in shard f3ca9f744c48d0936aac81effc05f18d12726c64
I0521 10:06:17.139736       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:17.139739       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:17.139747       1 * 18:M GOSSIP 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 10.1.58.251:6380@16380 slave
I0521 10:06:17.160992       1 * 18:M --- Processing packet of type auth-req, 2256 bytes
I0521 10:06:17.161053       1 * 18:M Failover auth granted to 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () for epoch 12
I0521 10:06:17.166541       1 * 18:M --- Processing packet of type pong, 2616 bytes
I0521 10:06:17.166579       1 * 18:M pong packet received: 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6
I0521 10:06:17.166585       1 * 18:M node 5a152cdc8d43e1af1d925caa8bd68380d1bba6a6 () announces that it is a primary in shard 2b7282a44c31f2b1ca3ef83ec18885f29a59e0e6
I0521 10:06:17.166781       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:17.166791       1 * 18:M GOSSIP d4c2cd060ce031a35f35efeea956e710c981e683 10.1.154.149:6380@16380 master
I0521 10:06:17.166796       1 * 18:M GOSSIP ec87079104e9f7205d69a3390e03d4124863ff84 10.1.58.250:6380@16380 slave
I0521 10:06:17.239912       1 * 18:M Sending ping packet to node ec87079104e9f7205d69a3390e03d4124863ff84 () on outbound link
I0521 10:06:17.240663       1 * 18:M --- Processing packet of type pong, 2568 bytes
I0521 10:06:17.240688       1 * 18:M pong packet received: ec87079104e9f7205d69a3390e03d4124863ff84
I0521 10:06:17.240697       1 * 18:M node ec87079104e9f7205d69a3390e03d4124863ff84 () announces that it is a replica in shard f3ca9f744c48d0936aac81effc05f18d12726c64
I0521 10:06:17.240702       1 * 18:M GOSSIP 05b93f680873c3722254841418a9af6311ee37e2 10.1.179.186:6380@16380 master
I0521 10:06:17.240709       1 * 18:M GOSSIP f239c865cd45746d02ef1196bfd50f611cd47edd 10.1.58.252:6380@16380 slave
I0521 10:06:17.442469       1 * 18:M Cluster forget 05b93f680873c3722254841418a9af6311ee37e2 (user request from 'id=87 addr=10.1.58.249:44806 laddr=10.1.232.42:6380 fd=17 name=*redacted* user=*redacted* lib-name= lib-ver=').
I0521 10:06:17.442507       1 * 18:M Deleting node 05b93f680873c3722254841418a9af6311ee37e2 () from cluster view
```

**Additional information**

Any additional information that is relevant to the problem.

### PR DESCRIPTION
**Pull request by enjoy-binbin**
When the primary changes the config epoch and then down immediately,
the replica may not update the config epoch in time. Although we will
broadcast the change in cluster (see #1813), there may be a race in
the network or in the code. In this case, the replica will never finish
the failover since other primaries will refuse to vote because the
replica's slot config epoch is old.

We need a way to allow the replica can finish the failover in this case.

When the primary refuses to vote because the replica's config epoch is
less than the dead primary's config epoch, it can send an UPDATE packet
to the replica to inform the replica about the dead primary. The UPDATE
message contains information about the dead primary's config epoch and
owned slots. The failover will time out, but later the replica can try
again with the updated config epoch and it can succeed.

Fixes #2169.

### CODE REVIEW

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -4682,6 +4683,16 @@ void clusterSendFailoverAuthIfNeeded(clusterNode *node, clusterMsg *request) {
...
+
+        /* Send an UPDATE message to the replica. After receiving the UPDATE message,
+         * the replica will update the slots config so that it can initiate a failover
+         * again later. Otherwise the replica will never get votes if the primary is down. */
+        serverLog(LL_VERBOSE,
+                  "Node %.40s (%s) has old slots configuration, sending "
+                  "an UPDATE message about %.40s (%s)",
+                  node->name, node->human_nodename,
+                  server.cluster->slots[j]->name, server.cluster->slots[j]->human_nodename);
+        clusterSendUpdate(node->link, server.cluster->slots[j]);
```
Comment (hpatro) [inline src/cluster_legacy.c:4695]: This will cause a storm of message in a large cluster setup i.e. each primary sending an update message to this replica and the information will be redundant. 

Could we instead initiate a request from the replica itself to a random node on failover denial (let's say after 3 attempts) ?

The other alternative which I could think of is have a `FAILOVER_AUTH_DENY` message and provide the reason in it. Further, the replica could request a `UPDATE` message from the node. The primary benefit of this approach is that the `DENY` message would be of much smaller payload size in comparison to the `UPDATE` message payload size.

**Review by hpatro — COMMENTED** [review]
Thanks for the PR.

Have an apprehension around large cluster setup. Shared couple of ideas in a comment.

File: src/cluster_legacy.c (hunk 1 above)
Comment (zuiderkwast) [reply src/cluster_legacy.c:4695]: A storm from all to one is not too bad? In a successful failover, the replica will receive a storm of votes from all primaries. Here, the primary just sends an UPDATE instead of a vote so the number of messages is the same as a successful failover.

File: tests/unit/cluster/failover2.tcl [hunk 2]
```diff
@@ -133,3 +133,100 @@ run_solo {cluster} {
         }
     } ;# start_cluster
 } ;# run_solo
+
+proc test_replica_config_epoch_failover {type} {
```
Comment (zuiderkwast) [inline tests/unit/cluster/failover2.tcl:139]: This proc has some pre-conditions about the nodes in the cluster. Node 0-2 are primaries and node 3 is a replica of node 0? Basically, this needs to run in `start_cluster 3 1`. Please write this in a comment for this proc.

**Review by zuiderkwast — APPROVED** [review]
Awesome work!

I think we can merge this because it fixes a problem the cluster can't recover from. We can backport this PR.

To address Hari's concern about a traffic storm, we can introduce a new message as a follow up, either an UPDATE with lightweight header or an AUTH_DENY lightweight message. But this would be only for future versions, not to be backported.

File: src/cluster_legacy.c (hunk 1 above)
Comment (zuiderkwast) [reply src/cluster_legacy.c:4695]: What's the size of an UPDATE message? I believe it's 4KB, because it contains the senders slot map in the header and the 3rd node's slot map in the payload. Each slot map is 2KB (one bit for each of the 16K slots). The rest are just small fields. The UPDATE doesn't contain gossip sections like PING and PONG, so it's not that big.

To compare, AUTH_ACK is 2KB (the header with the sender's slot map), so UPDATE is just twice that size.

I'm not too worried about this in a large cluster, because this problem is very rare.

File: tests/unit/cluster/failover2.tcl (hunk 2 above)
Comment (enjoy-binbin) [reply tests/unit/cluster/failover2.tcl:139]: We (or I) have written this elsewhere (like test_sub_replica)... These procs do need to be related to the caller to be readable, but they are usually at the end. Or maybe i can do that (i pushed a commit)

File: src/cluster_legacy.c (hunk 1 above)
Comment (PingXie) [reply src/cluster_legacy.c:4695]: >This will cause a storm of message in a large cluster setup i.e. each primary sending an update message to this replica and the information will be redundant.

How big a cluster in your experience would this be a concern? is your concern on the burst-able VMs too? the processing on the receiving replica should be minimum after it receives the first UPDATE packet since there is a fast-fail to bail out of the processing if the incoming epoch is not higher, which is only true for the first UPDATE packet

File: tests/unit/cluster/failover2.tcl [hunk 3]
```diff
@@ -133,3 +133,101 @@ run_solo {cluster} {
         }
     } ;# start_cluster
 } ;# run_solo
+
+# start_cluster 3 1 {tags {external:skip cluster} overrides {cluster-replica-validity-factor 0}}
```
Comment (madolson) [inline tests/unit/cluster/failover2.tcl:138]: Is this left over code?

File: src/cluster_legacy.c (hunk 1 above)
Comment (hpatro) [reply src/cluster_legacy.c:4695]: That's a good callout as well @PingXie. I think let's get this in and see if we need optimization in the future. This scenario is pretty rare so we should be fine with this approach I believe.

**Review by hpatro — APPROVED** [review]

File: tests/unit/cluster/failover2.tcl (hunk 3 above)
Comment (hpatro) [reply tests/unit/cluster/failover2.tcl:138]: https://github.com/valkey-io/valkey/pull/2178#discussion_r2132323729

Comment (zuiderkwast) [reply tests/unit/cluster/failover2.tcl:138]: It's a comment written in TCL instead of English. :)

Comment (zuiderkwast) [reply tests/unit/cluster/failover2.tcl:138]:
```suggestion
# Needs to run in the body of
# start_cluster 3 1 {tags {external:skip cluster} overrides {cluster-replica-validity-factor 0}}
```

File: tests/unit/cluster/failover2.tcl [hunk 4]
```diff
@@ -133,3 +133,101 @@ run_solo {cluster} {
...
+        # Restore the old primary, make sure it can covert
+        resume_process [srv 0 pid]
+        wait_for_condition 1000 50 {
+            [s 0 role] == "slave" &&
+            [CI 0 cluster_state] == "ok"
+        } else {
+            fail "The old primary was not converted into replica"
+        }
+    }
+} ;# start_cluster
```
Comment (madolson) [inline tests/unit/cluster/failover2.tcl]:
```suggestion
}
```

File: tests/unit/cluster/failover2.tcl (hunk 3 above)
Comment (madolson) [inline tests/unit/cluster/failover2.tcl:138]:
```suggestion
```
I would still prefer, but I don't feel strongly.

**Review by madolson — APPROVED** [review]

File: tests/unit/cluster/failover2.tcl (hunk 3 above)
Comment (zuiderkwast) [reply tests/unit/cluster/failover2.tcl:138]: The proc only works in very specific pre-conditions and I think a comment about it would be good to have. I'd prefer a comment in plain English, but a code example is better than nothing IMHO.
