### PR TITLE
Fix used_memory_dataset underflow due to miscalculated used_memory_overhead

### LINKED ISSUE #2994: [BUG] Serious and Curious Memory Statistic Problem of `used_memory` and `used_memory_dataset`
# Describe the bug

On a server with multiple cpu sockets, the statistic data overflowed. We assume it is related to `NUMA`.

a) `used_memory` < `used_memory_overhead`, which caused `INFO memory` returned a very large `used_memory_dataset` value
b) `used_memory` showed a very large number, definitely greater than `maxmemory`, which prevented key-values to be modified (OOM error)

We are still investigating the problem. Thank you all for any advancing help/advice.

# To reproduce

Install a 3-master and 3-slave cluster on x86_64 server, which has multi-socket Intel or AMD CPUs and NUMA enabled. A qemu virtual machine with NUMA enabled will also work. So far, we are not able to reproduced on any aarch64 cpu, single cpu socket or NUMA disabled environment.

When the cluster starts, invoke `INFO memory` command on any node. An overflowed `used_memory_dataset` will be observed,

```
# Memory
used_memory:2905323
used_memory_human:2.77M
used_memory_rss:4767744
used_memory_rss_human:4.55M
used_memory_peak:2907216
used_memory_peak_human:2.77M
used_memory_peak_perc:99.93%
used_memory_overhead:2997967
used_memory_startup:2707502
used_memory_dataset:18446744073709458972
used_memory_dataset_perc:9324967778844672.00%
```

If you insert enough key-values to it, the problem may go away, along with the increasing statistic data (overflowed negative will eventually become positive), though the statistic data are still suspicious.

**`used_memory` overflow is very hard to reproduce**. We only observed once on  4 nodes out of a 96-node cluster, which is a production system. When the nodes were restarted, `used_memory` became reasonable and never overflowed since then.

# Expected behavior

Memory statistics should be work on any CPU architecture, at least `used_memory` should be correct enough for the server to function normally (no OOM).

# Additional information

The following are proved **NOT helpful** to solve the problem,

- modify code to use atomic operations on array elements of `used_memory_thread`
- start valkey-server with `numactl --cpunodebind=0 --membind=0`
- start valkey-server with `numactl --interleave=all`
- add kernel boot parameter `numa=off`

These Redis / Valkey versions are proved to work well (no overflow),
- redis 7.2.12 w/ glibc 2.41
- redis 8.4.0 w/ musl libc 1.2.5 (also threaded)
- valkey 7.2.11 w/ glibc 2.41

The following versions are proved to be affected by the problem (`used_memory_dataset` overflow),
- valkey 8.1.5 w/ jemalloc 5.3.0
- valkey 9.0.1 w/ jemalloc 5.3.0
- valkey 8.1.5 w/ glibc 2.41
- valkey 9.0.1 w/ glibc 2.41
- valkey 9.0.0 w/ musl libc 1.2.5

# Test Cases

## Case #1 Overflowed `used_memory`

Production system with AMD-compatible Hygon CPU. There were 4 out of 96 nodes with similar problem.

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        8
Vendor ID:           HygonGenuine
CPU family:          24
Model:               2
Model name:          Hygon C86 7390 32-core Processor
Stepping:            2
CPU MHz:             2701.478
CPU max MHz:         2700.0000
CPU min MHz:         1600.0000
BogoMIPS:            5399.67
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7,64-71
NUMA node1 CPU(s):   8-15,72-79
NUMA node2 CPU(s):   16-23,80-87
NUMA node3 CPU(s):   24-31,88-95
NUMA node4 CPU(s):   32-39,96-103
NUMA node5 CPU(s):   40-47,104-111
NUMA node6 CPU(s):   48-55,112-119
NUMA node7 CPU(s):   56-63,120-127
```

```
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:8.1.5
valkey_release_stage:ga
redis_git_sha1:00272339
redis_git_dirty:0
redis_build_id:a6bba4949d886f70
redis_mode:cluster
os:Linux 4.19.0-91.82.152.28.uelc20.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:14.2.0
process_id:3706465
process_supervised:no
run_id:3c22bf162e4a1fd605a1eee1c4d2459a671cbda8
tcp_port:16383
server_time_usec:1767084372087477
uptime_in_seconds:1032247
uptime_in_days:11
hz:10
configured_hz:10
clients_hz:10
lru_clock:5476692
...
# Memory
used_memory:18446744073702280352
used_memory_human:18446744073702280352B
used_memory_rss:735404032
used_memory_rss_human:701.34M
used_memory_peak:18446744073703498314
used_memory_peak_human:18446744073703498314B
used_memory_peak_perc:100.00%
used_memory_overhead:3467812
used_memory_startup:2815368
used_memory_dataset:18446744073698812540
used_memory_dataset_perc:100.00%
allocator_allocated:18446744073702261128
allocator_active:735335424
allocator_resident:735335424
allocator_muzzy:0
total_system_memory:540186210304
total_system_memory_human:503.09G
used_memory_lua:32768
used_memory_vm_eval:32768
used_memory_lua_human:32.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:35840
used_memory_vm_total:68608
used_memory_vm_total_human:67.00K
used_memory_functions:272
used_memory_scripts:272
used_memory_scripts_human:272B
maxmemory:21474836480
maxmemory_human:20.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.00
allocator_frag_bytes:0
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.00
rss_overhead_bytes:68608
mem_fragmentation_ratio:0.00
mem_fragmentation_bytes:742694520
mem_not_counted_for_evict:0
mem_replication_backlog:131588
mem_total_replication_buffers:131584
mem_clients_slaves:0
mem_clients_normal:29112
mem_cluster_links:203680
mem_aof_buffer:0
mem_allocator:libc
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:46830
...
# Keyspace
db0:keys=172,expires=3,avg_ttl=759749015
```
## Case #2 Overflowed `used_memory_dataset`

Same system as Case #1. There were 92 out of 96 nodes with similar problem.

```
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:8.1.5
valkey_release_stage:ga
redis_git_sha1:00272339
redis_git_dirty:0
redis_build_id:a6bba4949d886f70
redis_mode:cluster
os:Linux 4.19.0-91.82.152.28.uelc20.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:14.2.0
process_id:2589535
process_supervised:no
run_id:80a405533c300b1832c05f0105a9dde7ed24ab51
tcp_port:16383
server_time_usec:1767084372104592
uptime_in_seconds:957588
uptime_in_days:11
hz:10
configured_hz:10
clients_hz:10
lru_clock:5476692
...
used_memory:657508290
used_memory_human:627.05M
used_memory_rss:777129984
used_memory_rss_human:741.13M
used_memory_peak:657697374
used_memory_peak_human:627.23M
used_memory_peak_perc:99.97%
used_memory_overhead:668361560
used_memory_startup:3078688
used_memory_dataset:18446744073698698346
used_memory_dataset_perc:2818751332352.00%
...
# Keyspace
db0:keys=640,expires=149,avg_ttl=105596692
```

## Case #3 Overflowed `used_memory_dataset`

Test environment with Intel CPU.

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               47
Model name:          Intel(R) Xeon(R) CPU E7- 8837  @ 2.67GHz
Stepping:            2
CPU MHz:             2660.031
BogoMIPS:            5320.06
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            24576K
NUMA node0 CPU(s):   0-7
```

```
# Memory
used_memory:2148591278
used_memory_human:2.00G
used_memory_rss:4354002944
used_memory_rss_human:4.05G
used_memory_peak:2336832074
used_memory_peak_human:2.18G
used_memory_peak_perc:91.94%
used_memory_overhead:2157606256
used_memory_startup:2819064
used_memory_dataset:18446744073700536638
used_memory_dataset_perc:859678572544.00%
allocator_allocated:2148573886
allocator_active:4353923072
allocator_resident:4353923072
allocator_muzzy:0
total_system_memory:134636740608
total_system_memory_human:125.39G
used_memory_lua:44032
used_memory_vm_eval:44032
used_memory_lua_human:43.00K
used_memory_scripts_eval:296
number_of_cached_scripts:1
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:35840
used_memory_vm_total:79872
used_memory_vm_total_human:78.00K
used_memory_functions:256
used_memory_scripts:552
used_memory_scripts_human:552B
maxmemory:7516192768
maxmemory_human:7.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.00
allocator_frag_bytes:0
allocator_rss_ratio:1.00
...
```

## Case #4 Overflowed `used_memory_dataset`

QEMU virtual machine configured with 4 NUMA-nodes,

```xml
<domain type="kvm">
  <name>xxx</name>
  <uuid>93607032-a5f1-4ad2-b453-93be39198a02</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://alpinelinux.org/alpinelinux/3.21"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">16777216</memory>
  <currentMemory unit="KiB">16777216</currentMemory>
  <vcpu placement="static">8</vcpu>
  <os>
    <type arch="x86_64" machine="pc-i440fx-rhel7.0.0">hvm</type>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode="host-passthrough" check="none">
    <topology sockets="2" cores="2" threads="2"/>
    <numa>
      <cell id="0" cpus="0-1" memory="4194304" unit="KiB"/>
      <cell id="1" cpus="2-3" memory="4194304" unit="KiB"/>
      <cell id="2" cpus="4-5" memory="4194304" unit="KiB"/>
      <cell id="3" cpus="6-7" memory="4194304" unit="KiB"/>
    </numa>
  </cpu>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="xxx.qcow2"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x06" function="0x0"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <target dev="hda" bus="ide"/>
      <readonly/>
      <address type="drive" controller="0" bus="0" target="0" unit="0"/>
    </disk>
    <controller type="usb" index="0" model="ich9-ehci1">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x7"/>
    </controller>
    <controller type="usb" index="0" model="ich9-uhci1">
      <master startport="0"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x0" multifunction="on"/>
    </controller>
    <controller type="usb" index="0" model="ich9-uhci2">
      <master startport="2"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x1"/>
    </controller>
    <controller type="usb" index="0" model="ich9-uhci3">
      <master startport="4"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x2"/>
    </controller>
    <controller type="pci" index="0" model="pci-root"/>
    <controller type="ide" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x1"/>
    </controller>
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x05" function="0x0"/>
    </controller>
    <interface type="bridge">
      <mac address="52:54:00:4b:4e:aa"/>
      <source bridge="br0"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0"/>
    </interface>
    <serial type="pty">
      <target type="isa-serial" port="0">
        <model name="isa-serial"/>
      </target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"/>
    </console>
    <channel type="unix">
      <target type="virtio" name="org.qemu.guest_agent.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="1"/>
    </channel>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="2"/>
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1"/>
    </input>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <graphics type="spice" autoport="yes">
      <listen type="address"/>
    </graphics>
    <video>
      <model type="qxl" ram="65536" vram="65536" vgamem="16384" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/>
    </video>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="2"/>
    </redirdev>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="3"/>
    </redirdev>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x07" function="0x0"/>
    </memballoon>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x08" function="0x0"/>
    </rng>
  </devices>
</domain>

```

```console
$ sudo numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1
node 0 size: 3966 MB
node 0 free: 3917 MB
node 1 cpus: 2 3
node 1 size: 3994 MB
node 1 free: 3911 MB
node 2 cpus: 4 5
node 2 size: 4031 MB
node 2 free: 3949 MB
node 3 cpus: 6 7
node 3 size: 4028 MB
node 3 free: 3914 MB
node distances:
node   0   1   2   3 
  0:  10  20  20  20 
  1:  20  10  20  20 
  2:  20  20  10  20 
  3:  20  20  20  10 

$ sudo lscpu
Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             46 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      8
  On-line CPU(s) list:       0-7
Vendor ID:                   GenuineIntel
  Model name:                Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
    CPU family:              6
    Model:                   79
    Thread(s) per core:      2
    Core(s) per socket:      2
    Socket(s):               2
    Stepping:                1
    BogoMIPS:                3990.75
...
Caches (sum of all):         
  L1d:                       256 KiB (8 instances)
  L1i:                       256 KiB (8 instances)
  L2:                        16 MiB (4 instances)
NUMA:                        
  NUMA node(s):              4
  NUMA node0 CPU(s):         0,1
  NUMA node1 CPU(s):         2,3
  NUMA node2 CPU(s):         4,5
  NUMA node3 CPU(s):         6,7

$ redis-cli -h 192.168.3.211 -p 6800 INFO
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:8.1.5
valkey_release_stage:ga
redis_git_sha1:43561f89
redis_git_dirty:0
redis_build_id:3ccd4da2279d1971
server_mode:cluster
os:Linux 6.18.1-0-lts x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:14.2.0
process_id:3554
process_supervised:no
run_id:5f5dfe5e588c03a3b6be6cb7b76538f6a05bb162
tcp_port:6800
server_time_usec:1767342082451174
uptime_in_seconds:3
uptime_in_days:0
hz:10
configured_hz:10
clients_hz:10
lru_clock:5734402
executable:/cache/test/dep/valkey-server
config_file:/cache/test/conf/6800.conf
io_threads_active:0
availability_zone:
listener0:name=tcp,bind=192.168.3.211,port=6800

# Clients
connected_clients:1
cluster_connections:10
maxclients:15000
client_recent_max_input_buffer:16392
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0
paused_reason:none
paused_actions:none
paused_timeout_milliseconds:0

# Memory
used_memory:2945720
used_memory_human:2.81M
used_memory_rss:8916992
used_memory_rss_human:8.50M
used_memory_peak:2945720
used_memory_peak_human:2.81M
used_memory_peak_perc:100.09%
used_memory_overhead:3093692
used_memory_startup:2819672
used_memory_dataset:18446744073709403644
used_memory_dataset_perc:14634698407936000.00%
allocator_allocated:2925848
allocator_active:8848384
allocator_resident:8848384
allocator_muzzy:0
total_system_memory:16799281152
total_system_memory_human:15.65G
used_memory_lua:32768
used_memory_vm_eval:32768
used_memory_lua_human:32.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:35840
used_memory_vm_total:68608
used_memory_vm_total_human:67.00K
used_memory_functions:272
used_memory_scripts:272
used_memory_scripts_human:272B
maxmemory:8589934592
maxmemory_human:8.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.00
allocator_frag_bytes:0
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.01
rss_overhead_bytes:68608
mem_fragmentation_ratio:3.05
mem_fragmentation_bytes:5991144
mem_not_counted_for_evict:0
mem_replication_backlog:4
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:0
mem_cluster_links:10720
mem_aof_buffer:0
mem_allocator:libc
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1767342079
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:4
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:3
total_commands_processed:8
instantaneous_ops_per_sec:0
total_net_input_bytes:381
total_net_output_bytes:22
total_net_repl_input_bytes:0
total_net_repl_output_bytes:0
instantaneous_input_kbps:0.03
instantaneous_output_kbps:0.00
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:1
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:9
total_writes_processed:3
io_threaded_reads_processed:0
io_threaded_writes_processed:0
io_threaded_freed_objects:0
io_threaded_accept_processed:0
io_threaded_poll_processed:0
io_threaded_total_prefetch_batches:0
io_threaded_total_prefetch_entries:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:1
reply_buffer_expands:0
eventloop_cycles:82
eventloop_duration_sum:6933
eventloop_duration_cmd_sum:99
instantaneous_eventloop_cycles_per_sec:13
instantaneous_eventloop_duration_usec:76
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0

# Replication
role:master
connected_slaves:1
slave0:ip=192.168.3.211,port=6803,state=online,offset=109968508,lag=0,type=replica
replicas_waiting_psync:0
master_failover_state:no-failover
master_replid:50f9fae6f4076ddc2d8755d3e2b8f5d6a6a6980d
master_replid2:623d46e8f42bfa5950c8e30ffd746f48fcf20f14
master_repl_offset:109968508
second_repl_offset:109968509
repl_backlog_active:1
repl_backlog_size:2147483648
repl_backlog_first_byte_offset:109968509
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.007687
used_cpu_user:0.004200
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:0.008272
used_cpu_user_main_thread:0.003353

# Modules

# Errorstats

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=4,expires=0,avg_ttl=0
```

## Case #5  NO Overflowed `used_memory_dataset` (Control Group to Case #4)

QEMU virtual machine configured without NUMA. Only different configurations are shown,

```xml
  <cpu mode="host-passthrough" check="none">
    <topology sockets="2" cores="2" threads="2"/>
  </cpu>
```

```console
$ sudo lscpu
Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             46 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      8
  On-line CPU(s) list:       0-7
Vendor ID:                   GenuineIntel
  Model name:                Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
    CPU family:              6
    Model:                   79
    Thread(s) per core:      2
    Core(s) per socket:      2
    Socket(s):               2
    Stepping:                1
    BogoMIPS:                3990.75
...
Caches (sum of all):         
  L1d:                       256 KiB (8 instances)
  L1i:                       256 KiB (8 instances)
  L2:                        16 MiB (4 instances)
NUMA:                        
  NUMA node(s):              1
  NUMA node0 CPU(s):         0-7

$ sudo numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 15997 MB
node 0 free: 14932 MB
node distances:
node   0 
  0:  10 

$ redis-cli -h 192.168.3.212 -p 6800 INFO
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:8.1.5
valkey_release_stage:ga
redis_git_sha1:43561f89
redis_git_dirty:0
redis_build_id:3a7126567ba476b5
server_mode:cluster
os:Linux 6.18.1-0-lts x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:14.2.0
process_id:6846
process_supervised:no
run_id:bb2f8d87856fa302ad1a62afaf86208482d65841
tcp_port:6800
server_time_usec:1767342299829649
uptime_in_seconds:7273
uptime_in_days:0
hz:10
configured_hz:10
clients_hz:10
lru_clock:5734619
executable:/cache/test/dep/valkey-server
config_file:/cache/test/conf/6800.conf
io_threads_active:0
availability_zone:
listener0:name=tcp,bind=192.168.3.212,port=6800

# Clients
connected_clients:1
cluster_connections:10
maxclients:15000
client_recent_max_input_buffer:20480
client_recent_max_output_buffer:20504
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0
paused_reason:none
paused_actions:none
paused_timeout_milliseconds:0

# Memory
used_memory:3225272
used_memory_human:3.08M
used_memory_rss:14319616
used_memory_rss_human:13.66M
used_memory_peak:3245824
used_memory_peak_human:3.10M
used_memory_peak_perc:99.37%
used_memory_overhead:3033260
used_memory_startup:3001792
used_memory_dataset:192012
used_memory_dataset_perc:85.92%
allocator_allocated:3302456
allocator_active:3588096
allocator_resident:7270400
allocator_muzzy:0
total_system_memory:16774176768
total_system_memory_human:15.62G
used_memory_lua:32768
used_memory_vm_eval:32768
used_memory_lua_human:32.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:35840
used_memory_vm_total:68608
used_memory_vm_total_human:67.00K
used_memory_functions:240
used_memory_scripts:240
used_memory_scripts_human:240B
maxmemory:8589934592
maxmemory_human:8.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.09
allocator_frag_bytes:285640
allocator_rss_ratio:2.03
allocator_rss_bytes:3682304
rss_overhead_ratio:1.97
rss_overhead_bytes:7049216
mem_fragmentation_ratio:4.47
mem_fragmentation_bytes:11113624
mem_not_counted_for_evict:0
mem_replication_backlog:20508
mem_total_replication_buffers:20504
mem_clients_slaves:0
mem_clients_normal:0
mem_cluster_links:10720
mem_aof_buffer:0
mem_allocator:jemalloc-5.3.0
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1767335026
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:6
total_commands_processed:7256
instantaneous_ops_per_sec:0
total_net_input_bytes:268122
total_net_output_bytes:24306
total_net_repl_input_bytes:0
total_net_repl_output_bytes:10122
instantaneous_input_kbps:0.02
instantaneous_output_kbps:0.00
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:1
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:52
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:3
dump_payload_sanitizations:0
total_reads_processed:7260
total_writes_processed:739
io_threaded_reads_processed:0
io_threaded_writes_processed:0
io_threaded_freed_objects:0
io_threaded_accept_processed:0
io_threaded_poll_processed:0
io_threaded_total_prefetch_batches:0
io_threaded_total_prefetch_entries:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:1
reply_buffer_expands:0
eventloop_cycles:197383
eventloop_duration_sum:14344394
eventloop_duration_cmd_sum:15560
instantaneous_eventloop_cycles_per_sec:25
instantaneous_eventloop_duration_usec:70
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0

# Replication
role:master
connected_slaves:1
slave0:ip=192.168.3.212,port=6804,state=online,offset=10122,lag=1,type=replica
replicas_waiting_psync:0
master_failover_state:no-failover
master_replid:02010b31e660df67153856b6b598344d5a974e16
master_replid2:e4c306f4fd6fccd883b525b2e0f40f647b7960ad
master_repl_offset:10122
second_repl_offset:1
repl_backlog_active:1
repl_backlog_size:2147483648
repl_backlog_first_byte_offset:1
repl_backlog_histlen:10122

# CPU
used_cpu_sys:4.996556
used_cpu_user:11.185159
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:4.995144
used_cpu_user_main_thread:11.184697

# Modules

# Errorstats
errorstat_ERR:count=3

# Cluster
cluster_enabled:1

# Keyspace

```

### PR DESCRIPTION
**Pull request by bpint**
# Describe the bug

The metric `used_memory_dataset` turned into an insanely large number close to 2^64 (actually overflowed negative value),
as reported in <https://github.com/valkey-io/valkey/issues/2994#issuecomment-3706853079>.

Versions affected include 8.x and 9.x. (Should i submit multiple PRs?)

# Analysis

We found that miscalculated `used_memory_overhead` is the core reason.

## Double-Counted database memory

When server starts, the global variable `server.initial_memory_usage` is used to record a memory baseline in [InitServerLast()](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/server.c#L3117). This `server.initial_memory_usage` has clearly included initial database memory, since databases are created in [initServer()](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/server.c#L2892).

In function [getMemoryOverheadData()](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/object.c#L1304), the `mem_total` is [firstly assigned the baseline](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/object.c#L1325), which includes initial database memory. And then [all extra memory usage of databases are added](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/object.c#L1374) to mem_total. The initial database memory are therefore counted TWICE.

This eventually caused wrongly larger `used_memory_overhead`. For a database with only a couple of keys, the `used_memory_overhead` is easily larger than `used_memory` and causes an overflowed `used_memory_dataset`.

## Missed Empty Databases

In function [getMemoryOverheadData()](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/object.c#L1304), kvstores without any allocated hashtable are ignored from calculation,

```c
if (db == NULL || !kvstoreNumAllocatedHashtables(db->keys)) continue;
```

However, even the kvstore has no allocated hashtable, there are still some memory allocated by [kvstoreCreate()](https://github.com/valkey-io/valkey/blob/e4a3e9f0a298fbaa7320e76dbdd4b790425c148e/src/kvstore.c#L286), including `hashtable_size_index`, which can be larger than 128 KiB.

On the contrary, this caused wrongly smaller `used_memory_overhead` for an empty database. When we insert only ONE key to the database, the database is suddenly taken into account, and `used_memory_overhead` will increase (for `used_memory_dataset` decrease) by more than 128 KiB due to the single key insertion.

# Proposed Fix

In this PR,

a) We record the zmalloc_used_memory() change before and after database creation during server initialization. And later when we decide the baseline `server.initial_memory_usage`, the initial database memory usage is excluded.

b) We remove the condition  kvstoreNumAllocatedHashtables() in getMemoryOverheadData(), to make the `used_memory_overhead` reasonable for both empty and non-empty kvstores.

### CODE REVIEW

**Comment by madolson** [comment]
> Versions affected include 8.x and 9.x. (Should i submit multiple PRs?)

We'll backport it as needed after the main PR is submitted.

File: src/server.c [hunk 1]
```diff
@@ -3114,7 +3123,12 @@ void InitServerLast(void) {
     bioInit();
     initIOThreads();
     set_jemalloc_bg_thread(server.jemalloc_bg_thread);
-    server.initial_memory_usage = zmalloc_used_memory();
+
+    /* The value of initial_memory_usage was temporarily set to the memory usage of server.db in initServer().
+     * Now we record the initial memory usage EXCLUDING server.db, which is necessary for
+     * getMemoryOverheadData() to prevent initial server.db memory from being double-counted into used_memory_overhead.
+     */
+    server.initial_memory_usage = zmalloc_used_memory() - server.initial_memory_usage;
```
Comment (madolson) [inline src/server.c]:
```suggestion
    server.initial_memory_usage = 0;
    server.initial_memory_usage = zmalloc_used_memory() - getMemoryOverheadData().mem_total;
```

I think if we just make a smaller change, we can then make sure we are always avoiding double counting in the future.

Comment (bpint) [reply src/server.c]: brilliant.

i resubmitted the PR according to your advice.

File: src/server.c [hunk 2]
```diff
@@ -3114,7 +3114,11 @@ void InitServerLast(void) {
     bioInit();
     initIOThreads();
     set_jemalloc_bg_thread(server.jemalloc_bg_thread);
-    server.initial_memory_usage = zmalloc_used_memory();
+
+    server.initial_memory_usage = 0; /* first set initial_memory_usage to zero as baseline for getMemoryOverheadData() */
+    struct serverMemOverhead *mh = getMemoryOverheadData();
+    server.initial_memory_usage = zmalloc_used_memory() - mh->overhead_total; /* exclude current overhead memory to avoid double counting in the future */
+    freeMemoryOverheadData(mh);
```
Comment (enjoy-binbin) [inline src/server.c]:
```suggestion
    /* First set initial_memory_usage to zero as baseline for getMemoryOverheadData(). */
    server.initial_memory_usage = 0; 
    struct serverMemOverhead *mh = getMemoryOverheadData();
    /* Exclude current overhead memory to avoid double counting in the future. */
    server.initial_memory_usage = zmalloc_used_memory() - mh->overhead_total;
    freeMemoryOverheadData(mh);
```

File: src/object.c [hunk 3]
```diff
@@ -1373,7 +1373,8 @@ struct serverMemOverhead *getMemoryOverheadData(void) {
 
     for (j = 0; j < server.dbnum; j++) {
         serverDb *db = server.db[j];
-        if (db == NULL || !kvstoreNumAllocatedHashtables(db->keys)) continue;
+        if (db == NULL) continue;
```
Comment (enjoy-binbin) [inline src/object.c:1376]:
```suggestion
        /* Even if kvstoreNumAllocatedHashtables() is zero, kvstoreCreate() still allocated significant memory. */
        if (db == NULL) continue;
```

File: src/object.c [hunk 4]
```diff
@@ -1373,7 +1373,8 @@ struct serverMemOverhead *getMemoryOverheadData(void) {
...
+        /* Even if kvstoreNumAllocatedHashtables() is zero, kvstoreCreate() still allocated significant memory. */
```
Comment (enjoy-binbin) [inline src/object.c]:
```suggestion
```

**Review by enjoy-binbin — APPROVED** [review]
LGTM, good catch.

File: src/server.c [hunk 5]
```diff
@@ -3114,7 +3114,13 @@ void InitServerLast(void) {
     bioInit();
     initIOThreads();
     set_jemalloc_bg_thread(server.jemalloc_bg_thread);
-    server.initial_memory_usage = zmalloc_used_memory();
+
+    /* First set initial_memory_usage to zero as baseline for getMemoryOverheadData(). */
+    server.initial_memory_usage = 0;
```
Comment (madolson) [inline src/server.c]:
```suggestion
    server.initial_memory_usage = 0;
```

**Review by enjoy-binbin — APPROVED** [review]
Would you able to write a TCL test case to cover this? If not, i can take a look later.

**Comment by bpint** [comment]
> Would you able to write a TCL test case to cover this? If not, i can take a look later.

really sorry that i am familiar with neither tcl language nor the principle of test cases.

**Comment by enjoy-binbin** [comment]
@bpint Merged, thank you.

**Comment by bpint** [comment]
respect to @madolson @enjoy-binbin and all maintainers for your efficient and awesome work
