### PR TITLE
Make modules opt-in to atomic slot migration and add server events

### LINKED ISSUE #2579: Introduce mechanism to block atomic slot migration when a module does not support it
Atomic slot migration was introduced here: https://github.com/valkey-io/valkey/issues/2507 and it does not work if there the VSS index enabled since AUX data is not properly serialized.

### PR DESCRIPTION
**Pull request by murphyjacob4**
As discussed in https://github.com/valkey-io/valkey/issues/2579

Notably, I am exposing this feature as "Atomic Slot Migration" to modules. If we want to call it something else, we should consider that now (e.g.. "Replication-Based Slot Migration"?)

Also note: I am exposing both target and source node in the event. It is not guaranteed that either target or source would be the node the event fires on (e.g. replicas will fire the event after replica containment is introduced). Even though it could be potentially inferred from CLUSTER SLOTS, it should help modules parse it this way. Modules should be able to infer whether it is occurring on primary/replica from `ctx` flags, so not duplicating that here.

Closes #2579

### CODE REVIEW

File: src/module.c [hunk 1]
```diff
@@ -2586,7 +2586,15 @@ void VM_Yield(ValkeyModuleCtx *ctx, int flags, const char *busy_reply) {
  * to reduce overhead or handle trusted custom command logic.
  * ValkeyModule_Replicate and ValkeyModule_EmitAOF
  * are affected by this option, allowing them to operate without
- * command validation check. */
+ * command validation check.
+ *
+ * VALKEYMODULE_OPTIONS_HANDLE_ATOMIC_SLOT_MIGRATION:
+ * When set, this option indicates that the module is capable of handling
+ * atomic slot migration. If not set, the module is assumed to not be aware of
```
Comment (zuiderkwast) [inline src/module.c:2593]: HANDLE sounds as if the module needs to do something actively, which not all modules need to do. Maybe ALLOW is a better word?

VALKEYMODULE_OPTIONS_ALLOW_ATOMIC_SLOT_MIGRATION

File: src/cluster_migrateslots.c [hunk 2]
```diff
@@ -823,6 +844,12 @@ bool clusterSlotFailoverGranted(int slot) {
  * source will attempt to migrate the slot ranges to the specified target
  * node. */
 void clusterCommandMigrateSlots(client *c) {
+    if (!moduleAllModulesHandleAtomicSlotMigration()) {
+        addReplyError(c, "At least one module does not support atomic slot "
+                         "migrations. Please ensure all modules have declared "
+                         "support for atomic slot migration and try again.");
```
Comment (zuiderkwast) [inline src/cluster_migrateslots.c]: (Not important) Should we say which one, or is that sensitive information?

**Review by zuiderkwast — COMMENTED** [review]
LGTM in general.

File: src/cluster_migrateslots.c (hunk 2 above)
Comment (madolson) [reply src/cluster_migrateslots.c]: The module name isn't sensitive, so yeah, perhaps the `moduleAllModulesHandleAtomicSlotMigration` should addd the reply and indicate which one doesn't support it.

File: src/module.c (hunk 1 above)
Comment (murphyjacob4) [reply src/module.c:2593]: Yeah I was copying terminology from VALKEYMODULE_OPTIONS_HANDLE_REPL_ASYNC_LOAD. But I think they were copying from VALKEYMODULE_OPTIONS_HANDLE_IO_ERRORS (where handle makes more sense)

I like ALLOW

File: src/cluster_migrateslots.c (hunk 2 above)
Comment (murphyjacob4) [reply src/cluster_migrateslots.c]: Makes sense. Updated and tested manually by making `testhook` not declare it:

```
ERR The module testhook does not support atomic slot migrations. Please ensure all modules have declared support for atomic slot migration and try again
```

File: src/module.c [hunk 3]
```diff
@@ -12707,6 +12749,8 @@ sds genModulesInfoStringRenderModuleOptions(struct ValkeyModule *module) {
         output = sdscat(output, "handle-repl-async-load|");
     if (module->options & VALKEYMODULE_OPTION_NO_IMPLICIT_SIGNAL_MODIFIED)
         output = sdscat(output, "no-implicit-signal-modified|");
+    if (module->options & VALKEYMODULE_OPTIONS_ALLOW_ATOMIC_SLOT_MIGRATION)
+        output = sdscat(output, "handle-atomic-slot-migration|");
```
Comment (zuiderkwast) [inline src/module.c:12778]:
```suggestion
        output = sdscat(output, "allow-atomic-slot-migration|");
```

File: src/valkeymodule.h [hunk 4]
```diff
@@ -653,6 +660,14 @@ static const ValkeyModuleEvent ValkeyModuleEvent_ReplicationRoleChanged = {VALKE
 #define _VALKEYMODULE_SUBEVENT_CRON_LOOP_NEXT 0
 #define _VALKEYMODULE_SUBEVENT_SWAPDB_NEXT 0
 
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_STARTED 0
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_STARTED 1
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_ABORTED 2
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_ABORTED 3
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_COMPLETED 4
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_COMPLETED 5
+#define _VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_NEXT 6
```
Comment (madolson) [inline src/valkeymodule.h:669]:
```suggestion
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_STARTED 0
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_STARTED 1
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_ABORTED 2
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_ABORTED 3
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_COMPLETED 4
#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_COMPLETED 5
#define _VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_NEXT 6
```
Import start, abort, and complete all make sense to me since we're queuing data that needs to be processed. What do we think the use cases are for export start and aborted are though? Using our two existing modules:
1. Search will continue to behave normally throughout the entire process, and then needs to take action on export completed.
2. JSON and Bloom don't seem to need anything, as they get cleaned up when we call delete at the end.

Actually, the more I wonder if we even need to incorporate the export at all. I see we have a `VALKEYMODULE_SUBEVENT_FLUSHDB_START`, maybe we should just have a FLUSHSLOT start and end?

I'm just trying to think through how the modules will use these events.

File: src/cluster_migrateslots.c [hunk 5]
```diff
@@ -823,6 +844,9 @@ bool clusterSlotFailoverGranted(int slot) {
  * source will attempt to migrate the slot ranges to the specified target
  * node. */
 void clusterCommandMigrateSlots(client *c) {
+    if (moduleVerifyAllModulesAllowAtomicSlotMigrationOrReply(c) == C_ERR) {
```
Comment (madolson) [inline src/cluster_migrateslots.c]: We should also do this check on the target if for some reason the cluster is non-homogenous in the modules that are running.

**Review by madolson — COMMENTED** [review]
Mostly makes sense. I'm worried we'll need more hooks thinking it through more for search, is there a plan anywhere outlining what is needed?

File: src/valkeymodule.h (hunk 4 above)
Comment (murphyjacob4) [reply src/valkeymodule.h:669]: It's hard to predict what modules will and won't need. For example, during migration, I once needed my module to hook into the RDB save start server event to add some data to the keyspace for backwards compat (at one point, valkey-search used keys to store indexes, and we were moving them to aux).

I would lend on the side of too many events than not enough events. Although modules in the valkey-bundle have the privilege of being connected to the core and getting new module APIs added, many non-bundle modules won't have this advantage.

All that said - I can come up with a few reasons modules might want to know about the migration. For example, a module might want to know ASM has started in order to throttle users. Or the module itself might be performing some mutations that it should stop to allow the ASM to complete.

**Comment by murphyjacob4** [comment]
> I'm worried we'll need more hooks thinking it through more for search, is there a plan anywhere outlining what is needed?

We will need more. I have a follow-up PR I am working on. But essentially, I think modules need to be able to register a "Consistency Check".

When we do manual failover or atomic slot migration, we should check that all modules are consistent. So we will go through all registered consistency checks, and wait until they are done. The module should return true/false indicating whether it has fully processed all changes.

It mostly applies just to secondary indexing, but I can imagine a few other ways it might be useful - e.g. if there is a module that is doing some async persistence to an external source (disk, cloud storage) or if there is a module that is doing some kind of manual async replication.

In a way, it is kind of like the "WAIT" command, but for modules. We will need to update the ASM state machine to:

1. Wait for target to have module consistency before the source pauses
2. Wait for target to have module consistency before slot takeover

**Comment by madolson** [comment]
> All that said - I can come up with a few reasons modules might want to know about the migration. For example, a module might want to know ASM has started in order to throttle users. Or the module itself might be performing some mutations that it should stop to allow the ASM to complete.

You probably wouldn't proactively throttle users. You would probably wait until some scenario that would trigger you to start throttling. I guess my point is we can always add more hooks later, but adding hooks now requires us to maintain them. I would just like us to be very deliberate about the hooks we are adding. Like I think we also need a fork hook?

> When we do manual failover or atomic slot migration, we should check that all modules are consistent. So we will go through all registered consistency checks, and wait until they are done. The module should return true/false indicating whether it has fully processed all changes.

Not exactly related, but we maybe should also do a consistency check such as checking key counts or checking a crc. (Unfortunately we don't have native crc since we use AOF instead of RDB) It would be unfortunate if we miss some edge case and don't replicate data. We wouldn't know.

**Comment by murphyjacob4** [comment]
> You probably wouldn't proactively throttle users. You would probably wait until some scenario that would trigger you to start throttling. I guess my point is we can always add more hooks later, but adding hooks now requires us to maintain them. I would just like us to be very deliberate about the hooks we are adding. Like I think we also need a fork hook?

Start and stop events on both source/target feels like a fairly minimal number of server events right now. To me, it feels odd to not make the events symmetric on both ends. It also feels in line with the other events we have (VALKEYMODULE_SUBEVENT_PERSISTENCE_AOF_START, VALKEYMODULE_SUBEVENT_PERSISTENCE_RDB_START).

I know we internally will take advantage of these EXPORT_START/ABORT/COMPLETED events to cancel/postpone other background operations we do via modules when we start doing a migration.

> Not exactly related, but we maybe should also do a consistency check such as checking key counts or checking a crc. (Unfortunately we don't have native crc since we use AOF instead of RDB) It would be unfortunate if we miss some edge case and don't replicate data. We wouldn't know.

Makes sense. It shouldn't be too difficult to add slot key count to the SYNCSLOTS FAILOVER-GRANTED and fail the migration if it doesn't match. Ideally it would also cover content, but we can iterate

File: src/module.c [hunk 6]
```diff
@@ -7146,6 +7154,24 @@ int moduleAllModulesHandleReplAsyncLoad(void) {
...
+            addReplyErrorFormat(c, "The module %s does not support atomic slot migrations. "
+                                   "Please ensure all modules have declared support for "
+                                   "atomic slot migration and try again",
+                                module->name);
+            return C_ERR;
+        }
+    }
+    dictReleaseIterator(di);
+    return C_OK;
+}
```
Comment (hpatro) [inline src/module.c]: * Shall we just verify here if all the modules support ASM or not and add the error reply on the caller end ? With the current output format we don't guarantee we are able to inform the client about all the modules which  don't support ASM.
* And I think you're just following the code structure but do we need to prepend the method name with `module` ?

File: src/module.c [hunk 7]
```diff
@@ -7146,6 +7154,24 @@ int moduleAllModulesHandleReplAsyncLoad(void) {
...
+    dictEntry *de;
+
+    while ((de = dictNext(di)) != NULL) {
+        struct ValkeyModule *module = dictGetVal(de);
+        if (!(module->options & VALKEYMODULE_OPTIONS_ALLOW_ATOMIC_SLOT_MIGRATION)) {
+            addReplyErrorFormat(c, "The module %s does not support atomic slot migrations. "
+                                   "Please ensure all modules have declared support for "
+                                   "atomic slot migration and try again",
+                                module->name);
+            return C_ERR;
```
Comment (hpatro) [inline src/module.c:7169]: * With the early return, we are leaking `di`.

File: src/module.h [hunk 8]
```diff
@@ -211,6 +211,7 @@ int TerminateModuleForkChild(int child_pid, int wait);
 ssize_t rdbSaveModulesAux(rio *rdb, int when);
 int moduleAllDatatypesHandleErrors(void);
 int moduleAllModulesHandleReplAsyncLoad(void);
+int moduleVerifyAllModulesAllowAtomicSlotMigrationOrReply(client *c);
```
Comment (hpatro) [inline src/module.h]: I would prefer it to be
```suggestion
int verifyAllModulesAllowAtomicSlotMigration(void);
```

Comment (zuiderkwast) [reply src/module.h]: May I ask why? Are prefixes like these not useful?

File: src/valkeymodule.h [hunk 9]
```diff
@@ -653,6 +660,14 @@ static const ValkeyModuleEvent ValkeyModuleEvent_ReplicationRoleChanged = {VALKE
 #define _VALKEYMODULE_SUBEVENT_CRON_LOOP_NEXT 0
 #define _VALKEYMODULE_SUBEVENT_SWAPDB_NEXT 0
 
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_STARTED 0
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_STARTED 1
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_ABORTED 2
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_ABORTED 3
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_IMPORT_COMPLETED 4
+#define VALKEYMODULE_SUBEVENT_ATOMIC_SLOT_MIGRATION_EXPORT_COMPLETED 5
```
Comment (hpatro) [inline src/valkeymodule.h:668]: I guess topology change would be important for modules to keep track of. Could we add documentation for module dev to understand the start and end of the job based on these events ?

I guess these are the terminating conditions.
```
0 -> 2
0 -> 4
1 -> 3
1 -> 5
```

This information along with failover / new node addition could complete the following request https://github.com/valkey-io/valkey/issues/2558

File: src/module.h (hunk 8 above)
Comment (hpatro) [reply src/module.h]: Yeah, I don't see any value.

Comment (madolson) [reply src/module.h]: I like the prefixes, then I can fairly quickly find the corresponding file something is in. We normally omit the prefix for internal functions.

We do something more extreme inside aws, where everything in the same type of unit is like "amzUnit_functionName".

**Comment by madolson** [comment]
> Start and stop events on both source/target feels like a fairly minimal number of server events right now. To me, it feels odd to not make the events symmetric on both ends. It also feels in line with the other events we have (VALKEYMODULE_SUBEVENT_PERSISTENCE_AOF_START, VALKEYMODULE_SUBEVENT_PERSISTENCE_RDB_START).

I just like to support the minimal amount we think is useful. I'm okay leave it as is for now.

File: src/module.c (hunk 3 above)
Comment (madolson) [reply src/module.c:12778]: I liked handle since it's consistent with handle-repl-async-load, but I have no strong preference.

File: src/module.h (hunk 8 above)
Comment (hpatro) [reply src/module.h]: I still think unit name in the method name seems redundant to me. If people actually benefit from this, I don't want to push this further.

AWS `amz` thing is to indicate internal code i.e. definitely helpful.

File: src/module.c (hunk 6 above)
Comment (murphyjacob4) [reply src/module.c]: > Shall we just verify here if all the modules support ASM or not and add the error reply on the caller end

Haha, this is what I did originally, with just a "at least one module doesn't support it" message. But I think communicating a specific module makes sense. I don't know if it really matters that the reply encompasses all modules or just gives one. We can append them together into one response if you like?

> And I think you're just following the code structure but do we need to prepend the method name with module ?

Yeah it is a pattern throughout the code - we sometimes use a prefix as a namespace. E.g. "clusterX", "moduleY". I'm not sure if we should continue it, but it would be odd for this to be the only function not following it IMO

File: src/module.h (hunk 8 above)
Comment (zuiderkwast) [reply src/module.h]: I find it useful. I remember I forgot where `getNodeByQuery` is, so I had to use `git grep` to find it (or use a smart IDE, but I don't :laughing:).

We don't have to repeat the word "module" again in the same name though. How about this?

```suggestion
int moduleVerifyAllAllowAtomicSlotMigrationOrReply(client *c);
```

File: src/module.c (hunk 3 above)
Comment (zuiderkwast) [reply src/module.c:12778]: We can use "handle" but shall we also use HANDLE in  `VALKEYMODULE_OPTIONS_HANDLE_ATOMIC_SLOT_MIGRATION` then?

File: src/cluster_migrateslots.c [hunk 10]
```diff
@@ -402,6 +421,10 @@ void clusterCommandSyncSlotsEstablish(client *c) {
     clusterNode *owning_node = NULL;
     list *slot_ranges = NULL;
 
+    if (moduleVerifyAllModulesAllowAtomicSlotMigrationOrReply(c) == C_ERR) {
```
Comment (ranshid) [inline src/cluster_migrateslots.c]: Question: How will the error propagate back to the user which initially started the slot migration? 
I mean, although it is not expected to have different modules loaded on source and target, it is possible right? (maybe in some migration cases)

File: src/cluster_migrateslots.c [hunk 11]
```diff
@@ -823,6 +848,9 @@ bool clusterSlotFailoverGranted(int slot) {
  * source will attempt to migrate the slot ranges to the specified target
  * node. */
 void clusterCommandMigrateSlots(client *c) {
+    if (moduleVerifyAllModulesAllowAtomicSlotMigrationOrReply(c) == C_ERR) {
```
Comment (ranshid) [inline src/cluster_migrateslots.c]: We are validating this case when we start the ASM. Although hard to imagine, but modules can be theoretically dynamically loaded after the ASM started right? should we abort ASM in that case?

**Review by ranshid — COMMENTED** [review]
2 small comments/questions.

Side note: You introduced 2 separate functionalities in this PR (new events + opt-in) IMO it is better to try and split them into 2 PRs or at least to have them in separate commits.

File: src/cluster_migrateslots.c (hunk 10 above)
Comment (murphyjacob4) [reply src/cluster_migrateslots.c]: SYNCSLOTS ESTABLISH will return +OK or -ERR. If -ERR is returned, it will parsed on the source side, and displayed in the status_msg when the slot migration fails

File: src/module.h (hunk 8 above)
Comment (hpatro) [reply src/module.h]: My bad, I'm a IDE person, @murphyjacob4 feel free to resolve this conversation or take in Viktor's suggestion.

File: src/cluster_migrateslots.c (hunk 11 above)
Comment (murphyjacob4) [reply src/cluster_migrateslots.c]: Fair point. IMO we should probably prevent loading modules during complicated server processes like: RDB save, RDB load, full sync, slot migration.

Otherwise - we need to "backfill" the server events to the module so it can figure out where we are. E.g. if we fire the ASM start event, then the module is loaded and it doesn't get the ASM start event, how would it know to handle the keyspace notifications?

Right now, we don't handle this for VALKEYMODULE_OPTIONS_HANDLE_REPL_ASYNC_LOAD, which would cause problems if a module is loaded during the diskless load as well.

What does everyone else think?

File: src/module.c (hunk 3 above)
Comment (murphyjacob4) [reply src/module.c:12778]: I think we need to just pick option A or option B. I am just going to go with "HANDLE" throughout for now, does that work for everyone?

File: src/cluster_migrateslots.c (hunk 11 above)
Comment (hpatro) [reply src/cluster_migrateslots.c]: > IMO we should probably prevent loading modules during complicated server processes like: RDB save, RDB load, full sync, slot migration.

I don't mind us making the module load more restrictive than cancelling ongoing operation for a module load which doesn't support a particular feature.

File: src/module.c (hunk 6 above)
Comment (hpatro) [reply src/module.c]: >  I don't know if it really matters that the reply encompasses all modules or just gives one.

Or none. Generic message should be fine I believe.

File: src/module.c (hunk 7 above)
Comment (murphyjacob4) [reply src/module.c:7169]: Good catch. If I had a test for this, it would have caught it in ASAN testing. Adding one now

File: src/cluster_migrateslots.c (hunk 2 above)
Comment (murphyjacob4) [reply src/cluster_migrateslots.c]: @hpatro - let's converge the conversation on the error reply here

File: src/module.c (hunk 6 above)
Comment (murphyjacob4) [reply src/module.c]: Let's converge the discussion to the other comment chain (unresolved it now)

File: src/module.h (hunk 8 above)
Comment (murphyjacob4) [reply src/module.h]: Taking in Viktor's suggestion

File: src/valkeymodule.h (hunk 9 above)
Comment (murphyjacob4) [reply src/valkeymodule.h:668]: Added some additional info on this in the docs - lmk if it looks good!

File: src/cluster_migrateslots.c (hunk 11 above)
Comment (murphyjacob4) [reply src/cluster_migrateslots.c]: Given it is a pre-existing issue - let's file a follow up? https://github.com/valkey-io/valkey/issues/2603

**Review by madolson — APPROVED** [review]
I'm aligned with the current version.

**Review by zuiderkwast — APPROVED** [review]
LGTM. I didn't review the tests.

I wish that we make it extra clear in the release notes that old modules will prevent ASM if they're not updated. We should also mention it in the CLUSTER MIGRATESLOTS command documentation and add crosslinks to the module API docs.

> Side note: You introduced 2 separate functionalities in this PR (new events + opt-in) IMO it is better to try and split them into 2 PRs or at least to have them in separate commits.

Splitting them seems to be more work. I don't mind it's a single commit.
