### PR TITLE
fix cluster slot stats assertion during promotion of replica

### LINKED ISSUE #1912: [CRASH] Promotion of replica (using `cluster failover`) triggers `server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)llabs(len)` assert
### Crash report

```
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=info message="Accepted 127.0.0.1:36960"
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=notice message="Manual failover user request accepted (user request from 'id=929 addr=127.0.0.1:36960 laddr=127.0.0.1:21004 fd=158 name= user=default lib-name= lib-ver=')."
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=info message="Client closed connection id=929 addr=127.0.0.1:36960 laddr=127.0.0.1:21004 fd=158 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=37376 events=r cmd=cluster|failover user=default redir=-1 resp=3 lib-name= lib-ver= tot-net-in=138 tot-net-out=154 tot-cmds=3"
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=notice message="Received replication offset for paused primary manual failover: 2828065509906"
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=notice message="All primary replication stream processed, manual failover can start."
pid=1 role=replica timestamp="2025-04-03T17:24:55.256+00:00" level=notice message="Start of election delayed for 0 milliseconds (rank #0, primary rank #0, offset 2828065509906)."
pid=1 role=replica timestamp="2025-04-03T17:24:55.257+00:00" level=notice message="Starting a failover election for epoch 74, node config epoch is 37"
pid=1 role=replica timestamp="2025-04-03T17:24:55.266+00:00" level=notice message="Currently unable to failover: Waiting for votes, but majority still not reached."
pid=1 role=replica timestamp="2025-04-03T17:24:55.266+00:00" level=notice message="Needed quorum: 17. Number of votes received so far: 1"
pid=1 role=replica timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Failover election won: I'm the new primary."
pid=1 role=replica timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="configEpoch set to 74 after successful failover"
pid=1 role=replica timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Setting myself to primary in shard ba5b17c895507886e8ab83dfa7362f776fd97b99 after failover; my old primary is e9a7ae007bbf944b6403e946dc91a7dd93be5640 (cache_3)"
pid=1 role=primary timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Connection with primary lost."
pid=1 role=primary timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Caching the disconnected primary state."
pid=1 role=primary timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Discarding previously cached primary state."
pid=1 role=primary timestamp="2025-04-03T17:24:55.270+00:00" level=notice message="Setting secondary replication ID to 13c72c45fd4ec5bc023f8ac663275020bc5c2fbd, valid up to offset: 2828065509907. New replication ID is 89a69e1a4ac820854e4b9946e959f3b60f998858"
pid=1 role=primary timestamp="2025-04-03T17:24:55.312+00:00" level=info message="Accepted 192.168.235.21:51160"
pid=1 role=primary timestamp="2025-04-03T17:24:55.322+00:00" level=info message="Accepted 172.31.78.181:48184"
pid=1 role=primary timestamp="2025-04-03T17:24:55.322+00:00" level=info message="Accepted 172.31.71.61:49876"
pid=1 role=primary timestamp="2025-04-03T17:24:55.328+00:00" level=info message="Accepted 172.31.79.75:46868"


=== VALKEY BUG REPORT START: Cut & paste starting from here ===
pid=1 role=primary timestamp="2025-04-03T17:24:55.328+00:00" level=warning message="=== ASSERTION FAILED ==="
pid=1 role=primary timestamp="2025-04-03T17:24:55.328+00:00" level=warning message="==> cluster_slot_stats.c:153 'server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)llabs(len)' is not true"

------ INFO OUTPUT ------
# Server
redis_version:7.2.4
server_name:valkey
valkey_version:8.1.0
valkey_release_stage:ga
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:c29f691f4c41c800
server_mode:cluster
os:Linux 6.12.21-0-virt aarch64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
gcc_version:14.2.0
process_id:1
process_supervised:no
run_id:50c80eba0a1d0825b41156212b8b00093ae6cd32
tcp_port:21004
server_time_usec:1743701095328763
uptime_in_seconds:325
uptime_in_days:0
hz:10
configured_hz:10
clients_hz:10
lru_clock:15647847
executable:/data/valkey-server
config_file:
io_threads_active:0
availability_zone:
listener0:name=tcp,bind=0.0.0.0,port=21004

# Clients
connected_clients:25
cluster_connections:126
maxclients:65536
client_recent_max_input_buffer:524288
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0
paused_reason:none
paused_actions:none
paused_timeout_milliseconds:0

# Memory
used_memory:1142426280
used_memory_human:1.06G
used_memory_rss:1214963712
used_memory_rss_human:1.13G
used_memory_peak:2146424656
used_memory_peak_human:2.00G
used_memory_peak_perc:53.22%
used_memory_overhead:103509020
used_memory_startup:6939616
used_memory_dataset:1038917260
used_memory_dataset_perc:91.50%
allocator_allocated:1144306320
allocator_active:1217331200
allocator_resident:1253048320
allocator_muzzy:0
total_system_memory:398379765760
total_system_memory_human:371.02G
used_memory_lua:32768
used_memory_vm_eval:32768
used_memory_lua_human:32.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:33792
used_memory_vm_total:66560
used_memory_vm_total_human:65.00K
used_memory_functions:224
used_memory_scripts:224
used_memory_scripts_human:224B
maxmemory:198616269840
maxmemory_human:184.98G
maxmemory_policy:noeviction
allocator_frag_ratio:1.06
allocator_frag_bytes:73024880
allocator_rss_ratio:1.03
allocator_rss_bytes:35717120
rss_overhead_ratio:0.97
rss_overhead_bytes:-38084608
mem_fragmentation_ratio:1.06
mem_fragmentation_bytes:72633128
mem_not_counted_for_evict:3584
mem_replication_backlog:67282316
mem_total_replication_buffers:67281760
mem_clients_slaves:0
mem_clients_normal:347136
mem_cluster_links:135072
mem_aof_buffer:3584
mem_allocator:jemalloc-5.3.0
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:614326

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:283207
rdb_bgsave_in_progress:0
rdb_last_save_time:1743700770
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:615973
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:9
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:1
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:994869248
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:1187055993
aof_base_size:881255620
aof_pending_rewrite:0
aof_buffer_length:98
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:885
total_commands_processed:248553
instantaneous_ops_per_sec:680
total_net_input_bytes:1186487441
total_net_output_bytes:8157901
total_net_repl_input_bytes:1186277323
total_net_repl_output_bytes:0
instantaneous_input_kbps:1319.32
instantaneous_output_kbps:24.13
instantaneous_input_repl_kbps:1318.74
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:1
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:35902
total_forks:1
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:22
dump_payload_sanitizations:0
total_reads_processed:168388
total_writes_processed:3697
io_threaded_reads_processed:9
io_threaded_writes_processed:3
io_threaded_freed_objects:2
io_threaded_accept_processed:0
io_threaded_poll_processed:6
io_threaded_total_prefetch_batches:0
io_threaded_total_prefetch_entries:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:110
reply_buffer_expands:221
eventloop_cycles:173992
eventloop_duration_sum:23598907
eventloop_duration_cmd_sum:556552
instantaneous_eventloop_cycles_per_sec:540
instantaneous_eventloop_duration_usec:67
acl_access_denied_auth:0
acl_access_denied_cmd:21
acl_access_denied_key:0
acl_access_denied_channel:0

# Replication
role:master
connected_slaves:0
replicas_waiting_psync:0
master_failover_state:no-failover
master_replid:89a69e1a4ac820854e4b9946e959f3b60f998858
master_replid2:13c72c45fd4ec5bc023f8ac663275020bc5c2fbd
master_repl_offset:2828065509944
second_repl_offset:2828065509907
repl_backlog_active:1
repl_backlog_size:67108864
repl_backlog_first_byte_offset:2827998372470
repl_backlog_histlen:67137475

# CPU
used_cpu_sys:3.841634
used_cpu_user:6.692531
used_cpu_sys_children:1.073917
used_cpu_user_children:3.711168
used_cpu_sys_main_thread:3.503043
used_cpu_user_main_thread:6.367681

# Modules

# Commandstats
cmdstat_hello:calls=2,usec=6,usec_per_call=3.00,rejected_calls=0,failed_calls=0
cmdstat_config|set:calls=307,usec=1762,usec_per_call=5.74,rejected_calls=0,failed_calls=0
cmdstat_cluster|slots:calls=856,usec=6214,usec_per_call=7.26,rejected_calls=0,failed_calls=0
cmdstat_cluster|failover:calls=1,usec=15,usec_per_call=15.00,rejected_calls=0,failed_calls=0
cmdstat_select:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_info:calls=622,usec=71793,usec_per_call=115.42,rejected_calls=21,failed_calls=0
cmdstat_multi:calls=11707,usec=3908,usec_per_call=0.33,rejected_calls=0,failed_calls=0
cmdstat_exec:calls=11707,usec=83851,usec_per_call=7.16,rejected_calls=0,failed_calls=0
cmdstat_pexpireat:calls=101025,usec=104671,usec_per_call=1.04,rejected_calls=0,failed_calls=0
cmdstat_randomkey:calls=1,usec=5,usec_per_call=5.00,rejected_calls=0,failed_calls=0
cmdstat_unlink:calls=51888,usec=176750,usec_per_call=3.41,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=303,usec=89,usec_per_call=0.29,rejected_calls=1,failed_calls=0
cmdstat_auth:calls=885,usec=3109,usec_per_call=3.51,rejected_calls=0,failed_calls=0
cmdstat_srem:calls=391,usec=2554,usec_per_call=6.53,rejected_calls=0,failed_calls=0
cmdstat_client|setname:calls=856,usec=392,usec_per_call=0.46,rejected_calls=0,failed_calls=0
cmdstat_readwrite:calls=3,usec=2,usec_per_call=0.67,rejected_calls=0,failed_calls=0
cmdstat_set:calls=48740,usec=138696,usec_per_call=2.85,rejected_calls=0,failed_calls=0
cmdstat_sadd:calls=9706,usec=26507,usec_per_call=2.73,rejected_calls=0,failed_calls=0
cmdstat_readonly:calls=892,usec=324,usec_per_call=0.36,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_NOAUTH:count=1
errorstat_NOPERM:count=21

# Latencystats
latency_percentiles_usec_hello:p50=3.007,p99=3.007,p99.9=3.007
latency_percentiles_usec_config|set:p50=6.015,p99=17.023,p99.9=20.095
latency_percentiles_usec_cluster|slots:p50=5.023,p99=47.103,p99.9=64.255
latency_percentiles_usec_cluster|failover:p50=15.039,p99=15.039,p99.9=15.039
latency_percentiles_usec_select:p50=1.003,p99=1.003,p99.9=1.003
latency_percentiles_usec_info:p50=89.087,p99=667.647,p99.9=983.039
latency_percentiles_usec_multi:p50=0.001,p99=1.003,p99.9=1.003
latency_percentiles_usec_exec:p50=6.015,p99=20.095,p99.9=119.295
latency_percentiles_usec_pexpireat:p50=1.003,p99=4.015,p99.9=10.047
latency_percentiles_usec_randomkey:p50=5.023,p99=5.023,p99.9=5.023
latency_percentiles_usec_unlink:p50=3.007,p99=12.031,p99.9=103.423
latency_percentiles_usec_ping:p50=0.001,p99=1.003,p99.9=1.003
latency_percentiles_usec_auth:p50=3.007,p99=7.007,p99.9=65.023
latency_percentiles_usec_srem:p50=5.023,p99=32.127,p99.9=40.191
latency_percentiles_usec_client|setname:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_readwrite:p50=1.003,p99=1.003,p99.9=1.003
latency_percentiles_usec_set:p50=3.007,p99=9.023,p99.9=24.063
latency_percentiles_usec_sadd:p50=2.007,p99=8.031,p99.9=83.455
latency_percentiles_usec_readonly:p50=0.001,p99=1.003,p99.9=1.003

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=616606,expires=616606,avg_ttl=18948252

# Cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:64
cluster_size:32
cluster_current_epoch:74
cluster_my_epoch:74
cluster_stats_messages_ping_sent:435
cluster_stats_messages_pong_sent:594
cluster_stats_messages_meet_sent:9
cluster_stats_messages_fail_sent:63
cluster_stats_messages_auth-req_sent:63
cluster_stats_messages_mfstart_sent:1
cluster_stats_messages_sent:1165
cluster_stats_messages_ping_received:506
cluster_stats_messages_pong_received:444
cluster_stats_messages_meet_received:25
cluster_stats_messages_fail_received:1
cluster_stats_messages_auth-req_received:3
cluster_stats_messages_auth-ack_received:32
cluster_stats_messages_received:1011
total_cluster_links_buffer_limit_exceeded:0

------ CLUSTER NODES OUTPUT ------
41d3dd4e5705d84409495a21e6b954af6dc00327 192.168.235.20:21021@31021,,tls-port=0,nodename=cache_20,shard-id=0b1eb02ddb8ae87b7b7b9429df4017bacc5f189b slave 76f0289bb60d9979d48b287682187eb75adf83ad 0 1743701093283 60 connected
8d905d5c494e022571436d6a9becae325cbac9c1 192.168.235.21:21012@31012,,tls-port=0,nodename=cache_11,shard-id=8271d9596ad15df94d16cdd8ec01c0a6a1c36186 master - 0 1743701085000 38 connected 5632-6143
5f82001c88a5448296150b9f4283fb4a8615559e 192.168.235.21:21022@31022,,tls-port=0,nodename=cache_21,shard-id=1b555cc5e293414c8a35f5b516258699e2a28738 master - 0 1743701082000 61 connected 10752-11263
480827065837055022d0f2aeb76e4a9ab5453501 192.168.235.21:21008@31008,,tls-port=0,nodename=cache_7,shard-id=b9fe54694b89839ca315f0b44d7561566ea25847 master - 0 1743701078000 36 connected 3584-4095
cf7ee8eb14a8225e62d9d220dc5e4220732b015b 192.168.235.20:21028@31028,,tls-port=0,nodename=cache_27,shard-id=c6c881529ed05a9b53622e58efd41761a744c8ab slave 893c287085d5f8f6d8f7d1593764dfdc85931772 0 1743701085000 66 connected
a8d6525a453a00b83800ecfd006f701280c305c3 192.168.235.21:21013@31013,,tls-port=0,nodename=cache_12,shard-id=b304b795f150293fefb55ccc24c5ea7477a9bd33 master - 0 1743701076000 52 connected 6144-6655
dbd3b9696a0fc4fe696f1673a63a07b1fa3207e8 192.168.235.20:21032@31032,,tls-port=0,nodename=cache_31,shard-id=a6ae4a279198ecf8cd2a585830209c666f2fae93 slave af20f8c1379397bcd5bc62eb74e3c530e212a9ce 0 1743701084000 70 connected
779a5d1aea701069e894af57182bfacab430a7df 192.168.235.20:21016@31016,,tls-port=0,nodename=cache_15,shard-id=ee4b18ecf56463adf141fe6cdca728bc76daa994 slave cbd71412647db640dc46fa04495284b2a03e2596 0 1743701086000 55 connected
4337d7da1c2da46d38fe5ddafd0a36d32438d2cd 192.168.235.21:21023@31023,,tls-port=0,nodename=cache_22,shard-id=7bb2bd5ec9cbb0e85bc2b64dec6bad57af533aa1 master - 0 1743701086000 62 connected 11264-11775
02e6005883d7f2c4337a84f5dda6b00a023982e8 192.168.235.20:21023@31023,,tls-port=0,nodename=cache_22,shard-id=7bb2bd5ec9cbb0e85bc2b64dec6bad57af533aa1 slave 4337d7da1c2da46d38fe5ddafd0a36d32438d2cd 0 1743701090261 62 connected
9be37aa7b6b1fa8360ebcab3c3b12992e99e5582 192.168.235.21:21014@31014,,tls-port=0,nodename=cache_13,shard-id=ccf6cfb9521958bebcfd63a3975c6a22f3408e1f master - 0 1743701085221 53 connected 6656-7167
1f6c10be9821e930c4e308e13978a89d99a04811 192.168.235.21:21030@31030,,tls-port=0,nodename=cache_29,shard-id=d704dbb084df4ab201e0275976e7fbbfdb3851ad master - 0 1743701073000 68 connected 14848-15359
848655d96956078b5bcfd8b6ea3f3fde3235aa2e 192.168.235.20:21003@31003,,tls-port=0,nodename=cache_2,shard-id=bc71d458726aaa52bef9a70f26d4322b75681eb7 master - 0 1743701088000 73 connected 1024-1535
6b935fb5505fd65e6b4eefc7c19e1dda30c93969 192.168.235.21:21001@31001,,tls-port=0,nodename=cache_0,shard-id=ab2ff78b902f537e2f9944a36a1b3765043753dc slave 2e782293cbca46ebb11f3f306ddd36b8ef5493b7 0 1743701082000 71 connected
13c3002d417e9d236a90aaad2bdbb1a086f9305f 192.168.235.20:21006@31006,,tls-port=0,nodename=cache_5,shard-id=a42a8f2b38ebd6ad495c281328aa031e1fd0b399 slave e24409f9c63bc028b90faeb4c7b7c116255dbef4 0 1743701086000 44 connected
7dbbe58f6715e20a16c6e733e2627abc10bd7bcf 192.168.235.20:21015@31015,,tls-port=0,nodename=cache_14,shard-id=7ed5eb97e19cb3ba0305ae5542ad2403ca21dbe4 slave 513de82db0cbf028879181bc2a6ae23c98d1d867 0 1743701079000 54 connected
82cf94e4414aba5369042cf8af1082e6587447b5 192.168.235.21:21025@31025,,tls-port=0,nodename=cache_24,shard-id=5f344ad64a1f799ce56d235cb64fb2fde0e3752e master - 0 1743701089000 64 connected 12288-12799
d614e703ab11c83d0beeaed4391758964ad48928 192.168.235.21:21024@31024,,tls-port=0,nodename=cache_23,shard-id=8564a30d9e8a5836594944e67ef263c8bc934e12 master - 0 1743701087000 63 connected 11776-12287
04e5b6afd4d6a3f9e8803294c8fab617f4593e97 192.168.235.20:21011@31011,,tls-port=0,nodename=cache_10,shard-id=2743e0752ef6ce25d9de009c2d35be390e59ab22 slave b728e87687b2d49c44bf9320e1b54e282b2dc3ce 0 1743701091268 39 connected
23bada1e44eba651cae9387e6c318150d93c9ed4 192.168.235.21:21009@31009,,tls-port=0,nodename=cache_8,shard-id=a111090e677448a5e97964799036b0885fb72885 master - 0 1743701080000 46 connected 4096-4607
7b610c836f34221fc322030838498787a2f08483 192.168.235.20:21022@31022,,tls-port=0,nodename=cache_21,shard-id=1b555cc5e293414c8a35f5b516258699e2a28738 slave 5f82001c88a5448296150b9f4283fb4a8615559e 0 1743701093000 61 connected
3052f8446a1a664a9d8223620723cbf0376e571b 192.168.235.20:21002@31002,,tls-port=0,nodename=cache_1,shard-id=abd63970dbb36792ac1a73f3e7b2aaacad2af72f master - 0 1743701085000 72 connected 512-1023
c0a8b9d408893fd0c65939c4939e380be1eb58b2 192.168.235.20:21024@31024,,tls-port=0,nodename=cache_23,shard-id=8564a30d9e8a5836594944e67ef263c8bc934e12 slave d614e703ab11c83d0beeaed4391758964ad48928 0 1743701087000 63 connected
6accea8cec1af5b97d446b36475cbaacb0eed035 192.168.235.20:21018@31018,,tls-port=0,nodename=cache_17,shard-id=9e6be2f6cf77f566317930e7b9a7efe2271251d3 slave a5ed458b3f1873cb3e62eab11c8d62174cd29f0a 0 1743701084000 57 connected
a9b05b971fbab19069a8c00b83dacecd35d664d2 192.168.235.20:21027@31027,,tls-port=0,nodename=cache_26,shard-id=c646154c787938ca0f7c972aca9fcdfe99d01e82 slave 7e1621b284cf5f072d8928f81193955a84aaf11c 0 1743701087237 42 connected
16b89d335b72d7adb60977df07b9582c78ea3a65 192.168.235.21:21031@31031,,tls-port=0,nodename=cache_30,shard-id=46a918bc572980231ad3db28af446a7327085ae0 master - 0 1743701076000 69 connected 15360-15871
de40d491ef6b9571dd375da6c6ebf0c703572ee9 192.168.235.20:21007@31007,,tls-port=0,nodename=cache_6,shard-id=1ea7ca9baa12abace6503811cf546577b8924b15 slave 5c4e5b60324fbd44d72cb245176068e3eca65bf7 0 1743701089253 47 connected
da75f924e25189315ed418291eebebcf39d4da0c 192.168.235.20:21005@31005,,tls-port=0,nodename=cache_4,shard-id=8d95eb6619e928af324f1143ac1b8c4ab140dd9e slave 306c6bb8a119fae69bbf6c8c3fb01e0a794fd9cd 0 1743701091000 34 connected
1fb407bb835c1bc5d918031fcea377b386dc7085 192.168.235.20:21009@31009,,tls-port=0,nodename=cache_8,shard-id=a111090e677448a5e97964799036b0885fb72885 slave 23bada1e44eba651cae9387e6c318150d93c9ed4 0 1743701089000 46 connected
5c4e5b60324fbd44d72cb245176068e3eca65bf7 192.168.235.21:21007@31007,,tls-port=0,nodename=cache_6,shard-id=1ea7ca9baa12abace6503811cf546577b8924b15 master - 0 1743701084000 47 connected 3072-3583
1275ebd046fae82426f805ce6a149a25c9eb18f7 192.168.235.20:21029@31029,,tls-port=0,nodename=cache_28,shard-id=e96fa778b7996c6bed5b285028428bd563b8f7b0 slave c24e91396dce53ed1439e49202c5b39ad71e8ff3 0 1743701092000 67 connected
76f0289bb60d9979d48b287682187eb75adf83ad 192.168.235.21:21021@31021,,tls-port=0,nodename=cache_20,shard-id=0b1eb02ddb8ae87b7b7b9429df4017bacc5f189b master - 0 1743701085000 60 connected 10240-10751
306c6bb8a119fae69bbf6c8c3fb01e0a794fd9cd 192.168.235.21:21005@31005,,tls-port=0,nodename=cache_4,shard-id=8d95eb6619e928af324f1143ac1b8c4ab140dd9e master - 0 1743701086228 34 connected 2048-2559
74b51cc274fd243b64d1b8f189d0d638d69e778d 192.168.235.21:21026@31026,,tls-port=0,nodename=cache_25,shard-id=f5af59ebc574421d8fd7afdd049a807e8bc87e48 master - 0 1743701095324 65 connected 12800-13311
e9a7ae007bbf944b6403e946dc91a7dd93be5640 192.168.235.21:21004@31004,,tls-port=0,nodename=cache_3,shard-id=ba5b17c895507886e8ab83dfa7362f776fd97b99 master - 0 1743701089000 37 connected
95ef38645b4550225e1cd49e2f7c5b2771891b74 192.168.235.21:21017@31017,,tls-port=0,nodename=cache_16,shard-id=82330fb0e9e5cf41619b086ebb9aa098bfce1068 master - 0 1743701072000 56 connected 8192-8703
e24409f9c63bc028b90faeb4c7b7c116255dbef4 192.168.235.21:21006@31006,,tls-port=0,nodename=cache_5,shard-id=a42a8f2b38ebd6ad495c281328aa031e1fd0b399 master - 0 1743701085000 44 connected 2560-3071
7aa72c302f93ebb7608ba7c3e221dc9f4709f46b 192.168.235.20:21012@31012,,tls-port=0,nodename=cache_11,shard-id=8271d9596ad15df94d16cdd8ec01c0a6a1c36186 slave 8d905d5c494e022571436d6a9becae325cbac9c1 0 1743701092276 38 connected
67bd22affae036bcfa1aa5fb3786d12c809ec8ee 192.168.235.20:21019@31019,,tls-port=0,nodename=cache_18,shard-id=2b95a598bdebfce9ca04ae4bf8280877cb136cfd slave f026543fe841ee57219d501dfd18fd2fc728727f 0 1743701083000 58 connected
7e1621b284cf5f072d8928f81193955a84aaf11c 192.168.235.21:21027@31027,,tls-port=0,nodename=cache_26,shard-id=c646154c787938ca0f7c972aca9fcdfe99d01e82 master - 0 1743701086000 42 connected 13312-13823
2e782293cbca46ebb11f3f306ddd36b8ef5493b7 192.168.235.20:21001@31001,,tls-port=0,nodename=cache_0,shard-id=ab2ff78b902f537e2f9944a36a1b3765043753dc master - 0 1743701085000 71 connected 0-511
b728e87687b2d49c44bf9320e1b54e282b2dc3ce 192.168.235.21:21011@31011,,tls-port=0,nodename=cache_10,shard-id=2743e0752ef6ce25d9de009c2d35be390e59ab22 master - 0 1743701088244 39 connected 5120-5631
de8b996a70e0d4f65fe6c5930997502925813bbc 192.168.235.20:21031@31031,,tls-port=0,nodename=cache_30,shard-id=46a918bc572980231ad3db28af446a7327085ae0 slave 16b89d335b72d7adb60977df07b9582c78ea3a65 0 1743701085000 69 connected
c24e91396dce53ed1439e49202c5b39ad71e8ff3 192.168.235.21:21029@31029,,tls-port=0,nodename=cache_28,shard-id=e96fa778b7996c6bed5b285028428bd563b8f7b0 master - 0 1743701087000 67 connected 14336-14847
cbd71412647db640dc46fa04495284b2a03e2596 192.168.235.21:21016@31016,,tls-port=0,nodename=cache_15,shard-id=ee4b18ecf56463adf141fe6cdca728bc76daa994 master - 0 1743701081000 55 connected 7680-8191
e473a8e54a49def4cfd5fc0635c5262cdf4c45af 192.168.235.21:21003@31003,,tls-port=0,nodename=cache_2,shard-id=bc71d458726aaa52bef9a70f26d4322b75681eb7 slave 848655d96956078b5bcfd8b6ea3f3fde3235aa2e 0 1743701080000 73 connected
0d21ae0bf4aaab0715a60b00eb5e380e12ca98e7 192.168.235.20:21014@31014,,tls-port=0,nodename=cache_13,shard-id=ccf6cfb9521958bebcfd63a3975c6a22f3408e1f slave 9be37aa7b6b1fa8360ebcab3c3b12992e99e5582 0 1743701083000 53 connected
19a7ba1ce8d977a165f1f62829631067a7445a19 192.168.235.20:21025@31025,,tls-port=0,nodename=cache_24,shard-id=5f344ad64a1f799ce56d235cb64fb2fde0e3752e slave 82cf94e4414aba5369042cf8af1082e6587447b5 0 1743701087000 64 connected
cfb8b2788dc57034323d4077f2f5ccc32fe5d628 192.168.235.21:21002@31002,,tls-port=0,nodename=cache_1,shard-id=abd63970dbb36792ac1a73f3e7b2aaacad2af72f slave 3052f8446a1a664a9d8223620723cbf0376e571b 0 1743701081000 72 connected
92d995b1d58172e3612c9105fc45744d35fdeed9 192.168.235.21:21010@31010,,tls-port=0,nodename=cache_9,shard-id=365850fae08f0708ff1f5a0e22e4e10b47802fa0 master - 0 1743701080000 51 connected 4608-5119
d5d99ac4ccee0ccbf46992b5a2632bf6fba35856 192.168.235.20:21008@31008,,tls-port=0,nodename=cache_7,shard-id=b9fe54694b89839ca315f0b44d7561566ea25847 slave 480827065837055022d0f2aeb76e4a9ab5453501 0 1743701090000 36 connected
f0b3b3494096e9b9205d04809a0509002ac9b6cc 192.168.235.20:21026@31026,,tls-port=0,nodename=cache_25,shard-id=f5af59ebc574421d8fd7afdd049a807e8bc87e48 slave 74b51cc274fd243b64d1b8f189d0d638d69e778d 0 1743701083000 65 connected
1529498669e33555f2954b080f2d56056445cf59 192.168.235.20:21010@31010,,tls-port=0,nodename=cache_9,shard-id=365850fae08f0708ff1f5a0e22e4e10b47802fa0 slave 92d995b1d58172e3612c9105fc45744d35fdeed9 0 1743701084213 51 connected
6097936d3ac41c92d8f05e94699b102704d45d58 192.168.235.20:21020@31020,,tls-port=0,nodename=cache_19,shard-id=8f900d1ec91ba9480ff6e5602de3f3236eacf821 slave 918dd872d9466cab3d8a74a9f0817572c759e752 0 1743701087000 59 connected
918dd872d9466cab3d8a74a9f0817572c759e752 192.168.235.21:21020@31020,,tls-port=0,nodename=cache_19,shard-id=8f900d1ec91ba9480ff6e5602de3f3236eacf821 master - 0 1743701089000 59 connected 9728-10239
e15e45a1329ab5b749bb1ae03a66c90a8193ce85 192.168.235.20:21004@31004,,tls-port=0,nodename=cache_3,shard-id=ba5b17c895507886e8ab83dfa7362f776fd97b99 myself,master - 0 0 74 connected 1536-2047
513de82db0cbf028879181bc2a6ae23c98d1d867 192.168.235.21:21015@31015,,tls-port=0,nodename=cache_14,shard-id=7ed5eb97e19cb3ba0305ae5542ad2403ca21dbe4 master - 0 1743701089000 54 connected 7168-7679
56d0f13e36677a3e32390c1c9cf232226dac099a 192.168.235.20:21030@31030,,tls-port=0,nodename=cache_29,shard-id=d704dbb084df4ab201e0275976e7fbbfdb3851ad slave 1f6c10be9821e930c4e308e13978a89d99a04811 0 1743701091000 68 connected
af20f8c1379397bcd5bc62eb74e3c530e212a9ce 192.168.235.21:21032@31032,,tls-port=0,nodename=cache_31,shard-id=a6ae4a279198ecf8cd2a585830209c666f2fae93 master - 0 1743701094000 70 connected 15872-16383
f026543fe841ee57219d501dfd18fd2fc728727f 192.168.235.21:21019@31019,,tls-port=0,nodename=cache_18,shard-id=2b95a598bdebfce9ca04ae4bf8280877cb136cfd master - 0 1743701089000 58 connected 9216-9727
d5a220a7f3caf4cf187133498d77ca806b790e43 192.168.235.20:21017@31017,,tls-port=0,nodename=cache_16,shard-id=82330fb0e9e5cf41619b086ebb9aa098bfce1068 slave 95ef38645b4550225e1cd49e2f7c5b2771891b74 0 1743701089000 56 connected
b73290308f8a64113cdf4b7937545e1c958646a3 192.168.235.20:21013@31013,,tls-port=0,nodename=cache_12,shard-id=b304b795f150293fefb55ccc24c5ea7477a9bd33 slave a8d6525a453a00b83800ecfd006f701280c305c3 0 1743701085000 52 connected
893c287085d5f8f6d8f7d1593764dfdc85931772 192.168.235.21:21028@31028,,tls-port=0,nodename=cache_27,shard-id=c6c881529ed05a9b53622e58efd41761a744c8ab master - 0 1743701094289 66 connected 13824-14335
a5ed458b3f1873cb3e62eab11c8d62174cd29f0a 192.168.235.21:21018@31018,,tls-port=0,nodename=cache_17,shard-id=9e6be2f6cf77f566317930e7b9a7efe2271251d3 master - 0 1743701090000 57 connected 8704-9215

------ CLIENT LIST OUTPUT ------
id=406 addr=172.31.68.128:45518 laddr=192.168.235.20:21004 fd=151 name= age=173 idle=173 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=396 addr=172.31.75.110:57758 laddr=192.168.235.20:21004 fd=148 name= age=177 idle=177 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=6 addr=127.0.0.1:35522 laddr=127.0.0.1:21004 fd=12 name= age=314 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=9224 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=info user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=7330 tot-net-out=2788646 tot-cmds=316
id=912 addr=127.0.0.1:43660 laddr=127.0.0.1:21004 fd=10 name= age=4 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=config|set user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=380 tot-net-out=30 tot-cmds=6
id=913 addr=127.0.0.1:43662 laddr=127.0.0.1:21004 fd=11 name= age=4 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=2048 rbp=1542 obl=0 oll=0 omem=0 tot-mem=2560 events=r cmd=info user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=215 tot-net-out=7713 tot-cmds=6
id=491 addr=172.31.68.225:59200 laddr=192.168.235.20:21004 fd=154 name= age=144 idle=144 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=328 addr=172.31.66.56:37022 laddr=192.168.235.20:21004 fd=144 name= age=203 idle=203 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=347 addr=172.31.77.72:59796 laddr=192.168.235.20:21004 fd=146 name= age=197 idle=197 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=407 addr=172.31.68.128:49640 laddr=192.168.235.20:21004 fd=152 name= age=173 idle=173 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=229 addr=172.31.66.56:52086 laddr=192.168.235.20:21004 fd=140 name= age=237 idle=237 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=99 addr=172.31.72.107:50294 laddr=192.168.235.20:21004 fd=134 name= age=267 idle=267 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=113 addr=172.31.70.209:47890 laddr=192.168.235.20:21004 fd=136 name= age=265 idle=265 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=398 addr=172.31.72.63:46230 laddr=192.168.235.20:21004 fd=149 name= age=177 idle=177 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=111 addr=172.31.70.209:59844 laddr=192.168.235.20:21004 fd=135 name= age=265 idle=265 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=329 addr=172.31.66.56:57006 laddr=192.168.235.20:21004 fd=145 name= age=203 idle=203 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=760 addr=172.31.66.56:59034 laddr=192.168.235.20:21004 fd=157 name= age=47 idle=47 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=508 addr=172.31.75.78:57508 laddr=192.168.235.20:21004 fd=155 name= age=137 idle=137 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=509 addr=172.31.75.78:40132 laddr=192.168.235.20:21004 fd=156 name= age=137 idle=137 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=490 addr=172.31.68.225:41988 laddr=192.168.235.20:21004 fd=153 name= age=144 idle=144 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=395 addr=172.31.75.110:49136 laddr=192.168.235.20:21004 fd=147 name= age=177 idle=177 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=400 addr=172.31.72.63:54646 laddr=192.168.235.20:21004 fd=150 name= age=177 idle=177 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=readonly user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=144 tot-net-out=78 tot-cmds=3
id=930 addr=192.168.235.21:51160 laddr=192.168.235.20:21004 fd=109 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=auth user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=99 tot-net-out=39 tot-cmds=1
id=931 addr=172.31.78.181:48184 laddr=192.168.235.20:21004 fd=158 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=readwrite user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=127 tot-net-out=73 tot-cmds=2
id=932 addr=172.31.71.61:49876 laddr=192.168.235.20:21004 fd=159 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=readwrite user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=127 tot-net-out=73 tot-cmds=2
id=933 addr=172.31.79.75:46868 laddr=192.168.235.20:21004 fd=160 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=69 multi-mem=0 rbs=16384 rbp=16384 obl=5 oll=0 omem=0 tot-mem=17005 events=r cmd=set user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=232 tot-net-out=73 tot-cmds=3

------ CURRENT CLIENT INFO ------
id=933 addr=172.31.79.75:46868 laddr=192.168.235.20:21004 fd=160 name= age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=69 multi-mem=0 rbs=16384 rbp=16384 obl=5 oll=0 omem=0 tot-mem=17005 events=r cmd=set user=api redir=-1 resp=2 lib-name= lib-ver= tot-net-in=232 tot-net-out=73 tot-cmds=3
argc: 5
argv[0]: "SET"
argv[1]: "<redacted>"
argv[2]: "[]"
argv[3]: "PXAT"
argv[4]: "1743701695328"
pid=1 role=primary timestamp="2025-04-03T17:24:55.329+00:00" level=warning message="valkey 8.1.0 crashed by signal: 11, si_code: 1"
pid=1 role=primary timestamp="2025-04-03T17:24:55.329+00:00" level=warning message="Accessing address: 0x195fcb85b60"

------ INFO OUTPUT ------
[same as above]

------ CLUSTER NODES OUTPUT ------
[same as above]

------ CLIENT LIST OUTPUT ------
[same as above]

------ CURRENT CLIENT INFO ------
[same as above]
1:signal-handler (1743701095) Crashed running signal handler. Providing reduced version of recursive crash report.
pid=1 role=primary timestamp="2025-04-03T17:24:55.329+00:00" level=warning message="valkey 8.1.0 crashed by signal: 11, si_code: 1"
pid=1 role=primary timestamp="2025-04-03T17:24:55.329+00:00" level=warning message="Accessing address: 0x195fcb85b60"

=== VALKEY BUG REPORT END. Make sure to include from START to END. ===
```

### Additional information

During a maintenance-related manual cluster failover, several of our Valkey nodes crashed with the same assertion message of

```
=== ASSERTION FAILED ===
==> cluster_slot_stats.c:153 'server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)llabs(len)' is not true
```

This appears to be related to having `--cluster-slot-stats-enabled yes` enabled.

We're running Valkey inside Docker using the following configuration:

```
image: docker.io/valkey/valkey:8.1-alpine
valkey-server
--aclfile /users.acl
--activedefrag yes
--aof-timestamp-enabled yes
--appendfsync everysec
--appendonly yes
--bind ::
--bind 0.0.0.0
--client-output-buffer-limit normal 1gb 16mb 15
--client-output-buffer-limit pubsub 64mb 8mb 15
--client-output-buffer-limit replica 2gb 128mb 15
--client-query-buffer-limit 512mb
--cluster-allow-pubsubshard-when-down yes
--cluster-allow-reads-when-down yes
--cluster-allow-replica-migration no
--cluster-announce-human-nodename ${PROJECT}_${SHARD}
--cluster-enabled yes
--cluster-node-timeout 60000
--cluster-replica-validity-factor 0
--cluster-require-full-coverage no
--cluster-slot-stats-enabled yes
--databases 1
--dual-channel-replication-enabled yes
--enable-debug-command local
--enable-module-command local
--enable-protected-configs local
--hide-user-data-from-log no
--io-threads 2
--log-format logfmt
--loglevel verbose
--log-timestamp-format iso8601
--maxclients 65536
--maxmemory ${MAXMEMORY:-0}
--maxmemory-clients 1%
--maxmemory-policy ${MAXMEMORY_POLICY:-noeviction}
--no-appendfsync-on-rewrite yes
--oom-score-adj relative
--port ${PORT}
--primaryauth "${MANAGEMENT_PASSWORD}"
--proto-max-bulk-len 512mb
--repl-backlog-size 64mb
--repl-diskless-load swapdb
--repl-ping-replica-period 1
--repl-timeout 300
--save ''
--set-proc-title no
--shutdown-on-sigint nosave
--shutdown-on-sigterm nosave
--shutdown-timeout 300
--supervised no
--tcp-backlog 1024
--tcp-keepalive 30
```

### PR DESCRIPTION
**Pull request by Fusl**
This affects only the configuration `cluster-slot-stats-enabled yes`.

For the first command a newly promoted primary receives, we send a `SELECT` command to all replicas via `replicationFeedReplicas`. This calls a chain of functions (`feedReplicationBufferWithObject` -> `feedReplicationBuffer` -> `clusterSlotStatsIncrNetworkBytesOutForReplication` -> `clusterSlotStatsUpdateNetworkBytesOutForReplication`) that increments the per-slot `network_bytes_out` by `len * listLength(server.replicas)`. However, if the new primary receives a command before any replicas connected yet, `server.replicas` is still empty, causing the increment to add zero.

Right after, we call `clusterSlotStatsDecrNetworkBytesOutForReplication` to remove the `SELECT` overhead from the per-slot stats. The assert in `clusterSlotStatsUpdateNetworkBytesOutForReplication` was using (basically) `>= -len` instead of `>= -(len * listLength(server.replicas))`, so it could fail if the previous increment was zero because we never included the `server.replicas` length in the assertion.

This patch makes the addition and subtraction use the same computed value (`rlen = len * listLength(server.replicas)`) in both the stats update and the assert, ensuring the logic remains consistent when replicas are promoted.

Fixes #1912

### CODE REVIEW

**Review by sarthakaggarwal97 — APPROVED** [review]

**Comment by sarthakaggarwal97** [comment]
Thanks @Fusl for raising the PR!

File: src/cluster_slot_stats.c [hunk 1]
```diff
@@ -148,10 +148,11 @@ static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
     client *c = server.current_client;
     if (c == NULL || !canAddNetworkBytesOut(c)) return;
 
+    uint64_t rlen = len*listLength(server.replicas);
```
Comment (hpatro) [inline src/cluster_slot_stats.c]: Would prefer explicit conversion than implicit conversion.

```suggestion
    uint64_t rlen = (uint64_t)llabs(len) * listLength(server.replicas);
```

File: src/cluster_slot_stats.c [hunk 2]
```diff
@@ -148,10 +148,11 @@ static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
...
     serverAssert(c->slot >= 0 && c->slot < CLUSTER_SLOTS);
     serverAssert(nodeIsPrimary(server.cluster->myself));
-    if (len < 0) serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)llabs(len));
-    server.cluster->slot_stats[c->slot].network_bytes_out += (len * listLength(server.replicas));
+    if (len < 0) serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out >= -rlen);
```
Comment (hpatro) [inline src/cluster_slot_stats.c]:
```suggestion
    serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out - rlen >= 0);
```

**Review by hpatro — COMMENTED** [review]
Good catch! 

Haven't thought through how to reproduce this but adding test case would be great.

File: src/cluster_slot_stats.c (hunk 1 above)
Comment (Fusl) [reply src/cluster_slot_stats.c]: We can't do the llabs here since that would turn negative numbers into positive numbers and we need to handle negative and positive numbers separately. Positive numbers increase the counter while negative numbers decrease the counter (for the special handling of the `SELECT` command) where wo do the explicit assert check.

File: src/cluster_slot_stats.c (hunk 2 above)
Comment (Fusl) [reply src/cluster_slot_stats.c]: Same as other change suggestion: We only need to treat negative numbers in this assert case, not positive numbers.

**Comment by Fusl** [comment]
@hpatro I added `cluster-slot-stats-enabled yes` to the `cluster_options` list during test runs which successfully catches this bug.

File: src/cluster_slot_stats.c [hunk 3]
```diff
@@ -148,10 +148,11 @@ static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
...
+    server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
```
Comment (hpatro) [inline src/cluster_slot_stats.c]:
```suggestion
    int incr = 1;
    if (len < 0) {
    	incr = 0;
    }
    uint64_t rlen = (uint64_t)llabs(len) * listLength(server.replicas);
    if (incr) {
    	server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
    } else {
    	serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out - rlen >= 0);
    	server.cluster->slot_stats[c->slot].network_bytes_out -= rlen;
    }
```

**Review by hpatro — COMMENTED** [review]
@Fusl I see your point. I think we also need to maintain if it's an increment / decrement operation with the changes I suggested above.

I'm getting mildly anxious with all the type conversion we're performing with the change in PR 😀. Could you take a look at my new suggestion?

File: src/cluster_slot_stats.c (hunk 3 above)
Comment (Fusl) [reply src/cluster_slot_stats.c]: That does look unnecessarily verbose and you have to consider that this is also in the hot-path of the primary node so any additional branching here should be avoided whenever possible. My patch had already taken into account reducing branching as much as possible without getting rid of the asserts.

Additionally, your assert would never trigger since if `server.cluster->slot_stats[c->slot].network_bytes_out` is `0` and `rlen` would be a positive number, `network_bytes_out` would underflow from `0` to `18446744073709551616-rlen` which would always pass the `>= 0` condition in the assert case.

I also believe that the implicit conversion in `uint64_t rlen = len*listLength(server.replicas);` isn't going to be an issue here and it never was never an issue before my changes either (when we used `+= (len * listLength(server.replicas))` to update the stats) except for the assertion where we didn't do that.

Comment (hpatro) [reply src/cluster_slot_stats.c]: I'm a bit confused. With the code you have submitted, where do we decrement the value?

rlen will always be a positive number
```
uint64_t rlen = len*listLength(server.replicas);
```

and then this will always lead to increment of network_bytes_out

```
server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
```

Or am I missing something?

Comment (Fusl) [reply src/cluster_slot_stats.c]: You're right, that's my bad. I erroneously used `uint64_t` when it should have been `int64_t`.

Comment (Fusl) [reply src/cluster_slot_stats.c]: Will this slightly modified version of yours work for you?

```c
/* Accumulates egress bytes upon sending replication stream. This only applies for primary nodes. */
static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
    client *c = server.current_client;
    if (c == NULL || !canAddNetworkBytesOut(c)) return;

    int neg = 0;
    if (len < 0) {
        neg = 1;
        len = -len;
    }
    uint64_t rlen = (uint64_t)len*listLength(server.replicas);
    serverAssert(c->slot >= 0 && c->slot < CLUSTER_SLOTS);
    serverAssert(nodeIsPrimary(server.cluster->myself));
    if (neg) {
        serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out >= rlen);
        server.cluster->slot_stats[c->slot].network_bytes_out -= rlen;
    } else {
        server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
    }
}
```

This adds only one extra branch that I believe the compiler is able to optimize out into a branchless call.

Comment (hpatro) [reply src/cluster_slot_stats.c]: Yeah, it looks good to me.

Comment (zuiderkwast) [reply src/cluster_slot_stats.c]: I think it looks cleaner without branching actually. Maybe the variable name `rlen` could be more descriptive or add a code comment for it.

For the unusual case `len < 0` we could add some comment to make it clearer, or to check that `rlen` is negative instead of checking `len`, or by checking that we have >= 0 bytes left after adding the negative `rlen`:

```c
    if (rlen < 0) {
        /* Negative number: undo some already counted bytes. */
        serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out + rlen >= 0);
    }
    server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
```

Comment (Fusl) [reply src/cluster_slot_stats.c]: Yeah I don't like the branching either. I'll try to come up with some cleaner code here in a moment.

Comment (zuiderkwast) [reply src/cluster_slot_stats.c:155]: > I think it looks cleaner without branching actually. Maybe the variable name `rlen` could be more descriptive or add a code comment for it.
> 
> For the unusual case `len < 0` we could add some comment to make it clearer, or to check that `rlen` is negative instead of checking `len`, or by checking that we have >= 0 bytes left after adding the negative `rlen`:
> 
> ```c
>     if (rlen < 0) {
>         /* Negative number: undo some already counted bytes. */
>         serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out + rlen >= 0);
>     }
>     server.cluster->slot_stats[c->slot].network_bytes_out += rlen;
> ```

File: src/cluster_slot_stats.c (hunk 1 above)
Comment (zuiderkwast) [inline src/cluster_slot_stats.c]:
```suggestion
    int64_t rlen = len * listLength(server.replicas);
```

This was confusing to me too. :) I think just fixing this makes the code easy to follow.

File: src/cluster_slot_stats.c (hunk 2 above)
Comment (zuiderkwast) [reply src/cluster_slot_stats.c]: This makes the assert clear IMO:

```suggestion
    if (rlen < 0) {
        /* Decrement bytes added earlier. We should not reach below zero. */
        serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out + rlen >= 0);
    }
```

File: tests/support/cluster_util.tcl [hunk 4]
```diff
@@ -253,7 +253,7 @@ proc start_cluster {masters replicas options code {slot_allocator continuous_slo
 
     # Configure the starting of multiple servers. Set cluster node timeout
     # aggressively since many tests depend on ping/pong messages. 
-    set cluster_options [list overrides [list cluster-enabled yes cluster-ping-interval 100 cluster-node-timeout 3000]]
+    set cluster_options [list overrides [list cluster-enabled yes cluster-ping-interval 100 cluster-node-timeout 3000 cluster-slot-stats-enabled yes]]
```
Comment (zuiderkwast) [inline tests/support/cluster_util.tcl:256]: Why change this globally for all cluster tests? To make sure have good coverage on that assert?

**Review by zuiderkwast — COMMENTED** [review]
LGTM, just minor suggestions.

File: tests/support/cluster_util.tcl (hunk 4 above)
Comment (Fusl) [reply tests/support/cluster_util.tcl:256]: To have good coverage on that assert was my main goal with this change, yes.

**Comment by Fusl** [comment]
@zuiderkwast @hpatro Please let me know if that change looks better?

File: src/cluster_slot_stats.c [hunk 5]
```diff
@@ -148,10 +148,12 @@ static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
     client *c = server.current_client;
     if (c == NULL || !canAddNetworkBytesOut(c)) return;
 
+    // we multiply the bytes len by the number of replicas to account for us broadcasting to multiple replicas at once
```
Comment (zuiderkwast) [inline src/cluster_slot_stats.c]: Good comment!

File: src/cluster_slot_stats.c [hunk 6]
```diff
@@ -148,10 +148,12 @@ static void clusterSlotStatsUpdateNetworkBytesOutForReplication(long long len) {
...
+    len *= (long long)listLength(server.replicas);
     serverAssert(c->slot >= 0 && c->slot < CLUSTER_SLOTS);
     serverAssert(nodeIsPrimary(server.cluster->myself));
-    if (len < 0) serverAssert(server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)llabs(len));
-    server.cluster->slot_stats[c->slot].network_bytes_out += (len * listLength(server.replicas));
+    serverAssert(len >= 0 || server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)-len);
```
Comment (zuiderkwast) [inline src/cluster_slot_stats.c:157]: Can you add a comment here? Or maybe even better: a comment before the function, to explain what it means to call the function with a negative len. Normally you can't send a negative number of bytes over a network, so I think a comment would be useful to explain what it means.

```C
    /* If len is negative, check bla bla bla ... */
    serverAssert(len >= 0 || server.cluster->slot_stats[c->slot].network_bytes_out >= (uint64_t)-len);
```

**Review by zuiderkwast — COMMENTED** [review]
Yes, great, I'd just like a comment about negative length, to make it easier to understand what negative length means and why we have the assert.

**Comment by zuiderkwast** [comment]
> Yes, great, I'd just like to add one more code comment about negative length, to make it easier to understand what negative length means and why we have the assert.

File: src/cluster_slot_stats.c (hunk 6 above)
Comment (Fusl) [reply src/cluster_slot_stats.c:157]: There we go, added a more verbose comment for that as well now.

**Review by hpatro — APPROVED** [review]

**Review by zuiderkwast — APPROVED** [review]
It's perfect.
