### PR TITLE
Converge divergent shard-id persisted in nodes.conf to primary's shard id

### LINKED ISSUE #2171: [BUG] "Unrecoverable error: corrupted cluster config file" due to incorrect shard-id
**Describe the bug**

Valkey cluster member unable to start when the replica shard-id does not match the shard-id from it's master. This is from a production system after some nodes were restarted.

After investigation this is fixed in Redis by PR [#13428](https://github.com/redis/redis/pull/13428/files/aa976d3a023e4d7da8ceb255f31d8f5edbd6fb8a) 

**To reproduce**

Shutdown a cluster member and assign a different shard-id in the nodes.conf for this member.

**Expected behavior**

Shard-id from nodes.conf is ignored and taken from the primary for this cluster member.

**Additional information**

example nodes.conf
```
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143722 13 connected
ff2bb70f5966dce0bdbe107159c40820c58d9fab 10.125.153.178:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 master - 0 1748776143716 1 connected 0-5460
998b0f988d1b695a57b9384e491090040af8609f 10.125.153.186:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 disconnected
e5571288f2bc9c5aca7ffe0571b954149e560dd8 10.124.45.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 998b0f988d1b695a57b9384e491090040af8609f 0 1748776143733 0 connected
a6bafb11bb6203667eb6065243a3bdda2263a9f3 10.124.43.64:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 slave ff2bb70f5966dce0bdbe107159c40820c58d9fab 0 1748776143729 1 connected
22ec534c44c4e981585c96743cdd260c6648a799 10.124.45.183:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 slave ff2bb70f5966dce0bdbe107159c40820c58d9fab 0 1748776143726 1 connected
0ae4a85046b3c65ad12ad178459e90307b033250 10.125.153.184:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd myself,slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 connected
adcd0c05680d79f652e6e622085f84a29fbd7321 10.125.153.185:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 disconnected
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd master - 0 1748776143695 13 disconnected 5461-16383
fa902861e26b83e41b7f825b9fd23f76101e8cea 10.124.43.15:0@28007,,tls-port=18007,shard-id=7e6ea01d543a80915c3a60aad26fcb182c8c6c1d slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143726 13 connected
vars currentEpoch 13 lastVoteEpoch 9
```

### PR DESCRIPTION
**Pull request by hpatro**
Fixes #2171

Handle divergent shard-id across primary and replica from nodes.conf and reconcile all the nodes in the shard to the primary node's shard-id.

### CODE REVIEW

**Review by hwware — APPROVED** [review]

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -720,10 +722,12 @@ int clusterLoadConfig(char *filename) {
                 clusterAddNodeToShard(primary->shard_id, n);
             } else if (clusterGetNodesInMyShard(primary) != NULL &&
                        memcmp(primary->shard_id, n->shard_id, CLUSTER_NAMELEN) != 0) {
-                /* If the primary has been added to a shard, make sure this
-                 * node has the same persisted shard id as the primary. */
-                sdsfreesplitres(argv, argc);
-                goto fmterr;
+                /* If the primary has been added to a shard and this replica has
+                 * a different shard id stored in nodes.conf, update it to match
+                 * the primary instead of aborting the startup. */
```
Comment (PingXie) [inline src/cluster_legacy.c:731]: let's add a NOTICE log line here so that this doesn't completely slip through the crack

**Comment by hpatro** [comment]
@martinrvisser I tried few scenarios manually, they seem to run fine. Could you try running this patch and see if it helps ?

**Comment by hpatro** [comment]
Test scenarios:

```
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd myself,master - 0 1749488968682 13 connected 5461-16383
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=a91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1749488968682 13 connected
vars currentEpoch 13 lastVoteEpoch 9
```

```
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=a91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1749488968682 13 connected
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd myself,master - 0 1749488968682 13 connected 5461-16383
vars currentEpoch 13 lastVoteEpoch 9
```

```
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd master - 0 1749488968682 13 connected 5461-16383
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=a91532eb722943e035f34292cf586f3f750d65bd myself,slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1749488968682 13 connected
vars currentEpoch 13 lastVoteEpoch 9
```

```
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=a91532eb722943e035f34292cf586f3f750d65bd myself,slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1749488968682 13 connected
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd master - 0 1749488968682 13 connected 5461-16383
vars currentEpoch 13 lastVoteEpoch 9
```

All of these load fine.

**Comment by martinrvisser** [comment]
> @martinrvisser I tried few scenarios manually, they seem to run fine. Could you try running this patch and see if it helps ?

@hpatro fine in my tests also, nice work
2804808:M 13 Jun 2025 12:13:25.599 * Node 386bac3e5337540f2bce4181ff8980f33a989667 has a different shard id (4009ad6c27a3fe91b709a6502bd111b5d58eada0) than its primary's shard id bb85c3d913bb6f9e3d02e68ae89b5c5e61111fb4 (f713a7d0f3079e30fcc47348260a09de0c9b8b72). Updating replica's shard id to match primary's shard id.
2804808:M 13 Jun 2025 12:13:25.599 * Node configuration loaded, I'm 386bac3e5337540f2bce4181ff8980f33a989667

**Review by enjoy-binbin — COMMENTED** [review]
This look correct, please also update the top comment to desc it. So it is somehow like a corrupted (or a outupdated) nodes.conf cause the trouble?

**Comment by hpatro** [comment]
> This look correct, please also update the top comment to desc it. So it is somehow like a corrupted (or a outupdated) nodes.conf cause the trouble?

Yes. Updated.

**Review by enjoy-binbin — APPROVED** [review]
LGTM

**Comment by zuiderkwast** [comment]
I tried backporting this one to 7.2 but I couldn't get the test case to pass, so I'm skipping it for now. If anyone wants to help backporting it, feel free to open a PR targeting the 7.2 branch. Some difficulties to note:

* `src/cluster_legacy.c` doesn't exist in 7.2. It's still called `src/cluster.c` here.
* Variables for primaries and replicas are using the old names masters and slaves.

**Comment by roshkhatri** [comment]
>I tried backporting this one to 7.2 but I couldn't get the test case to pass, so I'm skipping it for now. If anyone wants to help backporting it, feel free to open a PR targeting the 7.2 branch. Some difficulties to note:
src/cluster_legacy.c doesn't exist in 7.2. It's still called src/cluster.c here.
Variables for primaries and replicas are using the old names masters and slaves.

@zuiderkwast opened a PR for this here: https://github.com/valkey-io/valkey/pull/3229
