### PR TITLE
Converge divergent shard-id persisted in nodes.conf to master's shard…

### LINKED ISSUE #2171: [BUG] "Unrecoverable error: corrupted cluster config file" due to incorrect shard-id
**Describe the bug**

Valkey cluster member unable to start when the replica shard-id does not match the shard-id from it's master. This is from a production system after some nodes were restarted.

After investigation this is fixed in Redis by PR [#13428](https://github.com/redis/redis/pull/13428/files/aa976d3a023e4d7da8ceb255f31d8f5edbd6fb8a) 

**To reproduce**

Shutdown a cluster member and assign a different shard-id in the nodes.conf for this member.

**Expected behavior**

Shard-id from nodes.conf is ignored and taken from the primary for this cluster member.

**Additional information**

example nodes.conf
```
8d89f4d4e7c57a2819277732f86213241c3ec0d3 10.124.45.182:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143722 13 connected
ff2bb70f5966dce0bdbe107159c40820c58d9fab 10.125.153.178:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 master - 0 1748776143716 1 connected 0-5460
998b0f988d1b695a57b9384e491090040af8609f 10.125.153.186:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 disconnected
e5571288f2bc9c5aca7ffe0571b954149e560dd8 10.124.45.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 998b0f988d1b695a57b9384e491090040af8609f 0 1748776143733 0 connected
a6bafb11bb6203667eb6065243a3bdda2263a9f3 10.124.43.64:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 slave ff2bb70f5966dce0bdbe107159c40820c58d9fab 0 1748776143729 1 connected
22ec534c44c4e981585c96743cdd260c6648a799 10.124.45.183:0@28007,,tls-port=18007,shard-id=87512800accd227b7dee6667293ee3aff8ad69a2 slave ff2bb70f5966dce0bdbe107159c40820c58d9fab 0 1748776143726 1 connected
0ae4a85046b3c65ad12ad178459e90307b033250 10.125.153.184:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd myself,slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 connected
adcd0c05680d79f652e6e622085f84a29fbd7321 10.125.153.185:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143695 13 disconnected
43ee1cacd6948ee96bb367eb8795e62e8d153f05 10.125.153.181:0@28007,,tls-port=18007,shard-id=f91532eb722943e035f34292cf586f3f750d65bd master - 0 1748776143695 13 disconnected 5461-16383
fa902861e26b83e41b7f825b9fd23f76101e8cea 10.124.43.15:0@28007,,tls-port=18007,shard-id=7e6ea01d543a80915c3a60aad26fcb182c8c6c1d slave 43ee1cacd6948ee96bb367eb8795e62e8d153f05 0 1748776143726 13 connected
vars currentEpoch 13 lastVoteEpoch 9
```

### PR DESCRIPTION
**Pull request by roshkhatri**
Backporting https://github.com/valkey-io/valkey/pull/2174 to 7.2 branch

Handle divergent shard-id across master and replica from nodes.conf and reconcile all the nodes in the shard to the master node's shard-id.

Fixes #2171

(cherry picked from commit 4a3e713032ff73fc652221fef958bae6bb1958f4)

### CODE REVIEW

**Review by Nikhil-Manglore — APPROVED** [review]

**Review by sarthakaggarwal97 — APPROVED** [review]
@roshkhatri known 7.2 CI failures? also why not do it in #3139 itself?

File: src/cluster.c [hunk 1]
```diff
@@ -708,6 +727,8 @@ int clusterLoadConfig(char *filename) {
     if (clusterGetMaxEpoch() > server.cluster->currentEpoch) {
         server.cluster->currentEpoch = clusterGetMaxEpoch();
     }
+    if (dirty || shard_id_reconciled) clusterSaveConfigOrDie(1);
```
Comment (sarthakaggarwal97) [inline src/cluster.c:730]: maybe I missed, why did we add this?

**Review by zuiderkwast — APPROVED** [review]
LGTM

File: src/cluster.c (hunk 1 above)
Comment (zuiderkwast) [reply src/cluster.c:730]: @roshkhatri Do you want to answer this before we merge?

In unstable, I can't see that we save cluster config after loading it even if we have reconciled the shard ids.

Comment (roshkhatri) [reply src/cluster.c:730]: we needed those to get the same behavior, the configs did not save to the files after the shardid we reconciled in-memory
The tests were failing. I will look into unstable why we dont need these there

Comment (roshkhatri) [reply src/cluster.c:730]: So in `clusterUpdateMyselfFlags`  in clusterInit, 
on unstable:
`(myself->flags != oldflags)` is always true as we are adding new flags so the configs are saved automatically before sleep
on 7.2:
we dont add flags and `(myself->flags != oldflags)` is not true so we dont add `clusterDoBeforeSleep(CLUSTER_TODO_SAVE_CONFIG | CLUSTER_TODO_UPDATE_STATE);`

Maybe we can add a save config before sleep in clusterinit by default on 7.2 and we wont need this

Comment (zuiderkwast) [reply src/cluster.c:730]: Thanks. That would affect other behavior too? Maybe best to do the minimum impact.

Comment (sarthakaggarwal97) [reply src/cluster.c:730]: +1 to minimum blast radius

Comment (zuiderkwast) [reply src/cluster.c:730]: I'll merge this as-is then.

Comment (roshkhatri) [reply src/cluster.c:730]: Yeah minimum is good
