### PR TITLE
Fix reconfiguring sub-replica causing data loss when myself change shard_id

### LINKED ISSUE #942: [Test failure] Migrated replica reports zero repl offset issue
*** [err]: Migrated replica reports zero repl offset and rank, and fails to win election in tests/unit/cluster/replica-migration.tcl

https://github.com/valkey-io/valkey/actions/runs/10542509223/job/29209355583#step:6:10878
https://github.com/valkey-io/valkey/actions/runs/10542509223/job/29209355497#step:6:10904
https://github.com/valkey-io/valkey/actions/runs/10551198752/job/29228285306#step:6:10767

### PR DESCRIPTION
**Pull request by enjoy-binbin**
When reconfiguring sub-replica, there may a case that the sub-replica will
use the old offset and win the election and cause the data loss if the old
primary went down.

In this case, sender is myself's primary, when executing updateShardId,
not only the sender's shard_id is updated, but also the shard_id of
myself is updated, casuing the subsequent areInSameShard check, that is,
the full_sync_required check to fail.

As part of the recent fix of #885, the sub-replica needs to decide whether
a full sync is required or not when switching shards. This shard membership
check is supposed to be done against sub-replica's current shard_id, which
however was lost in this code path. This then leads to sub-replica joining
the other shard with a completely different and incorrect replication history.

This is the only place where replicaof state can be updated on this path
so the most natural fix would be to pull the chain replication reduction
logic into this code block and before the updateShardId call.

This one follow #885 and closes #942.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
Is there a good way to write a test case to cover this? I don't know how to trigger this sub-replica case easier.

Full CI: https://github.com/valkey-io/valkey/actions/runs/10555652357

**Comment by PingXie** [comment]
>In this case, sender is myself's primary, when executing updateShardId,
not only the sender's shard_id is updated, but also the shard_id of
myself is updated,

I take it that we ended up with a replica (myself) disagreeing with its primary on the shard-id? Do you have a log snippet handy that demonstrates this? Let me take a closer look at the shard id update logic, holistically. There have been a few tricky bugs in this area. I wonder if they are affected by common issues.

**Comment by enjoy-binbin** [comment]
The link in #942 has the full logs, but i happend has some

9e03820e6636099e9a10d26a1677ae00b3b452d3:
```
# The primary
33772:M 25 Aug 2024 01:14:36.928 * Migrating slot 0 to node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 ()
33772:M 25 Aug 2024 01:14:37.027 * Slot 0 is migrated from node 9e03820e6636099e9a10d26a1677ae00b3b452d3 () in shard 1338c68632657b706e6233d3ad9ae051427d1b6b to node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32.
33772:M 25 Aug 2024 01:14:37.029 * Slot 0 is no longer being migrated to node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32.
33772:M 25 Aug 2024 01:14:37.043 * Configuration change detected. Reconfiguring myself as a replica of node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32

# The offset is 0 as we expected
33772:S 25 Aug 2024 01:14:37.055 * Connecting to PRIMARY 127.0.0.1:21455
33772:S 25 Aug 2024 01:14:37.057 * PRIMARY <-> REPLICA sync started
33772:S 25 Aug 2024 01:14:37.083 * Non blocking connect for SYNC fired the event.
33772:S 25 Aug 2024 01:14:37.090 * Primary replied to PING, replication can continue...
33772:S 25 Aug 2024 01:14:37.098 * Partial resynchronization not possible (no cached primary)
33772:S 25 Aug 2024 01:14:37.103 * Full resync from primary: 42896f8f4927136a9514b738af65fbb571806be4:32118
33772:S 25 Aug 2024 01:14:37.109 - Client closed connection id=6 addr=127.0.0.1:34708 laddr=127.0.0.1:21452 fd=27 name= age=19 idle=0 flags=S db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=16384 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=16448 tot-mem=34758 events=r cmd=replconf user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=974 tot-net-out=635598 tot-cmds=26
33772:S 25 Aug 2024 01:14:37.110 * Connection with replica 127.0.0.1:21448 lost.
33772:S 25 Aug 2024 01:14:37.152 * Node 183d130727181bd5f28b3cf0675cbf0153f6b283 () is now a replica of node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 1338c68632657b706e6233d3ad9ae051427d1b6b
33772:S 25 Aug 2024 01:14:48.593 * Start of election delayed for 2885 milliseconds (rank #2, offset 0).
```

183d130727181bd5f28b3cf0675cbf0153f6b283:
```
# The replica
33547:S 25 Aug 2024 01:14:36.914 * Migrating slot 0 to node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 ()
33547:S 25 Aug 2024 01:14:37.029 * Assigning slot 0 to node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32
33547:S 25 Aug 2024 01:14:37.097 * Node 9e03820e6636099e9a10d26a1677ae00b3b452d3 () is no longer primary of shard 1338c68632657b706e6233d3ad9ae051427d1b6b; removed all 0 slot(s) it used to own
33547:S 25 Aug 2024 01:14:37.097 * Node 9e03820e6636099e9a10d26a1677ae00b3b452d3 () is now part of shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32

# In here, the replica's primary send its PING, and the replica need to update the sender's shard_id, and since the sender is myself's primary,
# here we also update myself's shard_id. see `updateShardId(sender, sender_claimed_primary->shard_id)`
33547:S 25 Aug 2024 01:14:37.097 * Node 9e03820e6636099e9a10d26a1677ae00b3b452d3 () is now a replica of node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () in shard 7b9ca1414bb71e553cce31e358efb7fef29e7e32

# And then, doing the reconfiguring. Since myself's shard_id is updated in the above, here `!areInSameShard(myself->replicaof->replicaof, myself)`
# check failed, and we think we can do a psync and remain the old offset.
33547:S 25 Aug 2024 01:14:37.099 * I'm a sub-replica! Reconfiguring myself as a replica of 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 from 9e03820e6636099e9a10d26a1677ae00b3b452d3

# Doing the psync with the old offset
33547:M 25 Aug 2024 01:14:37.103 * Connection with primary lost.
33547:M 25 Aug 2024 01:14:37.104 * Caching the disconnected primary state.
33547:S 25 Aug 2024 01:14:37.110 * Connecting to PRIMARY 127.0.0.1:21455
33547:S 25 Aug 2024 01:14:37.110 * PRIMARY <-> REPLICA sync started
33547:S 25 Aug 2024 01:14:37.121 * Non blocking connect for SYNC fired the event.
33547:S 25 Aug 2024 01:14:37.123 * Primary replied to PING, replication can continue...
33547:S 25 Aug 2024 01:14:37.151 * Trying a partial resynchronization (request a23ef12063d15051cfb636553d48c95933a8429f:317789).
33547:S 25 Aug 2024 01:14:37.244 - Client closed connection id=8 addr=127.0.0.1:52912 laddr=127.0.0.1:21448 fd=28 name= age=1 idle=1 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=16384 argv-mem=0 multi-mem=0 rbs=1024 rbp=987 obl=0 oll=0 omem=0 tot-mem=18310 events=r cmd=cluster|nodes user=default redir=-1 resp=2 lib-name= lib-ver= tot-net-in=56 tot-net-out=1974 tot-cmds=2
33547:S 25 Aug 2024 01:14:47.522 # Failed to read response from the server: Success
33547:S 25 Aug 2024 01:14:47.522 # Primary did not reply to PSYNC, will try later
33547:S 25 Aug 2024 01:14:47.604 - Connection with Node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 at 127.0.0.1:31455 failed: Connection refused
33547:S 25 Aug 2024 01:14:48.008 * Connecting to PRIMARY 127.0.0.1:21455
33547:S 25 Aug 2024 01:14:48.008 * PRIMARY <-> REPLICA sync started
33547:S 25 Aug 2024 01:14:48.009 # Error condition on socket for SYNC: Connection refused
33547:S 25 Aug 2024 01:14:48.010 - Connection with Node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 at 127.0.0.1:31455 failed: Connection refused
33547:S 25 Aug 2024 01:14:48.415 * NODE 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 () possibly failing.
33547:S 25 Aug 2024 01:14:48.418 - Connection with Node 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 at 127.0.0.1:31455 failed: Connection refused
33547:S 25 Aug 2024 01:14:48.512 * FAIL message received from 9e03820e6636099e9a10d26a1677ae00b3b452d3 () about 3081a0e079dd41c05fc5f8f7078f04c1816a8fe7 ()
33547:S 25 Aug 2024 01:14:48.513 # Cluster state changed: fail

# Using the old offset. It is wrong
33547:S 25 Aug 2024 01:14:48.521 * Start of election delayed for 729 milliseconds (rank #0, offset 317788).
```

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -3312,10 +3314,16 @@ int clusterProcessPacket(clusterLink *link) {
                     if (sender->replicaof) clusterNodeRemoveReplica(sender->replicaof, sender);
                     serverLog(LL_NOTICE, "Node %.40s (%s) is now a replica of node %.40s (%s) in shard %.40s",
                               sender->name, sender->human_nodename, sender_claimed_primary->name,
-                              sender_claimed_primary->human_nodename, sender->shard_id);
+                              sender_claimed_primary->human_nodename, sender_claimed_primary->shard_id);
                     clusterNodeAddReplica(sender_claimed_primary, sender);
                     sender->replicaof = sender_claimed_primary;
```
Comment (PingXie) [inline src/cluster_legacy.c:3317]: This is the only place where `->replicaof` state can be updated on this path so the most natural fix would be to pull the chain replication reduction logic into this code block and before the `updateShardId` call. We don't need to introduce yet another very purpose-built state this way.

**Comment by PingXie** [comment]
Capturing the minimum repro setup and event sequence based on offline discussion (thanks for the details, @enjoy-binbin!).

## Minimum repro setup ##
* two shards, `shard 1` with `primary 1` and `replica 2`, and `shard 2` with `primary 2`
* `shard 1` has one slot, `slot 0`, while `shard 2` has the remaining slots
* `cluster-allow-replica-migration` is enabled on `primary 1` (which defaults to true)

## Event sequence ##
1. now migrate `slot 0` from `shard 1` to `shard 2`
2. `primary 1` loses `slot 0`, which is its last slot, to `primary 2`
3. because `cluster-allow-replica-migration` (this name seems a misnomer btw) is enabled on `primary 1`, `primary 1` joins `shard 2`, following `primary 2`. 
4. `primary 1` sends `PING` to `replica 1` claiming its `replicaof` is `primary 2`
5. `replica 1` processes the `PING` message in `clusterProcessPacket`

## Code flow ##
1. `replica 1` first notices that `primary 1` claims a different `replicaof`, changing from NULL to `primary 2` at https://github.com/valkey-io/valkey/blob/54c0f743dd6971bf8636c13600a6d4e2ef10106f/src/cluster_legacy.c#L3311
2. `replica 1` then updates its view of `primary 1`'s `replicaof` at https://github.com/valkey-io/valkey/blob/54c0f743dd6971bf8636c13600a6d4e2ef10106f/src/cluster_legacy.c#L3317
3. and updates `primary 1`'s shard_id at https://github.com/valkey-io/valkey/blob/54c0f743dd6971bf8636c13600a6d4e2ef10106f/src/cluster_legacy.c#L3321
4. it then proceeds to the chain replication reduction logic at https://github.com/valkey-io/valkey/blob/54c0f743dd6971bf8636c13600a6d4e2ef10106f/src/cluster_legacy.c#L3388
5. there it decides to replicate directly from `primary 1`'s `replicaof`, which is `primary 2`, at https://github.com/valkey-io/valkey/blob/54c0f743dd6971bf8636c13600a6d4e2ef10106f/src/cluster_legacy.c#L3401

## Bug ##
As part of the recent fix of #885, `replica 1` needs to decide whether a full sync is required or not when switching shards (from `shard 1` to `shard 2`). This shard membership check is supposed to be done against `replica 1`'s current shard_id, which however was lost in step 3 of "code flow". This then leads to `replica 1` joining `shard 2` with a completely different and incorrect replication history.

Does this match your understanding of the issue, @enjoy-binbin?

**Comment by enjoy-binbin** [comment]
yes. It match, thank you for the full details, it's very clear

File: src/cluster_legacy.c (hunk 1 above)
Comment (enjoy-binbin) [reply src/cluster_legacy.c:3317]: ok, make sense to me, i will try to think of a test case that can cover it, by any chance you have the hint on the test case?

Comment (PingXie) [reply src/cluster_legacy.c:3317]: >by any chance you have the hint on the test case?

I think we could get a consistent repro if we disable `cluster-allow-replica-migration` on `replica 1`. Something like below:

* two shards, `shard 1` with `primary 1` and `replica 2`, and `shard 2` with `primary 2`
* `shard 1` has one slot, slot 0, while `shard 2` has the remaining slots
* `cluster-allow-replica-migration` is enabled on `primary 1` 
* `cluster-allow-replica-migration` is disabled on `replica 1`

Comment (enjoy-binbin) [reply src/cluster_legacy.c:3317]: ok, i get it, i can take a try, just kind of a reverse version of #928

File: src/cluster_legacy.c [hunk 2]
```diff
@@ -3312,10 +3312,33 @@ int clusterProcessPacket(clusterLink *link) {
...
 
+                    /* Currently this is the only place where replicaof state can be updated on
+                     * this function, since updateShardId may update myself shard_id and caused
+                     * areInSameShard check failed. Explicitly check for a replication loop before
+                     * attempting the replication chain folding logic. */
```
Comment (PingXie) [inline src/cluster_legacy.c]: I was thinking of adding a bit more context here. WDYT?
```suggestion
                    /* The chain reduction logic requires correctly establishing the replication relationship.
                     * A key decision when designating a new primary for 'myself' is determining whether
                     * 'myself' and the new primary belong to the same shard, which would imply shared
                     * replication history and allow safe partial synchronization (psync).
                     *
                     * This decision hinges on the shard_id, a per-node property that helps verify if the
                     * two nodes share the same replication history. It's critical not to update 'myself's
                     * shard_id prematurely during this process. Doing so could incorrectly associate
                     * 'myself' with the sender's shard_id, leading the subsequent clusterSetPrimary call
                     * to falsely assume that 'myself' and the new primary have been in the same shard.
                     * This mistake could result in data loss by incorrectly permitting a psync.
                     *
                     * Therefore, it's essential to delay any shard_id updates until after the replication
                     * relationship has been properly established and verified. */
```

File: src/cluster_legacy.c [hunk 3]
```diff
@@ -3312,10 +3312,33 @@ int clusterProcessPacket(clusterLink *link) {
...
+                         * else to trigger replica migration. In this case, they are not in the
+                         * same shard, so a full sync is required.
+                         *
+                         * Or a replica's primary can turn itself into a replica of its other
+                         * replica during a failover. In this case, they are in the same shard,
+                         * so we can try a psync. */
+                        serverLog(LL_NOTICE, "I'm a sub-replica! Reconfiguring myself as a replica of %.40s from %.40s",
+                                  myself->replicaof->replicaof->name, myself->replicaof->name);
+                        int are_in_same_shard = areInSameShard(myself->replicaof->replicaof, myself);
+                        clusterSetPrimary(myself->replicaof->replicaof, 1, !are_in_same_shard);
```
Comment (PingXie) [inline src/cluster_legacy.c]: the more concise single line form would be my favorite. the new variable `are_in_same_shard` doesn't provide additional context, but if you'd still prefer a variable, I would suggest `full_sync_required`
```suggestion
                        clusterSetPrimary(myself->replicaof->replicaof, 1, !areInSameShard(myself->replicaof->replicaof, myself));
```

File: src/cluster_legacy.c [hunk 4]
```diff
@@ -3312,10 +3312,33 @@ int clusterProcessPacket(clusterLink *link) {
...
+                        /* We will add the CLUSTER_TODO_SAVE_CONFIG flag when we exit the if statement. */
+                        clusterDoBeforeSleep(CLUSTER_TODO_UPDATE_STATE | CLUSTER_TODO_FSYNC_CONFIG);
```
Comment (PingXie) [inline src/cluster_legacy.c]: since there is no penalty, maybe just add `CLUSTER_TODO_SAVE_CONFIG` to the call so this code is more contained and hence more resilient in future refactoring. We also don't have to explain it.
```suggestion
                        clusterDoBeforeSleep(CLUSTER_TODO_SAVE_CONFIG| CLUSTER_TODO_UPDATE_STATE | CLUSTER_TODO_FSYNC_CONFIG);
```

**Review by PingXie — COMMENTED** [review]
LGTM overall. I assume the test failed as we expect without the server fix?

**Comment by enjoy-binbin** [comment]
> LGTM overall. I assume the test failed as we expect without the server fix?

Yes, the test i added will fail if the code without the server fix

File: src/cluster_legacy.c (hunk 3 above)
Comment (enjoy-binbin) [reply src/cluster_legacy.c]: i am using this because the fomat action will complain it. and `are_in_same_shard` this var name, i am using it everywhere in the fisrt PR...

File: src/cluster_legacy.c (hunk 4 above)
Comment (enjoy-binbin) [reply src/cluster_legacy.c]: i do the changes because the format action complainning it, so i want to reduce the length, but maybe i can try, let see if this work.

**Review by PingXie — APPROVED** [review]

**Review by lilpoozie2005 — APPROVED** [review]
