### PR TITLE
For MEETs, save the extensions support flag immediately during MEET processing

### LINKED ISSUE #774: [BUG] nodes.conf can be corrupted when node is restarted before cluster shard ID stabilizes (for 7.2)
**Describe the bug**

During cluster setup, the shard id gets established through cluster message extension data. For backwards compatibility reasons, this is delayed until it is established that the node can properly receive these extensions, leading to a propagation delay for the shard ID. When an engine crashes or restarts before the shard ID has stabilized, the config file can become corrupted, leading to failure to restart the engine.

**To reproduce**
Set up a cluster and then immediately restart a node. It will (flakily) fail to restart due to a corrupted nodes.conf file - either because the replicas do not agree on the shard ID, or there is a shard ID mismatch.

**Expected behavior**

Engine restarts successfully.

**Additional information**

Related to this PR - https://github.com/valkey-io/valkey/pull/573

### PR DESCRIPTION
**Pull request by bentotten**
For backwards compatibility reasons, a node will wait until it receives a cluster message with the extensions flag before sending its own extensions. This leads to a delay in shard ID propagation that can corrupt nodes.conf with inaccurate shard IDs if a node is restarted before this can stabilize.

This fixes much of that delay by immediately triggering the extensions-supported flag during the MEET processing and attaching the node to the link, allowing the PONG reply to contain OSS extensions.

Partially fixes #774

### CODE REVIEW

**Comment by bentotten** [comment]
(force pushed with DCO)

**Review by hpatro — APPROVED** [review]
Thanks @bentotten. LGTM.

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -2996,14 +2996,20 @@ int clusterProcessPacket(clusterLink *link) {
...
         if (!sender && type == CLUSTERMSG_TYPE_MEET) {
             clusterNode *node;
 
             node = createClusterNode(NULL, CLUSTER_NODE_HANDSHAKE);
             serverAssert(nodeIp2String(node->ip, link, hdr->myip) == C_OK);
             getClientPortFromClusterMsg(hdr, &node->tls_port, &node->tcp_port);
             node->cport = ntohs(hdr->cport);
+            if (hdr->mflags[0] & CLUSTERMSG_FLAG0_EXT_DATA) {
+                node->flags |= CLUSTER_NODE_EXTENSIONS_SUPPORTED;
+            }
```
Comment (enjoy-binbin) [inline src/cluster_legacy.c:3012]: Move it around here? line 2936
```
    if (sender && (hdr->mflags[0] & CLUSTERMSG_FLAG0_EXT_DATA)) {
        sender->flags |= CLUSTER_NODE_EXTENSIONS_SUPPORTED;
    }
```

but i am ok with it. Not a blocker

**Review by enjoy-binbin — APPROVED** [review]
LGTM.

File: src/cluster_legacy.c (hunk 1 above)
Comment (bentotten) [reply src/cluster_legacy.c:3012]: In this circumstance, I believe we need to add it here so that the newly created node has this flag immediately in the PONG writing call on line 3017 

```
if (!sender && type == CLUSTERMSG_TYPE_MEET) clusterProcessGossipSection(hdr, link);
        /* Anyway reply with a PONG */
        clusterSendPing(link, CLUSTERMSG_TYPE_PONG);
    }
```

This allows this node to be marked as extensions-supported right away in the logic on line 3814

```
if (link->node && nodeSupportsExtensions(link->node))
```

Comment (bentotten) [reply src/cluster_legacy.c:3012]: I have updated the commit message - this does save time to stabilization however not in the way I had anticipated - the node does not attach to the link here so does not attach extensions to the PONG, but instead saving the flag here saves one hop, it seems by allowing extensions to be attached to the next message instead of waiting for a second PING/PONG

Comment (bentotten) [reply src/cluster_legacy.c:3012]: It may be worth exploring if there would be negative issues with attaching the node to the link in this meet, I believe that would have the intended effect - but this commit still has a speed benefit, even without attaching extensions to the PONG

Comment (PingXie) [reply src/cluster_legacy.c:3012]: >It may be worth exploring if there would be negative issues with attaching the node to the link in this meet, I believe that would have the intended effect

I also feel that we should fix the link here but in addition, I think we need another change to create the node with its real name on [L3006](https://github.com/valkey-io/valkey/pull/778/files#diff-2515500619600c5a1e7a8d9aaa8761a6071314cd226c3b7ee4d0e054691f0a8eR3006), i.e.,

```c
    node = createClusterNode(hdr->sender, CLUSTER_NODE_HANDSHAKE);
```

Would you like to take a shot at it, @bentotten?

Comment (bentotten) [reply src/cluster_legacy.c:3012]: I could try adding the link + name here, no problem. 

It is worth noting that attaching the nodename here will cause the `sender` variable to be filled on the next PING/PONG, while leaving it blank appears to still cause `sender` to have its original behavior on the next PING/PONG. What effect that will have, Im not sure 

```
        /* Otherwise, fetch sender based on the message */
        sender = clusterLookupNode(hdr->sender, CLUSTER_NAMELEN);
```

https://github.com/valkey-io/valkey/blob/unstable/src/cluster_legacy.c#L2807

File: src/cluster_legacy.c [hunk 2]
```diff
@@ -2996,14 +2996,22 @@ int clusterProcessPacket(clusterLink *link) {
...
+            node->inbound_link = link;
+            link->node = node;
```
Comment (PingXie) [inline src/cluster_legacy.c]: Let's use `setClusterNodeToInboundClusterLink` to connect the node and link.

**Review by bentotten — COMMENTED** [review]
Interesting, if I am understanding this correctly, adding the node name here did seem to cause a problem for the next packet exchanges - it looks like adding the name here during the MEET causes `sender` to be valid during the next packet received, which hits this logic and frees the node/link before the handshake flag can be removed

```
                if (sender) {
                    serverLog(LL_VERBOSE,
                        "Handshake: we already know node %.40s (%s), "
                        "updating the address if needed.", sender->name, sender->human_nodename);
                    if (nodeUpdateAddressIfNeeded(sender,link,hdr))
                    {
                        clusterDoBeforeSleep(CLUSTER_TODO_SAVE_CONFIG|
                                             CLUSTER_TODO_UPDATE_STATE);
                    }
                    /* Free this node as we already have it. This will
                     * cause the link to be freed as well. */
                    clusterDelNode(link->node);
                    return 0;
```

Follow up question:
Do we want to finish the handshake during MEET processing (maybe after sending the PONG) or leave the name as-is and keep the handshake completion for the ping/pong after the MEET?

File: src/cluster_legacy.c (hunk 1 above)
Comment (bentotten) [reply src/cluster_legacy.c:3012]: Accidentally made a review comment instead of continuing the thread: https://github.com/valkey-io/valkey/pull/778#pullrequestreview-2189498791

Adding the name here unfortunately causes problems with handshake resolution on the next packet

**Comment by PingXie** [comment]
Sorry for dropping the ball on this one, @bentotten. Let me find some time next and get back to this thread.

**Comment by bentotten** [comment]
any update on this?

**Comment by PingXie** [comment]
Thanks for your patience, @bentotten! I think this change makes sense overall. I think we should also consider updating the extension_capable flag right after completing the handshake as below:

https://github.com/valkey-io/valkey/blob/089048d36485bf0d0d202221a7497aec0563bcdd/src/cluster_legacy.c#L3194

otherwise, I think we will have to wait for the next `PONG` message to fix the flag at: 

https://github.com/valkey-io/valkey/blob/089048d36485bf0d0d202221a7497aec0563bcdd/src/cluster_legacy.c#L3070



> it looks like adding the name here during the MEET causes `sender` to be valid during the next packet received, which hits this logic and frees the node/link before the handshake flag can be removed

Yeah, you are right. Setting the name during `MEET` alters the handshake sequence. I agree we should not make this change.

Along the same line, I'm now wondering whether we should connect the `link` and `node` during the `MEET` phase (via `setClusterNodeToInboundClusterLink`). Currently, we establish these "links" (between `link` and `node`) *after* the handshake is completed. Based on the existing implementation, I don't anticipate any issues with moving this logic earlier into the `MEET` phase. However, I would be a lot more comfortable if we could find a way to instruct `clusterSendPing` to explicitly set this extension-capable flag without relying on `link->node`.

**Comment by madolson** [comment]
Based on some offline discussion, we're going to merge this to see if it helps with another issue and I will create an issue with Ping's comment to followup with.

**Review by madolson — APPROVED** [review]
