### PR TITLE
Fix crash during TLS handshake with I/O threads

### LINKED ISSUE #1883: [CRASH] Valkey Crashes in cluster mode with message 'tls.c:603 '0' is not true'
### Crash report

		19:M 25 Mar 2025 15:20:20.481 * Migrating slot 15760 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 ()
		19:M 25 Mar 2025 15:20:20.485 * Assigning slot 15760 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 () in shard da6d20e2f47244e6c86ac108f791b459b5cf714c
		19:M 25 Mar 2025 15:20:20.493 * Migrating slot 15761 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 ()
		19:M 25 Mar 2025 15:20:20.498 * Assigning slot 15761 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 () in shard da6d20e2f47244e6c86ac108f791b459b5cf714c
		19:M 25 Mar 2025 15:20:20.503 * Migrating slot 15762 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 ()
		19:M 25 Mar 2025 15:20:20.507 * Assigning slot 15762 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 () in shard da6d20e2f47244e6c86ac108f791b459b5cf714c
		19:M 25 Mar 2025 15:20:20.512 * Migrating slot 15763 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 ()
		19:M 25 Mar 2025 15:20:20.517 * Assigning slot 15763 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 () in shard da6d20e2f47244e6c86ac108f791b459b5cf714c
		19:M 25 Mar 2025 15:20:20.522 * Migrating slot 15764 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 ()
		19:M 25 Mar 2025 15:20:20.527 * Assigning slot 15764 to node 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 () in shard da6d20e2f47244e6c86ac108f791b459b5cf714c
		19:M 25 Mar 2025 15:20:42.036 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.58.205:40291 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:20:50.355 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.220.2:52938 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:00.608 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.165.171:1567 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:02.037 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.58.205:19327 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:07.418 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.88.77.194:33170 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:10.536 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.223.35:24296 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:11.923 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.184.139:3733 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:40.355 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.220.2:42455 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:50.354 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.220.2:29112 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:51.922 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.184.139:50962 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:21:54.934 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.88.251.15:19833 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:02.036 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.58.205:40003 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:10.112 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.88.83.56:26485 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:35.938 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.181.140:33419 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:44.934 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.88.251.15:26923 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:50.354 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.220.2:43577 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:50.425 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.66.47.122:17251 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:22:50.608 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.92.165.171:27520 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:23:05.938 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.181.140:22804 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:23:15.938 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.96.181.140:45527 laddr=10.92.102.243:17379)
		19:M 25 Mar 2025 15:23:37.418 # Error accepting a client connection: error:0A000126:SSL routines::unexpected eof while reading (addr=10.88.77.194:56494 laddr=10.92.102.243:17379)
		
		
		=== VALKEY BUG REPORT START: Cut & paste starting from here ===
		19:M 25 Mar 2025 15:23:39.021 # === ASSERTION FAILED ===
		19:M 25 Mar 2025 15:23:39.021 # ==> tls.c:603 '0' is not true
		
		------ INFO OUTPUT ------
		# Server
		redis_version:7.2.4
		server_name:valkey
		valkey_version:255.255.255
		valkey_release_stage:dev
		redis_git_sha1:00000000
		redis_git_dirty:0
		redis_build_id:4ab6d72c811767e7
		server_mode:cluster
		os:Linux 5.10.234-225.910.amzn2.aarch64 aarch64
		arch_bits:64
		monotonic_clock:POSIX clock_gettime
		multiplexing_api:epoll
		gcc_version:14.2.0
		process_id:19
		process_supervised:no
		run_id:77dea60e022a336689008d24cdab05ac83f12708
		tcp_port:17379
		server_time_usec:1742916219021063
		uptime_in_seconds:413
		uptime_in_days:0
		hz:40
		configured_hz:40
		clients_hz:40
		lru_clock:14862970
		executable:/data/keydb-server
		config_file:/redis-conf/redis.conf
		io_threads_active:1
		availability_zone:us-east-1b
		listener2:name=tls,bind=0.0.0.0,port=17379
		
		# Clients
		connected_clients:90
		cluster_connections:16
		maxclients:80000
		client_recent_max_input_buffer:20480
		client_recent_max_output_buffer:41008
		blocked_clients:0
		tracking_clients:0
		pubsub_clients:0
		watching_clients:0
		clients_in_timeout_table:0
		total_watched_keys:0
		total_blocking_keys:0
		total_blocking_keys_on_nokey:0
		paused_reason:none
		paused_actions:none
		paused_timeout_milliseconds:0
		
		# Memory
		used_memory:601364528
		used_memory_human:573.51M
		used_memory_rss:621125632
		used_memory_rss_human:592.35M
		used_memory_peak:601364528
		used_memory_peak_human:573.51M
		used_memory_peak_perc:100.00%
		used_memory_overhead:288993364
		used_memory_startup:6983440
		used_memory_dataset:312371164
		used_memory_dataset_perc:52.55%
		allocator_allocated:602494728
		allocator_active:614727680
		allocator_resident:620298240
		allocator_muzzy:0
		total_system_memory:66595758080
		total_system_memory_human:62.02G
		used_memory_lua:32768
		used_memory_vm_eval:32768
		used_memory_lua_human:32.00K
		used_memory_scripts_eval:0
		number_of_cached_scripts:0
		number_of_functions:0
		number_of_libraries:0
		used_memory_vm_functions:33792
		used_memory_vm_total:66560
		used_memory_vm_total_human:65.00K
		used_memory_functions:224
		used_memory_scripts:224
		used_memory_scripts_human:224B
		maxmemory:39208026931
		maxmemory_human:36.52G
		maxmemory_policy:allkeys-random
		allocator_frag_ratio:1.02
		allocator_frag_bytes:12232952
		allocator_rss_ratio:1.01
		allocator_rss_bytes:5570560
		rss_overhead_ratio:1.00
		rss_overhead_bytes:827392
		mem_fragmentation_ratio:1.03
		mem_fragmentation_bytes:20565664
		mem_not_counted_for_evict:0
		mem_replication_backlog:272727092
		mem_total_replication_buffers:272723704
		mem_clients_slaves:0
		mem_clients_normal:1362432
		mem_cluster_links:17152
		mem_aof_buffer:0
		mem_allocator:jemalloc-5.3.0
		mem_overhead_db_hashtable_rehashing:1024
		active_defrag_running:0
		lazyfree_pending_objects:0
		lazyfreed_objects:0
		
		# Persistence
		loading:0
		async_loading:0
		current_cow_peak:0
		current_cow_size:0
		current_cow_size_age:0
		current_fork_perc:0.00
		current_save_keys_processed:0
		current_save_keys_total:0
		rdb_changes_since_last_save:237766
		rdb_bgsave_in_progress:0
		rdb_last_save_time:1742915806
		rdb_last_bgsave_status:ok
		rdb_last_bgsave_time_sec:0
		rdb_current_bgsave_time_sec:-1
		rdb_saves:0
		rdb_last_cow_size:917504
		rdb_last_load_keys_expired:0
		rdb_last_load_keys_loaded:0
		aof_enabled:0
		aof_rewrite_in_progress:0
		aof_rewrite_scheduled:0
		aof_last_rewrite_time_sec:-1
		aof_current_rewrite_time_sec:-1
		aof_last_bgrewrite_status:ok
		aof_rewrites:0
		aof_rewrites_consecutive_failures:0
		aof_last_write_status:ok
		aof_last_cow_size:0
		module_fork_in_progress:0
		module_fork_last_cow_size:0
		
		# Stats
		total_connections_received:460
		total_commands_processed:331682
		instantaneous_ops_per_sec:4510
		total_net_input_bytes:273712927
		total_net_output_bytes:546025840
		total_net_repl_input_bytes:0
		total_net_repl_output_bytes:543708586
		instantaneous_input_kbps:4983.58
		instantaneous_output_kbps:9988.94
		instantaneous_input_repl_kbps:0.00
		instantaneous_output_repl_kbps:9966.93
		rejected_connections:0
		sync_full:2
		sync_partial_ok:2
		sync_partial_err:0
		expired_keys:0
		expired_stale_perc:0.00
		expired_time_cap_reached_count:0
		expire_cycle_cpu_milliseconds:3
		evicted_keys:0
		evicted_clients:0
		evicted_scripts:0
		total_eviction_exceeded_time:0
		current_eviction_exceeded_time:0
		keyspace_hits:0
		keyspace_misses:0
		pubsub_channels:0
		pubsub_patterns:0
		pubsubshard_channels:0
		latest_fork_usec:694
		total_forks:1
		migrate_cached_sockets:0
		slave_expires_tracked_keys:0
		active_defrag_hits:0
		active_defrag_misses:0
		active_defrag_key_hits:0
		active_defrag_key_misses:0
		total_active_defrag_time:0
		current_active_defrag_time:0
		tracking_total_keys:0
		tracking_total_items:0
		tracking_total_prefixes:0
		unexpected_error_replies:0
		total_error_replies:0
		dump_payload_sanitizations:0
		total_reads_processed:311466
		total_writes_processed:749182
		io_threaded_reads_processed:6575
		io_threaded_writes_processed:50154
		io_threaded_freed_objects:0
		io_threaded_accept_processed:85
		io_threaded_poll_processed:8351
		io_threaded_total_prefetch_batches:458
		io_threaded_total_prefetch_entries:1736
		client_query_buffer_limit_disconnections:0
		client_output_buffer_limit_disconnections:0
		reply_buffer_shrinks:126
		reply_buffer_expands:9
		eventloop_cycles:831173
		eventloop_duration_sum:22916900
		eventloop_duration_cmd_sum:820476
		instantaneous_eventloop_cycles_per_sec:11105
		instantaneous_eventloop_duration_usec:18
		acl_access_denied_auth:0
		acl_access_denied_cmd:0
		acl_access_denied_key:0
		acl_access_denied_channel:0
		
		# Replication
		role:master
		connected_slaves:2
		slave0:ip=10.96.74.166,port=17379,state=online,offset=270170053,lag=1,type=replica
		slave1:ip=10.88.251.15,port=17379,state=online,offset=269896147,lag=1,type=replica
		replicas_waiting_psync:0
		master_failover_state:no-failover
		master_replid:c2c24d861a4ee7a0c8e21cba47de7fc727223716
		master_replid2:0000000000000000000000000000000000000000
		master_repl_offset:271857703
		second_repl_offset:-1
		repl_backlog_active:1
		repl_backlog_size:1000000000
		repl_backlog_first_byte_offset:1
		repl_backlog_histlen:271857703
		
		# CPU
		used_cpu_sys:9.307591
		used_cpu_user:30.702964
		used_cpu_sys_children:0.000997
		used_cpu_user_children:0.001539
		used_cpu_sys_main_thread:8.903861
		used_cpu_user_main_thread:15.689218
		
		# Modules
		module:name=statsd,ver=1,api=1,filters=0,usedby=[],using=[],options=[]
		
		# Commandstats
		cmdstat_client|setname:calls=3,usec=4,usec_per_call=1.33,rejected_calls=0,failed_calls=0
		cmdstat_cluster|addslots:calls=1,usec=762,usec_per_call=762.00,rejected_calls=0,failed_calls=0
		cmdstat_cluster|setslot:calls=41787,usec=393678,usec_per_call=9.42,rejected_calls=0,failed_calls=0
		cmdstat_cluster|slots:calls=41,usec=866,usec_per_call=21.12,rejected_calls=0,failed_calls=0
		cmdstat_cluster|getkeysinslot:calls=10922,usec=10275,usec_per_call=0.94,rejected_calls=0,failed_calls=0
		cmdstat_cluster|meet:calls=8,usec=293,usec_per_call=36.62,rejected_calls=0,failed_calls=0
		cmdstat_cluster|nodes:calls=279,usec=20701,usec_per_call=74.20,rejected_calls=0,failed_calls=0
		cmdstat_cluster|info:calls=38,usec=1670,usec_per_call=43.95,rejected_calls=0,failed_calls=0
		cmdstat_info:calls=163,usec=10865,usec_per_call=66.66,rejected_calls=0,failed_calls=0
		cmdstat_psync:calls=4,usec=160,usec_per_call=40.00,rejected_calls=0,failed_calls=0
		cmdstat_dbsize:calls=38,usec=22,usec_per_call=0.58,rejected_calls=0,failed_calls=0
		cmdstat_ping:calls=3,usec=4,usec_per_call=1.33,rejected_calls=0,failed_calls=0
		cmdstat_config|get:calls=17,usec=3769,usec_per_call=221.71,rejected_calls=0,failed_calls=0
		cmdstat_set:calls=237766,usec=372876,usec_per_call=1.57,rejected_calls=0,failed_calls=0
		cmdstat_readonly:calls=87,usec=112,usec_per_call=1.29,rejected_calls=0,failed_calls=0
		cmdstat_sync:calls=2,usec=54,usec_per_call=27.00,rejected_calls=0,failed_calls=0
		cmdstat_role:calls=6,usec=51,usec_per_call=8.50,rejected_calls=0,failed_calls=0
		cmdstat_module|list:calls=17,usec=35,usec_per_call=2.06,rejected_calls=0,failed_calls=0
		cmdstat_replconf:calls=40500,usec=13444,usec_per_call=0.33,rejected_calls=0,failed_calls=0
		
		# Errorstats
		
		# Latencystats
		latency_percentiles_usec_client|setname:p50=1.003,p99=2.007,p99.9=2.007
		latency_percentiles_usec_cluster|addslots:p50=765.951,p99=765.951,p99.9=765.951
		latency_percentiles_usec_cluster|setslot:p50=14.015,p99=20.095,p99.9=26.111
		latency_percentiles_usec_cluster|slots:p50=6.015,p99=53.247,p99.9=53.247
		latency_percentiles_usec_cluster|getkeysinslot:p50=1.003,p99=2.007,p99.9=3.007
		latency_percentiles_usec_cluster|meet:p50=33.023,p99=46.079,p99.9=46.079
		latency_percentiles_usec_cluster|nodes:p50=73.215,p99=95.231,p99.9=112.127
		latency_percentiles_usec_cluster|info:p50=44.031,p99=62.207,p99.9=62.207
		latency_percentiles_usec_info:p50=65.023,p99=99.327,p99.9=105.471
		latency_percentiles_usec_psync:p50=39.167,p99=46.079,p99.9=46.079
		latency_percentiles_usec_dbsize:p50=1.003,p99=1.003,p99.9=1.003
		latency_percentiles_usec_ping:p50=1.003,p99=2.007,p99.9=2.007
		latency_percentiles_usec_config|get:p50=225.279,p99=254.975,p99.9=254.975
		latency_percentiles_usec_set:p50=1.003,p99=4.015,p99.9=11.007
		latency_percentiles_usec_readonly:p50=1.003,p99=5.023,p99.9=5.023
		latency_percentiles_usec_sync:p50=21.119,p99=33.023,p99.9=33.023
		latency_percentiles_usec_role:p50=8.031,p99=11.007,p99.9=11.007
		latency_percentiles_usec_module|list:p50=2.007,p99=3.007,p99.9=3.007
		latency_percentiles_usec_replconf:p50=0.001,p99=1.003,p99.9=2.007
		
		# Cluster
		cluster_enabled:1
		
		# Keyspace
		db0:keys=237766,expires=0,avg_ttl=0
		
		# Cluster info
		cluster_state:ok
		cluster_slots_assigned:16384
		cluster_slots_ok:16384
		cluster_slots_pfail:0
		cluster_slots_fail:0
		cluster_known_nodes:9
		cluster_size:3
		cluster_current_epoch:10
		cluster_my_epoch:5
		cluster_stats_messages_ping_sent:410
		cluster_stats_messages_pong_sent:429
		cluster_stats_messages_meet_sent:8
		cluster_stats_messages_sent:847
		cluster_stats_messages_ping_received:421
		cluster_stats_messages_pong_received:11349
		cluster_stats_messages_update_received:28
		cluster_stats_messages_received:11798
		total_cluster_links_buffer_limit_exceeded:0
		
		------ CLUSTER NODES OUTPUT ------
		6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 10.96.223.35:0@27379,,tls-port=17379,shard-id=da6d20e2f47244e6c86ac108f791b459b5cf714c master - 0 1742916215285 10 connected 10924-16383
		114cc8e47ffcf8bba9bd311c1614cc40e30600df 10.92.184.139:0@27379,,tls-port=17379,shard-id=da6d20e2f47244e6c86ac108f791b459b5cf714c slave 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 0 1742916216000 10 connected
		a21291b10fc7b6cac5f75ca854c49add8b8735f7 10.88.83.56:0@27379,,tls-port=17379,shard-id=da6d20e2f47244e6c86ac108f791b459b5cf714c slave 6d629c99eb74c4d06f3b5ebd5db2ebb874fc6496 0 1742916218340 10 connected
		1451cd4e99d0c65a25d56b4f4ba2f6335c6171b2 10.92.102.243:0@27379,,tls-port=17379,shard-id=7ec9caabba0b133978fc3708703266796aae9bea myself,master - 0 0 5 connected 0-5461
		f05df0f95cd61e341f6e1fb51cc4b4dc9116b536 10.96.220.2:0@27379,,tls-port=17379,shard-id=896405bbe4538bfb213fc95c75db47f6010a3275 slave 6ed60d5c7facd78eb0c7b7ff758abca816a2314c 0 1742916216000 9 connected
		50e3534709d7b701166fefe3ec323f7684af3e09 10.96.74.166:0@27379,,tls-port=17379,shard-id=7ec9caabba0b133978fc3708703266796aae9bea slave 1451cd4e99d0c65a25d56b4f4ba2f6335c6171b2 0 1742916217000 5 connected
		6ed60d5c7facd78eb0c7b7ff758abca816a2314c 10.88.77.194:0@27379,,tls-port=17379,shard-id=896405bbe4538bfb213fc95c75db47f6010a3275 master - 0 1742916217322 9 connected 5462-10923
		30d7c72c93c58188648d718cc8517857549b058d 10.88.251.15:0@27379,,tls-port=17379,shard-id=7ec9caabba0b133978fc3708703266796aae9bea slave 1451cd4e99d0c65a25d56b4f4ba2f6335c6171b2 0 1742916216305 5 connected
		0655511623c0c5582b5794957910f1a75447e022 10.92.165.171:0@27379,,tls-port=17379,shard-id=896405bbe4538bfb213fc95c75db47f6010a3275 slave 6ed60d5c7facd78eb0c7b7ff758abca816a2314c 0 1742916215000 9 connected
		
		------ CLIENT LIST OUTPUT ------
		id=456 addr=10.66.20.124:52668 laddr=10.92.102.243:17379 fd=78 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3120626 tot-net-out=20122 tot-cmds=2759
		id=415 addr=10.65.156.136:60048 laddr=10.92.102.243:17379 fd=58 name=*redacted* age=60 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=5 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=9431999 tot-net-out=47976 tot-cmds=8335
		id=528 addr=10.66.18.97:37642 laddr=10.92.102.243:17379 fd=111 name=*redacted* age=9 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=391649 tot-net-out=8078 tot-cmds=348
		id=381 addr=10.67.29.176:58460 laddr=10.92.102.243:17379 fd=33 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=8850173 tot-net-out=45365 tot-cmds=7821
		id=393 addr=10.67.191.35:53244 laddr=10.92.102.243:17379 fd=44 name=*redacted* age=69 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3472658 tot-net-out=21633 tot-cmds=3070
		id=394 addr=10.67.58.94:48398 laddr=10.92.102.243:17379 fd=45 name=*redacted* age=69 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3946905 tot-net-out=23728 tot-cmds=3489
		id=465 addr=10.67.6.196:56832 laddr=10.92.102.243:17379 fd=83 name=*redacted* age=40 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=10 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4164246 tot-net-out=24733 tot-cmds=3681
		id=432 addr=10.65.149.217:37430 laddr=10.92.102.243:17379 fd=68 name=*redacted* age=56 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=5 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5455734 tot-net-out=30416 tot-cmds=4822
		id=457 addr=10.66.99.98:42858 laddr=10.92.102.243:17379 fd=79 name=*redacted* age=42 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3070824 tot-net-out=19900 tot-cmds=2715
		id=458 addr=10.66.72.138:48836 laddr=10.92.102.243:17379 fd=80 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1993264 tot-net-out=15140 tot-cmds=1763
		id=509 addr=10.67.182.89:49806 laddr=10.92.102.243:17379 fd=97 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6354 tot-cmds=2
		id=459 addr=10.66.78.181:54434 laddr=10.92.102.243:17379 fd=81 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1190773 tot-net-out=11595 tot-cmds=1054
		id=460 addr=10.66.130.35:34676 laddr=10.92.102.243:17379 fd=82 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2092888 tot-net-out=15582 tot-cmds=1851
		id=529 addr=10.67.58.94:55048 laddr=10.92.102.243:17379 fd=112 name=*redacted* age=8 idle=8 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6349 tot-cmds=2
		id=530 addr=10.67.191.35:42646 laddr=10.92.102.243:17379 fd=113 name=*redacted* age=8 idle=8 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6351 tot-cmds=2
		id=390 addr=10.67.166.249:37934 laddr=10.92.102.243:17379 fd=41 name=*redacted* age=70 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=8655520 tot-net-out=44524 tot-cmds=7649
		id=396 addr=10.67.29.176:58470 laddr=10.92.102.243:17379 fd=46 name=*redacted* age=69 idle=11 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2344153 tot-net-out=16648 tot-cmds=2073
		id=416 addr=10.65.220.14:47530 laddr=10.92.102.243:17379 fd=59 name=*redacted* age=60 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3195332 tot-net-out=20432 tot-cmds=2825
		id=510 addr=10.67.88.138:54028 laddr=10.92.102.243:17379 fd=98 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=511 addr=10.67.58.94:55042 laddr=10.92.102.243:17379 fd=99 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=531 addr=10.67.188.162:54966 laddr=10.92.102.243:17379 fd=114 name=*redacted* age=8 idle=8 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6349 tot-cmds=2
		id=532 addr=10.67.21.98:44178 laddr=10.92.102.243:17379 fd=115 name=*redacted* age=8 idle=8 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6349 tot-cmds=2
		id=512 addr=10.67.188.162:50590 laddr=10.92.102.243:17379 fd=100 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=513 addr=10.67.91.42:50292 laddr=10.92.102.243:17379 fd=101 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=514 addr=10.67.29.176:34704 laddr=10.92.102.243:17379 fd=102 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=502 addr=10.66.41.66:48724 laddr=10.92.102.243:17379 fd=93 name=*redacted* age=15 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1413746 tot-net-out=12594 tot-cmds=1251
		id=467 addr=10.67.182.89:59352 laddr=10.92.102.243:17379 fd=84 name=*redacted* age=39 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1306229 tot-net-out=12109 tot-cmds=1156
		id=391 addr=10.67.141.254:50944 laddr=10.92.102.243:17379 fd=42 name=*redacted* age=70 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5889193 tot-net-out=32305 tot-cmds=5205
		id=405 addr=10.65.192.132:49442 laddr=10.92.102.243:17379 fd=48 name=*redacted* age=61 idle=26 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2787831 tot-net-out=18630 tot-cmds=2465
		id=424 addr=10.65.100.189:42200 laddr=10.92.102.243:17379 fd=60 name=*redacted* age=57 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=10 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3856333 tot-net-out=23354 tot-cmds=3409
		id=515 addr=10.67.21.98:44162 laddr=10.92.102.243:17379 fd=103 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6351 tot-cmds=2
		id=516 addr=10.67.166.249:37806 laddr=10.92.102.243:17379 fd=104 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=425 addr=10.65.192.132:49454 laddr=10.92.102.243:17379 fd=61 name=*redacted* age=57 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5072004 tot-net-out=28724 tot-cmds=4483
		id=472 addr=10.66.13.58:58702 laddr=10.92.102.243:17379 fd=85 name=*redacted* age=39 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2865968 tot-net-out=19000 tot-cmds=2534
		id=406 addr=10.65.135.164:56570 laddr=10.92.102.243:17379 fd=49 name=*redacted* age=61 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3234974 tot-net-out=20605 tot-cmds=2860
		id=407 addr=10.65.87.134:56500 laddr=10.92.102.243:17379 fd=50 name=*redacted* age=61 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=7656043 tot-net-out=40135 tot-cmds=6766
		id=382 addr=10.67.6.196:36810 laddr=10.92.102.243:17379 fd=34 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6653211 tot-net-out=35660 tot-cmds=5880
		id=517 addr=10.67.191.35:42634 laddr=10.92.102.243:17379 fd=105 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6351 tot-cmds=2
		id=383 addr=10.67.166.249:37924 laddr=10.92.102.243:17379 fd=35 name=*redacted* age=71 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2585265 tot-net-out=17693 tot-cmds=2286
		id=387 addr=10.67.188.162:33618 laddr=10.92.102.243:17379 fd=39 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=2666 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4501511 tot-net-out=26167 tot-cmds=3979
		id=482 addr=10.65.211.39:52862 laddr=10.92.102.243:17379 fd=91 name=*redacted* age=31 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=10 obl=0 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4035170 tot-net-out=24174 tot-cmds=3567
		id=473 addr=10.66.130.35:51028 laddr=10.92.102.243:17379 fd=86 name=*redacted* age=39 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1500905 tot-net-out=12970 tot-cmds=1328
		id=474 addr=10.66.182.20:48992 laddr=10.92.102.243:17379 fd=87 name=*redacted* age=39 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2212828 tot-net-out=16115 tot-cmds=1957
		id=475 addr=10.66.72.138:48856 laddr=10.92.102.243:17379 fd=88 name=*redacted* age=39 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1641256 tot-net-out=13591 tot-cmds=1452
		id=503 addr=10.66.99.98:48270 laddr=10.92.102.243:17379 fd=94 name=*redacted* age=15 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1037964 tot-net-out=10937 tot-cmds=919
		id=384 addr=10.67.58.94:48392 laddr=10.92.102.243:17379 fd=36 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6813970 tot-net-out=36374 tot-cmds=6022
		id=505 addr=10.66.20.124:45436 laddr=10.92.102.243:17379 fd=95 name=*redacted* age=12 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1006266 tot-net-out=10796 tot-cmds=891
		id=397 addr=10.67.21.98:58478 laddr=10.92.102.243:17379 fd=47 name=*redacted* age=69 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4322706 tot-net-out=25388 tot-cmds=3821
		id=408 addr=10.65.149.217:37424 laddr=10.92.102.243:17379 fd=51 name=*redacted* age=61 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4887555 tot-net-out=27906 tot-cmds=4320
		id=524 addr=10.67.6.196:42026 laddr=10.92.102.243:17379 fd=110 name=*redacted* age=9 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6351 tot-cmds=2
		id=409 addr=10.65.5.223:39342 laddr=10.92.102.243:17379 fd=52 name=*redacted* age=61 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=10 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6842258 tot-net-out=36541 tot-cmds=6047
		id=410 addr=10.65.188.26:45954 laddr=10.92.102.243:17379 fd=53 name=*redacted* age=61 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2058933 tot-net-out=15411 tot-cmds=1821
		id=476 addr=10.66.106.14:38870 laddr=10.92.102.243:17379 fd=89 name=*redacted* age=39 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3651456 tot-net-out=22471 tot-cmds=3228
		id=447 addr=10.66.41.66:40188 laddr=10.92.102.243:17379 fd=69 name=*redacted* age=42 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2381495 tot-net-out=16856 tot-cmds=2106
		id=448 addr=10.66.208.6:36068 laddr=10.92.102.243:17379 fd=70 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1564293 tot-net-out=13246 tot-cmds=1384
		id=449 addr=10.66.13.58:58688 laddr=10.92.102.243:17379 fd=71 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1882355 tot-net-out=14652 tot-cmds=1665
		id=426 addr=10.65.149.108:51152 laddr=10.92.102.243:17379 fd=62 name=*redacted* age=57 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5219150 tot-net-out=29374 tot-cmds=4613
		id=386 addr=10.67.182.89:48122 laddr=10.92.102.243:17379 fd=38 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=10374847 tot-net-out=52112 tot-cmds=9168
		id=477 addr=10.66.208.6:36074 laddr=10.92.102.243:17379 fd=90 name=*redacted* age=38 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1543908 tot-net-out=13161 tot-cmds=1366
		id=518 addr=10.67.141.254:41854 laddr=10.92.102.243:17379 fd=106 name=*redacted* age=10 idle=10 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6353 tot-cmds=2
		id=380 addr=10.67.191.35:53240 laddr=10.92.102.243:17379 fd=32 name=*redacted* age=71 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6911270 tot-net-out=36799 tot-cmds=6108
		id=114 addr=10.96.74.166:33294 laddr=10.92.102.243:17379 fd=28 name=*redacted* age=315 idle=0 flags=S capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=20504 tot-mem=42520 events=r cmd=replconf user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=802107 tot-net-out=271854320 tot-cmds=20252
		id=115 addr=10.88.251.15:57314 laddr=10.92.102.243:17379 fd=29 name=*redacted* age=315 idle=0 flags=S capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=1 omem=20504 tot-mem=42520 events=r cmd=replconf user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=802106 tot-net-out=271854320 tot-cmds=20252
		id=450 addr=10.66.21.230:48696 laddr=10.92.102.243:17379 fd=72 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4053295 tot-net-out=24242 tot-cmds=3583
		id=451 addr=10.66.18.97:46010 laddr=10.92.102.243:17379 fd=73 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3426204 tot-net-out=21470 tot-cmds=3029
		id=520 addr=10.67.88.138:52212 laddr=10.92.102.243:17379 fd=107 name=*redacted* age=9 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6349 tot-cmds=2
		id=521 addr=10.67.141.254:41868 laddr=10.92.102.243:17379 fd=108 name=*redacted* age=9 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6349 tot-cmds=2
		id=488 addr=10.65.87.134:46750 laddr=10.92.102.243:17379 fd=92 name=*redacted* age=26 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1128514 tot-net-out=11334 tot-cmds=999
		id=389 addr=10.67.88.138:43398 laddr=10.92.102.243:17379 fd=40 name=*redacted* age=70 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5317632 tot-net-out=29779 tot-cmds=4700
		id=427 addr=10.65.220.14:47538 laddr=10.92.102.243:17379 fd=63 name=*redacted* age=57 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5090089 tot-net-out=28805 tot-cmds=4499
		id=428 addr=10.65.135.164:56578 laddr=10.92.102.243:17379 fd=64 name=*redacted* age=57 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4300044 tot-net-out=25315 tot-cmds=3801
		id=411 addr=10.65.149.108:51144 laddr=10.92.102.243:17379 fd=54 name=*redacted* age=61 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1920848 tot-net-out=14801 tot-cmds=1699
		id=522 addr=10.67.166.249:37810 laddr=10.92.102.243:17379 fd=109 name=*redacted* age=9 idle=9 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=info user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=32 tot-net-out=6351 tot-cmds=2
		id=412 addr=10.65.211.39:53586 laddr=10.92.102.243:17379 fd=55 name=*redacted* age=61 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3677459 tot-net-out=22561 tot-cmds=3251
		id=452 addr=10.66.106.14:38864 laddr=10.92.102.243:17379 fd=74 name=*redacted* age=42 idle=12 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=1536 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2036296 tot-net-out=15332 tot-cmds=1801
		id=453 addr=10.66.173.113:37298 laddr=10.92.102.243:17379 fd=75 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3949165 tot-net-out=23782 tot-cmds=3491
		id=413 addr=10.65.120.231:56734 laddr=10.92.102.243:17379 fd=56 name=*redacted* age=60 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=10 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=5026684 tot-net-out=28521 tot-cmds=4443
		id=506 addr=10.66.21.230:51614 laddr=10.92.102.243:17379 fd=96 name=*redacted* age=12 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=1010810 tot-net-out=10814 tot-cmds=895
		id=414 addr=10.65.100.189:42194 laddr=10.92.102.243:17379 fd=57 name=*redacted* age=60 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4124613 tot-net-out=24536 tot-cmds=3646
		id=377 addr=10.67.91.42:50160 laddr=10.92.102.243:17379 fd=27 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=1106 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=23146 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=9677602 tot-net-out=48980 tot-cmds=8552
		id=429 addr=10.65.188.26:45960 laddr=10.92.102.243:17379 fd=65 name=*redacted* age=57 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4144953 tot-net-out=24630 tot-cmds=3664
		id=392 addr=10.67.188.162:38080 laddr=10.92.102.243:17379 fd=43 name=*redacted* age=69 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6620379 tot-net-out=35538 tot-cmds=5851
		id=454 addr=10.66.182.20:48988 laddr=10.92.102.243:17379 fd=76 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2423380 tot-net-out=17040 tot-cmds=2143
		id=455 addr=10.66.78.181:54430 laddr=10.92.102.243:17379 fd=77 name=*redacted* age=42 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=2191364 tot-net-out=16015 tot-cmds=1938
		id=378 addr=10.67.21.98:58464 laddr=10.92.102.243:17379 fd=30 name=*redacted* age=71 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=6907871 tot-net-out=36778 tot-cmds=6105
		id=385 addr=10.67.141.254:52666 laddr=10.92.102.243:17379 fd=37 name=*redacted* age=71 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4473217 tot-net-out=26040 tot-cmds=3954
		id=430 addr=10.65.120.231:48052 laddr=10.92.102.243:17379 fd=66 name=*redacted* age=56 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=3079889 tot-net-out=19924 tot-cmds=2723
		id=431 addr=10.65.5.223:36450 laddr=10.92.102.243:17379 fd=67 name=*redacted* age=56 idle=1 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=973437 tot-net-out=10619 tot-cmds=862
		id=379 addr=10.67.88.138:35978 laddr=10.92.102.243:17379 fd=31 name=*redacted* age=71 idle=0 flags=r capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22016 events=r cmd=set user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=4483354 tot-net-out=26068 tot-cmds=3963
		id=536 addr=10.65.120.231:47464 laddr=10.92.102.243:17379 fd=116 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=NULL user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=0 tot-net-out=0 tot-cmds=0
		id=537 addr=10.65.135.164:40942 laddr=10.92.102.243:17379 fd=117 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=NULL user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=0 tot-net-out=0 tot-cmds=0
		id=538 addr=10.65.5.223:53738 laddr=10.92.102.243:17379 fd=118 name=*redacted* age=0 idle=0 flags=N capa= db=0 sub=0 psub=0 ssub=0 multi=-1 watch=0 qbuf=0 qbuf-free=0 argv-mem=0 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=16896 events=r cmd=NULL user=*redacted* redir=-1 resp=2 lib-name= lib-ver= tot-net-in=0 tot-net-out=0 tot-cmds=0
		
		------ MODULES INFO OUTPUT ------
		
		------ CONFIG DEBUG OUTPUT ------
		lazyfree-lazy-expire yes
		replica-read-only yes
		list-compress-depth 0
		client-query-buffer-limit 1gb
		lazyfree-lazy-server-del yes
		slave-read-only yes
		repl-diskless-sync yes
		proto-max-bulk-len 512mb
		io-threads 6
		debug-context ""
		lazyfree-lazy-user-del yes
		repl-diskless-load on-empty-db
		lazyfree-lazy-eviction yes
		activedefrag yes
		lazyfree-lazy-user-flush yes
		dual-channel-replication-enabled yes
		sanitize-dump-payload no
		import-mode no
		
		------ FAST MEMORY TEST ------
		19:M 25 Mar 2025 15:23:39.022 # Bio worker thread #0 terminated
		19:M 25 Mar 2025 15:23:39.022 # Bio worker thread #1 terminated
		19:M 25 Mar 2025 15:23:39.022 # Bio worker thread #2 terminated
		19:M 25 Mar 2025 15:23:39.022 * IO thread(tid:281473313357784) terminated
		19:M 25 Mar 2025 15:23:39.022 * IO thread(tid:281473313210328) terminated
		19:M 25 Mar 2025 15:23:39.022 * IO thread(tid:281473313062872) terminated
		19:M 25 Mar 2025 15:23:39.022 * IO thread(tid:281473312915416) terminated

### Additional information

We ran this docker image: docker.io/valkey/valkey:unstable-alpine3.21@sha256:975d1d97c6321a28e2d1fa0d124197bb0be64a662a7c2096699ed20dd36827a5

Each node in the cluster had traffic of SET commands about 4K QPS
No crashes without the traffic.
Also Crashes are pretty stable. It crashes pretty much guaranteed in 10-15 minutes after starting the traffic.

We also tested image 8.0.2 and we didn't observe any crashes: docker.io/valkey/valkey:8.0.2@sha256:08ffc65e795d6a2082543431b07756816928816c1704141043a62dfc5ed36d8b

### PR DESCRIPTION
**Pull request by uriyage**
Fix https://github.com/valkey-io/valkey/issues/1883

The issue arises from a missing memory release fence, which can cause the main thread to see the updated client's IO read state (`CLIENT_COMPLETED_IO`) but not the updated connection flags. In this case, it crashes as the flags are not as expected.

Following @skolosov-snap instructions I was able to consistently reproduce the issue on ARM instances by generating sufficient load to invoke the IO threads while constantly creating new connections to trigger the accept flow. I've validated that no crashes occur with this fix.

I didn't write a regression test for the fix since reproduction is difficult and flaky.

### CODE REVIEW

**Comment by ranshid** [comment]
@zuiderkwast AFAIK this was only introduced in 8.1 as part of https://github.com/valkey-io/valkey/pull/1338 so I think we can drop the 8.0 backport

**Review by ranshid — APPROVED** [review]
LGTM.

@uriyage will we observe some performance degradations for connections establishment? I guess this is better than a crash/bug (as rare as it might be) but just to understand

**Review by ovaiskhansc — APPROVED** [review]
Thanks @uriyage for the fix

File: src/io_threads.c [hunk 1]
```diff
@@ -574,6 +574,7 @@ void trySendPollJobToIOThreads(void) {
 static void ioThreadAccept(void *data) {
     client *c = (client *)data;
     connAccept(c->conn, NULL);
+    atomic_thread_fence(memory_order_release);
     c->io_read_state = CLIENT_COMPLETED_IO;
```
Comment (zuiderkwast) [inline src/io_threads.c:578]: Why not do the fence after updating `c->io_read_state` to make `processIOThreadsReadDone` see that it's completed ASAP? There's a risk the read state will be seen but not the flags... :thinking: So why is `io_read_state` marked as volatile and not as atomic?

**Review by zuiderkwast — APPROVED** [review]
LGTM. Just a question.

File: src/io_threads.c (hunk 1 above)
Comment (zuiderkwast) [reply src/io_threads.c:578]: > Why not do the fence after updating `c->io_read_state` to make `processIOThreadsReadDone` see that it's completed ASAP? There's a risk the read state will be seen but not the flags... So why is `io_read_state` marked as volatile rather than atomic?

Comment (uriyage) [reply src/io_threads.c:578]: `io_read_state` is not marked as atomic for performance reasons because we read it in many places in the main thread, mostly just as sanity checks. It is marked as volatile to avoid incorrect compilation time optimizations.
As we activate IO threads only under load, the possibility that it may take a bit longer  for the main thread to get the updated results is amortized and we didn't observe a degradation because of  that. 
In any way, we intend to use MPSC queue for the IO threads to signal the main thread when a job is done.

**Comment by uriyage** [comment]
> LGTM.
> 
> @uriyage will we observe some performance degradations for connections establishment? I guess this is better than a crash/bug (as rare as it might be) but just to understand

@ranshid, Thanks, I didn't observe and degradation for connection establishment.

File: src/io_threads.c (hunk 1 above)
Comment (zuiderkwast) [reply src/io_threads.c:578]: > `io_read_state` is not marked as atomic for performance reasons because we read it in many places in the main thread, mostly just as sanity checks. It is marked as volatile to avoid incorrect compilation time optimizations.

Thanks, it could be useful to add a code comment about this in server.h at the declaration of these volatile variables. Otherwise I will forget it very soon and ask you again in another PR. ;)

> we intend to use MPSC queue for the IO threads to signal the main thread when a job is done

Interesting! Are you working on this now?
