### PR TITLE
Fix loading AOF files from future Valkey versions

### LINKED ISSUE #2888: [BUG] valkey 8.1 fails to read valkey 9.0 aof base files in rdb format
**Describe the bug**

Valkey 8.1 is configured with:
save ""
appendonly yes
rdb-version-check relaxed

After upgrading the server to 9.0 and issuing a `bgrewriteaof` the base rdb file in the appendonlydir directory is now in valkey 9.0 format:

cat appendonlydir/appendonly.aof.3.base.rdb
VALKEY080�
valkey-ver9.0.0�

If I now stop valkey 9 and restart 8.1.4, the server fails to start:

26017:M 01 Dec 2025 13:34:32.577 # Bad file format reading the append only file appendonly.aof.3.base.rdb: make a backup of your AOF file, then use ./valkey-check-aof --fix <filename.manifest>

**Expected behavior**

The same test configured without aof, but only using rdb files works due to the relaxed rdb-version-check flag.

It also works if I set `aof-use-rdb-preamble no` in the config.

I expected this would work with with aof as well with rdb preamble due to the relaxed rdb-version-check flag.

**Additional information**

The problem seems to stem from this code in `loadSingleAppendOnlyFile` in 8.1 doesn't account for the signature change of the rdb files in 9.0 and doesn't detect it as an rdb file where the `rdb-version-check relaxed` flag could apply.

```
    /* Check if the AOF file is in RDB format (it may be RDB encoded base AOF
     * or old style RDB-preamble AOF). In that case we need to load the RDB file
     * and later continue loading the AOF tail if it is an old style RDB-preamble AOF. */
    char sig[5]; /* "REDIS" */
    if (fread(sig, 1, 5, fp) != 5 || memcmp(sig, "REDIS", 5) != 0) {
        /* Not in RDB format, seek back at 0 offset. */
        if (fseek(fp, 0, SEEK_SET) == -1) goto readerr;
    } else {
        /* RDB format. Pass loading the RDB functions. */
```

The check in 9.0 looks for REDIS or VALKEY

```
    char sig[6]; /* "REDIS" or "VALKEY" */
    if (fread(sig, 1, 6, fp) != 6 || (memcmp(sig, "REDIS0", 6) != 0 && memcmp(sig, "VALKEY", 6) != 0)) {
        /* Not in RDB format, seek back at 0 offset. */
        if (fseek(fp, 0, SEEK_SET) == -1) goto readerr;
    } else {
        /* RDB format. Pass loading the RDB functions. */
```

### PR DESCRIPTION
**Pull request by zuiderkwast**
This allows loading an AOF file in Valkey 8.1 with the config 'rdb-version-check' set to 'relaxed', when the AOF file is created by a future Valkey version.

Fixes #2888.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
The CI failures are caused by other problems in the 8.1 branch. We will backport fixes for them in #2902.

**Review by enjoy-binbin — APPROVED** [review]

File: src/aof.c [hunk 1]
```diff
@@ -1431,8 +1431,8 @@ int loadSingleAppendOnlyFile(char *filename) {
     /* Check if the AOF file is in RDB format (it may be RDB encoded base AOF
      * or old style RDB-preamble AOF). In that case we need to load the RDB file
      * and later continue loading the AOF tail if it is an old style RDB-preamble AOF. */
-    char sig[5]; /* "REDIS" */
-    if (fread(sig, 1, 5, fp) != 5 || memcmp(sig, "REDIS", 5) != 0) {
+    char sig[6]; /* "REDIS" or "VALKEY" */
+    if (fread(sig, 1, 6, fp) != 6 || (memcmp(sig, "REDIS0", 6) != 0 && memcmp(sig, "VALKEY", 6) != 0)) {
```
Comment (flori) [inline src/aof.c:1435]: Don't we need to initialize these arrays with 0s and the check for "REDIS\0" for this to work?

Comment (zuiderkwast) [reply src/aof.c:1435]: No, here we read exactly 6 characters from the file and compare them. None of them will not be `\0`. The magic word is followed by the zero-padded RDB version number (e.g. "REDIS0011" for RDB 11 or "VALKEY080" for Valkey's RDB 80) and it always starts with zero for the REDIS RDB versions we support.

Comment (flori) [reply src/aof.c:1435]: Ah, ok. It was a stab in the dark b/c I had this issue with 8.1.5 crashing: https://github.com/valkey-io/valkey/issues/2917 Apparently this file had been already converted to valkey 9.0.0 format.
