### PR TITLE
Fix the incorrect stdout redirect logic

### LINKED ISSUE #2224: [BUG]Build Failure in Alpine-Linux
**Describe the bug**
Build Failure in Alpine-Linux

Commit that might have added this: https://github.com/valkey-io/valkey/pull/1743
Failure instance: https://github.com/valkey-io/valkey-container/actions/runs/15694960906/job/44219225483#step:5:739:~:text=valkey%2Dcheck%2Drdb.c,directory%20%27/usr/src/valkey%27
```
valkey-check-rdb.c: In function 'rdbShowGenericInfo':
valkey-check-rdb.c:498:20: error: assignment of read-only variable 'stdout'
  498 |             stdout = fdopen(1, "w");
      |                    ^
make[1]: *** [Makefile:546: valkey-check-rdb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/valkey/src'
make: *** [Makefile:6: all] Error 2
make: Leaving directory '/usr/src/valkey'
```

**To reproduce**

Build on alpine-linux

### PR DESCRIPTION
**Pull request by artikell**
Use the standard `dup2` to redirect `stdout`

Closes #2224
Follow-up of #1743

### CODE REVIEW

File: src/valkey-check-rdb.c [hunk 1]
```diff
@@ -444,13 +444,17 @@ void rdbShowGenericInfo(void) {
...
     if (rdbCheckStats) {
         if (rdbCheckOutput) {
-            stats_fp = freopen(rdbstate.stats_output, "w", stdout);
-            if (stats_fp == NULL) {
-                printf("Cannot open output file: %s\n", rdbstate.stats_output);
+            original_stdout_fd = dup(STDOUT_FILENO);
+            stats_fd = open(rdbstate.stats_output, O_WRONLY | O_CREAT, 0644);
+            if (stats_fd == -1) {
+                fprintf(stderr, "Cannot open output file: '%s': %s\n", rdbstate.stats_output, strerror(errno));
                 exit(0);
```
Comment (enjoy-binbin) [inline src/valkey-check-rdb.c]:
```suggestion
                exit(1);
```

**Comment by enjoy-binbin** [comment]
I added a commit to do the exit(1), please check. At the same time, this commit is also meant to trigger the extra-ci

File: src/valkey-check-rdb.c [hunk 2]
```diff
@@ -444,13 +445,17 @@ void rdbShowGenericInfo(void) {
...
-    FILE *stats_fp = NULL;
+    int stats_fd = -1;
+    int original_stdout_fd = -1;
     if (rdbCheckStats) {
         if (rdbCheckOutput) {
-            stats_fp = freopen(rdbstate.stats_output, "w", stdout);
-            if (stats_fp == NULL) {
-                printf("Cannot open output file: %s\n", rdbstate.stats_output);
-                exit(0);
+            original_stdout_fd = dup(STDOUT_FILENO);
```
Comment (zuiderkwast) [inline src/valkey-check-rdb.c]: I was slightly confused by this variable name. The original stdout fd is actually STDOUT_FILENO. This is a copy AKA duplicate. It's another file descriptor for the same file.

Maybe rename it to `original_stdout_dup` or `saved_stdout`? Not sure if it make any difference.

**Review by zuiderkwast — APPROVED** [review]
LGTM, thanks

File: src/valkey-check-rdb.c (hunk 2 above)
Comment (artikell) [reply src/valkey-check-rdb.c]: I tried searching on GitHub and it seems that `saved_stdout` is used in many places, so I replaced it with `saved_stdout`.
