### PR TITLE
Fix hashtable memory leak and kvstore `overhead_hashtable_lut` assert

### LINKED ISSUE #1657: [test-failure] Unit test failure in test_kvstore.c
https://github.com/valkey-io/valkey/actions/runs/13120508567/job/36605063835

```
[serverAssert - unit/../kvstore.c:329] - kvs->overhead_hashtable_lut == 0
```

### PR DESCRIPTION
**Pull request by artikell**
When releasing a kvstore and its hashtables, if it is still rehashed and table 0 has no data, it may still have allocated buckets that were not released. This lead to allocated hashtable buckets being leaked. This looked like missed statistics but it was actually a memory leak.

fix: https://github.com/valkey-io/valkey/issues/1657

### CODE REVIEW

**Comment by artikell** [comment]
@zuiderkwast Please help me review it, maybe you have a better way to fix it.

File: src/unit/test_kvstore.c [hunk 1]
```diff
@@ -70,6 +70,13 @@ int test_kvstoreIteratorRemoveAllKeysNoDeleteEmptyHashtable(int argc, char **arg
     UNUSED(argv);
     UNUSED(flags);
 
+    uint8_t seed[16];
+    int cycle = 17;
+    for (unsigned int i = 0; i < sizeof(seed); i++) {
+        seed[i] = (i + cycle) % 0xFF;
+    }
+    hashtableSetHashFunctionSeed(seed);
+
```
Comment (zuiderkwast) [inline src/unit/test_kvstore.c]: It's a good idea to seed the hash function, but why not use `getRandomBytes` as we do in test_hashtable.c?

File: src/hashtable.c [hunk 2]
```diff
@@ -1032,31 +1032,29 @@ void hashtableEmpty(hashtable *ht, void(callback)(hashtable *)) {
         if (ht->bucket_exp[table_index] < 0) {
             continue;
         }
-        if (ht->used[table_index] > 0) {
```
Comment (zuiderkwast) [inline src/hashtable.c:1035]: Can we use `ht->used[table_index] > 0 || ht->child_buckets[table_index] > 0`?

`ht->child_buckets[table_index]` is the number of allocated child buckets in the table that we need to free.

**Review by zuiderkwast — COMMENTED** [review]
Awesome! You found it!

I realized the diff is small if I review it with [whitespace changes hidden](https://github.com/valkey-io/valkey/pull/1750/files?diff=unified&w=1).

It means we also have a memory leak, right? We don't free the allocated child buckets?

**Comment by rjd15372** [comment]
I'm pretty sure this will also fix the assert errors that I was investigating in today's daily tests:
https://github.com/valkey-io/valkey/actions/runs/13380552486/job/37368256686
https://github.com/valkey-io/valkey/actions/runs/13380552486/job/37368260953

File: src/hashtable.c (hunk 2 above)
Comment (zuiderkwast) [reply src/hashtable.c:1035]: It's still weird that there are empty buckets in a table without any elements. Those should be deleted when the elements are deleted....

Comment (zuiderkwast) [reply src/hashtable.c:1035]: I've spotted something!

`kvstoreIteratorNext` calls `hashtableReinitIterator` to init the same iterator with the next hash table, but it doesn't reset the iterator for the previous hash table, so it leaves rehashing paused.

I think we need this:

```diff
 /* Reinitializes the iterator for the provided hashtable while
  * preserving the flags from its previous initialization. */
 void hashtableReinitIterator(hashtableIterator *iterator, hashtable *ht) {
     iter *iter = iteratorFromOpaque(iterator);
+    hashtableResetIterator(iterator);
     hashtableInitIterator(iterator, ht, iter->flags);
 }
```

File: src/unit/test_kvstore.c (hunk 1 above)
Comment (artikell) [reply src/unit/test_kvstore.c]: In fact, the original logic is a kind of random, so it is difficult to find.

I think this requires a separate test, and we can output the seed

File: src/hashtable.c (hunk 2 above)
Comment (artikell) [reply src/hashtable.c:1035]: Yes, I didn't notice child_buckets, I'll add these two logics

File: src/unit/test_kvstore.c (hunk 1 above)
Comment (artikell) [reply src/unit/test_kvstore.c]: I added a KvstoreConflictHashtableTestType to ensure a high conflict rate

File: src/hashtable.c (hunk 2 above)
Comment (artikell) [reply src/hashtable.c:1035]: There seems to be some problem with adding hashtableResetIterator. Maybe we can check it separately. @zuiderkwast

Comment (zuiderkwast) [reply src/hashtable.c:1035]: Sure, we can do it separately, but I think this might be a big problem. Once kvstore iterates over the hash tables, it leaves rehashing paused on them forever...

What was the problem?

Comment (artikell) [reply src/hashtable.c:1035]: I haven't had time to locate it today, but here are two test results:
https://github.com/valkey-io/valkey/actions/runs/13403931169/job/37440255634
https://github.com/valkey-io/valkey/actions/runs/13403899712/job/37440162349

It causes a crash

Comment (zuiderkwast) [reply src/hashtable.c:1035]: Ok, I see the assert:

```
10180:M 19 Feb 2025 02:08:05.703 # === ASSERTION FAILED ===
10180:M 19 Feb 2025 02:08:05.703 # ==> hashtable.c:1887 'iter->hashtable->pause_rehash >= 0' is not true
```

This means it was reset twice, which unpaused rehashing twice.

Looking at kvstoreIteratorNext again, it calls kvstoreIteratorNextHashtable which resets the iterator, but it seems to miss this for the last hashtable it iterates over. Notice the `return NULL` on the first line:

```c
/* Returns next hash table from the iterator, or NULL if iteration is complete. */
static hashtable *kvstoreIteratorNextHashtable(kvstoreIterator *kvs_it) {
    if (kvs_it->next_didx == -1) return NULL;

    /* The hashtable may be deleted during the iteration process, so here need to check for NULL. */
    if (kvs_it->didx != -1 && kvstoreGetHashtable(kvs_it->kvs, kvs_it->didx)) {
        /* Before we move to the next hashtable, reset the iter of the previous hashtable. */
        hashtableIterator *iter = &kvs_it->di;
        hashtableResetIterator(iter);
        /* In the safe iterator context, we may delete entries. */
        freeHashtableIfNeeded(kvs_it->kvs, kvs_it->didx);
    }

    kvs_it->didx = kvs_it->next_didx;
    kvs_it->next_didx = kvstoreGetNextNonEmptyHashtableIndex(kvs_it->kvs, kvs_it->didx);
    return kvs_it->kvs->hashtables[kvs_it->didx];
}
```

**Review by zuiderkwast — APPROVED** [review]
Nice, this fixes the memory leak.

There seems to be a problem with iterator not being reset properly which I think leads to rehashing being paused forever, which is quite serious if this is true. We can try to think about it but otherwise I'll merge this later today.
