### PR TITLE
Fix accounting for dual channel RDB bytes in replication stats

### LINKED ISSUE #2545: [BUG] Dual channel RDB bytes not included in stats when diskless sync is used
**Describe the bug**

Even when the snapshot is non-zero, total_net_repl_input_bytes will not include the snapshot bytes.

**To reproduce**

```
# Create primary
src/valkey-server --dual-channel-replication-enabled yes --repl-diskless-sync yes &
# Fill with some content
src/valkey-benchmark -n 100 -r 100 -t set
# Create replica
src/valkey-server --port 6380 --replicaof 127.0.0.1 6379 --repl-diskless-sync yes --repl-diskless-load swapdb --dual-channel-replication-enabled yes
# Look at the INFO
src/valkey-cli INFO
```

You should see:
```
total_net_repl_output_bytes:0
```

But if you do so with dual-channel disabled:

```
# Create primary
src/valkey-server --repl-diskless-sync yes &
# Fill with some content
src/valkey-benchmark -n 100 -r 100 -t set
# Create replica
src/valkey-server --port 6380 --replicaof 127.0.0.1 6379 --repl-diskless-sync yes --repl-diskless-load swapdb
# Look at the INFO
src/valkey-cli INFO
```

You should see something:

```
total_net_repl_output_bytes:1723
```

**Expected behavior**

Users will expect that all transmitted bytes would be shown in the INFO stats.

**Additional information**

Since there is no parent <-> child piping of the RDB contents, the parent process cannot record the networking stats directly. The child process should probably report these through the `sendChildInfo` pipe

### PR DESCRIPTION
**Pull request by sarthakaggarwal97**
Resolves #2545 

Followed the steps to reproduce the issue, and was able to get non-zero `total_net_repl_output_bytes`.

```
(base) ~/workspace/valkey git:[fix-bug-2545]
src/valkey-cli INFO | grep total_net_repl_output_bytes
total_net_repl_output_bytes:1788
```

### CODE REVIEW

File: src/rio.c [hunk 1]
```diff
@@ -564,6 +564,9 @@ static size_t rioConnsetWrite(rio *r, const void *buf, size_t len) {
                     break;
                 }
                 nwritten += retval;
+                if (server.in_fork_child) {
+                    server.stat_net_repl_output_bytes = retval;
```
Comment (murphyjacob4) [inline src/rio.c]: Instead of using the stat, and forcing rio to be coupled to this implementation detail - can we just report the processed_bytes already tracked in `struct rio`?

https://github.com/valkey-io/valkey/blob/9b11d3d9edf6b1f1f18976305c0923c5aad60297/src/rio.h#L68-L69

File: src/childinfo.c [hunk 2]
```diff
@@ -129,6 +129,8 @@ void updateChildInfo(childInfoType information_type, size_t cow, monotime cow_up
         server.stat_rdb_cow_bytes = server.stat_current_cow_peak;
     } else if (information_type == CHILD_INFO_TYPE_MODULE_COW_SIZE) {
         server.stat_module_cow_bytes = server.stat_current_cow_peak;
+    } else if (information_type == CHILD_INFO_TYPE_REPL_OUTPUT_BYTES) {
+        server.stat_net_repl_output_bytes += (long long)keys;
```
Comment (murphyjacob4) [inline src/childinfo.c]: It is the existing state - but the updateChildInfo method signature seems to be very coupled to a specific type of info report (COW, # of keys, % progress)

Would it make sense to update the child_info_data struct:

https://github.com/valkey-io/valkey/blob/9b11d3d9edf6b1f1f18976305c0923c5aad60297/src/childinfo.c#L34-L40

Something like:

```
typedef struct {
    size_t cow;
    monotime cow_updated;
} cowChildInfo;

typedef struct {
    size_t keys;
    double progress;
} progressChildInfo;

typedef struct {
    size_t output_bytes;
} replChildInfo;

typedef union {
    cowChildInfo cow;
    progressChildInfo progress;
    replChildInfo repl;
} childInfoContents;

typedef struct {
    childInfoType information_type; /* Type of information */
    childInfoContents contents;
} child_info_data;
```

For this PR - I think at the very least it would make sense to add a new field to child_info_data and not overload `keys`. WDYT?

**Review by murphyjacob4 — COMMENTED** [review]
Thanks for picking this up! Since it is a bug fix - we should mark it as needing backport.

Can we also clarify the exact behavior change in the title, so it will be clear in the changelog? Something like:

Fix accounting for dual channel RDB bytes in replication stats

File: src/rio.c (hunk 1 above)
Comment (sarthakaggarwal97) [reply src/rio.c]: yeah that's a good idea! I have made the change.

File: src/childinfo.c (hunk 2 above)
Comment (sarthakaggarwal97) [reply src/childinfo.c]: Even I wasn't a fan of overloading, but I wasn't sure about adding a new field I guess. The change looks much cleaner now though.

**Comment by sarthakaggarwal97** [comment]
> we should mark it as needing backport

@murphyjacob4 how do we mark this? I don't see a backport label that I can add somehow.

**Comment by Nikhil-Manglore** [comment]
> > we should mark it as needing backport
> 
> @murphyjacob4 how do we mark this? I don't see a backport label that I can add somehow.

Under the projects section I think you can select the versions we want to backport it to. Then in that project you can move it to the "to be backported" section.

**Review by ranshid — APPROVED** [review]
LGTM

**Comment by sarthakaggarwal97** [comment]
Thanks @ranshid for reviewing! 
@murphyjacob4 @madolson @naglera please take a look once you guys have some time.

File: src/childinfo.c [hunk 3]
```diff
@@ -64,7 +65,7 @@ void closeChildInfoPipe(void) {
 }
 
 /* Send save data to parent. */
-void sendChildInfoGeneric(childInfoType info_type, size_t keys, double progress, char *pname) {
+void sendChildInfoGeneric(childInfoType info_type, size_t keys, size_t output, double progress, char *pname) {
```
Comment (murphyjacob4) [inline src/childinfo.c]:
```suggestion
void sendChildInfoGeneric(childInfoType info_type, size_t keys, size_t repl_output_bytes, double progress, char *pname) {
```

WDYT? I feel like it probably makes sense to just give it a dedicated field for now (as I mentioned - this child process info function needs some general refactoring)

**Review by murphyjacob4 — APPROVED** [review]
LGTM with one small comment

File: src/childinfo.c (hunk 3 above)
Comment (sarthakaggarwal97) [reply src/childinfo.c]: sure. I don't have a strong opinion about this, dedicated field kind of takes away the scope for overloading in the future, but I guess it can be refactored accordingly. I'll make this change

Comment (sarthakaggarwal97) [reply src/childinfo.c]: Made the change and build is green :D

**Comment by zuiderkwast** [comment]
~~I'm preparing to release 8.0.6, but I can't cherry-pick this one to the 8.0 branch. There is a nasty merge conflict because of the refactoring in #2533. I'm going to skip this backport for now.~~

~~If we need it in 8.0, can you (@sarthakaggarwal97 or @enjoy-binbin) make a backporting PR for this one?~~

This one was already backported! It was done in #2616.

It was still in the `To be backported` column in the project board. That's was my confusion.
