### PR TITLE
Fix crash when freeing newly created node when nodeIp2String fail

### LINKED ISSUE #1527: Assertion 'dictDelete(server.cluster->nodes, nodename) == DICT_OK' is not true
```
### Starting server for test Handshake eventually succeeds after node handshake timeout on both sides with inconsistent view of the cluster in tests/unit/cluster/cluster-reliable-meet.tcl

...

17128:M 08 Jan 2025 10:51:44.061 # === ASSERTION FAILED ===
17128:M 08 Jan 2025 10:51:44.061 # ==> cluster_legacy.c:1693 'dictDelete(server.cluster->nodes, nodename) == DICT_OK' is not true

------ STACK TRACE ------

17128 valkey-server *
src/valkey-server 127.0.0.1:28627 [cluster][0x4ebdc4]
src/valkey-server 127.0.0.1:28627 [cluster][0x4e81d2]
src/valkey-server 127.0.0.1:28627 [cluster](clusterReadHandler+0x268)[0x4e8618]
/__w/valkey/valkey/src/valkey-tls.so(+0xb278)[0x7f109480b278]
src/valkey-server 127.0.0.1:28627 [cluster](aeMain+0x89)[0x592b09]
src/valkey-server 127.0.0.1:28627 [cluster](main+0x4b3)[0x453e23]
/lib64/libc.so.6(__libc_start_main+0xe5)[0x7f10958bf7e5]
src/valkey-server 127.0.0.1:28627 [cluster](_start+0x2e)[0x454a5e]
```

https://github.com/valkey-io/valkey/actions/runs/12669045432/job/35305718835?pr=1427

### PR DESCRIPTION
**Pull request by enjoy-binbin**
In #1441, we found a assert, and decided remove this assert and instead just free the newly created node and close the link, since if we cannot get the IP from the link it probably means the connection was closed.
```
=== VALKEY BUG REPORT START: Cut & paste starting from here ===
17847:M 19 Dec 2024 00:15:58.021 # === ASSERTION FAILED ===
17847:M 19 Dec 2024 00:15:58.021 # ==> cluster_legacy.c:3252 'nodeIp2String(node->ip, link, hdr->myip) == C_OK' is not true

------ STACK TRACE ------

17847 valkey-server *
src/valkey-server 127.0.0.1:27131 [cluster](clusterProcessPacket+0x1304) [0x4e5634]
src/valkey-server 127.0.0.1:27131 [cluster](clusterReadHandler+0x11e) [0x4e59de]
/__w/valkey/valkey/src/valkey-tls.so(+0x2f1e) [0x7f083983ff1e]
src/valkey-server 127.0.0.1:27131 [cluster](aeMain+0x8a) [0x41afea]
src/valkey-server 127.0.0.1:27131 [cluster](main+0x4d7) [0x40f547]
/lib64/libc.so.6(+0x40c8) [0x7f083985a0c8]
/lib64/libc.so.6(__libc_start_main+0x8b) [0x7f083985a18b]
src/valkey-server 127.0.0.1:27131 [cluster](_start+0x25) [0x410ef5]
```

But it also introduces another assert. The reason is that this new node is not added to the cluster nodes dict.
```
17128:M 08 Jan 2025 10:51:44.061 # === ASSERTION FAILED ===
17128:M 08 Jan 2025 10:51:44.061 # ==> cluster_legacy.c:1693 'dictDelete(server.cluster->nodes, nodename) == DICT_OK' is not true

------ STACK TRACE ------

17128 valkey-server *
src/valkey-server 127.0.0.1:28627 [cluster][0x4ebdc4]
src/valkey-server 127.0.0.1:28627 [cluster][0x4e81d2]
src/valkey-server 127.0.0.1:28627 [cluster](clusterReadHandler+0x268)[0x4e8618]
/__w/valkey/valkey/src/valkey-tls.so(+0xb278)[0x7f109480b278]
src/valkey-server 127.0.0.1:28627 [cluster](aeMain+0x89)[0x592b09]
src/valkey-server 127.0.0.1:28627 [cluster](main+0x4b3)[0x453e23]
/lib64/libc.so.6(__libc_start_main+0xe5)[0x7f10958bf7e5]
src/valkey-server 127.0.0.1:28627 [cluster](_start+0x2e)[0x454a5e]
```

This closes #1527.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
@pieturin please also take a look.

**Review by madolson — APPROVED** [review]
Makes sense to me.

File: src/cluster_legacy.c [hunk 1]
```diff
@@ -3254,11 +3260,14 @@ int clusterProcessPacket(clusterLink *link) {
...
+                         * valid IP, the node becomes unusable in the cluster. This failure might be
+                         * due to the connection being closed. To avoid leaving the cluster in an
+                         * inconsistent state, we close the link and free the node. */
+                        serverLog(LL_NOTICE, "Closing link and freeing node due to failure to retrieve IP "
+                                             "from the connection, possibly caused by a closed connection.");
                         freeClusterLink(link);
-                        freeClusterNode(node);
+                        freeClusterNode(node, 0);
                         return 0;
                     }
```
Comment (PingXie) [inline src/cluster_legacy.c]: This change introduces additional state to `freeClusterNode` in a way that might be hard to follow. I'd suggest optimizing for clarity by opting for a slightly less efficient approach (i.e., an extra memcpy) to improve intuitiveness.

```suggestion
char ip_buf[NET_IP_STR_LEN];
if (nodeIp2String(ip_buf, link, hdr->myip) != C_OK) {
    freeClusterLink(link);
    return 0;
}
clusterNode *node = createClusterNode(NULL, CLUSTER_NODE_HANDSHAKE);
memcpy(node->ip, ip_buf, sizeof(ip_buf));
```

Comment (enjoy-binbin) [reply src/cluster_legacy.c]: right! it is much better

**Review by zuiderkwast — APPROVED** [review]

**Review by PingXie — APPROVED** [review]

**Review by pieturin — APPROVED** [review]
LGTM. Thank you for the fix.
