### PR TITLE
Fix `valkey-cli --cluster del-node` for unreachable nodes

### LINKED ISSUE #3208: [BUG][CLI] del-node fails to delete unreachable nodes
**Describe the bug**

The `valkey-cli --cluster del-node` command reports a misleading `[ERR] No such node ID` when attempting to delete unreachable nodes, even though the node clearly exists in the cluster topology.

This is inconsistent with the instance-level `CLUSTER FORGET` command, which successfully removes unreachable nodes. The cluster-level wrapper should provide the same functionality.

**To reproduce**

1. Create a cluster with an unreachable node:

```
91b0f394a6052a8302415097dd9eed909adc0edb 127.0.0.1:7000@17000 myself,master - 0 0 1 connected 0-16383
df0ffd8d6071ed896f3c440925abb6f729de244d 127.0.0.1:7002@17002 slave,fail
```

2. Attempt to delete the failed node:

```
valkey-cli --cluster del-node 127.0.0.1:7000 df0ffd8d6071ed896f3c440925abb6f729de244d
```

3. Observe the error:
```
Could not connect to Valkey at 127.0.0.1:7002: Connection refused
>>> Removing node df0ffd8d6071ed896f3c440925abb6f729de244d from cluster 127.0.0.1:7000
[ERR] No such node ID df0ffd8d6071ed896f3c440925abb6f729de244d
```

**Expected behavior**

The `del-node` command should successfully remove unreachable nodes from the cluster, similar to how instance-level `CLUSTER FORGET` works.

**Workaround**

Manually execute `CLUSTER FORGET <node-id>` on all nodes within the `cluster-blacklist-ttl` period.

### PR DESCRIPTION
**Pull request by yang-z-o**
### Overview

The `valkey-cli --cluster del-node` command fails when attempting to delete unreachable or failed nodes, reporting `No such node ID` even though the node exists in the cluster topology.
The root cause is the command only loads information about reachable nodes, causing the lookup to fail. This PR added a new function for loading all nodes information to solve this.

### Implementation

1. Loading all nodes from gossip:
   - Added `clusterManagerLoadAllInfoFromNode()` that loads both reachable and unreachable nodes from cluster gossip
   - Extracts common logic into `clusterManagerLoadInfoCommon()` with an `include_unreachable` flag
   - Keeps the original `clusterManagerLoadInfoFromNode()` unchanged to avoid affecting existing callers
2. Added success message to be consistent with other cluster commands: `[OK] Node <id> removed from the cluster.`
3. Added test coverage for `del-node` which previously had none.
4. Load slot information from gossip for unreachable nodes in `clusterManagerNodeLoadInfo()`
5. Skip unreachable primaries in `clusterManagerNodeWithLeastReplicas()` 

### Testing
```
./runtest --single unit/cluster/cli

[ok]: del-node: Cannot delete node with slots (9 ms)
[ok]: del-node: Delete reachable node without slots (23 ms)
[ok]: del-node: Delete unreachable node without slots (1333 ms)
[ok]: del-node: Cannot delete unreachable primary with slots (3368 ms)
```
```
valkey-cli --cluster del-node 127.0.0.1:7000 eb837ea7c48908e5304eafd8b1b3ced57147c448

Could not connect to Valkey at 127.0.0.1:7002: Connection refused
>>> Removing node eb837ea7c48908e5304eafd8b1b3ced57147c448 from cluster 127.0.0.1:7000
>>> Sending CLUSTER FORGET messages to the cluster...
>>> WARNING: Could not connect to node 127.0.0.1:7002, unable to send CLUSTER RESET.
[OK] Node eb837ea7c48908e5304eafd8b1b3ced57147c448 removed from the cluster.
```

### Behavior change

Before
```
$ valkey-cli --cluster del-node <entry-node-ip>:<entry-node-port> <failed-node-id>
Could not connect to Valkey at <target-node-ip>:<target-node-port>: Connection refused
>>> Removing node <id> from cluster <entry-node-ip>:<entry-node-port>
[ERR] No such node ID <id>
```
After
```
$ valkey-cli --cluster del-node <entry-node-ip>:<entry-node-port> <failed-node-id>
Could not connect to Valkey at <target-node-ip>:<target-node-port>: Connection refused
>>> Removing node <id> from cluster <entry-node-ip>:<entry-node-port>
>>> Sending CLUSTER FORGET messages to the cluster...
>>> WARNING: Could not connect to node <target-node-ip>:<target-node-port>, unable to send CLUSTER RESET.
[OK] Node <id> removed from the cluster.
```

### Related Issue
Fixes https://github.com/valkey-io/valkey/issues/3208

### CODE REVIEW

File: src/valkey-cli.c [hunk 1]
```diff
@@ -7591,12 +7618,19 @@ static int clusterManagerCommandDeleteNode(int argc, char **argv) {
...
+                              "deleted node.\n");
+        valkeyReply *r = valkeyCommand(node->context, "CLUSTER RESET %s", "SOFT");
+        success = clusterManagerCheckValkeyReply(node, r, NULL);
+        if (r) freeReplyObject(r);
+    } else {
+        clusterManagerLogWarn(">>> WARNING: Could not connect to node %s:%d, "
+                              "unable to send CLUSTER RESET.\n",
+                              node->ip ? node->ip : "(null)", node->port);
+    }
+    clusterManagerLogOk("[OK] Node %s removed from the cluster.\n", node_id);
```
[the remark this answers is not in the document]
Comment (yang-z-o) [reply src/valkey-cli.c:7653]: Good catch, actually we should exit early when the command fails, to be consistent with existing actions.

File: tests/unit/cluster/cli.tcl [hunk 2]
```diff
@@ -561,4 +561,99 @@ start_multiple_servers 3 [list overrides $base_conf] {
...
+        wait_for_condition 1000 50 {
+            [CI 0 cluster_known_nodes] == 2 &&
+            [CI 1 cluster_known_nodes] == 1 &&
+            [CI 2 cluster_known_nodes] == 2
+        } else {
+            fail "Nodes don't have expected cluster state"
+        }
+    }
+
+    test "del-node: Delete unreachable node without slots" {
```
Comment (sarthakaggarwal97) [inline tests/unit/cluster/cli.tcl:621]: Can we also add a test for unreachable primary that still owns slots? I think this PR may not be able to handle this case since the node loaded from gossip might have 0 slots and be considered as empty node.

File: src/valkey-cli.c [hunk 3]
```diff
@@ -7575,6 +7595,13 @@ static int clusterManagerCommandDeleteNode(int argc, char **argv) {
...
+
+        /* Skip nodes without a valid connection. */
+        if (!n->context) {
+            clusterManagerLogWarn(">>> Skipping %s:%d (not connected)\n", n->ip, n->port);
+            continue;
+        }
+
         if (n->replicate && !strcasecmp(n->replicate, node_id)) {
             // Reconfigure the replica to replicate with some other node
             clusterManagerNode *primary = clusterManagerNodeWithLeastReplicas();
```
Comment (sarthakaggarwal97) [inline src/valkey-cli.c:7621]: I think we should put a reachability check inside this function as well. Currently, it only filters on the `REPLICA` flag. So maybe an unreachable primary can be returned from this function?

**Review by sarthakaggarwal97 — COMMENTED** [review]
Thanks for the change! I added some comments.

File: src/valkey-cli.c (hunk 3 above)
Comment (yang-z-o) [reply src/valkey-cli.c:7621]: Good catch, updated

File: tests/unit/cluster/cli.tcl (hunk 2 above)
Comment (yang-z-o) [reply tests/unit/cluster/cli.tcl:621]: Good point! Added a test for unreachable primary with slots, and fixed it by parsing slot info from gossip.

File: src/valkey-cli.c [hunk 4]
```diff
@@ -7575,6 +7603,13 @@ static int clusterManagerCommandDeleteNode(int argc, char **argv) {
     while ((ln = listNext(&li)) != NULL) {
         clusterManagerNode *n = ln->value;
         if (n == node) continue;
+
+        /* Skip nodes without a valid connection. */
```
Comment (sarthakaggarwal97) [inline src/valkey-cli.c:7610]: This `continue` skips both `CLUSTER REPLICATE` and `CLUSTER FORGET` for any node. If an empty primary node is being deleted, I think the replica which is offline, will continue to point to dead primary once it comes online.

Comment (yang-z-o) [reply src/valkey-cli.c:7610]: Just to confirm, this comment is for `continue` on L7610, not L7605, right? 

Yes, this skips both `CLUSTER REPLICATE` and `CLUSTER FORGET` for unreachable nodes since we can't send commands without a connection. So if an offline replica comes back, it will still point to the deleted primary.

However, this isn't a new behavior introduced by this change. Before this PR, unreachable nodes weren't in the list so they were never iterated over in this loop either. The net effect is the same: unreachable replicas don't get commands sent to them. 

We could improve the warning message to be more explicit about the consequence though.

Comment (sarthakaggarwal97) [reply src/valkey-cli.c:7610]: > Just to confirm, this comment is for continue on L7610

Yes!

> this isn't a new behavior introduced by this change

That's a good point. For now, we can improve the message! Should be good.

**Review by sarthakaggarwal97 — COMMENTED** [review]
The PR looks good to me! Thanks @yang-z-o

**Review by sarthakaggarwal97 — APPROVED** [review]

**Comment by zuiderkwast** [comment]
Do we consider this a bug? I think yes. Let's backport it?

**Comment by sarthakaggarwal97** [comment]
Yeah, I think this should be categorized as a bug.

File: src/valkey-cli.c [hunk 5]
```diff
@@ -6153,6 +6180,7 @@ static clusterManagerNode *clusterManagerNodeWithLeastReplicas(void) {
     while ((ln = listNext(&li)) != NULL) {
         clusterManagerNode *n = ln->value;
         if (n->flags & CLUSTER_MANAGER_FLAG_REPLICA) continue;
+        if (!n->context) continue; /* Skip unreachable primaries */
```
Comment (zuiderkwast) [inline src/valkey-cli.c:6183]: If all primaries are unreachable, this function (clusterManagerNodeWithLeastReplicas) will now return NULL.

At the case sites (two places) it's followed by an assert that will fail:

```C
            primary_node = clusterManagerNodeWithLeastReplicas();
            assert(primary_node != NULL);
```

It's unlikely but I guess it can happen in a netsplit scenario when valkey-cli can only reach one or a few replicas.

Instead of a failed assertion, we should probably print an error message and exit in these cases instead, or maybe think about if there is something else we should do in these cases.

File: src/valkey-cli.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (zuiderkwast) [reply src/valkey-cli.c:7653]: Will you change this or not? Here, we return 1 (success) even if CLUSTER RESET fails, but that's what we want when deleting unreachable nodes, isn't it? We have already sent FORGET to the other nodes.

**Review by zuiderkwast — COMMENTED** [review]
I finally got to review this. It's a great fix and it's the added test coverage is good too.

It's a large diff for where that slot parsing logic was moved around, but it wasn't change, just moved so I think it's correct. :)

I found an unlikely assert failure that probably is worth looking into. Other than that, looks great.

File: src/valkey-cli.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (yang-z-o) [reply src/valkey-cli.c:7653]: No I’m not going to make any change any more.

The change I made according to the Copilot feedback earlier is here https://github.com/valkey-io/valkey/pull/3209/changes/74fc443cc43d7d38bb9eca3c5ab00a08ab5b8def. 
I added `if (!success) return 0;` when the node is reachable so that it won’t print out success message before return.

This won’t impact unreachable node because we are checking the connection `if (node->context != NULL)` before sending reset.

File: src/valkey-cli.c (hunk 5 above)
Comment (yang-z-o) [reply src/valkey-cli.c:6183]: Make sense, updated.

**Review by zuiderkwast — APPROVED** [review]
LGTM

**Comment by zuiderkwast** [comment]
Thanks Yang! and thanks Sarthak for reviewing!
