### PR TITLE
fix test_entry to consider diffrerent allocator size classes

### LINKED ISSUE #3200: Unit test "test_entryUpdate" fails on macos
This fails locally on macOS, apple silicon, but I haven't seen it fail in our CI or Daily.

```
[test_entryUpdate - unit/test_entry.c:177] Failed assertion: entryMemUsage(e10) < current_embedded_allocation_size * 3 / 4
[fail] - test_entry.c:test_entryUpdate
```

How to reproduce:

```sh
cd src
make all-with-unit tests
./valkey-unit-tests
```

### PR DESCRIPTION
**Pull request by ranshid**
fixes: https://github.com/valkey-io/valkey/issues/3200

### CODE REVIEW

File: src/unit/test_entry.cpp [hunk 1]
```diff
@@ -182,7 +182,7 @@ TEST_F(EntryTest, entryUpdate) {
     // Update the value so that memory usage is at least 3/4 of the current memory usage
     // Ensuring required_embedded_size > current_embedded_allocation_size * 3 / 4 without creating a new entry
     current_embedded_allocation_size = entryMemUsage(e10);
-    sds value11 = sdsnew("yyyyyy");
+    sds value11 = sdsnew("yyyyyyyyyyyy");
```
Comment (zuiderkwast) [inline src/unit/test_entry.cpp:188]: Please explain why.

@asagege's explanation in https://github.com/valkey-io/valkey/issues/3200#issuecomment-4114394332 makes sense to me, but how does this change affect the numbers?

Comment (ranshid) [reply src/unit/test_entry.cpp:188]: It's just fits in both 16 and 8 alignment. But I will also add a fix to skip this test when jemalloc is not used

**Review by zuiderkwast — APPROVED** [review]
