### PR TITLE
Fix HEXPIRE should not delete items when GT rule is used and expiration is in the past

### LINKED ISSUE #3021: [BUG] HEXPIRE will delete fields even if condition is not met
**Describe the bug**

I'm not sure if this is how it's designed, but I feel that some users might rely on a condition (like `gt`) to filter `hexpire` for an expired time. However, in the current implementation, if an expired time is used, the condition is ignored, and it directly becomes the effect of the `hdel` command, which seems inconsistent with the implementation of the `expire` command too.

**To reproduce**

```
hsetex myhash ex 1000 fields 1 f1 v1
hexpireat myhash 1754846600 gt fields 1 f1
```

**Expected behavior**

return 0(condition has not been met) and do not hdel f1

### PR DESCRIPTION
**Pull request by ranshid**
if an expired time is used, the condition is ignored, and it directly becomes the effect of the `hdel` command.
This is mainly important for cases where the user would like to protect deleting the data in case the `HEXPIREAT` command is used and the user would like to protect delay execution of this command to delete fields.

fixes: https://github.com/valkey-io/valkey/issues/3021

### CODE REVIEW

File: src/t_hash.c [hunk 1]
```diff
@@ -1779,7 +1779,10 @@ void hexpireGenericCommand(client *c, long long basetime, int unit) {
 
     for (i = 0; i < num_fields; i++) {
         expiryModificationResult result = EXPIRATION_MODIFICATION_NOT_EXIST;
-        if (set_expired) {
+        /* If the flags included the GT flag, we cannot delete the entries since existing entries
+         * MUST have expiration time bigger than a past time.*/
```
Comment (ranshid) [inline src/t_hash.c]:
```suggestion
         * MUST have expiration time bigger than a past time. */
```

File: src/t_hash.c [hunk 2]
```diff
@@ -1779,7 +1779,10 @@ void hexpireGenericCommand(client *c, long long basetime, int unit) {
...
+        if (set_expired && !(flag & EXPIRE_GT)) {
+            /* In case the expiration time is past, we have no items to apply this change. */
```
Comment (ranshid) [inline src/t_hash.c]:
```suggestion
```

File: src/t_hash.c [hunk 3]
```diff
@@ -1779,7 +1779,9 @@ void hexpireGenericCommand(client *c, long long basetime, int unit) {
 
     for (i = 0; i < num_fields; i++) {
         expiryModificationResult result = EXPIRATION_MODIFICATION_NOT_EXIST;
-        if (set_expired) {
+        /* If the flags included the GT flag, we cannot delete the entries since existing entries
+         * MUST have expiration time bigger than a past time. */
+        if (set_expired && !(flag & EXPIRE_GT)) {
```
Comment (cjx-zar) [inline src/t_hash.c:1784]: What about the `NX` and `XX` options?

**Review by zuiderkwast — APPROVED** [review]
Include GT in the PR title. Without it, it's confusing.

File: src/t_hash.c (hunk 3 above)
Comment (ranshid) [reply src/t_hash.c:1784]: You are right :( I forgot about these

Comment (ranshid) [reply src/t_hash.c:1784]: @cjx-zar can you please check https://github.com/valkey-io/valkey/pull/3048?

Comment (cjx-zar) [reply src/t_hash.c:1784]: Sure.
