### PR TITLE
Dual-channel-replication announces itself at replica-announce-ip if configured

### LINKED ISSUE #2338: [BUG] dual-channel-replication-enabled causes "duplicate" replica on Sentinel
**Describe the bug**

We run Valkey on K8s as a statefulset. A statefulset has 3 pods, each with a Valkey container and a Sentinel container for managing HA. One of these pods is the master, and the other 2 are replicas. Pod IPs are ephemeral, so as pods cycle they will come up with a new IP address which Sentinel will detect as a new replica, marking the old one down. This causes stale replicas in the output of `sentinel replicas master_name`.

To mitigate this we configure K8s Services, one for each pod. We have an init container on the pods to find the ClusterIP for their respective Service, and then configures itself with `replica-announce-ip` for Valkey and `announce-ip` for Sentinel. This allows the replica IPs to remain the same as pods are cycled.

We recently migrated some of our workloads to Valkey 8.1.1 and are trialling the `dual-channel-replication-enabled yes` config. When enabled during a failover, the additional channel of type=rdb-channel appears as the pod IP. If sentinel were to be polling for replicas during this time, it will save this as a distinct replica. When the replica fully resyncs, it will use the announce IP address configured.

This duplication is bad for Valkey backed by Sentinel, as during a failover Sentinel would elect a new master from the list of replicas, and will instruct the new master to replicate from itself, which it cannot do.

Pod IPs

```
NAME                  READY   STATUS    RESTARTS   AGE     IP             
redis-test-0-server-0   5/5     Running   0          8m12s   100.104.75.103 
redis-test-0-server-1   5/5     Running   0          7m21s   100.111.250.31 
redis-test-0-server-2   5/5     Running   0          12m     100.99.64.48   
```

Service Cluster IPs

```
NAME                    TYPE        CLUSTER-IP     
redis-test-0-announce-0   ClusterIP   100.67.128.152 
redis-test-0-announce-1   ClusterIP   100.70.100.164 
redis-test-0-announce-2   ClusterIP   100.71.105.52  
```

In this scenario, redis-test-0-server-1 has been promoted to a master after a failover. The output of `info replication` is:

```
# Replication
role:master
connected_slaves:2
slave0:ip=100.71.105.52,port=6379,state=online,offset=7448294713549,lag=1,type=replica
slave1:ip=100.104.75.103,port=6379,state=wait_bgsave,offset=0,lag=0,type=rdb-channel
```

- slave0 is the ClusterIP for redis-test-0-announce-2, this maps to pod redis-test-0-server-2.
- slave1 is the Pod IP for redis-test-0-server-0

When slave1 resyncs, the output of `info replication` is:

```
# Replication
role:master
connected_slaves:2
slave0:ip=100.71.105.52,port=6379,state=online,offset=7448295098696,lag=1,type=replica
slave1:ip=100.67.128.152,port=6379,state=online,offset=7448295102193,lag=1,type=replica
```

- slave0 is unchanged to what it was previously
- slave1 is now the ClusterIP for redis-test-0-announce-0, this maps to pod redis-test-0-server-0.

When executing `sentinel replicas master_name | grep name -A1`, there are 4 replicas.

```
/data $ redis-cli -p 26379 sentinel replicas master_name | grep name -A1
name
100.99.64.48:6379
--
name
100.104.75.103:6379
--
name
100.67.128.152:6379
--
name
100.71.105.52:6379
```

In order they are:
- pod IP for redis-test-0-server-2
- pod IP for redis-test-0-server-0
- ClusterIP for redis-test-0-announce-2 (redis-test-0-server-2)
- ClusterIP for redis-test-0-announce-0 (redis-test-0-server-0)

Issuing `sentinel reset master_name` fixes this list. But this is not an appropriate solution given that pods can cycle for any reason and would resync with the master with a new pod IP.

**To reproduce**

- Establish any environment with announce IPs, backed by Sentinel
- Enable `dual-channel-replication-enabled yes`
- Execute a failover
- Retrieve replicas from Sentinel via `sentinel failover master_name`

**Expected behavior**

Stale/duplicate replicas are not persisted when a failover happens, or when pods are cycled.

**Additional information**

N/A

### PR DESCRIPTION
**Pull request by jdheyburn**
When dual-channel-replication is enabled, and replica-announce-ip is set, the RDB/AOF channel does not announce itself at this endpoint. This defaults to the IP address behind the NAT, or the Kubernetes Pod IP in our case.

This means that if Sentinel is polling the primary for connected replicas, it will first see the ephemeral pod IP, then revert to the announce-ip - leaving behind the pod IP as a down replica. 

This PR configures the RDB/AOF channel to also announce itself at the announce-ip to prevent the stale replica. 

## Testing

I evaluated writing unit tests for this, but I am not sure of a way we can test an IP address different to localhost (127.0.0.1) that would fail without the fix. I did test on Kubernetes against 9.0 tag and verified the fix there too.

### Status quo

On 9.0 image tag:

```
$ kubectl get pods -n valkey-baseline -o custom-columns=NAME:.metadata.name,POD-IP:.status.podIP
NAME                              POD-IP
valkey-primary-5bd78c8566-llb6k   10.244.0.25
valkey-replica-0                  10.244.0.17
valkey-replica-1                  10.244.0.13

$ kubectl get services -n valkey-baseline -o custom-columns=NAME:.metadata.name,CLUSTER-IP:.spec.clusterIP
NAME               CLUSTER-IP
valkey-primary     10.96.147.28
valkey-replica-0   10.96.66.233
valkey-replica-1   10.96.57.230
```

Logs below show that pod IP for valkey-primary-5bd78c8566-llb6k `10.244.0.25:6379` is being used for dual-channel replication. This should be its cluster IP `10.96.147.28` as this is what is set in replica-announce-ip.

```
1:M 14 Nov 2025 17:57:51.750 * Replica 10.96.147.28:6379 asks for synchronization
1:M 14 Nov 2025 17:57:51.751 * Replica 10.244.0.25:6379 asks for synchronization
1:M 14 Nov 2025 17:57:56.135 * Dual channel replication: Sending to replica 10.244.0.25:6379 RDB end offset 1763269 and client-id 35
1:M 14 Nov 2025 17:57:56.140 * Replica 10.96.147.28:6379 asks for synchronization
```

### This fix

```
$ kubectl get pods -n valkey-test -o custom-columns=NAME:.metadata.name,CLUSTER-IP:.status.podIP  
NAME                              POD-IP
valkey-primary-594c9597b5-qqvdk   10.244.0.26
valkey-replica-0                  10.244.0.10
valkey-replica-1                  10.244.0.18

$ kubectl get services -n valkey-test -o custom-columns=NAME:.metadata.name,CLUSTER-IP:.spec.clusterIP
NAME               CLUSTER-IP
valkey-primary     10.96.125.142
valkey-replica     None
valkey-replica-0   10.96.155.74
valkey-replica-1   10.96.64.111
valkey-sentinel    None
```

Logs show that the Cluster IP is now being used for dual-channel replication.

```
1:M 14 Nov 2025 17:57:49.923 * Replica 10.96.125.142:6379 asks for synchronization
1:M 14 Nov 2025 17:57:49.924 * Replica 10.96.125.142:6379 asks for synchronization
1:M 14 Nov 2025 17:57:54.913 * Dual channel replication: Sending to replica 10.96.125.142:6379 RDB end offset 1771247 and client-id 36
1:M 14 Nov 2025 17:57:54.916 * Replica 10.96.125.142:6379 asks for synchronization
```

Fixes #2338

### CODE REVIEW

File: src/replication.c [hunk 1]
```diff
@@ -2973,6 +2973,14 @@ static int dualChannelReplHandleHandshake(connection *conn, sds *err) {
         return C_ERR;
     }
 
+    if (server.replica_announce_ip) {
```
Comment (ranshid) [inline src/replication.c:3030]: Maybe we can ALWAYS include the ip-address in the first replconf and thus reduce the need to explicitly handle the second replconf error handing?

**Review by ranshid — COMMENTED** [review]
Overall the fix LGTM

Can we please add a tcl test for it?

File: src/replication.c (hunk 1 above)
Comment (jdheyburn) [reply src/replication.c:3030]: I wanted to be consistent with the current pattern for how replication handles replica_announce_ip. I am unsure how the REPLCONF command would handle a `null` ip-address.

- https://github.com/valkey-io/valkey/blob/e19ceb7a6de207d049378a29406cb1763a6e1844/src/replication.c#L3725-L3731

**Comment by jdheyburn** [comment]
> Can we please add a tcl test for it?

@ranshid I am not sure of a way to accurately test this via a tcl. The replica-announce-ip that would need to be set during the test would have to be a local IP address such as `127.0.0.1` which would be the IP address used anyway. I had a tcl test case before, but removing the code I added caused the test to pass anyway. 

Is there another means of testing? This is why I put the emphasis on the test I added in the description.

File: src/replication.c (hunk 1 above)
Comment (ranshid) [reply src/replication.c:3030]: Yes. I meant that we could pass the replica IP address even when the parameter is not configured. but it is not that critical TBH

**Comment by ranshid** [comment]
> > Can we please add a tcl test for it?
> 
> @ranshid I am not sure of a way to accurately test this via a tcl. The replica-announce-ip that would need to be set during the test would have to be a local IP address such as `127.0.0.1` which would be the IP address used anyway. I had a tcl test case before, but removing the code I added caused the test to pass anyway.
> 
> Is there another means of testing? This is why I put the emphasis on the test I added in the description.

I was thinking to set the config to something like 
replica-announce-ip 5.5.5.5

and then delay the full sync (IIRC you can use the `config set repl-diskless-sync-delay`)

during that time the primary info shuold indicate the 'rdb-channel' has ip address 5.5.5.5

**Comment by jdheyburn** [comment]
Hey @ranshid, apologies for the delay on this. I've got a TCL test together for this - could you trigger the CI tests to verify it please?

**Review by ranshid — APPROVED** [review]
LGTM

**Comment by jdheyburn** [comment]
Hey @ranshid - checking to see what is needed to get this PR merged, thanks!
