### PR TITLE
Defrag if slab 1/8 full to fix defrag didn't stop issue

### LINKED ISSUE #2398: [Test Failure] Fix Flaky Tests in Workflows
We've observed intermittent failures in our CI workflows that appear to be caused by flaky tests. These failures do not consistently reproduce and often pass when re-run, making it difficult to identify true regressions that need to be investigated and fixed.

List of falky tests (keep it updated):

* https://github.com/valkey-io/valkey/issues/2423

* https://github.com/valkey-io/valkey/actions/runs/16585350083/job/46909359496
```
[err]: Active Defrag stream: cluster in tests/unit/memefficiency.tcl
defrag didn't stop.
```

* https://github.com/valkey-io/valkey/issues/2205
```
*** [TIMEOUT]: Active Defrag big list: cluster in tests/unit/memefficiency.tcl
```

* https://github.com/valkey-io/valkey/actions/runs/16540895816/job/46781944780
```
*** [TIMEOUT]: pid:38921 - tests/integration/aof.tcl in tests/integration/aof.tcl
```

* ~~https://github.com/valkey-io/valkey/actions/runs/16440028719/job/46458486359~~
  * Fixed https://github.com/valkey-io/valkey/pull/2370
```
!!! WARNING The following tests failed:

*** Migration source is auto-updated after failover in source shard in tests/unit/cluster/slot-migration.tcl
*** Replica redirects key access in migrating slots in tests/unit/cluster/slot-migration.tcl
*** Replica of migrating node returns ASK redirect after READONLY in tests/unit/cluster/slot-migration.tcl
*** Replica of migrating node returns TRYAGAIN after READONLY in tests/unit/cluster/slot-migration.tcl
*** Replica of importing node returns TRYAGAIN after READONLY and ASKING in tests/unit/cluster/slot-migration.tcl
*** New replica inherits importing slot in tests/unit/cluster/slot-migration.tcl
```

* ~~https://github.com/valkey-io/valkey/actions/runs/16256552218/job/45937858917#logs~~
  * Fixed https://github.com/valkey-io/valkey/pull/2345
```
/__w/_temp/cd6e3fe0-daaa-448e-b09f-76d9689007a0.sh: 2: /__w/_temp/cd6e3fe0-daaa-448e-b09f-76d9689007a0.sh: make: not found
```

### PR DESCRIPTION
**Pull request by asagege**
**Issue History:**
1. The flaky test issue "defrag didn't stop" was originally detected in February 2025: https://github.com/valkey-io/valkey/issues/1746  
Solution for 1746: https://github.com/valkey-io/valkey/pull/1762
2. Similar issue occurred recently: https://github.com/valkey-io/valkey/actions/runs/16585350083/job/46909359496#step:5:7640

**Investigation:** 
1. First, the issue occurs specifically to Active Defrag stream in cluster mode. 
2. After investigating `test_stream` in `memefficiency.tcl`, I found the root cause is in defrag logic rather than the test itself - There are still failed tests with the same error even if I tried different parameters for the test. 
3. Then I looked at malloc-stats and identified potential defrag issues, particularly in the 80B bin where utilization only reaches ~75% after defrag instead of the expected near 100%, while other bins show proper defrag behavior - 80B actually is the size of a new stream(confirmed in `t_stream.c`) that we add during test.
4. For 80B, after adding 200000 streams and fragmenting, `curregs `= 100030, after a lot of defrag cycles, there are still 122 nonfull-slabs/511 slabs with the remaining 446 items not defragged (average 4/nonfull-slab).

**Detailed malloc-stats:**
- Total slabs: 511
- Non-full slabs: 122
- Full slabs: 511-122=389
- Theoretical maximum per slab: 256 items
- Allocated items in non-full slabs: 100030-389*256=446
- Average items per non-full slab: 446/122=3.66

**Root Cause:** 
**There are some immovable items which  prevent complete defrag**

**Problems in old defrag logic:**
1. The previous condition (we don't defrag if slab utilization > 'avg utilization' * 1.125), the 12.5% threshold doesn’t work well with low utilizations.

- Let's imagine we have 446 items in 122 nonfull-slabs (avg 3.66 items/nonfull-slab), let's say, e.g. we have 81 slabs with 5 items each +41 slabs with 1 item each)
- 12.5% threshold: 3.66*1.125=4.11
- If those 41 single items are immovable, they actually lower the average, so the rest 81 slabs will be above the threshold (5>4.11) and will not be defragged - defrag didn't stop. 

2. Distribution of immovable items across slabs was causing inconsistent defragmentation and flaky test outcome.

- If those 41 single items are movable, they will be moved and the avg will be 5, then 12.5% threshold: 5*1.125=5.625, so the rest 81 slabs will fall below the threshold (5<5.625) and will be defragged - defrag success. 
- This can explain why we got flaky defrag tests.

**Final solution :** 
1. Add one more condition before the old logic in `makeDefragDecision `to trigger defragmentation when slab is less than 1/8 full (1/8 threshold (12.5%) chosen to align with existing utilization threshold factor) - Ensures no low-utilization slabs left without defragged, and stabilize the defrag behavior.
2. The reason why we have immovable items and how to handle them is going to be investigate later.
3. Be sure to rebuild Valkey before testing it.

**Local test result:**
- Before fix: 
pass rate 80.8% (63/78)
- After fix:
Test only stream: pass rate 100% (200/200)
Test the whole memefficiency.tcl: pass rate 100% (100/100)

Resolves #2398 , the "defrag didn't stop" issue, with help from @JimB123 @madolson

### CODE REVIEW

**Review by hpatro — APPROVED** [review]

**Comment by zuiderkwast** [comment]
Good to know: To connect a PR to an issue so that it gets closed when the PR is merged, use one of the syntaxes explained here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

This will make the PR linked to the issue:

```diff
-Resolves the "defrag didn't stop" issue @ #2398
+Resolves #2398, the "defrag didn't stop" issue
```

File: src/allocator_defrag.c [hunk 1]
```diff
@@ -349,16 +349,24 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
...
     size_t allocated_nonfull = bin_usage->curr_regs - curr_full_slabs * bin_info->nregs;
-    if (bin_info->nregs == nalloced || bin_usage->curr_nonfull_slabs < 2 ||
-        1000 * nalloced * bin_usage->curr_nonfull_slabs > (1000 + UTILIZATION_THRESHOLD_FACTOR_MILLI) * allocated_nonfull) {
-        return 0;
-    }
+
+    /* Don't defrag if the slab is full or if there's only 1 nonfull slab */
+    if (bin_info->nregs == nalloced || bin_usage->curr_nonfull_slabs < 2) return 0;
+
+    /* Always defrag if the slab is less than 1/8 full */
```
Comment (zuiderkwast) [inline src/allocator_defrag.c]: It's not exacly "always". If the condition above is true, we don't defrag.

```suggestion
    /* Defrag if the slab is less than 1/8 full */
```

**Review by zuiderkwast — APPROVED** [review]
Good job! I don't fully understand why this works. Is the new condition logically necessary or is it heuristics?

File: src/allocator_defrag.c [hunk 2]
```diff
@@ -349,16 +349,24 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
...
  * 2. If the number of non-full slabs (bin_usage->curr_nonfull_slabs) is less than 2, defragmentation is not performed
  *    because there is no other slab to move regions to.
- * 3. If slab utilization < 'avg utilization'*1.125 [code 1.125 == (1000+UTILIZATION_THRESHOLD_FACTOR_MILLI)/1000]
+ * 3. Always defrag if the slab is less than 1/8 full: ensure no small-size items left without defragged, fixed defrag didn't stop issue.
+ * 4. If slab utilization < 'avg utilization'*1.125 [code 1.125 == (1000+UTILIZATION_THRESHOLD_FACTOR_MILLI)/1000]
  *    than we should defrag. This is aligned with previous je_defrag_hint implementation.
  */
 static inline int makeDefragDecision(jeBinInfo *bin_info, jemallocBinUsageData *bin_usage, unsigned long nalloced) {
     unsigned long curr_full_slabs = bin_usage->curr_slabs - bin_usage->curr_nonfull_slabs;
     size_t allocated_nonfull = bin_usage->curr_regs - curr_full_slabs * bin_info->nregs;
```
Comment (madolson) [inline src/allocator_defrag.c:360]: My notes for myself. `bin_info->nregs` is not documented correctly, it says it's the number of regions in the bin but it's really the number of regions per slab.

I think Nalloced is also wrong. It should be the number of allocated regions in the current slab.

**Review by madolson — COMMENTED** [review]
> Is the new condition logically necessary or is it heuristics?

I don't really get how this works either. Is this just a way to accelerate the defragmenting of small slabs?

**Comment by madolson** [comment]
> I don't really get how this works either. Is this just a way to accelerate the defragmenting of small slabs?

Chatted offline with asagege and I understand now! It seems that the root cause is if we have some very small pages that have some some items that aren't defragged (we do some allocations at startup for example). Those pages are the ones that are selected for defragmentation by the current algorithm, but since they are never emptied we need to move on to the other pages which are almost empty.

**Comment by asagege** [comment]
> Good job! I don't fully understand why this works. Is the new condition logically necessary or is it heuristics?

Thanks for your question! This new condition is logically necessary, please see the updated comment above.

**Comment by asagege** [comment]
> > I don't really get how this works either. Is this just a way to accelerate the defragmenting of small slabs?
> 
> Chatted offline with asagege and I understand now! It seems that the root cause is if we have some very small pages that have some some items that aren't defragged (we do some allocations at startup for example). Those pages are the ones that are selected for defragmentation by the current algorithm, but since they are never emptied we need to move on to the other pages which are almost empty.

Thanks for the explanation. How can we identify those never emptied pages and eliminate the effect?

File: src/allocator_defrag.c (hunk 2 above)
Comment (asagege) [reply src/allocator_defrag.c:360]: I can help update them in this PR if you need it.

Comment (madolson) [reply src/allocator_defrag.c:360]: If you want, you can also submit a separate PR clarifying it. This was just confusing me.

**Comment by madolson** [comment]
@asagege You should be able to use this link to do memory profiling. https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling

To add the configuration, you can use JEMALLOC_CONFIGURE_OPTS="--enable-prof". Note, this will only work on linux since profiling is disabled on MacOS.

After you run defrag, what's left should be all the *original* memory allocations, AKA those that weren't defragged. That should also you to identify which ones aren't moving.

@SoftlyRaining FYI. I think I also mentioned I would send you the link to do profiling.

File: src/allocator_defrag.c [hunk 3]
```diff
@@ -349,16 +349,24 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
  *    defragmentation is not necessary as moving regions is guaranteed not to change the fragmentation ratio.
  * 2. If the number of non-full slabs (bin_usage->curr_nonfull_slabs) is less than 2, defragmentation is not performed
  *    because there is no other slab to move regions to.
- * 3. If slab utilization < 'avg utilization'*1.125 [code 1.125 == (1000+UTILIZATION_THRESHOLD_FACTOR_MILLI)/1000]
+ * 3. Always defrag if the slab is less than 1/8 full: ensure no small-size items left without defragged, fixed defrag didn't stop issue.
```
Comment (madolson) [inline src/allocator_defrag.c]: Let's document why we have this 1/8 rule.

File: src/allocator_defrag.c [hunk 4]
```diff
@@ -349,16 +349,25 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
  *    defragmentation is not necessary as moving regions is guaranteed not to change the fragmentation ratio.
  * 2. If the number of non-full slabs (bin_usage->curr_nonfull_slabs) is less than 2, defragmentation is not performed
  *    because there is no other slab to move regions to.
- * 3. If slab utilization < 'avg utilization'*1.125 [code 1.125 == (1000+UTILIZATION_THRESHOLD_FACTOR_MILLI)/1000]
+ * 3. Defrag if the slab is less than 1/8 full to ensure no low-utilization slabs left without defragged, and stabilize the defrag behavior.
+ *    1/8 threshold (12.5%) chosen to align with existing utilization threshold factor.
```
Comment (madolson) [inline src/allocator_defrag.c]:
```suggestion
 * 3. Defrag if the slab is less than 1/8 full to ensure small slabs get defragmented even when average utilization is low.
 *    This also handles the case when there are items that aren't defragmented skewing the average utilization. The 1/8
 *    threshold (12.5%) was chosen to align with existing utilization threshold factor.
```

**Review by madolson — APPROVED** [review]

File: src/allocator_defrag.c [hunk 5]
```diff
@@ -349,16 +349,26 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
  *    defragmentation is not necessary as moving regions is guaranteed not to change the fragmentation ratio.
  * 2. If the number of non-full slabs (bin_usage->curr_nonfull_slabs) is less than 2, defragmentation is not performed
  *    because there is no other slab to move regions to.
- * 3. If slab utilization < 'avg utilization'*1.125 [code 1.125 == (1000+UTILIZATION_THRESHOLD_FACTOR_MILLI)/1000]
+ * 3. Defrag if the slab is less than 1/8 full to ensure small slabs get defragmented even when average utilization is low.
```
Comment (zuiderkwast) [inline src/allocator_defrag.c:352]: Should this be: ... even when average utilization is *not* low enough to trigger it?

```suggestion
 * 3. Defrag if the slab is less than 1/8 full to ensure small slabs get defragmented even when average utilization is above the threshold.
```

File: src/allocator_defrag.c [hunk 6]
```diff
@@ -349,16 +349,26 @@ unsigned long allocatorDefragGetFragSmallbins(void) {
...
-    if (bin_info->nregs == nalloced || bin_usage->curr_nonfull_slabs < 2 ||
-        1000 * nalloced * bin_usage->curr_nonfull_slabs > (1000 + UTILIZATION_THRESHOLD_FACTOR_MILLI) * allocated_nonfull) {
-        return 0;
-    }
+
+    /* Don't defrag if the slab is full or if there's only 1 nonfull slab */
+    if (bin_info->nregs == nalloced || bin_usage->curr_nonfull_slabs < 2) return 0;
+
+    /* Defrag if the slab is less than 1/8 full */
+    if (nalloced * 8 < bin_info->nregs) return 1;
```
Comment (zuiderkwast) [inline src/allocator_defrag.c]: Instead of hardcoding 8 here, should this calculation involve UTILIZATION_THRESHOLD_FACTOR_MILLI so if this macro is changed it affects both formulas?

Comment (asagege) [reply src/allocator_defrag.c]: I will change it.

File: src/allocator_defrag.c (hunk 5 above)
Comment (zuiderkwast) [reply src/allocator_defrag.c:352]: Or did I get this wrong?

Comment (asagege) [reply src/allocator_defrag.c:352]: The threshold = 1.125 * average utilization, if we have some items immovable, they actually lower the average, as well as the threshold, so the rest small slabs will be above the threshold and will not be defragged

Comment (zuiderkwast) [reply src/allocator_defrag.c:352]: Thanks! I think I got it now.

Comment (asagege) [reply src/allocator_defrag.c:352]: I will keep the comment from @madolson

**Comment by madolson** [comment]
Since Viktor previously approved, will go ahead and merge this.
