### PR TITLE
Fix test_reclaimFilePageCache to avoid tmpfs

### LINKED ISSUE #897: [Test failure] test_reclaimFilePageCache fails on Amazon Linux 2023 AARCH64
`test_reclaimFilePageCache` consistently fails on Amazon Linux 2023:
```
[test_reclaimFilePageCache - unit/test_util.c:302] Failed assertion: !cache_exist(fd)
[fail] - test_util.c:test_reclaimFilePageCache
```
The test successfully creates the tmp file. But looks like `fadvise` doesn't behave as expected. Another option is that `mincore` doesn't behave inside `cache_exists` test utility.

Kernel info:
```
$ uname -srv
Linux 6.1.87-99.174.amzn2023.aarch64 #1 SMP Tue Apr 23 00:06:47 UTC 2024
```

### PR DESCRIPTION
**Pull request by xbasel**
Avoid tmpfs as fadvise(FADV_DONTNEED) has no effect on memory-backed filesystems.

Fixes https://github.com/valkey-io/valkey/issues/897

### CODE REVIEW

File: src/unit/test_util.c [hunk 1]
```diff
@@ -283,6 +285,24 @@ static int cache_exist(int fd) {
...
+ */
+static const char *get_non_tmpfs_temp_file_path(void) {
+    struct statfs buf;
+
+    /* Check if /tmp is memory-backed (e.g., tmpfs) */
+    if (statfs("/tmp", &buf) == 0) {
+        if (buf.f_type != TMPFS_MAGIC) { // Not tmpfs, use /tmp
+            return "/tmp/redis-reclaim-cache-test";
+        }
+    }
```
Comment (ranshid) [inline src/unit/test_util.c]: Can we just make this check part of the test_reclaimFilePageCache and return 0 in case it is not file backed? I think forcing this test to retun 0? Honestly I would also be fine with eliminating this test.

Comment (xbasel) [reply src/unit/test_util.c]: done (use tmp and only if its non-tmpfs)

File: src/unit/test_util.c [hunk 2]
```diff
@@ -291,7 +309,12 @@ int test_reclaimFilePageCache(int argc, char **argv, int flags) {
     if (flags & UNIT_TEST_VALGRIND) return 0;
 
 #if defined(__linux__)
+    if (!is_tmp_disk_based()) {
+        return 0; // Can not be tested on a ram drive.
+    }
+    
     char *tmpfile = "/tmp/redis-reclaim-cache-test";
+
```
Comment (ranshid) [inline src/unit/test_util.c:307]:
```suggestion
```

**Review by ranshid — APPROVED** [review]
